### ISSUE TITLE
How to use this file mrbgem.rake?

### ISSUE THREAD

**Issue by charlescui** [mruby/mruby#1006]
How to use this file mrbgem.rake?
No usage about the mrbgem.rake in mruby's README.md either in doc/mrbgems/README.md.

For example:
ruby mrbgem.rake?
rake mrbgem.rake?
mruby mrbgem.rake?

thanks!

**Comment by sankarsubramanian** [comment]
I have a mrbgem.rake. In this dependency listed as 
spec.add_dependency('mruby-http')
  spec.add_dependency('mruby-socket')
  spec.add_dependency('mruby-json')
How can I add this dependency for my development

**Comment by matz** [comment]
@sankarsubramanian could you elaborate? Are you going to create a mrbgem?

**Comment by sankarsubramanian** [comment]
@matz 
No I am not going to create mrbgem. I am new to ruby. 
I have a repository in below architecture 
+- ruby_extension_example/
   |
   +- examples/
    |  + - test.rb
   +- mrblib/
   |  |
   |  +- example.rb        <- Ruby extension source
   |
   +- test/
   |  |
   |  +- example.rb        <- Test code for Ruby extension
   |
   +- mrbgem.rake          <- GEM specification
   |
   +- README.md

My doubt is how to include mrblib/example.rb/ in example/test.rb.
Is it ok to execute the test.rb using command "mruby ./example/test.rb"

**Comment by mattn** [comment]
Maybe, you know this already, but FYI. You've better to know `What you can do with mruby`.

mruby is used for:
(1) embedded ruby on you app. you can make app in C, C++, Go, C# or etc.
(2) or, run your ruby script with bin/mruby

You know mruby have minimal feature. Most of gems which CRuby have not exists in default. If you want to add dependencies for the external gems called mrbgems. As far as I can see, you seems to create app with you ruby script extended with you code like below?

mrblib/example.rb
```ruby
class MyExtension
   ...
end
```

app.rb
```ruby
ext = MyExtension.new
ext.do_something
```
Right? Then, you need to make it as local-mrbgems. Put below into you mruby_config.rb

```ruby
MRuby::Build.new do |conf|
  ...
  conf.gem 'mrbgems'
  ...
end
```
You have better to create nested directory like `mrbgems/my_ext`, and fix mruby_config.rb too.

```ruby
MRuby::Build.new do |conf|
  ...
  conf.gem 'mrbgems/my_ext'
  ...
end
```

You need to put mrbgem.rake into the directory. See example/mrbgems. After doing that, go `./minirake`. You can copy mruby_config.rb in another filen to avoid to modify mruby_config.rb. Don't forgot to set `MRUBY_CONFIG=your_mruby_config.rb` then. Have fun.

**Comment by sankarsubramanian** [comment]
Thanks for response. I am using Ruby 2.0.0
In my .rb file, I have HTTP::Parser.new  & require 'http' in top.
While executing getting the error as undefined method `parse_url' for #<HTTP::Parser:0x007f9cb7e983a0> (NoMethodError). 
Whether HTTP::Parser deprecated on Ruby 2.0.0
