### ISSUE TITLE
show a backtrace when when an error occurs on gem load

### ISSUE THREAD

**Issue by schmurfy** [mruby/mruby#1243]
Create a gem with this ruby code:

``` ruby
ezezeze
```

This code is obviously invalid but the problem is that when you will try executing mruby you will get no backtrace at all, only a very unhelpful:

``` text
NoMethodError: undefined method 'ezezeze' for main
```

I gave it a try but I failed, as far as I understand it the generated gem_init.c is the culprit and should show a backtrace when an error occurs during loading, as a test my first try was to duplicate the showcallinfo method from main.c in gem_init.c and add calls to it on error.
I suppose it misses something since all I get is an empty backtrace...

Debugging is currently really annoying due to this problem, I could try to make a patch if someone points me in the right direction, right now I am clueless as to what is required.

/cc @bovi

**Comment by schmurfy** [comment]
I just stumbled on this while doing some housekeeping, I am curious, where are we on this ? has anything changed/evolved ?

**Comment by matz** [comment]
We have to redesign irep structure or maybe invent work around. Any idea will help.

**Comment by schmurfy** [comment]
what are the remaining problems ? I just quickly reread the whole thread but maybe things have changed since this was first opened.
