### ISSUE TITLE
how do embed fiber for c/c++?

### ISSUE THREAD

**Issue by monadbobo** [mruby/mruby#1269]
I notice  that matz have added fiber  in mruby, and I want to known how do embed fiber for c/c++?

Thanks!

**Comment by wrl** [comment]
what are the API limitations preventing a function like `mruby_fiber_new()` from being written?

**Comment by wrl** [comment]
@matz 
what are the API limitations preventing a function like `mruby_fiber_new()` from being written?

**Comment by matz** [comment]
Just because Fiber execution cannot cross C function boundary. If you have implementation idea, let me know.

**Comment by wrl** [comment]
@matz 
Does that mean that mruby code running inside a fiber cannot call into C at all? Is this is a similar issue to Lua's coroutines being unable to yield across the C boundary?

My use-case, essentially, is event-driven green threading. I would like to be able to suspend a Fiber which calls a blocking function (implemented in C) and then resume it when the result of that operation is available again.

**Comment by matz** [comment]
This means you cannot switch context within C function, except for `mrb_fiber_yield` at return. And this is similar situation to Lua's coroutine. In fact, mruby's fiber is implemented very similar way to Lua.

I think it's possible to implement event-driven (non preemptive) green threads by combination of fibers and `return mrb_fiber_yield(...)`.

**Comment by wrl** [comment]
Yeah, that's my suspicion too. What I can't figure out is, once I've yielded from a fiber, how do I resume that fiber later? Is that something I'll need to do in mruby instead of being able to do it from C?

**Comment by matz** [comment]
Here's Lua example:

``` C
int prim_read(lua_State *L)
{
  if (nothing_to_read())
    return lua_yield(L, 0);
  lua_pushstring(L, read_some_data());
  return 1;
}
```

``` Lua
function read()
  local line
  repeat
    line = prim_read()
  until line
  return line
end
```

If there's nothing to read, `lua_yield` passes control to other fiber.  When it resumed `prim_read` will return with resumed value. You might need a counterpart of Lua's `lua_yieldk()` (yield with continuation function). If so tell me.  I will seriously consider adding that function.

**Comment by wrl** [comment]
From looking at a few of the libuv lua bindings, it looks like I'd need a counterpart to `lua_resume()`. The continuation functions may be useful too, but I think the yield/resume pair is the big thing I need.

**Comment by matz** [comment]
I added `mrb_fiber_resume` in 0609abb

**Comment by wrl** [comment]
Oh hey, thanks! I'll get to work and flesh out my code, and will let you know how things work out.

**Comment by mattn** [comment]
prototype definition of mrb_fiber_resume?

**Comment by matz** [comment]
Ah, I forgot.

**Comment by beoran** [comment]
To truly have fibers that can yield through the C boundary, we would have to implement fibers/coroutines in C. This cannot be done in pure ANSI C, but there are several platform-dependant ways in which this can work. See http://cvs.schmorp.de/libcoro/coro.h for an example of the wide range of possibilities.

Alternatively, a `mruby_fiber_yield_with_continuation` (or maybe `mruby_fiber_yieldk`) would be very useful to help work around the issue.
