### ISSUE TITLE
Is there a way to create private methods?

### ISSUE THREAD

**Issue by dmajkic** [mruby/mruby#1357]
Keyword private Is not in Kernel, but there is a list of privates. 

If there is no way to declare private methods, could the private keyword at least be supported as no-op?

**Comment by fregas** [comment]
This bit me.  I expected my private methods to be enforced by the interpreter, but one was still being called after I moved it to private.  I would just +1 for real private/protected methods since the keywords are there.

**Comment by matz** [comment]
We have PR #4498
