### ISSUE TITLE
block gets garbage collected

### ISSUE THREAD

**Issue by schmurfy** [mruby/mruby#1411]
I will try to provide a code example but for now here is what I think happens, I run this ruby code:

```ruby
@client.get() do |ret|
  p [:CB, ret]
end
```

the get method is implemented in C and creates a ruby object to be yielded to the block with "mrb_str_buf_new" then I call the block with mrb_funcall and I get a ruby error saying that the String object has no call method.

On the other if I do this in ruby (same C code):

```ruby

p = ->(ret){
  p [:CB, ret]
}

@client.get(&p)
```

This time it works as expected. It looks like the block object is overwritten when the string is created if the block syntax is used.

**Comment by schmurfy** [comment]
I just came back to this while looking at my opened issues, has something moved on this ?
if not I could give it a try the stupid way, that is adding an api backed by a "hidden" ruby array.

**Comment by matz** [comment]
I am sorry. I fixed.

**Comment by schmurfy** [comment]
no problem, thanks !:)
