### ISSUE TITLE
mrb_print_error does not seem to print the backtrace

### ISSUE THREAD

**Issue by postmodern** [mruby/mruby#2010]
Even though `mrb_print_error` calls `mrb_print_backtrace` only the exception message is printed.
### MRuby Code

<pre>
def one
  raise("oops")
end

def two
  one
end

def three
  two
end

three
</pre>

### C Code

<pre>
if (mrb->exc)
{
    mrb_print_error(mrb);
}

mrb_close(mrb);
return mrb->exc != NULL;
</pre>

### Output

```
RuntimeError: oops
```

**Comment by thomthom** [comment]
I see similar thing, with mruby 1.1.0 using mrb_load_file.  Any special setup needed for backtrace tren?
