### ISSUE TITLE
Add Object#freeze

### ISSUE THREAD

**Issue by IceDragon200** [mruby/mruby#2028]
Does mruby have Object#freeze by the way, I did a quick search and didn't find anything... (then again, I just skimmed over it)

**Comment by jemc** [comment]
I'd like to see at least `String#freeze` if possible.

**Comment by Asmod4n** [comment]
Also have a need for String#freeze.

Currently writing a "SecureBuffer" class where you can mark a malloced() Region as read only, read and write or deny any access to it.

Of course i want that buffer to be viewable from ruby land so it has a to_str method via mrb_str_new_static().

It would be cool if that String Object wouldn't be modifyable. Or at best, never be copied to ruby land but only be referenceable.

**Comment by syohex** [comment]
@jemc @Asmod4n `String#freeze` was introduced at this commit(1a45447b8b66159a4a7d0348c4a01a175b3778fd)

**Comment by archSeer** [comment]
Doesn't seem like the original issue was fixed here, the fix is limited to strings.

**Comment by matz** [comment]
OK, I reopen the issue.
