### ISSUE TITLE
mrb_float_to_str does not work with DISABLE_STDIO

### ISSUE THREAD

**Issue by XanClic** [mruby/mruby#2140]
With DISABLE_STDIO defined, mruby will not include stdio.h (as expected and desired). mrb_float_to_str will however use sprintf() for the conversion which then fails during the build because of the implicit declaration.

**Comment by cremno** [comment]
@matz: This issue can be closed. Since the merge of #2723 `mrb_float_to_str()` can be used regardless of `ENABLE_STDIO` / `DISABLE_STDIO`.
