### ISSUE TITLE
Cannot save local variable in a context

### ISSUE THREAD

**Issue by windwiny** [mruby/mruby#2326]
I am reading the @matz 's mruby book, chapter 3 example 2 and example 3, say local variable can be save in a context, but i compile the latest mruby(20140527) and test this code but not receive expect value.

```
#include "mruby.h"
#include "mruby/compile.h"

int
main()
{
  mrb_state *mrb = mrb_open();
  mrbc_context *cxt = mrbc_context_new(mrb);
  mrb_value v;

    v = mrb_load_string_cxt(mrb, "ab=123", cxt);
    v = mrb_load_string_cxt(mrb, "ab", cxt);
    mrb_p(mrb, v);   // nil,  EXPECT 123

    v = mrb_load_string_cxt(mrb, "$ab=1123", cxt);
    v = mrb_load_string_cxt(mrb, "$ab", cxt);
    mrb_p(mrb, v);   // 1123


  mrb_close(mrb);
  return 0;
}
```

my understanding is wrong?

**Comment by robfors** [comment]
I am having a hard time trying to figure out this same problem.
How did you get this working?
My program starts by calling `mrb_load_irep`. I want to be able to get and set local variables on the top level namespace from a c program, during and after the `mrb_load_irep` execution.

So far I have
```
    char *s; // assuming this is a string of code
    mrb_int len; // assuming this is the string's length
    mrb_value binding = mrb_nil_value();
    char *file = NULL;
    mrb_int line = 1;
    struct RProc *proc;
  
    proc = create_proc_from_string(mrb, s, len, binding, file, line);
    mrb_assert(!MRB_PROC_CFUNC_P(proc));
    
    mrb_value return_value = mrb_vm_run(mrb, proc, mrb_top_self(mrb), stack_keep)
```

But I don't know what number to set `stack_keep` to.
Does someone know how I may be able to solve this?

**Comment by take-cheeze** [comment]
Seems like you are referencing `mruby-eval` source.
As pointed you should see mirb:
https://github.com/mruby/mruby/blob/dc5de38414f83d46395f34aa092864ba504ff6cf/mrbgems/mruby-bin-mirb/tools/mirb/mirb.c#L391
https://github.com/mruby/mruby/blob/dc5de38414f83d46395f34aa092864ba504ff6cf/mrbgems/mruby-bin-mirb/tools/mirb/mirb.c#L578

**Comment by robfors** [comment]
I was able to figure out the code that solves @windwiny original problem, however it does not entirely solve my problem. Here is the code for anyone who may benefit from it in the future.
```cpp
// mrb and cxt were created (only once) at the start of the program
mrb_state* mrb = ...
mrbc_context* cxt = ...

// put the code under here in a function and call it many times with different 'code' strings
std::string code = "ruby_code_here";
std::vector<char> code_copy(code.begin(), code.end());
code_copy.push_back('\0');

static unsigned int stack_keep = 0;

cxt->lineno = 1;
mrbc_filename(mrb, cxt, "(mirb)");
cxt->capture_errors = TRUE;
cxt->no_optimize = TRUE;

/* parse code */
struct mrb_parser_state* parser = mrb_parse_nstring(mrb, &*cpp_code_copy.begin(), cpp_code_copy.size(), cxt);
/* only occur when memory ran out */
if (!parser)
{
  //mrb_raise(mrb, E_RUNTIME_ERROR, "Failed to create parser state.");
  printf("Failed to create parser state.\n");
  throw std::runtime_error("Failed to create parser state.");
}

if (parser->nwarn > 0)
{
  /* warning */
  printf("line %d: %s\n", parser->warn_buffer[0].lineno, parser->warn_buffer[0].message);
}
if (parser->nerr > 0)
{
  /* parse error */
  printf("line %d: %s\n", parser->error_buffer[0].lineno, parser->error_buffer[0].message);
  mrb_parser_free(parser);
  //mrb_exc_raise(mrb, mrb_exc_new_str(mrb, E_SYNTAX_ERROR, str));
  mrb->exc = 0; // needed ?
  throw std::runtime_error("");
}

/* generate bytecode */
struct RProc* proc = mrb_generate_code(mrb, parser);
if (proc == NULL)
{
  /* codegen error */
  mrb_parser_free(parser);
  // mrb_raise(mrb, E_SCRIPT_ERROR, "codegen error");
  printf("codegen error\n");
  throw std::runtime_error("codegen error");
}

/* adjust stack length of toplevel environment */
if (mrb->c->cibase->env)
{
  struct REnv* e = mrb->c->cibase->env;
  if (e && MRB_ENV_STACK_LEN(e) < proc->body.irep->nlocals)
    MRB_ENV_SET_STACK_LEN(e, proc->body.irep->nlocals);
}

/* pass a proc for evaluation */
/* evaluate the bytecode */
mrb_value ruby_return = mrb_vm_run(mrb, proc, mrb_top_self(mrb), stack_keep);
stack_keep = proc->body.irep->nlocals;
/* did an exception occur? */
if (mrb->exc)
{
  mrb_print_error(mrb);
  mrb->exc = 0;
  mrb_parser_free(parser);
  //mrb_exc_raise(mrb, mrb_exc_new_str(mrb, E_SYNTAX_ERROR, str));
  throw std::runtime_error("");
}

mrb_parser_free(parser);
```

What I want is to call this code after or inside a call to `mrb_load_irep_cxt`. Is this possible?

Both `mrb_load_irep_cxt` and this code use the same `mrbc_context*`. 
I have an `.rb` file with
```
a = 1
```
I run it's symbol with `mrb_load_irep_cxt`. It completes and returns. Then I run the code with a string of "a". I get `undefined method 'a'`. I can get it if I `mrb_funcall` the `eval` method with `"a"` so I know its not garbage collected or something.

**Comment by take-cheeze** [comment]
Ah, sorry I've misunderstood your problem.
Executing on top-level and evaluating on the nested context is different in mruby.
You should read these codes:
https://github.com/mruby/mruby/blob/181f980b6cc5dfa25b270e137c6d060a897b8bf4/mrbgems/mruby-eval/src/eval.c#L277-L287

Though if possible use `eval` method instead. (It's more easier.)
And I think `std::string` has `data` and `size` so that you don't need to copy data to `std::vector`,

**Comment by robfors** [comment]
No worries. Thanks for the help.

I am still very confused on how mruby functions internally, however, it appears like I could use eval to get the local variables and my new code to set local variables. Not an elegant solution but I think it will work.
