### ISSUE TITLE
method_added hook method?

### ISSUE THREAD

**Issue by syalon** [mruby/mruby#2339]
I dont found `method_added` hook method ~ have any plan about it？

**Comment by jbreeden** [comment]
Was this closed on purpose? I see it was a duplicate, but no answer on either issue regarding plans to add it. Just noticed it was missing on my current build and came here to investigate. Did a quick github code search and didn't turn anything up.

**Comment by sasq64** [comment]
Would like to see this functionality also...

**Comment by matz** [comment]
I hesitated to add this feature for some reasons:

* hook methods (and `mrb_funcall` in general) call VM recursively, so that it may not work well with fibers
* those hooks are called from VM, so that we cannot separate the functionality to `mrbgem`
* performance penalty for both time and space, although method definition rarely become a bottleneck

**Comment by sasq64** [comment]
It's very convenient when you need to add metadata to methods, like

```ruby
doc "Draws a circle"
def circle(x,y,r)
end
```
is there another way to accomplish this ?

**Comment by dearblue** [comment]
In current Ruby, evaluating the `def` statement returns it a symbol.
So what about passing the symbol as the second argument to the `doc` method?

```ruby
doc "Draws a circle",
def circle(x,y,r)
end
```

**Comment by sasq64** [comment]
That... works. Nice trick, thanks.

What I'm really using it for is tagging methods with their return types, so I can provide correct tab completion.. so

```ruby
    returns Image,
    def load_image(name)
    ...
    end
```

So now something like `load_image(name).width` can be tab completed from the REPL.

**Comment by sasq64** [comment]
Can I do this without subclassing ?
Ie, If I put self.doc or self.returns in a super-class it will be available as wanted, but it doesn't seem possible to include/extend a Module to get the same behavior ?

**Comment by sasq64** [comment]
To answer my own question;
```ruby
module Stuff
  def doc()
  end
end

module Other
  extend Stuff
end
```

(doc() needs to be a normal instance method)

**Comment by matz** [comment]
@sasq64 Reasonable. I will implement those hooks.
