### ISSUE TITLE
Feature test macros needed

### ISSUE THREAD

**Issue by nwmcsween** [mruby/mruby#259]
Time.c needs _xopen_source and parse.y needs something related to isascii gcc automagically defines the kitchen sink with _gnu_source I'll work on this later if no one else picks it up

**Comment by bovi** [comment]
@matz I think this can be closed as "time" is since a long time a gem. also a missing gmtime_r seems to be handled graceful via NO_GMTIME_R

**Comment by matz** [comment]
thanks.
