### ISSUE TITLE
backtrace corrupted if ensure block exist

### ISSUE THREAD

**Issue by yasuyuki** [mruby/mruby#2683]
ensure.rb
```ruby
def a(b)
  raise if b > 2
  b += 1
  c(b)
end

def c(d)
  a(d)
end

begin
  a(1)
ensure
  puts 1
end
```
% ruby ensure.rb           
1
ensure.rb:2:in \`a': unhandled exception
	from ensure.rb:8:in \`c'
	from ensure.rb:4:in \`a'
	from ensure.rb:8:in \`c'
	from ensure.rb:4:in \`a'
	from ensure.rb:12:in \`\<main>'
% mruby ensure.rb
1
trace:
	[5] ensure.rb:2:in Object.a
	[2] mruby/mrbgems/mruby-print/mrblib/print.rb:29:in Kernel#puts
	[1] ensure.rb:14
ensure.rb:2: RuntimeError

**Comment by matz** [comment]
It's already fixed.
