### ISSUE TITLE
Providing state to mrb_run invocations

### ISSUE THREAD

**Issue by glenjofe** [mruby/mruby#2688]
What is the recommended way of providing custom state (such as a C pointer) when invoking a struct RProc\* via mrb_run such that C functions can access that state?

These are the options I considered:

**Option 1:** (With 1.1.0 and higher only) Set the mrb_state's 'ud' member:

```
mrb->ud = pointer;
mrb_run(mrb, proc, mrb_top_self(mrb));
```

Then, a C function could access 'ud' from the mrb_state directly.

```
mrb_value function(mrb_state* mrb, mrb_value self)
{
    void* pointer = mrb->ud;
```

This could work with 1.0.0 but only if a custom allocator is not being used. (1.1.0 was when 'ud' was repurposed and a separate 'allocf_ud' was added).

**Option 2:** (Is this defined behavior?) Set the top_self's data pointer:

```
mrb_value o = mrb_top_self(mrb); 
DATA_PTR(o) = pointer; 
mrb_run(mrb, proc, o);
```

Then, a C function could access the data pointer:

```
mrb_value function(mrb_state* mrb, mrb_value self)
{
    void* pointer = DATA_PTR(self);
```

**Option 3:** Set a constant with the C pointer:

```
mrb_value v = mrb_cptr_value(mrb, pointer);
mrb_const_set(mrb, mrb_obj_value(module), mrb_intern_lit(mrb, "Constant"), v);
mrb_run(mrb, proc, mrb_top_self(mrb));
```

Then access that constant in the C function:

```
mrb_value function(mrb_state* mrb, mrb_value self)
{
    mrb_value v = mrb_const_get(mrb, mrb_obj_value(module), mrb_intern_lit(mrb, "Constant");
    void* pointer = mrb_cptr(v);
```

This seems like the least efficient route.

Are there better ways?

**Comment by glenjofe** [comment]
Thanks; I'll go with the option 3. To protect the constant from ruby code access/modification (and only allow access/modification from C code) I suppose I can just choose a literal that isn't a valid Ruby identifier for a constant.

**Comment by matz** [comment]
In that case, you can use instance variables instead of constants. TT_OBJECT including top_self can reference a cptr object via instance variables. You can use functions such as `mrb_iv_get()` and `mrb_iv_set()`.
