### ISSUE TITLE
mrbc: output file should be specified to compile multiple files

### ISSUE THREAD

**Issue by zw963** [mruby/mruby#2698]
What I want to do is add a bash shell script for automatic compile one ruby script to a binary in linux.
here is one example:
https://github.com/zw963/ass/blob/master/common/ruby/mruby/bin/mrb

I try output C format byte code to some location other than current directory. But it failed with following
attempt:

```sh
$ mrbc 1.rb -o 1.c
mrbc: output file should be specified to compile multiple files
$ mrbc 1.rb 2.rb -o 1.c
mrbc: output file should be specified to compile multiple files
$ mrbc 1.rb 2.rb -o 1.c 2.c
mrbc: output file should be specified to compile multiple files
$ mrbc 1.rb -o 1.c 2.rb -o 2.c
mrbc: output file should be specified to compile multiple files
```
How to use -o to output c file to another path?

Thanks.

**Comment by cremno** [comment]
Options go before the files:
```
mrbc -o 1.c 1.rb
```

**Comment by matz** [comment]
And you can specify `-o` only once.

**Comment by zw963** [comment]
Thank all.
