### ISSUE TITLE
Curious about default MRB_PARSER_BUF_SIZE size

### ISSUE THREAD

**Issue by mephux** [mruby/mruby#2724]
Why is this so small? https://github.com/mruby/mruby/commit/4656073b600715b58dfde1e64fc481225cf667b2

I'm currently using mruby as a plugin lang. https://github.com/mephux/clipby/blob/master/vm.go#L79 but the length of the data i'm pushing is causing this error. Am i just going about this incorrectly or was this limited for some other issue?

**Comment by matz** [comment]
Could you show us the error message? I have removed array length limitation long ago, but there might be something left.

**Comment by matz** [comment]
I just remembered that string literal length is kept in 16bit in compiled binary format.  I thought it was ok to limit the string literal size. But you've shown us the need, I will support it in similar way we've handled longer arrays.

**Comment by matz** [comment]
I opened #2725. If you don't have other limitation issues, close this one, and wait for the fix for #2725

**Comment by mephux** [comment]
roger - thanks @matz
