### ISSUE TITLE
Is there or will there be an equivalent to rb_define_virtual_variable ?

### ISSUE THREAD

**Issue by grrussel** [mruby/mruby#2731]
This would be nice, as I seek to maintain the same API for scripts embedded via mruby as for MRI (cruby)

**Comment by matz** [comment]
I hesitate to add the API since I am not a big fan of global variables any longer.
Global variables are to ugly to be a part of API.

**Comment by mattn** [comment]
Sorry OT, BTW, I wonder why CRuby provides this API(rb_define_virtual_variable/rb_define_hooked_variable) to global variable limited.

**Comment by matz** [comment]
I thought they were good idea 20 years ago.

**Comment by grrussel** [comment]
From a script writers point of view, I think its a nice syntactic notation for obtaining values from the host application - but it is really equivalent to function calls, and not a _must have_ feature.
