### ISSUE TITLE
What are “special” variables?

### ISSUE THREAD

**Issue by cremno** [mruby/mruby#2735]
https://github.com/mruby/mruby/blob/a1d4992187146f99cc81045e6757f2b146f49193/src/vm.c#L840-L851
```c
    CASE(OP_GETSPECIAL) {
      /* A Bx   R(A) := Special[Bx] */
      regs[GETARG_A(i)] = mrb_vm_special_get(mrb, GETARG_Bx(i));
      NEXT;
    }

    CASE(OP_SETSPECIAL) {
      /* A Bx   Special[Bx] := R(A) */
      mrb_vm_special_set(mrb, GETARG_Bx(i), regs[GETARG_A(i)]);
      NEXT;
    }

```

I'm curious what they were supposed to do.

**Comment by matz** [comment]
special variables are variables that look like global variables but have different semantics e.g. $1 or $~ etc.

**Comment by matz** [comment]
And currently mruby does not support any special variables (yet).
