### ISSUE TITLE
Use of 'abort()' in exception handling

### ISSUE THREAD

**Issue by grrussel** [mruby/mruby#2741]
Attempting to undefine a method via 'undef_method', resulted in a mrb_name_error() and mrb_exc_raise() resulting in a call to abort()

This use of abort is undesirable inside interpreter embedded in a host application

Is there a suggested alternative mechanism for reporting, for example, unhandled exceptions?

**Comment by grrussel** [comment]
See also https://github.com/mruby/mruby/issues/1064

**Comment by matz** [comment]
Sorry for being late. we have 3 `abort()` in the source of mruby.
1. in `mrb_exc_raise` when mruby API is called without exception handling.
2. in `add_gray_list` only effective with `MRB_GC_STRESS` (debug option)
3. from `OP_DEBUG` (debug instruction)
we can ignore case 2 and 3 for production usage, so if you avoid calling VM without exception handling, you don't have to worry about `abort()`.  To handle exception, invoke VM with `mrb_run()` or `mrb_funcall()`. If you have further question(s), reopen this issue.
