### ISSUE TITLE
mrb_get_args function returns 0 unexpectedly.

### ISSUE THREAD

**Issue by crimsonwoods** [mruby/mruby#2743]
When I called mrb_get_args function like below, it returns 0.

    mrb_get_args(mrb, "&", &proc);

Is this correct? It looks incorrect for me.

**Comment by matz** [comment]
`mrb_get_args` returns number of (real) arguments processed, and `"&"` is a implicit argument that is not counted in arguments.  So zero is the right value to return.

**Comment by crimsonwoods** [comment]
Hi @matz,

Thank you for replying.

I understood that block is a implicit argument.
But, I don't know what I should do when I want to know the block is given or not.
Should I call `Kernel.block_given?` method via `mrb_funcall`?
Is there another more convenient way?
I think, I don't have to check the value returned from `mrb_get_args`. And I ought to verify `proc` is nil or not instead. Is this right?

**Comment by matz** [comment]
`mrb_get_args("&")` will give  you `nil` when there's no block to pass.

**Comment by crimsonwoods** [comment]
I see. Thank you!
