### ISSUE TITLE
threading

### ISSUE THREAD

**Issue by mowrang** [mruby/mruby#2744]
Our understading is that the current mruby interpreter deos not support object creation inside a thread (when the class is defined outside of the thread) (discussion at https://github.com/mattn/mruby-thread/issues/28) 

What is the plan for supporting this? 

We think without this feature threading is not really impleted for mruby. This poses a major limitation on mruby.

**Comment by mattn** [comment]
mattn/mruby-thread is a one of implementations. it's not core. Since mruby is not thread-safe, currently we are discussing about GVL.

https://github.com/mruby/mruby/issues/1657

**Comment by mowrang** [comment]
Thanks! for now should we use C threading a embed the mruby classes in C?

**Comment by mattn** [comment]
you seems to post similar comment into mruby/mruby. so close this. :)

**Comment by mowrang** [comment]
Will do.

Just need a confirmation from you:

We have decided to use C for threading and embed our mruby classes in C.

Does it sound a reasonable solution for now in your opinion?

thanks,

Maryam

On Wed, Mar 11, 2015 at 6:50 PM, mattn <notifications@github.com> wrote:

> you seems to post similar comment into mruby/mruby. so close this. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mruby/mruby/issues/2744#issuecomment-78409801>.
>



-- 
------------------------------------------------------------
Maryam Analui (Owrang)
http://broadband4america.blogspot.com/

**Comment by beoran** [comment]
The way I would solve it is to keep mruby and one c thread with appropriate locking to deal with mruby. That C thread then communicates with the other c threads. But normally I don't program full threads, only worker threads, and for the rest I do event-based programming.

**Comment by mowrang** [comment]
thanks beoran! 

What if I have multiple C treads using mruby with appropriate locking? Do you see particular issues there?

**Comment by beoran** [comment]
For that use it's best to initialize mruby and define all classes and methods from a single thread. For the rest, locking access to the ruby state with access from multiple threads should have the same effect as a "GLV", a global interpreter lock as  is used in cruby. Note that your C functions that implement mruby methods will probably have to use that global lock as well...

**Comment by Asmod4n** [comment]
The most reliable way would be to have one mruby interpreter per c thread and pass messages between them, thats what https://github.com/Asmod4n/mruby-actor basically does.
