### ISSUE TITLE
How do you call a class method?

### ISSUE THREAD

**Issue by camertron** [mruby/mruby#2771]
Hey guys, I can't seem to find any way of calling a class method from C. The `mrb_funcall` method only works on instances (eg. `mrb_value` objects), but both `mrb_module_get` and `mrb_class_get` return instances of `RClass*`.

**Comment by tsahara** [comment]
You can just use `mrb_obj_value` to convert `struct RClass *` into `mrb_value`.

Example:
```
  struct RClass *c = mrb_class_get(mrb, "Time");
  mrb_value t = mrb_funcall(mrb, mrb_obj_value(c), "now", 0);
```

Then `t` is `Time.now`.

**Comment by camertron** [comment]
Awesome, thank you!

**Comment by schmurfy** [comment]
is there a page somewhere where info like this one can be found ?
I just realized most of this precious informations to get you started are scattered mostly in the issues.
