### ISSUE TITLE
Release Maintenance

### ISSUE THREAD

**Issue by bovi** [mruby/mruby#2794]
I understand that the @mruby-forum is from time to time taking a snapshot of the source and then labelling it with a revision number. Yet I notice that there is no kind of backporting of bugfixes etc. in these releases. Neither 1.0 nor 1.1 were getting any additional backports from the master. Is this suppose to be like that? I personally know of several people who neither use the mruby-forum version (due to the lack of bugfixes) nor the mruby master (due to the risk of instability), so they are forced to maintain their very own repository.

Any thoughts about that?

**Comment by kaz0505** [comment]
I agree with your comment.
The stable version (1.0, 1.1 etc) does not contain bug-fixes even if they are serious.
I'll discuss about applying serious bug-fixes to those snapshots and test them.

Thank you.

**Comment by bovi** [comment]
Thanks for your reply @kaz0505 

I would also be happy to help with the backporting if this is an issue. Maybe we can even try to do the backporting on GitHub via pull requests? In this case the backporting can also be reviewed and we can maintain the stability of this release.

**Comment by murasesyuka** [comment]
:+1:
