### ISSUE TITLE
referencing gems that are no longer included in the build_config

### ISSUE THREAD

**Issue by Mav7** [mruby/mruby#2812]
I keep having a problem where even after I change the build_config.rb to build another gem it keeps returning an error referencing an old gem that I'm no longer using and the build fails. I tried taking out the old gem by deleting it from build/host/mrbgems but It keeps referencing the old gem that I'm no longer using. I can't find any documentation describing how to remove old gems so I was hoping you could help me with that.

**Comment by take-cheeze** [comment]
Have you ever cleaned the build with `make clean`(or `minirake clean`)?

**Comment by Mav7** [comment]
Oh I haven't thank you for the help. What does that actually do why does it have to be clean?
