### ISSUE TITLE
singleton classes can be cloned

### ISSUE THREAD

**Issue by cremno** [mruby/mruby#2815]
mruby successfully clones the singleton class and then crashes when the clone's singleton class is accessed:
```ruby
singleton_class.clone.singleton_class
```

Expected (CRuby 2.2.2):
```
-e:1:in `initialize_copy': can't copy singleton class (TypeError)
        from -e:1:in `initialize_dup'
        from -e:1:in `dup'
        from -e:1:in `<main>'
```

**Comment by cremno** [comment]
@matz: `#dup` has the same issue, doesn't it?

**Comment by matz** [comment]
Indeed. Thank you.

**Comment by tsahara** [comment]
Just for your information: `Kernel#dup` will not be applied to a singleton class actually because singleton classes are subclass of Module and `Module#dup` is an alias of `Module#clone`.  I found that while I was trying to write a test case for this issue.
