### ISSUE TITLE
On windows I can't use mrbgems inside a C program.

### ISSUE THREAD

**Issue by Mav7** [mruby/mruby#2838]
For some reason on Windows when I build mruby with a gem like mruby-io or mruby-eject and then I compile and link them into a C program I get a weird linking error with a bunch of undefined references. For instance when I compile and link mruby-io it says 
```C
lib\libmruby.a(io.o): In function 'mrb_io_s_select': 
```
I get that followed by a bunch of undefined references. What's going on how do I fix this problem? mrbgems I build don't suffer from this problem.

**Comment by mattn** [comment]
Could you please show me full log output?

**Comment by mattn** [comment]
Probably this is same issue: https://github.com/iij/mruby-io/issues/17

**Comment by zzak** [comment]
I've seen similar issues, can you try adding this to your build config?

```ruby
MRuby::CrossBuild.new('mingw') do |conf|
  # other config..
  MRuby.targets["host"].gems.each do |mrbgem|
    conf.gem mrbgem.dir
  end
end
```

**Comment by mattn** [comment]
I wonder this part is passed.

https://github.com/iij/mruby-io/blob/master/mrbgem.rake#L9

**Comment by Mav7** [comment]
@mattn Yes that is my same issue! I don't think I can give the full log the other issue that was the same as mine was done on OSX. I can't find a good way to do this on Windows.

@zzak I put that in the build config in mruby but got another crazy error.

**Comment by Mav7** [comment]
Also as I mentioned before it does this for every mrbgem I try like mruby-eject was another one.

**Comment by expeditiousRubyist** [comment]
I tested this out, and it would appear that when building the C program, you will not only have to link to libmruby, but to any of the libraries used in your mruby gems. For the mruby-io gem, you need to link against libws2_32. Thus, as an example compilation of a program against libmruby with mruby-io as the only gem used, the following resulted in no errors for me:
`gcc -o foo.exe foo.c -I../include -L../build/host/lib -lmruby -lws2_32`

Also of note, the order in which the linker flags are added matters... for some reason.

**Comment by Mav7** [comment]
Thank you so much this solved the problem!
