### ISSUE TITLE
mrb_get_args() for ruby code?

### ISSUE THREAD

**Issue by dmajkic** [mruby/mruby#2856]
I really got used to mrb_get_args() on the C side of things.
It completly makes obsolete (unused) mrb_aspec parameter in mrb_define_method().

Now that I am done on C src, and polishing some things in mrblib dir, I find it that from time to time I would really like to have some kind of quick parameter sanity check. Especially when dealing with C API.

```ruby
def some_method(name, value, options = {})
    get_args "SoH"      # or raise ArgumentError
    return something
end 
```
Perhaps that "SoH" string is not readable in ruby, maybe symbols (:string, :object, :hash) could be a nicer fit. 

Anyway - I would like to try something like this inside my mgem. Can I just export mrb_get_args(), or is there a way to create function which gets its own args, but can also access outer function args?

**Comment by matz** [comment]
From my viewpoint, adding get_args like feature to Ruby side is agaist duck-type principle.
`mrb_get_args` is acceptable only because types (or structures) cannot be ignored in C side.
Feel free to reopen this issue, when you want to persuade me.
