### ISSUE TITLE
memory limit

### ISSUE THREAD

**Issue by donpdonp** [mruby/mruby#2870]
is it possible to set an upper limit on memory usage for an instance of mruby? I am working on app that keeps multiple mruby instances in one unix process and I'd like to be able to measure and constrain the memory usage of each instance.

**Comment by tsahara** [comment]
You can run an instance with customized memory allocator that sets an limit.  What you need are:

1. Write a custom memory allocator ([mrb_default_allocf](https://github.com/mruby/mruby/blob/master/src/state.c#L56) in src/state.c is a good starting point).
2. Replace `mrb_open()` with [mrb_open_allocf()](https://github.com/mruby/mruby/blob/master/doc/api/mruby.h.md#mrb_open_allocf).

**Comment by donpdonp** [comment]
I'll look at that, thanks!
