### ISSUE TITLE
broken exception backtraces

### ISSUE THREAD

**Issue by yregelman** [mruby/mruby#2902]
```
def raise_func
  raise "noise"
end

def err_func
  raise_func
end

def use_some_more_stack
  puts "used some more stack"
end

def use_some_stack
  puts "used some stack"
  use_some_more_stack
end

def func1
  begin
    err_func
  rescue => e
    use_some_stack
    e.backtrace.each { |entry|
      p entry
    }
  end
end

def func2
  begin
    err_func
  rescue => e
    e.backtrace.each { |entry|
      p entry
    }
  end
end
      

func1
func2
```
$>ruby broken_backtrace.rb 
used some stack
used some more stack
"broken_backtrace.rb:2:in raise_func"
"broken_backtrace.rb:6:in err_func"
"broken_backtrace.rb:20:in func1"
"broken_backtrace.rb:40:in main"
"broken_backtrace.rb:2:in raise_func"
"broken_backtrace.rb:6:in err_func"
"broken_backtrace.rb:31:in func2"
"broken_backtrace.rb:41:in main"

$>mruby broken_backtrace.rb 
used some stack
used some more stack
"broken_backtrace.rb:10:in Object.use_some_more_stack"
"broken_backtrace.rb:23:in Object.func1"
"broken_backtrace.rb:40"
"broken_backtrace.rb:2:in Object.raise_func"
"broken_backtrace.rb:33:in Object.func2"
"broken_backtrace.rb:41

I see several discrepancies:
1. err_func is not mentioned in the backtraces given by mruby
2. line numbers differ for 'func1' and 'func2' entries between mruby and ruby
3. in backtrace for 'func1',  'raise_func' is replaced by 'use_some_more_stack'  even though it was not on the call stack when the exception was thrown, but was called right before printing the backstack

**Comment by IceDragon200** [comment]
mruby pulls the stacktrace, instead of storing it on raise the moment you call `Exception#backtrace`, I've been meaning to make an issue for this myself.
So if you catch an exception and store it for later and try to get the backtrace it will give you the current stacktrace rather than the exception's stacktrace (if this makes any sense)

To solve this, the backtrace should be saved into the raised exception, if the backtrace was already set, just leave it as is. (in the case of exception forwarding)

Something like:
```ruby
def create_exception(exception_klass, str, *args)
  backtrace = current_stack_trace.dup
  inst = exception_klass.new
  inst.message = format(str, *args)
  inst.backtrace = backtrace
  inst
end  
```
Now you can't do this in ruby obviously, since this would mangle the stack trace

**Comment by yregelman** [comment]
Actually exception forwarding stacktrace also seems broken:

```
def raise_func
  raise "noise"
end

def err_func
  raise_func
end

def func
  begin
    err_func
  rescue => e
    raise e
  end
end


func
```
$ ruby broken_rethrow_backtrace.rb
broken_rethrow_backtrace.rb:2:in `raise_func`: noise (RuntimeError)
	from broken_rethrow_backtrace.rb:6:in `err_func`
	from broken_rethrow_backtrace.rb:11:in `func`
	from broken_rethrow_backtrace.rb:18:in `main`

$ ../mruby/git/mruby/bin/mruby broken_rethrow_backtrace.rb
trace:
	[1] broken_rethrow_backtrace.rb:13:in Object.func
	[0] broken_rethrow_backtrace.rb:18
broken_rethrow_backtrace.rb:13: noise (RuntimeError)


I'm surprised this issue is not getting more attention.  Seems like the core language feature is broken here.  Makes debugging even harder than it already is, especially since you can't enforce any special workarounds on other ruby libraries you might want to use in your project.

**Comment by cremno** [comment]
I'm still a bit unsure about it but https://github.com/cremno/mruby/commit/a6a7ce8d5fa957aee5ebe481a0ca574074473150 seems to fix at least the original issue.

>Actually exception forwarding stacktrace also seems broken:

That looks like a different issue. (Btw., `Exception.exception` is defined twice: in `src/error.c` and `mrblib/error.rb`.)

**Comment by yregelman** [comment]
Hi Cremno, I applied your patch to my project and so far it looks like it is working great.
You are right, this does not fix the exception forwarding stacktrace, but it looks like it is a big part of the solution for that problem as well.
Thanks!
