### ISSUE TITLE
Segfault while closing 

### ISSUE THREAD

**Issue by asfluido** [mruby/mruby#2911]
Hello again.

In my by now reasonably complex mruby application (unstripped mruby executable is about 11.5MB, linking to 106 shared libraries), I have for some time come across a crash that would happen when closing down the application (either with a `raise` or by Ctrl-C). The segfault takes place on line 279 of `vm.c`. 

The line is in the `ecall` function, and reads as follows:

```ruby
  ci->nregs = p->body.irep->nregs;
```

The address of `p` is bogus (0x91). The interesting thing is is that `ecall` is called from `vm.c`, line 1036, function `mrb_contect_run`, which passes parameter `i` as `-1`. 

This is effectively the value of `ci->eidx` as read on line 1033. 

Now: I **don't know** how that value came to be assigned. But it sounded improper to send it forward. I Thus I modified line 1035 from

```ruby
      for (n=0; n<a && (ci == mrb->c->cibase || eidx > ci[-1].eidx); n++) {
```

to 

```ruby
      for (n=0; n<a && eidx>0 && (ci == mrb->c->cibase || eidx > ci[-1].eidx); n++) {
```

With this little patch, my application now does not segfault anymore, and seems to behave properly. 

 As with my previous issue, I have no idea if this is the proper fix. In this case, I cannot say if an eidx of -1 at that point is a legal value, or if its origin should be investigated.

**Comment by matz** [comment]
It seems #2910 is related, and 5af770 should fix this too.  Could you recheck with the latest?

**Comment by asfluido** [comment]
Of course! The result is the same. I had a 3-day-old codebase and I thought that that was recent enough... Thanks for replying.
