### ISSUE TITLE
Undefined method '[]' when overriding square bracket operator with multiple indexes

### ISSUE THREAD

**Issue by Moon4u** [mruby/mruby#2918]
```ruby
class SomeArray
  def initialize(x, y = 1, z = 1)
    @xs = x
    @ys = y
    @zs = z
    @values = Array.new(x*y*z, 0)
  end

  def [](x, y = 0, z = 0)
    @values[x + y * @xs + z * @xs * @ys]
  end

  def []=(x, y = 0, z = 0, v = 0)
    @values [x + y * @xs + z * @xs * @ys] = v
  end
end
a = SomeArray.new(2, 2, 2)
a[0][0][0]
```
in ruby
```ruby
=> 0
```
in mruby
```mruby
(mirb):18: undefined method '[]' for 0 (NoMethodError)
```

As far as I know, I can use a[0, 0, 0] instead, but I need this for compatibility with ruby code.

**Comment by cremno** [comment]
I believe you want to use `a[0,0,0]` anyway. Because `a[0][0][0]` in your example calls `SomeArray#[]` and then 2x `Fixnum#[]`. Is that really what you want to do?

Adding [`Fixnum#[]`](http://ruby-doc.org/core/Fixnum.html#method-i-5B-5D) would be easy though. I think it even can be done in Ruby.

**Comment by Moon4u** [comment]
Is that really what's happening? I thought that in ruby it calls SomeArray's overriding method with the given parameters. I guess I misunderstood the legacy code. 

Thanks.
