### ISSUE TITLE
Question: How is puts et al. implemented?

### ISSUE THREAD

**Issue by scorpion007** [mruby/mruby#2928]
I couldn't find their definition, yet I see it in some of the samples.

I ask because I notice care was taken to provide a stdio-less option, but does that mean all hosts must roll their own expose a 'puts' function in the global namespace? I also don't see an IO class (I think puts would call IO.write in CRuby?)

**Comment by matz** [comment]
puts (simple output) is defined in `mruby-print` mrbgem.  `IO` class is defined in `mruby-io` mrbgem.

**Comment by scorpion007** [comment]
Thanks for the pointer!

However, I notice printstr calls fwrite to stdout directly.

    fwrite(s, len, 1, stdout);

This is problematic for embedders, since in GUIs they often have their own notion of "standard output". It would be better if all such IO went through a custom `mrb_fwrite`, etc which would default to fwrite, but the caller could override. (`mrb_set_stdio_callbacks` or something like that).

**Comment by cremno** [comment]
I agree. Squirrel has a [sq_setprintfunc()](http://squirrel-lang.org/doc/squirrel3.html#sq_setprintfunc) function. However simply overwriting `__printstr__` is sufficient here, isn't it?
