### ISSUE TITLE
Keys of hash are modifyable, leads to unexpected behavior

### ISSUE THREAD

**Issue by kazuho** [mruby/mruby#2945]
In case of MRI the keys returned by `Hash#keys` are frozen.  However they are not frozen in case of mruby, and leads to unexpected behavior when being modified.

```
$ bin/mirb 
mirb - Embeddable Interactive Ruby Shell

> h = {"AAA" => "b"}; h.keys[0].chop!
 => "AA"
> h
 => {"AA"=>"b"}
> h["AA"]
 => nil
> h["AAA"]
 => nil
```

I have not gone through the ISO specification of Ruby, but I believe that the keys should be frozen in case of mruby as well.

**Comment by matz** [comment]
I know it's safer, but it also consumes more memory (both code size and copied keys). SInce mruby should be memory efficient, I hesitate to seek safety over memory.

**Comment by kazuho** [comment]
Thank you for the response.

> I know it's safer, but it also consumes more memory (both code size and copied keys). SInce mruby should be memory efficient, I hesitate to seek safety over memory.

The points make sense, however my understanding is that it can be fixed at least in the same way as done in MRI now that you have implemented `String#freeze`.

Anyways I have opened a PR that does it.  I am sorry for bothering you in this corner case, but I would appreciate it if you could take a look at it.  Thank you in advance.

**Comment by matz** [comment]
OK, we already dup the key, so adding frozen flag is nothing.  I will merge #2947
