### ISSUE TITLE
get ruby backtrace from c

### ISSUE THREAD

**Issue by schmurfy** [mruby/mruby#2954]
What is the best way (and working way) to find out what is the last ruby line which was executed before entering the C side ?

I tried various ways but they don't seem to be very reliable...
My last attempt is (this is based on code from debug.c and backtrace.c):

``` C
  if( mrb ){
    if( mrb->c && mrb->c->ci ){
      mrb_callinfo *ci = mrb->c->ci;
      mrb_code *pc0 = ci->pc;
      mrb_int ciidx = (mrb_int)(ci - mrb->c->cibase - 1);

      const char *file = "";
      uint32_t line = 0;

      for (i = ciidx; i >= 0; i--) {
        ci = &mrb->c->cibase[i];

        if (!ci->proc) continue;
        if (MRB_PROC_CFUNC_P(ci->proc)) {
          continue;
        }
        else {
          const char *ruby_file;
          uint32_t ruby_line;

          mrb_irep *irep = ci->proc->body.irep;
          mrb_code *pc;

          if (mrb->c->cibase[i].err) {
            pc = mrb->c->cibase[i].err;
          }
          else if (i+1 <= ciidx) {
            pc = mrb->c->cibase[i+1].pc - 1;
          }
          else {
            pc = pc0;
          }

          ruby_file = mrb_debug_get_filename(irep, (uint32_t)(pc - irep->iseq));
          ruby_line = mrb_debug_get_line(irep, (uint32_t)(pc - irep->iseq));

          if (ruby_line != -1 && ruby_file) {
           // if we got there it worked, yeah o//   \\o \o/
            file = ruby_file;
            line = ruby_line;
            break;
          }
        }
      }
  }
}
```

This works sometimes but not everytime

**Comment by beoran** [comment]
The functions mrb_debug_get_filename() mrb_debug_get_line() only work if debugging information is available. For mrbc compiled scripts this requires the -g option. I don't know how to enable this for mrb scripts parsed at run time. I guess lack of debugging information explains why it doesn't always work for you?

**Comment by schmurfy** [comment]
While it was closed as "not a bug" I am pretty sure fixes have been made to fix issues related to batcktrace, that's not my only issue opened on this subject.
mruby has been evolving pretty quickly so the state it is in now has not much to do with what it was more than one year ago :)

PS: and yes I had debug symbols in that case
