### ISSUE TITLE
GC not reclaiming objects

### ISSUE THREAD

**Issue by schmurfy** [mruby/mruby#2955]
In my project I have a C core running MRuby scripts by calling functions in the VMS, basically I do this:

``` C
mrb_funcall(mrb, r_output, "flush", 0);
```

What I noticed recently is that object created in the flush method are not collected by the GC, here is the most simple ruby method I tested:

```
def flush
   built_msgs = {}
end
```

I then called it in loop and printed `arena_idx` and it increased everytime, since this method is not creating any persistent objects I tested a workaround (which works):

``` C
int idx = mrb_gc_arena_save(mrb);
mrb_funcall(mrb, r_output, "flush", 0);
mrb_gc_arena_restore(mrb, idx);
```

I consider this a bug, but is it ? I am doing something wrong ?

PS: I tried with 1.1.0 with same result, i tried master but it does not compile
PS2: if really necessary I can try to build a minimal application to reproduce it.

**Comment by matz** [comment]
It is not a bug, since `mrb_funcall()` protects its return value from accidental GC reclamation.  So you have to wrap it with arena_save/arena_restore. I still have to investigate if removing return value protection still works without causing this issue.

**Comment by schmurfy** [comment]
ah ok I understand now, what bothered me was that after a few changes this "leak" occured but I could not figure why but now it makes sense since the created hash is now the last evaluated value and so it is returned.

This make senses but I think this is still a trap, it would seems more logical for me to never ever protect anything unless specifically asked, althought a lot of documentation has now appeared the main issue is still it, I have been working with mruby on a few projects for around 2 years now judging by the first commit and I had no idea the return value of a mrb_funcall was protected so it might say a lot for newcomers...

is this behavior documented somewhere ?

**Comment by matz** [comment]
I have experimented to remove protection from `mrb_funcall` and saw a lot of GC errors. We found out we assume GC protection of return value from from `mrb_funcall`.

Maybe we can provide a new function without return value protection, but I cannot think of any good name candidate for the function. `mrb_funcall_void`?

**Comment by schmurfy** [comment]
I also thought about a new function, not about naming though xD
The name should be explicit, maybe `mrb_unprotected_funcall`, this might sound scary at first but if documented it should be ok (even a comment before the function definition).

There is another option, since there are 3 different funcall variants:
Adding one argument to all of them, changing the name and using a macro, this is arguably less clean but that is an option :)
(mrb_funcall2 is a placeholder, we would still need a new name)
```c
MRB_API mrb_value mrb_funcall2(mrb_state*, int protect, mrb_value, const char*, mrb_int,...);
#define mrb_funcall(MRB, VAL, FUNC, COUNT, ...) mrb_funcall2(MRB, 1, VAL, FUNC, COUNT, __VA_ARGS__ )
```


Also, is there an opposite function to `mrb_gc_protect`, I just looked at it and it does not appear to be one but I might have overlooked something.

**Comment by schmurfy** [comment]
any news on this ? The name does not really matter for me but it would be nice to have this method available.
