### ISSUE TITLE
on Ubuntu 14.04, yields "undefined reference"

### ISSUE THREAD

**Issue by Titanl** [mruby/mruby#2969]
When I try to compile my code:
gcc-4.6 -Iext/mruby-1.1.0/include -Lext/mruby-1.1.0/build/host/lib/ -lmruby -lmruby_core main.cpp
gcc (clang respectively) yields "undefined reference" for basic mruby functions:
mrb_open, mrb_load_file, mrb_funcall, mrb_close

This happens on Ubuntu 14.04, but not on Ubuntu 12.04.
WIth a copy of the working .a files to Ubuntu 14.04 (from my 12.04 VM), it still yields "undefined reference".

**Comment by Titanl** [comment]
with updated Ubuntu 12.04, this happens as well

**Comment by cremno** [comment]
Try `main.cpp -lmruby` instead of `-lmruby -lmruby_core main.cpp`.

**Comment by Titanl** [comment]
this is ridiculous, but works.
Many thanks!

**Comment by matz** [comment]
Closing the issue. If you have anything, please reopen.
