### ISSUE TITLE
mruby does not compile on the latest Android NDK

### ISSUE THREAD

**Issue by dragostis** [mruby/mruby#2974]
First of all, `string.h` is missing from the Android NDK.

```
mruby-1.1.0/src/debug.c:1:20: fatal error: string.h: No such file or directory
 #include <string.h>
```

Even if you add it manually, you still get into more trouble:

```
mruby-1.1.0/build/host/lib/libmruby_core.a(y.tab.o):y.tab.c:function yy_stack_print: error: undefined reference to 'fputc'
... // and way more
```

**Comment by dragostis** [comment]
Here's what the latest version of the NDK says:

> Using the NDK toolchain directly has a serious limitation: You won't be able to use any C++ STL (STLport, libc++, or the GNU libstdc++) with it. Also no exceptions and no RTTI."

**Comment by matz** [comment]
Does any one have info? @crimsonwoods ?

**Comment by dragostis** [comment]
Missing `string.h` can be solved easily by setting `SYSROOT` properly. By fixing this, you can compile for `armeabi`, `armeabi-v7a`, `x86` and `mips`, but you cannot compile for `arm64-v8a`, `x86_64` and `mips64`.

I would happily update the script myself, but I have no idea what flags are necessary for the newer (64 bit) architectures.

**Comment by crimsonwoods** [comment]
I have no info to fix the issue currently and I cannot help soon.
Because I have a fever now.
After my bad health is cured, and if the issue was not fixed, I can try to fix, maybe.

**Comment by sagmor** [comment]
Just compiled on `master` with this `build_config.rb`:
```ruby
MRuby::CrossBuild.new('android') do |conf|
  toolchain :androideabi
end
```

and this command:
```
ANDROID_NDK_HOME=/usr/local/opt/android-ndk \
GCC_VERSION=4.9 \
ANDROID_TARGET_ARCH_ABI=arm64-v8a \
ruby ./minirake
```

And at least it compiled without problems.

**Comment by sagmor** [comment]
By the way.

It would be great to get feedback for #2983 :stuck_out_tongue:

**Comment by crimsonwoods** [comment]
Current build script `androideabi.rake` is not support 64bit architectures (arm64, mips64 and x86_64) as @dragostis said.
Adding 64bit architecture support into 'androideabi.rake' is not so difficult. Because every required compiler options are written into `setup.mk` and that file is bundled with NDK.
`/path/to/your/NDK/toolchains/aarch64-linux-android-4.9/setup.mk` is one of `setup.mk`.

**Comment by crimsonwoods** [comment]
#2983 looks not enough for 64bit architecture for me, but that's good, I think.
`androideabi.rake` should be replaced by `androidndk.rake`, as soon as possible.
So, I have no motive to update `androideabi.rake`, currently.
We should maintain only `androidndk.rake`.

By the way, only adding "ANDROID_TARGET_ARCH_ABI=arm64-v8a" is not enough to build for 64bit architecture.
Prefix of toolchains and CFLAGS/LDFLAGS have to be changed.

**Comment by matz** [comment]
@crimsonwoods So you mean, we should merge #2983 and remove androidabi.rake, right?

**Comment by crimsonwoods** [comment]
@matz Yes. 'androidndk.rake' is better than 'androideabi.rake' for me. Of course, remaining 'androideabi.rake' to keep compatibility is not bad.

**Comment by crimsonwoods** [comment]
I uploaded tentative workaround to fix this issue for `arm64` architecture.
See diff https://github.com/mruby/mruby/compare/master...crimsonwoods:update_androideabi_rake
Support for `mips64` and `x86_64` are not supported.

**Comment by matz** [comment]
@crimsonwoods should I update andoidndk.rake according to your patch?

**Comment by crimsonwoods** [comment]
@matz Thank you for your kindness. I should make a new pull-request to update it.

**Comment by matz** [comment]
@crimsonwoods will you? I appreciate your cooperation.
I am going to remove androideabi.rake after your pull-request.

**Comment by crimsonwoods** [comment]
@matz I did. I submitted a new PR #2988. please see that.

@sagmor would you review my PR?. and let me know your feedback if you found something.

@dragostis would you try my PR to build mruby on your environment for your target architecture?

**Comment by matz** [comment]
#2988 merged.

**Comment by sagmor** [comment]
@crimsonwoods Everything looks fine!

Never played with higher platform numbers. Now I understand why I couldn't see the 64bits arch failure :stuck_out_tongue:
