### ISSUE TITLE
input line too long under windows

### ISSUE THREAD

**Issue by kaibioinfo** [mruby/mruby#2976]
Hi,

I'm trying to compile mruby under windows 7 with visual studio 10.0. However, I always get the error
```
input line too long
```
for the following line in mruby_build_commands.rake in line 294:
```ruby
IO.popen("#{filename @command} #{@compile_options % {:funcname => funcname}} #{filename(infiles).join(' ')}", 'r+') do |io|
  out.puts io.read
end
```

It seems that the visual studio commandline prompt is not able to handle lines with too much characters...

**Comment by matz** [comment]
I don't have WIndows programming skills nor WIndows machine.  Will anybody help us please?

**Comment by mattn** [comment]
afaik, the message `input line too long` appear when environment variables are too long. i often see the error when CLASSPATH is expanded from nested `%CLASSPATH%`.
currently, I don't reproduce. @kaibioinfo could you please confirm your environment variables?

**Comment by kaibioinfo** [comment]
Thanks for the fast answers!

I can isolate the problem on this line:
```ruby
# this is the parameter which is given to IO.popen in line 294
cmd = %q{"D:\mruby\build\host\bin\mrbc.exe" -Bmrblib_irep -o- -g "D:\mruby\mrblib\array.rb" "D:\mruby\mrblib\class.rb" "D:\mruby\mrblib\compar.rb" "D:\mruby\mrblib\enum.rb" "D:\mruby\mrblib\error.rb" "D:\mruby\mrblib\hash.rb" "D:\mruby\mrblib\kernel.rb" "D:\mruby\mrblib\numeric.rb" "D:\mruby\mrblib\range.rb" "D:\mruby\mrblib\string.rb"}

IO.popen(cmd) {|io| io.read}
# Input line too long
#=> nil
IO.popen("dir") {|io| io.read} #=> that, however, is working
Ruby_VERSION #=> 2.2.2
```
Strangely, I can run the same command within my command prompt and it outputs the bytecode of the ruby files. I cannot, however, run the command within JRuby, so it might be not an MRI problem.

I guess a workaround would be to split the bytecode generation in a reduce loop, running mrbc for every file separately. However, I'm curious if other windows user have the same problem.

**Comment by mattn** [comment]
How about this?
```ruby
IO.popen("#{filename @command} #{@compile_options % {:funcname => funcname}} #{filename(infiles).join(' ')}", 'r+') do |io|
  IO.copy_stream(io, out)
end
```

**Comment by kaibioinfo** [comment]
Ouch, sorry! While checking my path variable I recognized that the JRuby bins come before my MRI bins. So I ran rake with JRuby the whole time.
When switching to MRI the problem disappears. So the "input line too long" seems to be JRuby-related. I will open an issue in the JRuby tracker.
Thx.
