### ISSUE TITLE
mrb_value returns MRB_TT_OBJECT when MRB_TT_DATA is expected

### ISSUE THREAD

**Issue by Moon4u** [mruby/mruby#2980]
I'm writing a [SDL_gpu](https://github.com/grimfang4/sdl-gpu/) gem and I'm trying to encapsulate a structure and expose it in mruby. I'm creating a ``mrb_data_type``. When I try to get the pointer to the structure (from mrb_value) with ``mrb_data_get_ptr`` I get error message:
``wrong argument type *name* (expected Data) (TypeError)``
I found out that mruby is treating the ``mrb_value`` as MRB_TT_OBJECT instead of MRB_TT_DATA. I can manually set the type of the ``mrb_value`` as MRB_TT_DATA and that fixes the problem, but I'm not sure that I'm supposed to do that. I worked a little bit on a fork of the SDL gem, and I used the same methods for encapsulating structures, but I didn't had such problems there.

Example code can be seen here:
["encapsulation"](https://github.com/Moon4u/mruby-sdl2-gpu/blob/master/src/gpu.c#L134-L181)
[functions](https://github.com/Moon4u/mruby-sdl2-gpu/blob/master/src/gpu.c#L1855-L1962)

**Comment by take-cheeze** [comment]
You've forgot `MRB_SET_INSTANCE_TT`.

**Comment by Moon4u** [comment]
That seems so obvious right now.

Thank you for the quick response.
