### ISSUE TITLE
How to Allocate and Initialize?

### ISSUE THREAD

**Issue by Mav7** [mruby/mruby#2981]
In Ruby you have rb_define_alloc_func to define our allocation methods how would I go about doing this in mruby? Also when writing the initialize method I maybe want to use Data_Get_Struct but it's defined under a comment saying "/* obsolete functions and macros */" what would I use in it's place in mruby?

**Comment by cremno** [comment]
Do the allocations in `#initialize. See https://github.com/mruby/mruby/issues/9#issuecomment-147048489

>what would I use in it's place in mruby?

`mrb_data_get_ptr()` or `DATA_GET_PTR()`. They're basically the same except they return the data pointer instead of taking a pointer as argument.

**Comment by Mav7** [comment]
Thank so much for the help!
