### ISSUE TITLE
frexpl and frexp issues in fmt_fp.c

### ISSUE THREAD

**Issue by bovi** [mruby/mruby#2998]
At https://github.com/mruby/mruby/blob/master/src/fmt_fp.c#L93 we have the following construct:
```
#if ((defined(__CYGWIN__) || defined(__NetBSD__) || defined(mips)) && !defined(__linux__)) || defined(__android__)
#undef frexpl
#define frexpl frexp
#endif
```
I had a look in the history and over time people have appended more and more exceptions due to the missing frexpl. I now have a case where I cross-compile for mips 34kc by using uClibc. In this case ```defined(mips)) && !defined(__linux__)``` is not correct due to the reason that this linux with mips has no frexpl. I don't wanna change this part by append also my case there and make it even more complex. Instead I want to have some feedback if someone has an idea how we can get rid of this problem. One example would be to default to frexp instead of frexpl which of course reduces from long double to float but this case would work on more platforms. Another option would be to make it choosable to use float or long.

**Comment by cremno** [comment]
>One example would be to default to frexp instead of frexpl

I (still) believe this is the optimal solution. See #2879.

**Comment by matz** [comment]
#2879 merged.
