### ISSUE TITLE
XSB path-- cd $XSB_DIR does not work

### ISSUE THREAD

**Issue by Romeee** [mruby/mruby#3042]
hello,
I want to work on cygwin64 to open XSB directory but the flowing error appears
cd $XSB_DIR
-bash: cd: C:/"Program: No such file or directory

XSB path in environment variable with name:
 XSB_DIR: C:/"Program Files (x86)"/XSB
and PATH: C:/"Program Files (x86)"/XSB

can any person help me please??

**Comment by matz** [comment]
I am afraid it's Cygwin issue, not mruby issue. I am sorry but I close this here.
