### ISSUE TITLE
String to Integer conversion incompatibility with CRuby

### ISSUE THREAD

**Issue by tsahara** [mruby/mruby#3043]
`Kernel#sprintf` behaves differently from CRuby for some inputs.
(I found these incompatibilities while applying https://github.com/mruby/mruby/commit/0701236dacd1c108d79f9cc90665fb4069d43c55 to our fork of mruby repository.)

```
% bin/mruby -e 'sprintf("%u", "0x")'
trace:
        [0] -e:1
-e:1: string contains null byte (ArgumentError)

% ruby -e 'sprintf("%u", "0x")'
-e:1:in `sprintf': invalid value for Integer(): "0x" (ArgumentError)
	from -e:1:in `<main>'
```

The message of the exception mruby raises is wrong ("0x" does not contain any nul character).  `"0x"` can be `"-"`, `"+"`, or "".

```
% bin/mruby -e 'p sprintf("%u", "0_1")'
trace:
	[0] -e:1
-e:1: invalid string for number("0_1") (ArgumentError)

% ruby -e 'p sprintf("%u", "0_1")'
"1"
```

It should be "1".

```
% bin/mruby -e 's="0x0"+"0"*100; t=s[0,2]; p t, sprintf("%u", t)'
"0x"
"0"

% ruby -e 's="0x0"+"0"*100; t=s[0,2]; p t, sprintf("%u", t)'
-e:1:in `sprintf': invalid value for Integer(): "0x" (ArgumentError)
	from -e:1:in `<main>'
```

I don't know which one is right but they behave differently.

```
% bin/mruby -e 's="1_"+"0"*100; t=s[0,2]; p t, sprintf("%u", t)'
"1_"
"10"

% ruby -e 's="1_"+"0"*100; t=s[0,2]; p t, sprintf("%u", t)'
-e:1:in `sprintf': invalid value for Integer(): "1_" (ArgumentError)
	from -e:1:in `<main>'
```

It should raise an exception, or return "1" (not "10").

**Comment by tsahara** [comment]
Thank you for fixing the first issue.  But others are not changed.  Especially, 3rd one looks strange to me because it returns a string when it takes a shared string as an argument but raises an exception when it takes a non-shared string.  For example:

a.rb:
```rb
s = "0x0" + "0" * 100

a = "0x"
b = s[0, 2]

puts "a=#{a}"
puts "b=#{b}"
puts "(a==b) == #{a==b}"

begin
  printf "'%%u' %% a => "
  printf "%u\n", a
rescue => e
  printf "(#{e})\n"
end

begin
  printf "'%%u' %% b => "
  printf "%u\n", b
rescue => e
  printf "(#{e})\n"
end
```

```
% bin/mruby a.rb
a=0x
b=0x
(a==b) == true
'%u' % a => (invalid string for number("0x"))
'%u' % b => 0
```

**Comment by matz** [comment]
Sorry for the partial fix.  I will fix the rest of the problems.
