### ISSUE TITLE
Cross-compilation for Windows using MinGW fails

### ISSUE THREAD

**Issue by YordanAdamov** [mruby/mruby#3046]
When I try to cross-compile MRuby for Windows on Linux Mint 17.2 using MinGW I get a lot of messages like the ones bellow and compilation fails.

/home/d/projects/mrubyscript/mruby/build/win32/lib/libmruby.a(codedump.o):codedump.c:(.text+0x5a): undefined reference to `_putchar'
/home/d/projects/mrubyscript/mruby/build/win32/lib/libmruby.a(codedump.o):codedump.c:(.text+0x120): undefined reference to `_printf'
/home/d/projects/mrubyscript/mruby/build/win32/lib/libmruby.a(dump.o):dump.c:(.text+0x30f): undefined reference to `_memcpy'
/home/d/projects/mrubyscript/mruby/build/win32/lib/libmruby.a(backtrace.o):backtrace.c:(.text+0x15a): undefined reference to `_fputc'
/home/d/projects/mrubyscript/mruby/build/win32/lib/libmruby.a(backtrace.o):backtrace.c:(.text+0x6d7): undefined reference to `__imp___iob'
/home/d/projects/mrubyscript/mruby/build/win32/lib/libmruby.a(vm.o):vm.c:(.text+0xc00): undefined reference to `__setjmp3'
/home/d/projects/mrubyscript/mruby/build/win32/lib/libmruby.a(symbol.o):symbol.c:(.text+0x16f1): undefined reference to `_memcmp'
/home/d/projects/mrubyscript/mruby/build/win32/lib/libmruby.a(numeric.o):numeric.c:(.text+0x297): undefined reference to `_pow'
/home/d/projects/mrubyscript/mruby/build/win32/lib/libmruby.a(debug.o):debug.c:(.text+0x3c8): undefined reference to `_strlen'
/home/d/projects/mrubyscript/mruby/build/win32/lib/libmruby.a(print.o):print.c:(.text+0xb8): undefined reference to `_fwrite'
/home/d/projects/mrubyscript/mruby/build/win32/lib/libmruby.a(math.o):math.c:(.text+0xc30): undefined reference to `_erfc'
/home/d/projects/mrubyscript/mruby/build/win32/lib/libmruby.a(time.o):time.c:(.text+0x29): undefined reference to `___ms_vsnprintf'
/home/d/projects/mrubyscript/mruby/build/win32/lib/libmruby.a(range.o):range.c:(.text+0x74e): undefined reference to `_ceil'
/home/d/projects/mrubyscript/mruby/build/win32/lib/libmruby.a(random.o):random.c:(.text+0x181): undefined reference to `_time'
/home/d/projects/mrubyscript/mruby/build/win32/lib/libmruby.a(fiber.o):fiber.c:(.text+0x259): undefined reference to `_memset'
/home/d/projects/mrubyscript/mruby/build/win32/lib/libmruby.a(sprintf.o):sprintf.c:(.text+0x29): undefined reference to `___ms_vsnprintf'

Has anyone tried this before? 
What can I do to fix these errors?

**Comment by matz** [comment]
The log looks like you are lacking basic functions like printf etc.  That indicates your installation of MinGW is incomplete.  Could you cross-compile other software using your MinGW?

**Comment by syohex** [comment]
@YordanAdamov Did you set linker command correctly ?

I can cross-compile by adding following configuration to `build_config.rb`.
```ruby
MRuby::CrossBuild.new('mingw') do |conf|
  toolchain :gcc

  conf.cc.command = 'x86_64-w64-mingw32-gcc'
  conf.linker.command = 'x86_64-w64-mingw32-gcc'

  conf.gembox 'default'
end
```

NOTE I install following mingw packages for testing on Ubuntu 14.04(Linux Mint 17.2 is based on this Ubuntu).

```
syohei@mingw:~/mruby$ dpkg -l |grep mingw
ii  binutils-mingw-w64-i686             2.23.52.20130620-1ubuntu1+3build1 amd64        Cross-binutils for Win32 (x86) using MinGW-w64
ii  binutils-mingw-w64-x86-64           2.23.52.20130620-1ubuntu1+3build1 amd64        Cross-binutils for Win64 (x64) using MinGW-w64
ii  g++-mingw-w64                       4.8.2-10ubuntu2+12                all          GNU C++ compiler for MinGW-w64
ii  g++-mingw-w64-i686                  4.8.2-10ubuntu2+12                amd64        GNU C++ compiler for MinGW-w64 targeting Win32
ii  g++-mingw-w64-x86-64                4.8.2-10ubuntu2+12                amd64        GNU C++ compiler for MinGW-w64 targeting Win64
ii  gcc-mingw-w64                       4.8.2-10ubuntu2+12                all          GNU C compiler for MinGW-w64
ii  gcc-mingw-w64-base                  4.8.2-10ubuntu2+12                amd64        GNU Compiler Collection for MinGW-w64 (base package)
ii  gcc-mingw-w64-i686                  4.8.2-10ubuntu2+12                amd64        GNU C compiler for MinGW-w64 targeting Win32
ii  gcc-mingw-w64-x86-64                4.8.2-10ubuntu2+12                amd64        GNU C compiler for MinGW-w64 targeting Win64
ii  gfortran-mingw-w64                  4.8.2-10ubuntu2+12                all          GNU Fortran compiler for MinGW-w64
ii  gfortran-mingw-w64-i686             4.8.2-10ubuntu2+12                amd64        GNU Fortran compiler for MinGW-w64 targeting Win32
ii  gfortran-mingw-w64-x86-64           4.8.2-10ubuntu2+12                amd64        GNU Fortran compiler for MinGW-w64 targeting Win64
ii  gnat-mingw-w64                      4.8.2-12ubuntu2+12.1              all          GNU Ada compiler for MinGW-w64
ii  gnat-mingw-w64-base                 4.8.2-12ubuntu2+12.1              amd64        GNU Ada compiler for MinGW-w64 (base package)
ii  gnat-mingw-w64-i686                 4.8.2-12ubuntu2+12.1              amd64        GNU Ada compiler for MinGW-w64 targeting Win32
ii  gnat-mingw-w64-x86-64               4.8.2-12ubuntu2+12.1              amd64        GNU Ada compiler for MinGW-w64 targeting Win64
ii  mingw-w64                           3.1.0-1                           all          Development environment targetting 32- and 64-bit Windows
ii  mingw-w64-common                    3.1.0-1                           all          Common files for Mingw-w64
ii  mingw-w64-i686-dev                  3.1.0-1                           all          Development files for MinGW-w64 targeting Win32
ii  mingw-w64-tools                     3.1.0-1                           amd64        Development tools for 32- and 64-bit Windows
ii  mingw-w64-x86-64-dev                3.1.0-1                           all          Development files for MinGW-w64 targeting Win64
```

**Comment by YordanAdamov** [comment]
Adding the configuration in the build_config.rb was the solution.
Thanks a lot.
