### ISSUE TITLE
mrb_parser_message::column broken after observing a variable

### ISSUE THREAD

**Issue by kazuho** [mruby/mruby#3053]
It seems like that `mrb_parser_message::column` gets incremented once more than it should have been, every time the parser observes a variable.

How to reproduce:

1. apply the patch at https://gist.github.com/kazuho/d775cc196ad3de280f40 and rebuild mirb
2. run mirb and evaluate strings like: `[a]]`

You would see results like following.
Expected results: ```column 8``` for all expressions.
Actual results: the reported column is 8 + number of variables found in the expression.

```
> [1,1,1]]
line 6:column 8: syntax error, unexpected ']', expecting $end
> [1,1,a]]
line 7:column 9: syntax error, unexpected ']', expecting $end
> [1,a,a]]
line 8:column 10: syntax error, unexpected ']', expecting $end
> [a,a,a]]
line 9:column 11: syntax error, unexpected ']', expecting $end
```

**Comment by matz** [comment]
#3054 fixed this.  Thanks.

**Comment by kazuho** [comment]
Thank you for merging the PR!
