### ISSUE TITLE
Do Array#== and Array#eql? have code which not is reached?

### ISSUE THREAD

**Issue by suzukaze** [mruby/mruby#3060]
mrblib/array.rb

@matz wrote:

--------------------------------------------

Array#==
```
  def ==(other)
    other = self.__ary_eq(other)
    return false if other == false
    return true  if other == true
    len = self.size
    ...
```

Array#eql?
```
  def eql?(other)
    other = self.__ary_eq(other)
    return false if other == false
    return true  if other == true
    len = self.size
    ...
```

--------------------------------------------

`return false if other == false` or `return true  if other == true` always execute return;
The following `len = self.size` code always is not executed.

**Comment by matz** [comment]
`__ary_eq` returns `true`, `false` or `other` (array), so the logic is correct.
It's weird behavior but `__ary_eq` is an internal check method.

**Comment by suzukaze** [comment]
Thank you. I got it.

```
__ary_eq returns true, false or other (array),
```
