### ISSUE TITLE
Cannot iterate over a Hash without allocating an array?

### ISSUE THREAD

**Issue by sgnr** [mruby/mruby#3073]
I currently use `mrb_hash_keys` to iterate over a hash like this
```c
mrb_value keys = mrb_hash_keys(mrb, value);
for (mrb_int i = 0, f = mrb_ary_len(mrb, keys); i < f; ++i) {
  mrb_value key = mrb_ary_ref(mrb, keys, i);
  mrb_value value = mrb_hash_get(self->state, value, key);
  my_function(key, value);
}
```
This has the downside of allocating an array and copying the keys, just to discard it it right after.

The fact that [mrb_hash_tbl](https://github.com/mruby/mruby/blob/ec711914a4af839fa0bd2cdc6d6d643dd10a915d/include/mruby/hash.h#L67) is exposed as a public API suggests that it is fine to access directly the `kh_ht`. This would allow to iterate without copying by using [`kh_begin and kh_end`](https://github.com/mruby/mruby/blob/ec711914a4af839fa0bd2cdc6d6d643dd10a915d/include/mruby/khash.h#L252-L253). The problem is that they do not work because these macros rely on the declaration of [`struct kh_ht` which is private in `hash.c`](https://github.com/mruby/mruby/blob/ec711914a4af839fa0bd2cdc6d6d643dd10a915d/src/hash.c#L99). In that case, I wonder if the `kh_ht` is really mean to be public?
* If yes, can I move `KHASH_DECLARE` to `khash.h` so it is usable from outside?
* If no, I guess `mrb_hash_tbl` should not be public at all. In that case, what do you think of adding functions similar to these to the Hash API?
```c
typedef size_t mrb_hash_iter_t;
mrb_hash_iter_t mrb_hash_begin(struct mrb_state *mrb, mrb_value hash);
mrb_hash_iter_t mrb_hash_end(struct mrb_state *mrb, mrb_value hash);
mrb_hash_iter_t mrb_hash_next(struct mrb_state *mrb, mrb_value hash, mrb_hash_iter_t iter);
```

Thank you.

**Comment by mattn** [comment]
One another suggestion to use callback.

```c
/* callback can break loop with return FALSE */
void mrb_hash_each(
    struct mrb_state *mrb,
    mrb_value hash,
    int (*callback)(mrb_value key, mrb_value value));
```

**Comment by matz** [comment]
It may cause serious problems if the hash is modified during the iteration. So I am not positive about providing public API to iterate over hashes. Instead I'd rather move `KHASH_DECLARE` to `mruby/hash.h`.
