### ISSUE TITLE
sprintf error on ARMv7 with MRB_INT64

### ISSUE THREAD

**Issue by kazuho** [mruby/mruby#3076]
I get following error when running `make test` on 32-bit ARM with `MRB_INT64`.

```
Fail: String#% (mrbgems: mruby-sprintf)
 - Assertion[1] Failed: Expected to be equal
    Expected: "one=1"
      Actual: "one=0"
 - Assertion[2] Failed: Expected to be equal
    Expected: "1 one 1.0"
      Actual: "0 one 1.0"
```

I assume this is because the implementation unconditionally uses `sprintf "%l?"` to stringify the value at line https://github.com/mruby/mruby/blob/master/mrbgems/mruby-sprintf/src/sprintf.c#L858.

**Comment by matz** [comment]
@kazuho could you check the new code 7c82bfa?

**Comment by kazuho** [comment]
Thank you for the quick fix!  Confirmed that the issue has been solved.
