### ISSUE TITLE
Trying to understand what mrb_intern_static() and mrb_str_new_static() do

### ISSUE THREAD

**Issue by Mav7** [mruby/mruby#3078]
I was trying out some functions in mruby.h to document them. I can't seem to understand what a couple of the static functions like ``mrb_intern_static()``, and ``mrb_str_new_static() ``do. What exactly do they do? For instance what makes ``mrb_intern_static()`` different from ``mrb_intern()``. The only difference I see is in those functions(located in symbol.c) is that the last parameter for sym_intern contains different boolean values.
```C
MRB_API mrb_sym
mrb_intern(mrb_state *mrb, const char *name, size_t len)
{
  return sym_intern(mrb, name, len, FALSE);
}

MRB_API mrb_sym
mrb_intern_static(mrb_state *mrb, const char *name, size_t len)
{
  return sym_intern(mrb, name, len, TRUE);
}
```

**Comment by matz** [comment]
String API with `_static` does not copy the C string passed to it. So it should be called with strings that does not have to be freed, for example, C strings from read-only data section.  For C string literals, there's more handy API with `_lit`.

**Comment by Mav7** [comment]
Thank you!

**Comment by zzak** [comment]
@Mav7 Are they documented?

**Comment by Mav7** [comment]
@zzak They will be. I started just doing the yard docs on my fork of mruby because I didn't want to clutter this repo with too many comments(which yard uses to generate docs). Please review my pull request here if you like https://github.com/Mav7/mruby/pull/2.
