### ISSUE TITLE
Pure ruby example gem - puts missing in 'make test'

### ISSUE THREAD

**Issue by hlogmans** [mruby/mruby#3095]
Hi all,

I noticed a small problem: the example pure ruby gem uses `puts`. This works fine when using `mruby` to interpret some script using this class. But in 'make test' this is a problem, as `puts` is not available. Adding this gem to the test runner does not notice the problem because the method using `puts` is not called, it is only checked if it exists (respond_to). Adding `mruby-print` as a dependency solves this problem.

The question is: using the gembox in `test` (and ruby-print is displayed in the make output), the puts command should be available, or not? If so, it seems to be a problem in test, otherwise the example ruby needs to be updated with a dependency. For the latter, I have a PR ready. If it's the first, maybe @zzak knows what's going on.

**Comment by matz** [comment]
I think you have to add `spec.add_dependency('mruby-print', :core => 'mruby-print')` in your `mgem.rake` file.

**Comment by matz** [comment]
fixed by #3096
