### ISSUE TITLE
GC callback

### ISSUE THREAD

**Issue by dragostis** [mruby/mruby#3097]
Is there any way to hook into the marking phase of the GC? I'm trying to write some bindings for the Rust language and I don't think there is any way of doing this without knowing when mruby is done with some object in order to return the ownership of the struct pointer back to Rust.

**Comment by matz** [comment]
Currently, no. Tell me what kind of hook in what timing, or you can send me pull-request.

**Comment by dragostis** [comment]
I was thinking of something similar to Java's `finalize()`.

I've been able to circumvent the problem by forcing every Rust `struct` to be sent by value to mruby and then returned by value as well. This works well for a functional style and when you have small structs which is okay for a first version.

I'll post a PR after I manage to get some work done on the project.

**Comment by Asmod4n** [comment]
You can use the data types for that;
https://gist.github.com/Asmod4n/12eb2eaee906579e878d

take a look at https://github.com/mruby/mruby/blob/master/include/mruby/data.h

**Comment by dragostis** [comment]
@Asmod4n Thanks a lot for the tip! This will definitely do.

@matz `data.h` definitely does the job. I don't really know if there's an actual need for a `finalize()` method considering the fact that this exists. If you need this in Ruby you can just call a method manually when you're done with the object, so I guess you can close the issue.

**Comment by matz** [comment]
Thanks.

**Comment by robfors** [comment]
I have a question about using DATA classes as finalizers. I followed the strategy previously mentioned to set up a finalizer by creating a DATA object and assigning it to the object of interest. Given that I can not set instance variables on the 'built-in' objects, I have found that the only universal way is to define a singleton method on the object of interest that returns the DATA object. I am assuming that the GC will collect the object of interest then the DATA object then call my GC function.

I don't know much about how the GC works but I am assuming that there could be a time gap between when the object of interest gets collected and when the DATA object gets collected. Is this the case? I need my GC callback function to be called immediately when the object of interest gets collected so can ensure nothing will try to call it.

**Comment by matz** [comment]
I am not sure what you want to do. The finalizers using DATA is a hack to ensure post process of objects from  C written libraries. If you "resurrect" dying objects, the resulting behavior is undefined (usually programs will crash). That means you are not supposed to use them from Ruby.

**Comment by robfors** [comment]
Actually I know how to solve this. I was confusing myself.
Essentially, I was looking to set a GC callback on an object of any type (data, Array, String, etc). But now I realize that I can build a wrapper object for them (of DATA type) and set the callback there.
Thanks for trying to help though.
