### ISSUE TITLE
Cannot compile mrb_load_file in cross-compile

### ISSUE THREAD

**Issue by k-muramatsu** [mruby/mruby#3112]
Hi, We compile mRuby with MDK-ARM. Edit like bellow in reference to [Cross-Compilation](https://github.com/mruby/mruby/blob/master/doc/guides/compile.md#cross-compilation-1) and make "libmruby.lib".
```
MRuby::CrossBuild.new('armcc') do |conf|
	TOOL_PATH = "C:/Keil_v5/ARM/ARMCC/bin"	

	conf.cc do |cc|
		cc.command="#{TOOL_PATH}/armcc"
		cc.flags << "--c99 -g -O0"
		cc.compile_options = "%{flags} -o %{outfile} -c %{infile}"
	end

	conf.linker do |linker|
		linker.command="#{TOOL_PATH}/armlink"
	end

	conf.archiver do |archiver|
		archiver.command = "#{TOOL_PATH}/armar"
		archiver.archive_options = '--create %{outfile} %{objs}'
	end

        # Parser generator settings
	PARSER_PATH = "C:\GnuWin32\bin"
        conf.yacc do |yacc|
		yacc.command = "#{PARSER_PATH}/bison" || 'bison'
		yacc.compile_options = '-o %{outfile} %{infile}'
        end

	conf.exts do |exts|
    exts.library = '.lib'
  end
end
```
But libmruby.lib have no symbol of mrb_load_file like:
```
.\Objects\monitor.axf: Error: L6218E: Undefined symbol mrb_load_file (referred from main.o).
```
I guess it is because cross-compile mode don't parse "parse.y" and don't compile "y.tab.c".
In this case, mrb_load_file defines in parse.y, so we need parse/compile y.tab.c
We don't use define "MRB_DISABLE_STDIO".

Could you give us advice how to parse/compile in cross-compile?

**Comment by matz** [comment]
We need more info. Especially build_config.rb file info. Did you enabled mruby-compiler gem?

**Comment by k-muramatsu** [comment]
Thank you for advice, matz-san.

I add following to build_config.rb, then it works!
```
conf.gem 'mrbgems/mruby-compiler'
```
