### ISSUE TITLE
Fixnum#divmod returns an incompatible result with MRI

### ISSUE THREAD

**Issue by mame** [mruby/mruby#3124]
Is this intentional?

```
$ mruby -e 'p (-32768).divmod(-1)'  # with MRB_INT16
[-32768, 0]

$ ruby -e 'p (-32768).divmod(-1)'
[32768, 0]
```

Re: #3123

**Comment by matz** [comment]
it's not intentional.

**Comment by matz** [comment]
`MRB_INT16` configuration was removed by ff57c0278fe7c2b83231fa40e0284e6685a29ee7
So there's no problem remains.
