### ISSUE TITLE
Is Visual Studio 2012/2010 stil important?

### ISSUE THREAD

**Issue by bggd** [mruby/mruby#3134]
Hi all.

I'm writing appveyor.yml for mruby (https://github.com/bggd/mruby/tree/appveyor).
vs2015 build is success :smile: (https://ci.appveyor.com/project/bggd/mruby/build/1.0.14/job/u4rp73rg3e54w0g8)
vs2010 buid is fail :disappointed: (https://ci.appveyor.com/project/bggd/mruby/build/1.0.14/job/f3t0lf01pmn769c2)

I think mruby should drop supporting of vs2012/vs2010 for several reasons if supporting vs2010 is hard.

- vs2012/vs2010 is bit old nowadays. also it isn't support C99.
- vs2015 fully implements the C99 Standard Library (https://msdn.microsoft.com/en-us/library/hh409293.aspx#BK_CRT).

Thank you.

**Comment by zzak** [comment]
I'm not sure about 2010 and 2012, although @matz has said that only C99 compatible platforms are supported -- what does "dropping support" for these two versions of Visual Studio actually mean? And how does it affect the current mruby users?

As for adding VS2015 support, or at least CI coverage, I'm definite :+1:!

**Comment by bggd** [comment]
>
what does "dropping support" for these two versions of Visual Studio actually mean?

- removing ifdef MACRO of vs2012/vs2010.
- using C99 's local variable declaration.

>
And how does it affect the current mruby users?

vs2012/vs2010, it looks like the compatible of C99 syntax without the declare of local variables. Forthermore, it lacks of many C99's headers or standard library.
Dropping those compiler is more easily to write for cross platform third party mrbgems from *nix guys.

Thank you for reading my bad english.

**Comment by matz** [comment]
I agree with you basically, but I am bit worrying some users may have issues to migrate to the newer VC.
So if someone complains, I might revert the patch.

@bggd could you send us a pull request?

**Comment by bggd** [comment]
> @bggd could you send us a pull request?

I'll try it at this week.

**Comment by yasuyuki** [comment]
We are still using old vs2008 with mruby. But now we are migrating projects into vs2015, so we will not need old vs support at late this year.

**Comment by cremno** [comment]
It could be fixed but I dislike workarounds (even though I'm responsible for some of them). Still I'd be OK with such a change.

Also a conservative counterproposal: deprecate <= VS2012 now and remove all workarounds after the next release (1.3.0?).

**Comment by matz** [comment]
@cremno sounds reasonable. since I have zero knowledge about VC, could you send us a pull request (to deprecate VS2012)?

**Comment by matz** [comment]
#3139 deprecates <=VS2012
