### ISSUE TITLE
different behavior each_with_index.inject 

### ISSUE THREAD

**Issue by matsumoto-r** [mruby/mruby#3137]
Hi, @matz 

`each_with_index.inject` of mruby is a different behavior with CRuby.

- mruby

```
> ["a", "b", "c"].each_with_index.inject("d") { |a, (b, c)| p a, b, c }
"d"
["a", 0]
nil
"d"
["b", 1]
nil
"d"
["c", 2]
nil
 => "d"
```

- CRuby

```
irb(main):006:0> ["a", "b", "c"].each_with_index.inject("d") { |a, (b, c)| p a, b, c }
"d"
"a"
0
["d", "a", 0]
"b"
1
[["d", "a", 0], "b", 1]
"c"
2
=> [[["d", "a", 0], "b", 1], "c", 2]
```

**Comment by matz** [comment]
mruby does not support destructuring in assignment or block parameters yet. #2841

**Comment by matsumoto-r** [comment]
Ah…sorry, Thank you for your pointer!

**Comment by matz** [comment]
Sorry for leaving destructuring unimplemented.

**Comment by zzak** [comment]
@matz Is there a reason it's not implemented? Should we put it on the roadmap, or is there another limitation I'm missing?

**Comment by matz** [comment]
It's difficult (but not impossible) to implement destructuring without adding new instruction (for the sake for compatibility).
