### ISSUE TITLE
"Or equals" operator fails with class variables

### ISSUE THREAD

**Issue by jbreeden** [mruby/mruby#3138]
The "or equals" operator `||=` seems to fail with class variables, but not instance variables.

```Sh
[jared:~/projects/mruby] mirb
mirb - Embeddable Interactive Ruby Shell

> class Test
*  @@var ||= 'testing'
* end
(mirb):4: uninitialized class variable @@var in Test (NameError)
> class Test2
*  @var ||= 'testing'
* end
 => "testing"
```

**Comment by matz** [comment]
Ah, I forgot to support this case. Sorry.
Since it is difficult to implement this without adding instructions, let it be restriction of mruby, at least for a while.

**Comment by matz** [comment]
I got an idea to support this without adding any new instruction using `rescue`.

**Comment by jbreeden** [comment]
Thanks for taking the time! It's easy enough to work around, but I'm trying to run ruby/spec code with as few alterations as possible, so this is very much appreciated!

While the simple case works, in practice I'm seeing "NameError: uninitialized class variable NameError in SocketSpecs." Of course I can't reproduce outside of ruby/spec... but I'll get back to you if I can come up with something.

**Comment by matz** [comment]
@jbreeden I fixed one error, please check if it address your issue.

**Comment by zzak** [comment]
I think this is worth mentioning on the #3140

**Comment by jbreeden** [comment]
Finally got to verify this. The NameError issue is gone. Hurray!
