### ISSUE TITLE
mrb_int_mul_overflow is missing

### ISSUE THREAD

**Issue by Asmod4n** [mruby/mruby#3149]
Currently multiplications aren't checked for overflowing, there is __builtin_mul_overflow in GCC/Clang etc. I just don't know how to implement it in compilers which lack it.

**Comment by zzak** [comment]
Is it available in C99?

**Comment by Asmod4n** [comment]
It would be mostly the same as https://github.com/mruby/mruby/blob/master/include/mruby/numeric.h#L40, so i guess its not in C99 too.

**Comment by zzak** [comment]
I'm not familiar enough with the builtin overflows, maybe matz can advise

**Comment by cremno** [comment]
I'll add it. The difficult part here is the fallback for compilers without these built-ins. It needs to be portable and fast. Of course, only to some degree. With 16/32 b `mrb_int` it's actually quite simple: 32/64 b multiplication + `FIXABLE()` (which btw. should be renamed to `mrb_fixable` or even `mrb_fixable_p`). But that's not an option with the 64b one…
