### ISSUE TITLE
How to check if mruby is built as 64 bit with visualcpp

### ISSUE THREAD

**Issue by Asmod4n** [mruby/mruby#3150]
Currently trying to make it easier to build mrbgems when C libraries need configure/build scripts to run.

On unix systems its quite easy.
But on windows 10 (64 bit) with visual studio 2015 mruby is build as 32 bit by default.

Is there a way in a MRuby::Gem::Specification to find out if its being build as a 32 bit or 64 bit lib with visual studio?

**Comment by cremno** [comment]
```ruby
ENV['Platform']
```

Returns `"X64"` when targeting x64/amd64/x86_64.

**Comment by Asmod4n** [comment]
Thanks!

**Comment by Asmod4n** [comment]
@cremno have tried it, its empty here https://github.com/Asmod4n/mruby-libsodium/blob/master/mrbgem.rake

**Comment by cremno** [comment]
Empty means x86. You could also parse the output of `cl.exe`. The first line ends with the target (x86/x64/ARM).

**Comment by Asmod4n** [comment]
Thanks again, seams to work :)
