### ISSUE TITLE
Some Float value call method to_s get invalid format

### ISSUE THREAD

**Issue by Hanumashin** [mruby/mruby#3158]
I try code.
99999.9999999999417923390865325927734375.to_s 
Get string
099999.999999999

Please, Help.

**Comment by matz** [comment]
I get "100000". Could you tell me your config?
try `mruby-config --cflags`.

**Comment by Hanumashin** [comment]
Thank you for fast response, Matz.
Sorry I'm late.

I run `mruby-config --cflags`
And I get
`-g -std=gnu99 -O3 -Wall -Werror-implicit-function-declaration -Wdeclaration-after-statement -DDISABLE_GEMS -DMRB_DEBUG -DDISABLE_GEMS -I/.../mruby-iOS/mruby/include`

**Comment by matz** [comment]
Please tell us your platform and OS information as well.

**Comment by Hanumashin** [comment]
I use `mruby 1.1.0` and compile on `OS X El Capitan` with `xCode 7.3.1 (gcc 4.8)`

**Comment by syohex** [comment]
This issue was fixed by https://github.com/mruby/mruby/commit/6f893b5183450384e89b3d8f03f9ef32a7522624.
Please use newer version.

**Comment by Hanumashin** [comment]
Thank you, syohex. I will try.
