### ISSUE TITLE
Symbol GC is missing

### ISSUE THREAD

**Issue by Asmod4n** [mruby/mruby#3161]
There currently is no way to create symbols in a C ext which can be GCed. I believe Ruby got support for that lately, could it be adopted for mruby?

**Comment by matz** [comment]
no plan yet due to the cost of symbol GC. It will add complexity to the code and slow down performance.

**Comment by jazzonmym1nd** [comment]
i don't think GC'ed symbols are something that is necessary but has the knock on effect that programmer should be careful when dynamic symbols are being created from user input. perhaps it should be documented somewhere, or mruby should prevent you shooting yourself in the foot by allowing GC of symbols.

**Comment by Asmod4n** [comment]
i mainly need it for server to server communication, disque for example misuses status codes for uuid's ..

**Comment by matz** [comment]
Use strings. After Rails, everyone misuse symbols. Symbols are fundamentally permanent for languages influenced by Lisp (including Ruby). Although Ruby 2 has symbol GC, it does not mean it can collect all unused symbols since it's so difficult to define "unused" for symbols.

**Comment by zw963** [comment]
> Symbols are fundamentally permanent for languages influenced by Lisp (including Ruby).

Cool, i think so many guys like me confuse about internal use permanent symbol with user created GC'ed symbol(to_sym)
