### ISSUE TITLE
Wrapping C++ objects

### ISSUE THREAD

**Issue by schmurfy** [mruby/mruby#3167]
When you are wrapping a C structure you can use mrb_malloc so there is no issue but how would you do it for a C++ object ? If I use new it won't be allocated on the mruby stack and if I use mrb_malloc the C++ specifc stuff won't be done...

In c I do it like this where manager_state is my c structure:
```c
static mrb_value _initialize(mrb_state *mrb, mrb_value self)
{
  struct manager_state *st = (struct manager_state *)mrb_malloc(mrb, sizeof(struct manager_state));
  // [...]
}
```

I would prefer avoiding C++ entirely but that is not an option here.

**Comment by Moon4u** [comment]
You can write your own _new_ and _delete_ functions that will be executed instead of the standard implementation. In your implementation use mrb_malloc and mrb_free.

**Comment by kyab** [comment]
I'm using "placement new" to create instance of C++ Class in mruby-arduino mrbgem.
Placement new allows you to use specific address (ex. memory area obtained by mrb_malloc), for  instance.
```
  void *p = mrb_malloc(mrb, sizeof(Foo));
  Foo *foo = new(p) Foo();
```

https://github.com/kyab/mruby-arduino/blob/master/src/chipKITMax32_ArduinoDue.cpp#L57

**Comment by schmurfy** [comment]
thanks for the answers I did not know about placement new, I will look into it.
