### ISSUE TITLE
How writing extension in C to mruby

### ISSUE THREAD

**Issue by texrg** [mruby/mruby#3168]
Hello,

Where is example,tutorial ,web page to show how writing extension in C

I know what embeding C code to mruby, but exist normal interpreter 'mruby'
How using it?
how runing 
$mruby file.mrb
10
$cat file.mrb
requite 'myextension'
puts myfunction(1)

in C
static mrb_value fun(mrb_state* mrb, mrb_value obj)
{
mrb_int a;
 mrb_get_args(mrb, "i", &a);
 a=a*10;
return a; /* return a 'a' variable */
}

**Comment by matz** [comment]
The documentation for C API is not done yet.  Check `doc/guides/mrbgems.md` file and `example/mrbgems` directory.

**Comment by xor256** [comment]
Is a trouble with mrb_get_args()
What I can chech how many variables is running in function?
my(1) or my(1,2,3,4).
how check what is a kind of value?

**Comment by matz** [comment]
If you want 4 mandatory arguments, call `mrb_get_args(mrb, "iiii", &i1, &i2, &i3, &i4)`.  For more information, check out comments in `class.c` (search for `mrb_get_args()`).

**Comment by xor256** [comment]
I would like to respond to any number of arguments. 2 if the program will work, but at 4 arguments it will work to.

**Comment by xor256** [comment]
How determining counts of arguments?
How writing this function

 def fajne(tytul,*argumenta)
  puts "[#{tytul}]"
  return argumenta.join("/")
 end

#How determine count and type
fajne("a",1,7,2.0)

**Comment by matz** [comment]
Why don't you write code in Ruby? It's much easier.
I think you will understand how to count argument numbers after reading mrb_get_args() comments.
Checking some functions in array.c and string.c would help too.

**Comment by xor256** [comment]
I cant write C extension in mruby !
Can You write me simple example/answer.

How determining number of *arg , default value etc. this is not easy.
Please dont close this issue
