### ISSUE TITLE
CONSTANT in C

### ISSUE THREAD

**Issue by xor256** [mruby/mruby#3170]
How creating a constant in C?
When I create a object I need some:

-  global variable $global_variable = 1
-  const variable VAR1 = 100 inside object

is possible to add 'read only' variable in object or constants?

**Comment by matz** [comment]
You can use `mrb_mod_const_set()` to define a constant.
And `mrb_gv_set()` to create a global variable.

But I don't really understand some of your terms, e.g. "const variable inside object" or "read-only variable in object". Could you elaborate?

**Comment by xor256** [comment]
Ok, I show wha i nedd in small program. Please temm me what I can writing in C this script.
(only $glob,CONSTGLOB,CONSTFUN and @read_only )

**$glob = 5.2
CONSTGLOB = 2

class Fun
 CONSTFUN=10
 attr_reader :read_only** #constant for me because i cannot chcange value

# test, not implementing only for show
#all below is not necesary to implementing
 def my(x)
  @read_only = 7
  return x*CONSTFUN
 end

end

puts "My glob #{$glob}"
f=Fun.new
puts "and my function #{f.my(3)}"
puts "Const variable #{CONSTGLOB*$glob}"
puts Fun::CONSTFUN
puts f.read_only

**Comment by matz** [comment]
You don't have to write everything in C. To write Ruby code, write in Ruby.
It's much much easier to write them in Ruby. You can create a mrbgem using Ruby.
In fact, mruby implements many of standard library classes in Ruby.

**Comment by xor256** [comment]
CONST variable inside object is not complicated

**Comment by matz** [comment]
OK, you don't need string interpolation, nor attr_reader.  Things would be much easier.

`#inlcude <mruby/variable.h>`
`void mrb_gv_set(mrb_state *mrb, mrb_sym sym, mrb_value val)` for global variables
`void mrb_define_global_const(mrb_state *mrb, const char *name, mrb_value val)` for global constants.
`void mrb_const_set(mrb_state *mrb, mrb_value mod, mrb_sym sym, mrb_value val)` for constants inside classes.

**Comment by matz** [comment]
Can I close the issue?

**Comment by xor256** [comment]
yes
