### ISSUE TITLE
EXC_BAD_ACCESS on mrb_malloc calls

### ISSUE THREAD

**Issue by schmurfy** [mruby/mruby#3172]
Hi,
I am sure the issue is on my side but I can't find it, after a batch of changes on a personal project I now get random EXC_BAD_ACCESS when mrb_malloc* functions are called and I have no clue why.
I did a lot of changes so I am not sure when exactly this started happening.

Can anyone tell me what could cause this ? I am a bit puzzled at to how it could happen, I have not redefined the memory allocation functions, i have no defined anything to change the default mruby memory management behavior.

Edit: here is the backtrace when running inside lldb (I am on os x): https://gist.github.com/schmurfy/242821ca142ea3ba168d213d3f337fb7

**Comment by Asmod4n** [comment]
Have you tried to delete the build folder?

**Comment by matz** [comment]
I agree with @Asmod4n Linking object files compiled with different mrb_state configuration can cause similar issues.

**Comment by schmurfy** [comment]
I already tried that without luck, I even removed the mruby folder to be sure I did not change anything but I get the same result, also tried with mruby master (was trying with 1.2.0).
The segfault always originates in the same C functions but since I find that weird since don't manipulate the memory directly :/

**Comment by schmurfy** [comment]
I managed to track down the root cause to mruby-io, I have no clue what is happening but `File.open` starts it, if I take out all mruby-io lines everything works, I guess I have more debugging to do xD

**Comment by schmurfy** [comment]
I tracked it down to using an unregistered object (as in created on the C side and not calling `mrb_gc_register` on it to protect it from the GC), I am not sure how it managed to completely screw up following memory allocation...
