### ISSUE TITLE
Help review mruby.h for any possible mistakes in the documentation.

### ISSUE THREAD

**Issue by Mav7** [mruby/mruby#3180]
I wrote some of the documentation on [mruby.h](http://mruby.org/docs/api/headers/mruby.h.html) more specifically the documentation with the examples a while back. I didn't have anyone say anything was wrong before but I want to make absolutely sure that there are no issues with that documentation and the examples to go with it. I would like to ask the community here to review those docs [here](http://mruby.org/docs/api/headers/mruby.h.html) and make sure there are no errors. Please if you'd like perhaps give me better examples(or maybe more for different use cases?).
@zzak @mattetti @matz

**Comment by matz** [comment]
I merged #3183. If you have more, please reopen this issue.
