### ISSUE TITLE
Where is mrb_load_irep_file()? How can I load mruby bytecode into C program?

### ISSUE THREAD

**Issue by Mav7** [mruby/mruby#3187]
I was looking at [Executing Ruby code with mruby](http://mruby.org/docs/articles/executing-ruby-code-with-mruby.html) I was trying to load an mruby bytecode file (``test.mrb``) and execute the code from inside my C program. On the *Bytecode (.mrb)* section of the page it says *This file can be executed by the mruby program or the ``mrb_load_irep_file()`` function.* but I can't find this function ``mrb_load_irep_file()`` anywhere. How would I go about loading mruby bytecode (``test.mrb``) into a a C program?

**Comment by Asmod4n** [comment]
Its in https://github.com/mruby/mruby/blob/master/include/mruby/dump.h and https://github.com/mruby/mruby/blob/master/src/load.c

**Comment by kyab** [comment]
Here is tiny sample to use mrb_load_irep_file() to load test.mrb

```
[koji@macbookpro2:~/work]$ cat mruby-test.c 
#include <stdio.h>
#include "mruby.h"
#include "mruby/dump.h"

int main()
{
	mrb_state *mrb = mrb_open();

	FILE *fp = fopen("test.mrb", "r");
	mrb_load_irep_file(mrb, fp);
	
	mrb_close(mrb);

	return 0;
}
[koji@macbookpro2:~/work]$ gcc -I mruby/include/ mruby-test.c mruby/build/host/lib/libmruby.a -o mruby-test
[koji@macbookpro2:~/work]$ ./mruby-test
hello mruby

```

**Comment by xor256** [comment]
is possible to 'join' two files?
for example in one is one function in other mrb file is second function uses first

**Comment by Mav7** [comment]
@Asmod4n @kyab Thank you for the help!

**Comment by kyab** [comment]
@xor256 

I don't know there are way to join mrb files, but you can simply call mrb_load_irep_file() twice.
```c
#include <stdio.h>
#include "mruby.h"
#include "mruby/dump.h"

int main()
{
    mrb_state *mrb = mrb_open();

    FILE *fp = fopen("test.mrb", "r");
    mrb_load_irep_file(mrb, fp);
    FILE *fp2 = fopen("test2.mrb", "r");
    mrb_load_irep_file(mrb, fp2);

    mrb_close(mrb);

    return 0;
}
```

**Comment by Kyoril** [comment]
It should also be possible to combine the contents of the *.rb files before converting them into *.mrb files using mrbc, right?

**Comment by texrg** [comment]
@Kyoril
Meybe yes but You must know what kind of file is *.rb
if You use if __FILE__ == $PROGRAM_NAME
or mixins. this si not cleary how it will or not working
