### ISSUE TITLE
I need a global version of stack extend

### ISSUE THREAD

**Issue by nozomiS** [mruby/mruby#3219]
Hi there,

I'm just developing a forked version of mruby-eval that has some performance improvement
and fully Binding support. Actually. Yes, I really need them for my project and
it has to be done by mruby not Ruby.

The idea is based on mirb and it consumes the machine stack to give local variables
to generated code. The different between them, mirb has to take care the stack keep value only
but my version has to extend the stack and then set the local variables on it before calling the function.
This is why I need a global version of stack extend.

Could you accept that? If it is okay, I'll push a patch and it may contain like the following highlighted codes.
https://github.com/nozomiS/mruby/blob/eval-opt/src/vm.c#L174-L177

Thanks,

**Comment by beoran** [comment]
@matz is this still relevant with Ruby 1.3? It seems like this may be useful if we don't already have it.
