### ISSUE TITLE
Destructor or finalizer in mruby?

### ISSUE THREAD

**Issue by dbsGen** [mruby/mruby#3220]
I using mruby in my c++ project, I have to free my memory when mruby object destroy by gc. Is there any way to get the event?
I have tried ```ObjectSpace.define_finalizer``` but it say ```undefined method 'define_finalizer' for ObjectSpace```.

**Comment by rmosolgo** [comment]
I'm struggling to find the usage details, but it looks like MRuby has a similar hook to CRuby. When you make a Ruby object with a C struct, you can provide a pointer to a finalizer function:

https://github.com/mruby/mruby/blob/master/include/mruby/data.h#L26

I can see here where the function is called:

https://github.com/mruby/mruby/blob/master/src/gc.c#L782-L784

Oh, and I found an example usage on a previous issue: 

https://github.com/mruby/mruby/issues/3097#issuecomment-181714227

Hope that helps!

**Comment by dbsGen** [comment]
Thanks @rmosolgo , It is helpful.

**Comment by tsahara** [comment]
If you are familiar with opendir(3) API, this one might help you understand how DATA interface works: https://github.com/iij/mruby-dir/blob/master/src/dir.c#L48 .  Just FYI.
