### ISSUE TITLE
Multiple prepend on the same class is broken

### ISSUE THREAD

**Issue by dabroz** [mruby/mruby#3225]
Normally I can define the same class multiple times. However if one of its included modules uses `prepend` to add some features, the class gets broken. Observe this code:

```
module Foo
  module Initializer
    def initialize
      puts 'pre-initialize'
      super
      puts 'post-initialize'
    end
  end

  def self.included(klass)
    klass.send :prepend, Initializer
  end
end

class Module
  def has_foo
    include Foo
  end
end

class Bar
  has_foo
  def initialize
    puts 'Bar.initialize'
  end
end

class Bar # this is repeated intentionally
  has_foo
  def initialize
    puts 'Bar.initialize'
  end
end

Bar.new
```

If I run this code under regular Ruby (`ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]`), I'm getting:

```
pre-initialize
Bar.initialize
post-initialize
```

However, when run under mruby (latest from master), I'm getting an error:

```
trace:
    [1] test.rb:28
    [0] test.rb:27
test.rb:28: undefined method 'has_foo' for #<Bar:0x7fb52c0077c0> (NoMethodError)
```

mruby works fine if I remove the duplicate of Bar. However this is not possible in the system I'm developing (which relies on dynamic reloading of files).

**Comment by bovi** [comment]
@matz is this intentional? if yes we should add it to mruby's limitation

**Comment by matz** [comment]
No, I will fix. But I can't say about when.

**Comment by dabroz** [comment]
Thanks! I can confirm this has fixed my issue.
