### ISSUE TITLE
Quoted symbols are not accepted as hash keys using new syntax

### ISSUE THREAD

**Issue by dabroz** [mruby/mruby#3231]
Following Ruby code:

    puts({'1': 1})

is correctly handled by CRuby (`ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]`):

    {:"1"=>1}

but doesn't work with mruby (latest from master, `9a126278`):

    ./test.rb:1:10: syntax error, unexpected ':', expecting tASSOC

Old syntax (`{:'1' => 1}`) works correctly in mruby.

**Comment by cremno** [comment]
That's a 2.2 feature. mruby targets 1.9 syntax including bug fixes. I don't oppose implementing it though.

**Comment by matz** [comment]
mruby gradually adopting 2.x features. It's a good chance to add quoted labels.

**Comment by ksss** [comment]
I found a corner case.

```
$ mirb
> {"#{1}": 1}
 => {:"1"=>1}
> {'#{1}': 1}
line 2: syntax error, unexpected tLABEL_END, expecting '}'

$ irb
irb(main):001:0> {"#{1}": 1}
=> {:"1"=>1}
irb(main):002:0> {'#{1}': 1}
=> {:"\#{1}"=>1}
```

**Comment by ksss** [comment]
Thank you for fixing ✨
