### ISSUE TITLE
Intrusive storage for small structures?

### ISSUE THREAD

**Issue by dabroz** [mruby/mruby#3237]
I am writing a game development oriented mruby gem for small vectors (primarily 4x float). I need at most 16 bytes per object to store its data.

I can use `mrb_data_type` to store this data, and this works fine. However I would like to avoid the extra allocation and store this data along the object if possible. Can I do it somehow? Would I need a new `MRB_TT_XXX` to correctly garbage collect such object?

**Comment by matz** [comment]
Seems good idea. I will consider adding new inlined data structure.
But it would take time.  Stay tuned.
