### ISSUE TITLE
MRB_ARGS_ARG is never used

### ISSUE THREAD

**Issue by dabroz** [mruby/mruby#3238]
It looks like `MRB_ARGS_ARG` (as well as `_REQ` and `_OPT`) argument (`mrb_aspec`) in `mrb_define_method` is never used when defining C functions:

```
MRB_API void
mrb_define_method_id(mrb_state *mrb, struct RClass *c, mrb_sym mid, mrb_func_t func, mrb_aspec aspec)
{
  struct RProc *p;
  int ai = mrb_gc_arena_save(mrb);

  p = mrb_proc_new_cfunc(mrb, func);
  p->target_class = c;
  mrb_define_method_raw(mrb, c, mid, p);
  mrb_gc_arena_restore(mrb, ai);
}

MRB_API void
mrb_define_method(mrb_state *mrb, struct RClass *c, const char *name, mrb_func_t func, mrb_aspec aspec)
{
  mrb_define_method_id(mrb, c, mrb_intern_cstr(mrb, name), func, aspec);
}
```

Is this intentional?

**Comment by felixjones** [comment]
I believe they all exist for possible future use (as of date of this posting), as such you should probably still respect their usage for if/when a future mruby release utilises these arg specifications.

You'll also notice there's a macro MRB_ARGS_KEY for keyword arguments, a feature that's yet to be implemented into mruby, so they certainly are there for future use.

**Comment by matz** [comment]
@felixjones is right.
