### ISSUE TITLE
Testing gem C API

### ISSUE THREAD

**Issue by dabroz** [mruby/mruby#3249]
Is it possible to test the C API of the gem?

I have C API in my mruby-float4 gem: 

https://github.com/dabroz/mruby-float4/blob/master/include/mruby/float4.h

and would like to have tests for it using standard gem testing infrastructure, like this (C pseudocode):

```c
mrb_value value = test_execute(mrb, "Vec3.new(1, -2) * 2.5");
mrb_bool result = mrb_float4_vec(mrb, value, &data, &size);
test_assert_equal(result, TRUE);
test_assert_equal(size, 3);
...
```

But it seems that currently I can have pure Ruby tests in `/test`, tests for a generated binary in `/bintest`, but no mixed C & Ruby tests.

**Comment by matz** [comment]
your mruby-inline-struct gem (already merged) will be a perfect example of C testing gem.
thank you!
