### ISSUE TITLE
Parse HTML with mruby

### ISSUE THREAD

**Issue by DamirSvrtan** [mruby/mruby#3266]
Sorry for using the issue tracker for this, I was wondering if there was a mruby html parser i could use that could easily run on any given OS?

If there's not, what would be the easiest way to tackle this problem? Thnx!

**Comment by matz** [comment]
As far as I know, there's no mrbgem to support HTML parsing.  For searching mrbgems, you can use `mgem` command.

```
gem install mgem
mgem update
mgem list
mgem search html
```

The easiest way may depend on your demand. Simple regular expression match may work (the easiest), or porting simple Ruby htmlparser (medium), or developing a wrapper for libxml (the hardest).

**Comment by DamirSvrtan** [comment]
Thank you for the suggestions!
