### ISSUE TITLE
Floating Point Parser Behavior Is Locale Dependent

### ISSUE THREAD

**Issue by fundamental** [mruby/mruby#3270]
Mruby's parse.y uses libc's strtod to parse floating point literals. For some locale configurations (those which use ',' in place of '.' as a decimal separator) this results in incorrectly parsed literals. Cruby appears to work around this with by using their own implementation, ruby_strtod which by default (unless USE_LOCALE is explicitly enabled) ignores locale settings when parsing ruby code.

A similar solution would be preferred here as setlocale cannot be safely used in applications where mruby is embedded within another program (e.g. for the case of plugins which make use of mruby).

**Comment by matz** [comment]
Hmm, difficult problem. The ideal solution must be reimplementing strtod(), but it would increase the size of mruby.

**Comment by fundamental** [comment]
If the resulting binary size is the main concern it should only affect binaries that pull in the mruby-compiler gem, but if the size of the overall codebase is the concern I don't see much of a way to work around that.

**Comment by dabroz** [comment]
`"1.25".to_f` uses `strtod` as well.

**Comment by dabroz** [comment]
Having said that, we could use `strtod_l` (or `_strtod_l`) on systems that are known to have it.

**Comment by matz** [comment]
I didn't know about `strtod_l`. I am sorry that it's not portable.
I found out that the locale insensitive `strtod` is not that big. I will merge it soon.

**Comment by fundamental** [comment]
Thanks for the fix.
