### ISSUE TITLE
Declaration of "errno" in string.c conflicts with platforms that define errno as a macro

### ISSUE THREAD

**Issue by felixjones** [mruby/mruby#3326]
Introduced in commit https://github.com/mruby/mruby/commit/a0fbc46ccd3e129532b05a9fe4f13f42a3c349b2
[string.c line 2772](https://github.com/mruby/mruby/blob/a0fbc46ccd3e129532b05a9fe4f13f42a3c349b2/src/string.c#L2772)

This breaks compilation for all Android NDK platforms across all current Android NDK architectures, where errno is an inbuilt macro of errno.h:
```c
#define  errno   (*__errno())
```

**Comment by felixjones** [comment]
I did some investigation; declaring extern int errno appears to be the wrong thing to do as errno.h is expected to take care of this declaration.

Removing the 3 lines seems to be safe and causes no problems for me. I'm going to update the PR, but some confirmation that this is safe would be appreciated.

**Comment by matz** [comment]
fixed by #3327
