### ISSUE TITLE
Hash#delete and Hash#clear don't check whether hash is frozen

### ISSUE THREAD

**Issue by clayton-shopify** [mruby/mruby#3370]
```
> h = { 'a' => 1, 'b' => 2 }.freeze
 => {"a"=>1, "b"=>2}
> h.delete('a')
 => 1
> h
 => {"b"=>2}
> h.clear
 => {}
```
These operations should fail with `can't modify frozen hash (RuntimeError)`.

This issue was reported by https://hackerone.com/an0n-j

**Comment by clayton-shopify** [comment]
The submitter suggested adding `mrb_hash_modify` calls to `mrb_hash_delete` and `mrb_hash_clear`.

**Comment by ksss** [comment]
I guess it need new method `Kernel#frozen?` to solve this issue.

E.g. `Hash#delete_if`

```diff
  def delete_if(&block)
    return to_enum :delete_if unless block_given?
+   raise RuntimeError, "can't modify frozen #{self.class}" if frozen?
    self.each do |k, v|
      self.delete(k) if block.call(k, v)
    end
    self
  end
```
