### ISSUE TITLE
postgresql/mruby

### ISSUE THREAD

**Issue by eiked** [mruby/mruby#3375]
not a bug, just a feature

mruby should well integrate with postgresql.
anyone working at that?

**Comment by kjunichi** [comment]
Hi,
there is a mrbgem:
https://github.com/authorNari/mruby-pg

you may some modify,but it works fine.

**Comment by mattn** [comment]
This is bug tracker for mruby core not mrbgems or something extensions. So is this closable?

**Comment by matz** [comment]
As @kjunichi told you, use mruby-pg.
