### ISSUE TITLE
Crash after to_s on recursive objects

### ISSUE THREAD

**Issue by clayton-shopify** [mruby/mruby#3385]
MRuby seems to deal with the problem of printing recursive objects (Array, Hash, Struct) by rescuing the `SystemStackError` if the stack runs out, e.g.:

https://github.com/mruby/mruby/blob/c4491e477b40adc842ef76e524647607780c8f25/mrblib/array.rb#L88-L94

But this appears to leave memory in a corrupted state, resulting in failures later on. For instance, the following input demonstrates a crash:
```ruby
a = []
a[0] = a
a.to_s
b
```
This crashes with:
```
Assertion failed: ((obj)->tt != MRB_TT_FREE), function mrb_gc_mark, file /Users/clayton/git/mruby/src/gc.c, line 697.
Abort trap: 6
```
I'm not sure what's causing the memory corruption.

MRI seems to handle recursive objects in a cleaner way, by keeping track of which object's it's already seen.

This issue was reported by https://hackerone.com/ston3

**Comment by dkasak** [comment]
This seems fixed now? At least it doesn't crash on my end anymore.

**Comment by matz** [comment]
I close the issue for the moment. If you see the problem again, please reopen.

FYI, MRI handles recursive data structure far better, but it consumes more memory. I didn't want to use more memory for rare cases.
