### ISSUE TITLE
Crash when inspecting recursive objects

### ISSUE THREAD

**Issue by clayton-shopify** [mruby/mruby#3386]
The following inputs demonstrates crashes:
```ruby
o = Object.new
o.instance_eval { @b = [o] }
o.inspect
```
```ruby
o = Object.new
o.instance_eval { @b = { a: o } }
o.inspect
```
The crashes occur because inspect enters into infinite recursion while traversing the recursive objects, thereby overflowing the stack.

MRI gracefully handles these cases:
```
irb(main):001:0> o = Object.new
=> #<Object:0x007fad8528cf28>
irb(main):002:0> o.instance_eval { @b = [o] }
=> [#<Object:0x007fad8528cf28 @b=[...]>]
irb(main):003:0> o.instance_eval { @b = { a: o } }
=> {:a=>#<Object:0x007fad8528cf28 @b={...}>}
```
This issue was reported by https://hackerone.com/ston3

**Comment by tsahara** [comment]
It is an expected behavior, one of known incompatibilities with MRI.
ref. https://github.com/mruby/mruby/issues/57.

**Comment by matz** [comment]
The issue seems to be resolved now. At least mruby does not crash with above programs.
