### ISSUE TITLE
Crash due to invalid irep->filename

### ISSUE THREAD

**Issue by clayton-shopify** [mruby/mruby#3392]
The following input demonstrates a crash:
```ruby
begin
  [0].each do
    [].each 0
  end
rescue => e
  GC.start
  e.backtrace
end
```
The crash happens here:

https://github.com/mruby/mruby/blob/c4491e477b40adc842ef76e524647607780c8f25/src/backtrace.c#L82

For some reason, an `irep`'s `filename` pointer is set to an invalid value (0x101).

This issue was reported by https://hackerone.com/ston3

**Comment by matz** [comment]
#3378 also fix this.
