### ISSUE TITLE
Incompatibility of Array#[]=

### ISSUE THREAD

**Issue by ksss** [mruby/mruby#3411]
```rb
a = []
a[3..4] = 1
p a
#=> CRuby: [nil, nil, nil, 1]
#=> mruby: []
```

```rb
a = []
a[-1..-1] = 1
#=> CRuby: RangeError: -1..-1 out of range
#=> mruby: return 1 and `a` is `[]`
```

I think, The cause is incompatibility of mruby's `mrb_range_beg_len` and CRuby's `rb_range_beg_len`

https://github.com/mruby/mruby/blob/bd50273bbc4afd68b7f9f0394af1baf0d396b53f/src/array.c#L803
https://github.com/ruby/ruby/blob/78b95b49f8715a4782f5b9bdc4c163e445cdc303/array.c#L1740

I think, We'll need another function same as `mrb_range_beg_len` if we want to fix this issue and expect no break backward compatibility.

**Comment by matz** [comment]
The difference is not intended, so I will fix this (and break compatibility).

**Comment by ksss** [comment]
Thank you for big deciding ✨

**Comment by dabroz** [comment]
cc #3140
