### ISSUE TITLE
Failed to link when build with C mrbgem

### ISSUE THREAD

**Issue by fatihsirin** [mruby/mruby#3414]
Hello

Steps:

1. Clone mruby.

`git clone git@github.com:mruby/mruby.git`

2. ./minirake

and result 

``/home/nope/Desktop/mruby/build/host/lib/libmruby.a(example.o): In function `mrb_mrbgems_example_gem_init':
/home/nope/Desktop/mruby/build/mrbgems/mrbgems-example/src/example.c:14: undefined reference to `ARGS_NONE'
collect2: error: ld returned 1 exit status
/home/nope/Desktop/mruby/build/host/lib/libmruby.a(example.o): In function `mrb_mrbgems_example_gem_init':
/home/nope/Desktop/mruby/build/mrbgems/mrbgems-example/src/example.c:14: undefined reference to `ARGS_NONE'
collect2: error: ld returned 1 exit status
rake aborted!
Command Failed: [gcc  -o "/home/nope/Desktop/mruby/build/host/bin/mirb" "/home/nope/Desktop/mruby/build/host/mrbgems/mruby-bin-mirb/tools/mirb/mirb.o" "/home/nope/Desktop/mruby/build/host/lib/libmruby.a"  -lm ]
Rakefile:70:in `block (4 levels) in <top (required)>'
``

Is my mrbgem.rake wrong? What should I change for build it?
Thanks.

**Comment by ksss** [comment]
https://github.com/masuidrive/mrbgems-example seems old.
It should use `MRB_ARGS_NONE` instead of `ARGS_NONE`

**Comment by ksss** [comment]
I sent a [PR](https://github.com/masuidrive/mrbgems-example/pull/1) to https://github.com/masuidrive/mrbgems-example.
Please try this branch.

**Comment by matz** [comment]
The issue seems to be solved.
