### ISSUE TITLE
dump bytecode from C

### ISSUE THREAD

**Issue by texrg** [mruby/mruby#3416]
Is possible to write simple dump mruby source or .mrb
I need read all opcode, header etc. Similar this but with writing to file(stdout)
all information about bytecode.

```
#include "mruby.h"
#include "mruby/dump.h"

int main() {
   mrb_state *mrb = mrb_open();
   FILE *fp = fopen("test.mrb", "r");
   mrb_load_irep_file(mrb, fp);
   <here dump function>
   mrb_close(mrb);
return 0;}
```

how using https://github.com/mruby/mruby/blob/master/include/mruby/dump.h
or meybe i must using codedump_recur? Anybody knows?

**Comment by texrg** [comment]
.

**Comment by matz** [comment]
I am not sure what  you want. If you want to convert Ruby source file to compiled binary (.mrb), simply use `mrbc`.

```
mrbc -o yours.mrb yours.rb
```
Check out `mrbc` source file in `mrbgems/mruby-bin-mrbc/tools/mrbc/mrbc.c` for implementation.

**Comment by texrg** [comment]
No, no. I need compiling in gcc
whitch files are important and witch no?

$gcc my_code.c some_c_mruby_code_from_src.c ...... -o program

**Comment by texrg** [comment]
How using dump function which are in mruby. Any example?

**Comment by texrg** [comment]
The question is simple. You have program above.
please wrote one line to change <here dump function>
This is not complicated for You.

**Comment by matz** [comment]
Don't be cruel. `mrb_load_irep_file(mrb, fp)` is a function to load and execute the binary file.
You have to retrieve an irep structure using `mrb_read_irep_file()`. Then call `mrb_dump_irep_binary()` to dump the binary file. But in this case, the program reads and writes same binary files.

**Comment by amirrajan** [comment]
This might help someone in the future:

```c
mrbc_context *cc = mrbc_context_new(mrb);
cc->dump_result = 1;
struct mrb_parser_state *parser = mrb_parse_nstring(mrb, code_as_string, strlen(code_as_string), cc);
```

The code above will at least print to standard out given the `mrb_parser_dump` in `parse.y`.

Aside (after reading this entitled comment thread): You can't just expect a quick/lazyweb answer for these kinds of complex projects. _You_ have to dig in everything, study deeply, and figure this stuff out _yourself_. You have to contribute many more answers than questions. The core-contributor-to-user-ratio is completely lopsided as is, so do your due diligence/hard work as opposed to overburdening people that are already strapped for time. Keep your entitlement to free software in check @texrg.
