### ISSUE TITLE
Build with "enable_test" fails due to broken "include_paths"

### ISSUE THREAD

**Issue by palkan** [mruby/mruby#3418]
Hi, everyone!

I have a gem tree like this:

```ruby
root
 |
 A –
      |
      B
      |
      C
```

Where `A` is using headers from `B` (say, `include <b/functions.h>`).

But when I'm running a build with `conf.enable_test` (i.e. adding `mruby-test` to the build pipeline), I've got the following error:

```
fatal error: 'b/functions.h' file not found
```

As it turned out, adding `mruby-test` initiates additional compiling task (one for each gem) with broken configuration – unpopulated `include_paths`.

Why does this happen?

- `mruby-test` [generates a gem_table](https://github.com/mruby/mruby/blob/master/mrbgems/mruby-test/mrbgem.rake#L36)

- That [involves a call](https://github.com/mruby/mruby/blob/master/tasks/mrbgem_spec.rake#L346)  to `Spec#setup`

- `Spec#setup` defines [compilers rules](https://github.com/mruby/mruby/blob/master/tasks/mrbgem_spec.rake#L95) – thus adds new tasks

- And we haven't [imported `include_paths`](https://github.com/mruby/mruby/blob/master/tasks/mrbgem_spec.rake#L427) to these compilers.

As I understand, we don't need these compiler rules at all, so we should just skip them. Am I right?

**Comment by matz** [comment]
We have to talk to @zzak who built mruby-test for the answer, but if you submit PR, I will review it anyway
