### ISSUE TITLE
how read string from value?

### ISSUE THREAD

**Issue by texrg** [mruby/mruby#3428]
How read 
@value from object 
attr_reader

class Foo
 attr_reader  :tee
....

how set and read it from C?

**Comment by matz** [comment]
To read instance variables (e.g. `@value`), you can use `mrb_iv_get()`.
To update instance variables, you can use `mrb_iv_set()`.

**Comment by texrg** [comment]
it working on private and public and other value?

**Comment by matz** [comment]
All instance variables in Ruby are private.

**Comment by texrg** [comment]
the instruction
`  private`
are not working?
for example 

class Foo
  attr_reader :bar
  private
  attr_writer :bar
end

**Comment by matz** [comment]
Visibility (public/protected/private) is not (yet) implemented in mruby.

**Comment by texrg** [comment]
ok, thanks
