### ISSUE TITLE
Crash in instance_eval and instance_exec

### ISSUE THREAD

**Issue by clayton-shopify** [mruby/mruby#3432]
The following input demonstrates a crash:
```ruby
instance_eval { super &0 }
```

This issue was reported by https://hackerone.com/d4nny

I noticed that the following also crashes:
```ruby
instance_exec { super &0 }
```

And the following don't behave as expected. In MRI they result in "super called outside of method" but in MRuby the results are different:
```
$ bin/mirb
mirb - Embeddable Interactive Ruby Shell

> instance_eval { super 0 }
(mirb):1: expected String (TypeError)
> instance_exec { super 0 }
(mirb):2: no block given (ArgumentError)
```

**Comment by matz** [comment]
Will be fixed.  `instance_eval` can take a string argument where `instance_exec` cannot. That's the reason they raise different exceptions.
