### ISSUE TITLE
Null pointer dereference in mrb_obj_iv_ifnone

### ISSUE THREAD

**Issue by clayton-shopify** [mruby/mruby#3433]
The following input demonstrates a crash:
```ruby
begin
rescue => a
end

begin
  b
rescue begin
    c ""
  rescue => d
    0
  ensure
  end
end
```
`mrb->exc` is NULL when this line executes: https://github.com/mruby/mruby/blob/794de3317aa2f2adb9c84900e470f140e581092c/src/vm.c#L1579

This issue was reported by https://hackerone.com/d4nny

**Comment by matz** [comment]
It seems the issue was fixed by 642ab8ec
