### ISSUE TITLE
ljust and rjust are slow 

### ISSUE THREAD

**Issue by clayton-shopify** [mruby/mruby#3445]
The implementations of [`String#ljust`](https://github.com/mruby/mruby/blob/d0ecf862d9d2e7aed461bc9360686449f56c5d25/mrbgems/mruby-string-ext/mrblib/string.rb#L277-L287)  and [`String#rjust`](https://github.com/mruby/mruby/blob/d0ecf862d9d2e7aed461bc9360686449f56c5d25/mrbgems/mruby-string-ext/mrblib/string.rb#L300-L310) are slow (i.e. O(n^2) running time) when MRuby is built with `MRB_UTF8_STRING`. This is because they repeatedly call `String#size`, which calls `utf8_strlen`, which must iterate over the whole string.

```
$ echo '"".ljust(100000)' | time bin/mruby
       57.46 real        57.01 user         0.21 sys

$ echo '"".rjust(100000)' | time bin/mruby
       57.17 real        56.90 user         0.14 sys
```

This issue was reported by https://hackerone.com/ssarong

**Comment by texrg** [comment]
Please run more than one times your benchmark

very similar
57.46+57.01+0.21=114.68
57.17+56.90+0.14=114.21

**Comment by dabroz** [comment]
Also, these functions with an empty padding parameter will stay in an infinite loop.
