### ISSUE TITLE
:: minimal a possible, mruby without stdio.h ,meybe some modules

### ISSUE THREAD

**Issue by texrg** [mruby/mruby#3454]
I have simple example:
```
#include "mruby.h"
#include <mruby/compile.h>
int main() {
mrb_int i; mrb_value c;
mrb_state *mrb = mrb_open();
char kod[] = "def suma(a,b) (a+b).to_i end";
 if (!mrb) { /* problemy */ }  mrb_load_string(mrb, kod);
 for(i=0;i<9;i++)
   {   c = mrb_funcall(mrb, mrb_top_self(mrb), "suma", 2,mrb_fixnum_value(i),mrb_fixnum_value(i)); }
 mrb_close(mrb);
return 0;}
```
What I can compiling it in static mode. Without library libmruby.a. Only add /src/*.c file.
I'm not need nothing without Array. No file acess, no other gems (time, test, sprintf, random etc.)
I'm not need compiler gem. I can run only bytecode if it is possible.
How doing this? now i compiling program above that:
gcc -I _[mruby]_/include/ file.c _[mruby]_/build/host/lib/libmruby.a -o file -lm
how removing libmruby.a and put here all files
_[mruby]_/src/array.c _[mruby]_/src/aclass.c ....etc

in Makefile
`ZRODLA = $(wildcard $(MRUBY)/src/*.c)`
prog: prog.c
        gcc prog.c $(ZRODLA) -o prog -lm
i get  undefined reference to mrb_load_string mrb_init_mrbgems etc.

**Comment by fundamental** [comment]
If you want to use mrb_load_string, you need at least one gem, mruby-compiler. The implementation for that particular function is in mrbgems/mruby-compiler/core/parse.y, though it's going to also need the codegen routines within that gem if you want it to be useful.

mrb_init_mrbgems is a function built at compile time which simply calls mrb_GEMNAME_gem_init() for all gems built. There should also be a matching mrb_final_mrbgems style routine which cleans up all gem based resources.

Given how you're trying to build this, it looks like you would also be missing any of the function provided by the mrblib/*.rb files.

Is there any particular reason why you're trying to build without the build system provided by mruby?

**Comment by texrg** [comment]
static compilation.

mrb_load_string is not obligatory. feel free and show code without it (and compiling method)

in lua this scenario is possible. only add all *.c file to project.

**Comment by matz** [comment]
Run `rake` in the mruby source directory. You will have `libmruby.a` in the `build/host/lib` directory.
Then you compile your program with `-I` option specified to the compiler. Then you link your program with `-lmruby` specified to the linker. You will have your executable.

You can configure your mruby build with editing `build_config.rb` and `mrbconf.h` but the above is a starting point.

**Comment by texrg** [comment]
@matz tell me what i can compiling above program without libmruby.a
make is good but i cant use make and rake. I must compiling all in one big command.

**Comment by matz** [comment]
To support cross compiling and mrbgems, we need to run `rake` to get `libmruby.a`.
It is a huge difference (or maybe drawback from your point of view) from Lua.

**Comment by dabroz** [comment]
After you compile mruby, you get Ruby sources of mrblib and mrbgems compiled to C sources. You can then add them to your project by copying files from `build/host/mrblib/**` and `build/host/mrbgems/**` to your project as well.

Lua is different because it is implemented entirely in C.
