### ISSUE TITLE
Confirmation of NODE_MATCH code genaeration

### ISSUE THREAD

**Issue by k-muramatsu** [mruby/mruby#3467]
I want to check code using ast node "NODE_MATCH".
I guess this node is used when regexp matching code (e.g. =~ (String/Object) or .match), but it was wrong.
Could you tell me sample code using "NODE_MATCH"?

I use this revision: 6420951463ec9ace9eecb50923dc6a1925a45d31

**Comment by cremno** [comment]
The parser doesn't create `NODE_MATCH` nodes. It would be used for implicitly matching `$_`, e.g.: `gets; if /hoge/; puts "hello world"; end`. While `=~` would be either `NODE_MATCH2` and `NODE_MATCH3` depending on which side the regex is. There are also a few other unused node types.

**Comment by k-muramatsu** [comment]
Thank you for information.

**Comment by k-muramatsu** [comment]
Thank you for information.
