### ISSUE TITLE
How to tell mruby the external allocated memory pressure

### ISSUE THREAD

**Issue by i110** [mruby/mruby#3520]
In [h2o](https://github.com/h2o/h2o), we want to bind a memory allocated in c to a mruby data instance, and free it when mruby object is destructed. It is for http request and response, and it may be so big (e.g. 1GB), so we want to free it as soon as possible after that mruby object is destructed to suppress memory footprint (as we have multiple mruby VMs for each threads).

for example, v8 has the method to tell VM the memory pressure: [AdjustAmountOfExternalAllocatedMemory ](https://v8docs.nodesource.com/io.js-3.0/d5/dda/classv8_1_1_isolate.html#ae1a59cac60409d3922582c4af675473e)

Is there any ways in mruby to do the same thing?

**Comment by fundamental** [comment]
From what I've seen you can tune the frequency of garbage collection via the interval_ratio and step_ratio ( https://github.com/mruby/mruby/blob/master/src/gc.c#L56-L62 ), but not the absolute threshold which is what you appear to want to configure. Additionally, based upon a quick skimming the GC thresholds appear to be defined in terms of the number of objects, not the amount of memory that the objects consume.

**Comment by i110** [comment]
yes I think so too that the current GC implementation checks only the number of objects allocated, not the amount of the memory. If so, let me change my question to a general one: what's the best way to resolve the same kind of problem? Are there any tricks to call `RData's dfree` callback as fast as possible, or should mruby GC implementation count allocated memory, not the number of objects?

**Comment by fundamental** [comment]
My own solution for deallocating high cost data attached to ruby objects is adding a 'clean' method to the object which deallocates the C structures and leaves the object in an invalid state. For my own application there's a few cases where it is known that an object no longer in use, so it's easy to call the 'clean' method then. I'm not sure if a similar workaround would work in your case as well or not.

**Comment by i110** [comment]
@fundamental sorry for my late reply. In my use case it's difficult to know that an object is no longer in use or not.

More correctly, h2o users can write mruby scripts in h2o configuration, and they can know the lifecycle of the data and even call something like `clean` method before releasing the reference of it. But I think that it's much better if mruby GC runs ASAP after a high cost data gets no longer used, without having the user call `clean` explicitly.

Any ideas would be greatly appreciated.

**Comment by beoran** [comment]
In general, garbage collectors cannot be relied on for immediate release of resources.

In Ruby, it is already an idiom that certain   objects that need to be closed, such as File. Furthermore, you normally provide for a block form of the open method. I think that for cases like yours a similar open/close method pair  API is best.

**Comment by i110** [comment]
Sorry for my late response. I've been thinking about this once again today, and felt that, as you said, calling close method explicitly is the most reasonable choice. On the other hand, I still believe that managing alive objects regarding their amount of memory consumption is worth considering, but it may needs big changes of current implementation, so at this time I choose the realistic way. Thanks for everyone.

close
