### ISSUE TITLE
Infinite loop in time_alloc

### ISSUE THREAD

**Issue by clayton-shopify** [mruby/mruby#3546]
The following inputs cause an infinite loop in `time_alloc`:
```ruby
Time.at(Float::NAN)
```
```ruby
Time.at(1, Float::NAN)
```
```ruby
Time.at(1, Float::INFINITY)
```
```ruby
Time.at(1, -Float::INFINITY)
```
Large `usec` values can also consume a lot of CPU time because `usec` is incremented or decremented 1,000,000 at a time: https://github.com/mruby/mruby/blob/66980493ae2f4d587a4a45b6b1061f46c01e34be/mrbgems/mruby-time/src/time.c#L236-L243

This issue was reported by https://hackerone.com/ahmadsherif

**Comment by matz** [comment]
closed by #3546
