### ISSUE TITLE
Crash in mrb_hash_keys after hash keys are modified

### ISSUE THREAD

**Issue by clayton-shopify** [mruby/mruby#3565]
The following input demonstrates a crash:
```ruby
h = {}
a = []
200.times do |n|
  a[0] = n
  h[a] = 0
  puts h
end
```
This issue was reported by https://hackerone.com/ssarong.

The crash occurs after `kh_resize` increases the size of the hash table. It considers all the keys to be equal and so after the resize `kh_size(h)` is 1. But the one remaining `mrb_hash_value` still uses the old numbering, and so a crash occurs when `mrb_hash_keys` tries to write beyond the end of its array: https://github.com/mruby/mruby/blob/905f46a129de65098b3130789bb9c412201f4cb4/src/hash.c#L766

**Comment by clayton-shopify** [comment]
It's also apparent from the output that insertions into the hash don't always work:
```
{[0]=>0}
{[1]=>0, [1]=>0}
{[2]=>0, [2]=>0, [2]=>0}
{[3]=>0, [3]=>0, [3]=>0, [3]=>0}
{[4]=>0, [4]=>0, [4]=>0, [4]=>0, [4]=>0}
{[5]=>0, [5]=>0, [5]=>0, [5]=>0, [5]=>0, [5]=>0}
{[6]=>0, [6]=>0, [6]=>0, [6]=>0, [6]=>0, [6]=>0, [6]=>0}
{[7]=>0, [7]=>0, [7]=>0, [7]=>0, [7]=>0, [7]=>0, [7]=>0, [7]=>0}
{[8]=>0, [8]=>0, [8]=>0, [8]=>0, [8]=>0, [8]=>0, [8]=>0, [8]=>0}         <--- incorrect
{[9]=>0, [9]=>0, [9]=>0, [9]=>0, [9]=>0, [9]=>0, [9]=>0, [9]=>0, [9]=>0}
...
```

**Comment by ksss** [comment]
I have heard from @matz.
The behavior is undefined if key objects are rewritten later (in CRuby).

**Comment by clayton-shopify** [comment]
@ksss OK, so the insertion behaviour is not incorrect then, and we have some flexibility in how to fix the crash.
