### ISSUE TITLE
Error on mrb_str_cat function (str_buf_cat)

### ISSUE THREAD

**Issue by rmalizia44** [mruby/mruby#3574]
Everytime I create a Ruby String and call mrb_str_cat it gives a Segmentation Fault (using Linux Ubuntu). 

Example Code:

```c
mrb_value new_obj = mrb_obj_new(mrb, mrb->string_class, 0, NULL);
const char* test_str = "test";
new_obj = mrb_str_cat(mrb, new_obj, test_str, 4);
```

I reverted str_buf_cat master to 1.2.0 on "string.c" and the Segmentation Fault stopped.

**Comment by fundamental** [comment]
Just a guess, but that sounds like new_obj is not fully initialized. Perhaps try using mrb_str_new_lit() to initialize it.

**Comment by matz** [comment]
Yes, use `mrb_str_new*` to create string objects.

**Comment by rmalizia44** [comment]
It worked! Thanks very much!
