### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by rwhitworth** [mruby/mruby#3585]
Hello,
I was using American Fuzzy Lop (afl-fuzz) to fuzz input to the mruby interpreter and found an input that causes mruby to segmentation fault.  Is fixing this crash something you're interested in?

The file is a ruby script that can be executed as `mruby output.txt` to cause a seg fault that looks like this according to dmesg output: `[496072.795990] mruby[25476]: segfault at 4 ip 000000000040c0ff sp 00007fff32b47590 error 4 in mruby[400000+140000]`

Let me know if I can provide any more information to help narrow down this issue.

[output.txt](https://github.com/mruby/mruby/files/892990/output.txt)

**Comment by matz** [comment]
I could not reproduce the crash (as of 60d20e18).  Probably it's fixed by recent changes.
Could you try again with the recent version?

**Comment by rwhitworth** [comment]
You are correct, latest mruby source no longer crashes.  I cloned the repo ~6 days ago so it must have been a recent change that fixed it.  Thanks.

**Comment by matz** [comment]
Good.  Thank you for the report anyway.
