### ISSUE TITLE
Fails to compile with MRB_DISABLE_STDIO defined

### ISSUE THREAD

**Issue by craiglrock** [mruby/mruby#3632]
Some recent changes, e.g. https://github.com/mruby/mruby/commit/dcf6a413cab097e39d2d883d7c8c297d29ea43b8
https://github.com/mruby/mruby/commit/e6b5c75ec5a299e43fd9b9e2ba63831780011c1a

break compiling when MRB_DISABLE_STDIO defined.

**Comment by matz** [comment]
Could you show us error messages?

**Comment by craiglrock** [comment]
Sure, it's the same type of error message in each case.

`error: implicit declaration of function 'snprintf'`

https://github.com/mruby/mruby/commit/ef105b5ca41018f30c38f9738d5b54c4aa0fe6e4 & https://github.com/mruby/mruby/commit/3703aed7ab7c056ef7a58fd8d25b84b59f715dad also add `snprintf` calls.
