### ISSUE TITLE
why to_i method not exist in :constants

### ISSUE THREAD

**Issue by xor256** [mruby/mruby#3667]
I would like to storage unique value in sql database

I can convert :foo.to_s but cant convert :foo.to_i 
I need get unique number from constans

**Comment by matz** [comment]
Even CRuby does not have `Symbol#to_i` (as of Ruby 2.3).

Implementation wise, symbols does have corresponding integer values. So it's relatively easy to retrieve those integer values to Ruby world. But they are not persistent unique values. They may differ for each execution. It's not suitable for databases anyway.
