### ISSUE TITLE
Float#to_i Tests don't pass with MRB_INT64

### ISSUE THREAD

**Issue by Asmod4n** [mruby/mruby#3671]
Since a few days ago,

Fail: Float#to_i [15.2.9.3.14] (mrbgems: mruby-test)
 - Assertion[2] Failed: FloatDomainError expected but nothing was raised.
 - Assertion[3] Failed: FloatDomainError expected but nothing was raised.
 - Assertion[4] Failed: FloatDomainError expected but nothing was raised.

happens when mruby is compiled with #define MRB_INT64

**Comment by matz** [comment]
I was testing MRB_WORD_BOXING that works correctly.

**Comment by Asmod4n** [comment]
Thank you! :)
