### ISSUE TITLE
Assertion failure in mrb_write_barrier

### ISSUE THREAD

**Issue by clayton-shopify** [mruby/mruby#3689]
The following input demonstrates an assertion failure:
```ruby
GC.start
ObjectSpace.each_object{ GC.generational_mode = nil }
a
```
`Assertion failed: (((gc)->generational) || gc->state != MRB_GC_STATE_ROOT), function mrb_write_barrier, file /Users/clayton/git/mruby/src/gc.c, line 1304.`

This issue was reported by Dinko Galetic & Denis Kasak (https://hackerone.com/dgaletic).

**Comment by matz** [comment]
It turns out it's (almost) impossible to keep consistency in GC after changing generational mode during iteration. I will make it impossible by raising an exception.
