### ISSUE TITLE
Building mruby without setjmp(3)

### ISSUE THREAD

**Issue by avsej** [mruby/mruby#3697]
Currently it does not seem possible to build mruby without setjmp/longjmp, but, in theory, can mruby work without exceptions mechanism?

**Comment by matz** [comment]
Exceptions are the essential part of the language. Implementing Ruby exceptions without `setjmp(3)` is theoretically possible, but pragmatically impossible.  It requires huge changes in mruby API.

**Comment by matz** [comment]
Do you want to compile mruby on a platform without `setjmp(3)`?

**Comment by avsej** [comment]
The xtensa compiler does not ship setjmp in standard library, but it seems like guys from micropython project solved it already. So I will try to port solution from them. I'm just experimenting with ESP board.
