### ISSUE TITLE
WebAssembly toolchain

### ISSUE THREAD

**Issue by Asmod4n** [mruby/mruby#3709]
I would like to see a WebAssembly toolchain or something similar for mruby, are there any plans for it? Or how could one be written?

**Comment by bovi** [comment]
I'm not sure if this is what you mean but there is a project (https://github.com/xxuejie/webruby) which compiles mruby via emscripten (which supports webassembly to my knowledge). What is your target?

**Comment by Asmod4n** [comment]
I want to replace javascript with mruby for browser scripting, now that webasm is in every browser it should be doable :)

**Comment by texrg** [comment]
opal is better and working good
https://github.com/opal/opal

**Comment by Asmod4n** [comment]
opal is implemented in javascript, as such it isn't as fast or versatile as wasm.

**Comment by Asmod4n** [comment]
@blacktm YAY! Thank you :))
