### ISSUE TITLE
local_variables is broken

### ISSUE THREAD

**Issue by i110** [mruby/mruby#3710]
```ruby
def _generate
  var = 110
  proc {|hoge| p local_variables }
end
_generate.call
```

outputs `[:hoge]`, but I expect `[:hoge, :var]` as CRuby does.

As I looked the code, `struct REnv *` assigned to the generated proc gets unshared when cipop called in OP_RETURN, and that makes the env [not enumarated](https://github.com/mruby/mruby/blob/master/src/kernel.c#L1168). Is this a mruby's spec or not?

Even if that's a spec, I believe that  the following behavior is absolutely a bug.

```ruby
def _generate
  eval("var = 110; proc {|hoge| p local_variables }")
end

def _call(invisible)
  invisible.call
end

_call(_generate)
```
says `[:hoge, :invisible]`, but if I'm correct `invisible` shouldn't appear.
In this case, the env of the generated proc is not unshared due to [another callinfo](https://github.com/mruby/mruby/blob/master/src/vm.c#L493), but [mrb_local_variables refers current callinfo stack,](https://github.com/mruby/mruby/blob/master/src/kernel.c#L1170) so variables not related to the proc appears. As a similar example,

```ruby
def _generate
  eval("var = 110; proc {|hoge| p local_variables }")
end

def dummy(invisible)
end

Fiber.new {
  ret = _generate
  dummy(nil)
  ret
}.resume.call
```
outputs the same, `[:hoge, :invisible]`. In this case, another context's callinfo which gets overwrited by calling `dummy` function is referred.

**Comment by matz** [comment]
The first issue is mruby limitation. We will try to address it but it would take time.
The second issue is caused by a bug in `eval` (`create_proc_from_string`).

**Comment by i110** [comment]
Actually I found the first issue when debugging the second one, so I'm not stacked at that if I know that's a limitation. Thanks a lot!

**Comment by matz** [comment]
Oops, issue number was wrong.
