### ISSUE TITLE
MRB_DISABLE_STDIO: String#upto native's mrb_str_upto requires snprintf

### ISSUE THREAD

**Issue by alexsnaps** [mruby/mruby#3714]
I think this is kind of the equivalent of #3632 
https://github.com/mruby/mruby/commit/6fdf2b035d563bf6502eba8953c3199c52c0a89d introduced a dependency to `snprintf` again that's not available with the `MRB_DISABLE_STDIO` defined. Maybe having a CI config that tests `MRB_DISABLE_STDIO` would avoid these in the future, wdyt?

**Comment by matz** [comment]
It may be too late for 1.3.

**Comment by ksss** [comment]
Oh... I'm sorry.
