### ISSUE TITLE
String#size is incorrect value  in multibyte character set

### ISSUE THREAD

**Issue by koooge** [mruby/mruby#3725]
Is this intended?

mruby 1.3.0 (2015-11-17)
```
> "あいうえお".size
 => 15
> "あいうえお".bytesize
 => 15
```

ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
```
[1] pry(main)> "あいうえお".size
=> 5
[2] pry(main)> "あいうえお".bytesize
=> 15
```

**Comment by matz** [comment]
You need to define `MRB_UTF8_STRING` in `mrbconf.h`  or rake configuration. To save the size of executable, it is turned off by default.

```
mirb - Embeddable Interactive Ruby Shell
> "あいうえお".size
 => 5
```

**Comment by koooge** [comment]
I understand thank you. 😄 

https://github.com/mruby/mruby/blob/master/doc/guides/mrbconf.md#other-configuration
