### ISSUE TITLE
format("%d", -2147483648) => "--2147483648"

### ISSUE THREAD

**Issue by tsahara** [mruby/mruby#3729]
`format("%d", -2147483648)` returns "--2147483648".  There should be only one "-" character at the beginning of the string.

```
% mruby -e 'p format("%d", -2147483648)'
"--2147483648"
```

It works as expected for other numbers.

```
% mruby -e 'p format("%d", -2147483647)'
"-2147483647"

% mruby -e 'p format("%d", -2147483649)'
trace:
	[0] -e:1
-e:1:number (-2147483649) too big for integer (ArgumentError)
```

**Comment by katzer** [comment]
@matz Now format("%d", 0) returns "-0"

**Comment by matz** [comment]
Oops, sorry. Wrong condition.
