### ISSUE TITLE
Mingw Build Failure Due To Missing (L)DBL_EPSILON

### ISSUE THREAD

**Issue by fundamental** [mruby/mruby#3733]
When building with mingw-w64 (5.3.1) on Ubuntu (16.04) mruby fails to build as the constants DBL_EPSILON and LDBL_EPSILON are not defined given the headers used by mruby. It is unclear which versions of the mingw float.h header are affected, but I've been working around this issue since I ported a mruby based project to windows a year ago or so.

I would recommend adding the values to mruby.h when float.h does not provide them. Using the values that I can see from my primary Linux machine this would amount to:

```
#include <float.h>

#ifndef DBL_EPSILON
#define DBL_EPSILON ((double)2.22044604925031308085e-16L)
#endif

#ifndef LDBL_EPSILON
#define LDBL_EPSILON (1.08420217248550443401e-19L)
#endif
```

**Comment by cremno** [comment]
This is a mingw-w64 bug then. Working around missing C99 features is (still?) acceptable but the `*EPSILON` macros already were defined by C89.

Also your `LDBL_EPSILON` isn't necessarily correct because `long double` and `double` can match the same IEEE 754 format (e.g. on non-MinGW Windows or ARM).

**Comment by fundamental** [comment]
It certainly is a bug with the library implementation in mingw-w64, but from what I've seen mingw is an actively used platform for various mruby gems. I would think a small 9 line workaround would be acceptable to avoid losing support for an entire compiler toolchain even if it's fixing a bug which should not be there in the first point.

For the second point, all other platforms should define the correct constants within float.h which would result in the workaround constants getting stripped out by the preprocessor.

**Comment by matz** [comment]
mruby uses `FLT_EPSILON` when `MRB_USE_FLOAT` is defined. Is `FLT_EPSILON` defined by mingw-w64?

**Comment by fundamental** [comment]
On 07-08, matz wrote:
> mruby uses `FLT_EPSILON` when `MRB_USE_FLOAT` is defined. Is `FLT_EPSILON` defined by mingw-w64?
FLT_EPSILON appears to be properly defined in mingw's float.h when I ran
some quick tests
