### ISSUE TITLE
MIPS big endian target is very slow

### ISSUE THREAD

**Issue by yamori813** [mruby/mruby#3744]
I try to use mruby at Atheros SOC target on FreeBSD-Current. This SOC is big endian MIPS architecture. mruby is very slow compared to little endian MIPS target.

For example fib(32) check.

Big endian Atheros AR7240(350MHz) is 64 sec.

Little endian Ralink(Mediatek) RT3050(320MHz) is 25sec.

This is mruby 1.2.0 result.

I make mruby for mips on FreeBSD/amd64 by gcc 4.2.

Besides this Atheros AR9330 mruby 1.2.0 is fib(32) is 43 sec. But mruby 1.3.0 and todays github master is almost 90 sec.

I try to this setting on cross build target but not effective.

  conf.mrbc do |mrbc|
    mrbc.compile_options = "-E -g -B%{funcname} -o-"
  end

**Comment by matz** [comment]
Is it possible to run the program through the profiler?
I don't have a big endian machine so that it`s nearly impossible for me to improve the code.

**Comment by yamori813** [comment]
FreeBSD/mips not work profiler. sorry.

I try to check with awk fib(32) on RT3050 and AR9330 on same version of FreeBSD.

RT3050 is 80 sec
AR9330 is 99 sec

I seem FreeBSD and compiler(gcc) is not cause this problem.

**Comment by matz** [comment]
Sorry for my ignorance. But the performance of RT3050 and AR9330 (and AR7240) means nothing for me at the moment. What are the relations of those chips (and endianness)? We need more info to solve the issue.

**Comment by yamori813** [comment]
RT3050 is Little endian mips 24K architecture. AR9330 is big endian mips 24K architecture. These soc support on FreeBSD by same code at kernel and user land. But only different making toolchain. Big endian mips is little bit slow at FreeBSD. But more slow at mruby. It is very strange . There is a possibility only FreeBSD. I can't check on linux because of I don't have linux.

**Comment by matz** [comment]
Thank you for the info. But I still have no clue to isolate the problem.
If you have any idea, let me know, please.

**Comment by yamori813** [comment]
I seem this is not mruby problem. I think this is Atheros SOC issue. Sorry for your patience.
