### ISSUE TITLE
A Segmentation fault when using CMruby

### ISSUE THREAD

**Issue by 0x36** [mruby/mruby#3787]
I'm using this following code : 
```
#include <mruby.h>
#include <mruby/compile.h>
#include <unistd.h>

int
main(void)
{
        unsigned char buf[1024] = {0};
        size_t rb;
        rb = read(0,buf,1023);
        mrb_state *mrb = mrb_open();
        mrb_load_string(mrb, buf);
        mrb_close(mrb);
  return 0;
}
```

Compile command : clang -I ../include -lm -o test code.c ../build/host/lib/libmruby.a -fsanitize=address -ggdb

When I put '}' it gets crashed , Here is the output  : 
ASAN:SIGSEGV
=================================================================
==22670==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000040 (pc 0x000000540940 bp 0x7ffd58768510 sp 0x7ffd58768320 T0)
    #0 0x54093f in mrb_load_exec /home/s/mruby/mrbgems/mruby-compiler/core/parse.y:5778:5
    #1 0x4e26ee in main /home/s/mruby/bin/fuzz.c:13:9
    #2 0x7fad8105f82f in __libc_start_main /build/glibc-bfm8X4/glibc-2.23/csu/../csu/libc-start.c:291
    #3 0x43c1e8 in _start (/home/s/mruby/bin/test+0x43c1e8)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/s/mruby/mrbgems/mruby-compiler/core/parse.y:5778 mrb_load_exec
==22670==ABORTING

**Comment by matz** [comment]
I forgot to address the case where the context is NULL. Thank you for the report.
