### ISSUE TITLE
Inconsistent override behavior for Fixnum/Float

### ISSUE THREAD

**Issue by fl0l0u** [mruby/mruby#3807]
I tried to override :== method for classes String, Fixnum and Float in both mruby and ruby.
The following behavior was observed:
```
flo@ubuntu:~/mruby$ bin/mruby test.rb # mruby@master:476af3c64726fed823e4a1fdc316f0780f340246
"String#==: a == b"
"String#==: a == 1"
"String#==: a == 1.1"
"Fixnum#==: 1 == a"
"Float#==: 1.1 == a"
flo@ubuntu:~/mruby$ ruby test.rb # ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
"String#==: a == b"
"String#==: a == 1"
"String#==: a == 1.1"
"Fixnum#==: 1 == 2"
"Fixnum#==: 1 == a"
"String#==: a == 1"
"Fixnum#==: 1 == 1.1"
"Float#==: 1.1 == 2.1"
"Float#==: 1.1 == 1"
"Float#==: 1.1 == a"
"String#==: a == 1.1"
```
Having `test.rb`:
```ruby
class ::String
  alias :equals :==
  def ==(obj)
    p "String#==: #{self} == #{obj}"
    self.equals(obj)
  end
end
class ::Fixnum
  alias :equals :==
  def ==(obj)
    p "Fixnum#==: #{self} == #{obj}"
    self.equals(obj)
  end
end
class ::Float
  alias :equals :==
  def ==(obj)
    p "Float#==: #{self} == #{obj}"
    self.equals(obj)
  end
end
"a" == "b"
"a" == 1
"a" == 1.1
1 == 2
1 == "a"
1 == 1.1
1.1 == 2.1
1.1 == 1
1.1 == "a"
```
I see no obvious explanation for this behavior...

**Comment by christopheraue** [comment]
Checking equality takes a shortcut if both operands are ints or floats and does not call `==`. That's why it only prints something if one operator is a string:

https://github.com/mruby/mruby/blob/483a038d39e7f8ff2b093819758c997014f88979/src/vm.c#L2449-L2466

Generally, operator modification is limited in mruby: https://github.com/mruby/mruby/blob/master/doc/limitations.md#operator-modification

**Comment by fl0l0u** [comment]
Do these shortcuts totally bypass functions like `fix_equal()` and `flo_eq()` from `src/numeric.c` for all shortcuted operators ?

**Comment by christopheraue** [comment]
No, the shortcut is only taken if both operands are numeric. As soon as one operand is not numeric, `==` is send to the left operand. That means (if `==` is not overwritten):

* `1 == "a"` calls `fix_equal`and
* `1.1 == "a"` calls `flo_eq`.

**Comment by matz** [comment]
It's mruby limitation introduced for the tradeoff between performance and implementation complexity. If you really need to override basic operators for numbers, use CRuby.
