### ISSUE TITLE
Cannot call super in a c ext

### ISSUE THREAD

**Issue by Asmod4n** [mruby/mruby#3808]
Unlike ruby, mruby has no c extension method to call super.

**Comment by matz** [comment]
Since mruby is a compact implementation of Ruby language, it does not provide all of CRuby API.
Is there any specific need for the function to call `super`? If so, reopen the issue, please.

**Comment by Asmod4n** [comment]
@matz yes and no, "initialize_copy" gets called for .dup and .clone so i wanted to override dup and clone to call different methods.
This of course could be done with mruby itself but would be slower. Guess ill just do that then.
