### ISSUE TITLE
Segfault in gc_mark_children

### ISSUE THREAD

**Issue by fourmond** [mruby/mruby#3812]
I'm unsure this is a mruby bug, but I'm submitting here as per the README.

I embed mruby (version 1.3.0) in a data analysis program to compute user-provided mathematical formulas. I get systematic segmentation faults, seemingly when the gc runs, always there:

0x000055555578382f in gc_mark_children (mrb=mrb@entry=0x555555dfcc10, obj=0x555555f4f2a0, gc=<optimized out>)
    at /home/vincent/tmp/mruby-1.3.0/src/gc.c:654
654             if (e->cxt.c->fib) {

I have:

(gdb) p *e
$1 = {tt = MRB_TT_ENV, color = 4, flags = 1, c = 0x0, gcnext = 0x0, stack = 0x555555fe4140, cioff = 0, 
  cxt = {mid = 750, c = 0x5555000002ee}}
(gdb) p *e->cxt.c
Cannot access memory at address 0x5555000002ee

I think it is probably my mistake, but I just can't understand what I did wrong; I would greatly appreciate any pointer.

Best regards

**Comment by Asmod4n** [comment]
Have you tried it with the last mruby master? Are you using gems?

**Comment by fourmond** [comment]
Hey, it seems to be fixed with the latest master (7450a774a5f796f7e9) !
Would you like me to pinpoint which commit fixed it ?

**Comment by Asmod4n** [comment]
I don't know, try to look at the changes since 1.3?

**Comment by matz** [comment]
We have changed a lot since 1.3.  If we have the error reproducing program, we can `git bisect` using it.
Under the current roadmap, we will release 1.4 on mid-November.

**Comment by fourmond** [comment]
It's too complicated to simply give you the program, but I'll do a git-bisect myself shortly.

**Comment by fourmond** [comment]
I've run git-bisect. It looks like commit 0a61df1c34c62da59bf1443d6913e99158a938a4 fixed the segmentation fault.

**Comment by fourmond** [comment]
So it looks like this is a duplicate of #3768 ?

**Comment by matz** [comment]
I guess so. The part you saw segfault is where we modified heavily.
