### ISSUE TITLE
String.dup doesn't duplicate strings

### ISSUE THREAD

**Issue by Asmod4n** [mruby/mruby#3818]
At the moment, String.dup does what String.clone should do: it creates a reference to the malloced memory.

```ruby
orig = "password"
duplicate = orig.dup
```
Some other library clears the string
```c
memset(RSTRING_PTR(orig), 0, RSTRING_LEN(orig));
```
```ruby
puts duplicate # its all zeroes
```

**Comment by matz** [comment]
I don't see above mentioned `memset` code in anywhere in mruby source. Could you elaborate?

**Comment by Asmod4n** [comment]
Sorry about that, i meant when some other library does that to the string, not mruby itself.

**Comment by matz** [comment]
Ah, I got it.

As a rule, you cannot modify the string region pointed by `RSTRING_PTR()` unless you call `mrb_str_modify()'. It's the rule to save memory. It's a kind of "copy on write".
