### ISSUE TITLE
Weird behavior of mrb_get_argc with *splat args

### ISSUE THREAD

**Issue by dabroz** [mruby/mruby#3825]
When I have a C function `foo`, and create a proxy for it like this:

```
def bar(*args)
  foo(*args)
end
```

and I call `mrg_get_argc` in `foo` C implementation, I get `-1` instead of an actual number of arguments. They can be however retrieved as usual.

Example program:

```
#include <mruby.h>
#include <mruby/proc.h>
#include <mruby/class.h>

mrb_value foo(mrb_state * mrb, mrb_value self)
{
  mrb_float arg[2] = {0};
  printf("%d: ", (int)mrb_get_argc(mrb));
  mrb_get_args(mrb, "ff", &arg[0], &arg[1]);
  printf("%f, %f\n", arg[0], arg[1]);
  return mrb_nil_value();
}

int main()
{
  mrb_state * mrb = mrb_open();
  struct RProc * proc = mrb_proc_new_cfunc(mrb, foo);
  mrb_define_method_raw(mrb, mrb->object_class, mrb_intern_cstr(mrb, "foo"), proc);
  mrb_load_string(mrb, "def bar(*args); foo(*args); end; foo(1, 2); bar(3, 4)");
  mrb_close(mrb);
}
```

Expected result:

```
2: 1.000000, 2.000000
2: 3.000000, 4.000000
```

Actual result:

```
2: 1.000000, 2.000000
-1: 3.000000, 4.000000
```

**Comment by take-cheeze** [comment]
Seems like some internal is exposed in `mrb_get_argc`.
In mruby VM, argc is `-1` and `argv[0]`(or maybe `[1]`) is a `RArray` when splat arguments is passed.
So you should rely on return value of `mrb_get_args` instead for now.
