### ISSUE TITLE
MRB_DISABLE_STDIO broken

### ISSUE THREAD

**Issue by clayton-shopify** [mruby/mruby#3834]
93f5f225772c398be6e409da3d3ef0f07ffbe1cf broke `MRB_DISABLE_STDIO`. I assume the following code wasn't meant to be left in:
https://github.com/mruby/mruby/blob/93f5f225772c398be6e409da3d3ef0f07ffbe1cf/src/vm.c#L154-L156

**Comment by matz** [comment]
Oops sorry.
