### ISSUE TITLE
minimal embeded mruby

### ISSUE THREAD

**Issue by Ox16** [mruby/mruby#3845]
I have very small program.
How I can producing minimal execution file? I'm no need **stdio**, **file access**, random **mrbgems/mruby-random**, print, time etc. Now I get 744kB exec file.

My mruby repo is in ~/mruby
Now I compiling my code:

    gcc -Wall -pedantic -O0 -I ~/mruby/include/ -I ~/mruby/include/mruby \
	   t.c ~/mruby/build/host/lib/libmruby.a -o t -lm

How disabling STDIO? I uncomment 
#define MRB_DISABLE_STDIO  line in ~/mruby/include/mrbconf.h but mruby not compilig.

    CC    mrbgems/mruby-bin-mrbc/tools/mrbc/mrbc.c -> build/host/mrbgems/mruby-bin-mrbc/tools/mrbc/mrbc.o
    mrbc.c:175:10: error: no member named 'f' in 'struct mrb_parser_state'
    if (p->f) fclose(p->f);

If I link all *.o files i get error not found readline and add_history

**Comment by dabroz** [comment]
Building mruby is a two-step process. You first need a minimal environment and a working `mrbc` binary to compile standard library and other gems. Having that in place, you rebuild your host and all other configurations. But the `mrbc` binary needs file IO so you can't disable it completely in `mrbconf.h`. Instead, you should create a new configuration in `build_config.rb`. There, you can disable all gems and features like IO, floating point number and so on. Bear in mind that you won't have any standard mruby binary without IO, so you'll need to compile your `.rb` scripts with host tools and use "minified" version as a library with precompiled mruby scripts only.

**Comment by texrg** [comment]
less build_config.rb | grep default
  # include the default GEMs
  conf.gembox 'default'
  # include the default GEMs
  conf.gembox 'default'
  conf.gembox 'default'
  conf.gembox 'default'

Where i must add/remowe to create my own small mruby?
Can You write any example? I use only unices system.

**Comment by dabroz** [comment]
You can start by adding this to your `build_config.rb`:

```
MRuby::Build.new('mini') do |conf|
    toolchain :gcc
    conf.cc.flags << '-Os'
    conf.cc.defines = %w(MRB_DISABLE_STDIO MRB_WITHOUT_FLOAT)
end
```

**Comment by texrg** [comment]
Wow! minimal 1786084 regular host 9535240
I can disable ruby gems in conf.gembox ''
for example time and random ?

**Comment by dabroz** [comment]
There are no gems enabled in the `mini` configuration I've posted. You must enable them manually, eg:

```
MRuby::Build.new('mini-with-class-ext') do |conf|
    toolchain :gcc
    conf.cc.flags << '-Os'
    conf.cc.defines = %w(MRB_DISABLE_STDIO MRB_WITHOUT_FLOAT)
    conf.gem :core => "mruby-class-ext"
end
```

Some gems won't work without IO (eg. parser).

**Comment by Ox16** [comment]
thanks for all

**Comment by texrg** [comment]
@dabroz i run minimal example with integer.
I'm using conf.cc.defines = %w(MRB_DISABLE_STDIO)

my code https://github.com/mruby/mruby/issues/3846
$ ./t
Aborted (zrzut pamięci)

irep what nedded of gem?
