### ISSUE TITLE
mrbc how including compiling program to C?

### ISSUE THREAD

**Issue by texrg** [mruby/mruby#3846]
I upgrade mruby and have trouble.

Before upgrade  I create file.c  **mrbc -Bdane -o file.c test.rb**

and including it: **#include <mruby/irep.h>**

including **#include "file.c"**

and load:  **mrb_load_irep(mrb, dane);**

How i can to do this now? How compiling my script and embeded it in compiled form not in text form.

**Comment by matz** [comment]
The process hasn't been changed. Do you see any problem?

**Comment by texrg** [comment]
my code:


======== t.c ====================
#include <stdio.h>
#include <mruby.h>
#include <mruby/irep.h>

#include "test.c"
int main()
{
mrb_int    i;
mrb_value  c;
mrb_state *mrb = mrb_open();

 if (!mrb) { printf("Problemy z programem"); }
 mrb_load_irep(mrb, dane);

 for(i=1;i<=8;i++)
  {
  c = mrb_funcall(mrb, mrb_top_self(mrb), "suma",
                    2,mrb_fixnum_value(i),mrb_fixnum_value(i));
  printf("%lld %lld\n",i,mrb_int(mrb, c));
  }

 mrb_close(mrb);

return 0;
}
======== test.rb ===========
#!/usr/bin/env ruby
# encoding: utf-8

def suma(a,b)
 (a+b).to_i
end

puts "Początek suma(2,3)=#{suma(2,3)}"

====similar Makefile====
$mrbc -Bdane -o test.c test.rb
gcc -W -Wall -pedantic -O0 -I ~/mruby/include/ -I ~/mruby/include/mruby \
   t.c ~/mruby/build/host/lib/libmruby.a -o t -lm
=====result: x86Linux|mac os X====
./t
TypeError: can't convert NoMethodError into Integer
Aborted (zrzut pamięci)
=====

**Comment by matz** [comment]
The output of your program was following on my machine.

```
Początek suma(2,3)=5
1 2
2 4
3 6
4 8
5 10
6 12
7 14
8 16
```

Can you show me your build configuration?

**Comment by texrg** [comment]
I send configuration for 2 days. I check this code and working on linux x86 (fedora), on mac not. 
in normal build_config.rb (/host/) all working on x86
I check it on other arch.

in 

    MRuby::Build.new('mini') do |conf|
     toolchain :gcc
     conf.cc.flags << '-Os'
     conf.cc.defines = %w(MRB_DISABLE_STDIO)
    end

I get on linux
**Aborted (zrzut pamięci)**
or in macosx
**Aborted 6**

please wait a moment, I search and check everithing

**Comment by texrg** [comment]
This is my problem,  I can not reproduce (repeat) this problem.
Sorry

**Comment by dabroz** [comment]
```
printf("%lld %lld\n",i,mrb_int(mrb, c));
```

`mrb_int` is not guaranteed to match `%lld`. Consider: 

```
printf("%lld %lld\n",(long long)i,(long long)mrb_int(mrb, c));
```

**Comment by texrg** [comment]
@dabroz no this is not a problem. I change version of mruby.
