### ISSUE TITLE
`mrb_check_intern_cstr` returning nil for valid C strings

### ISSUE THREAD

**Issue by blacktm** [mruby/mruby#3858]
Hi everyone! I'm working on a game and graphics engine called [Ruby 2D](http://www.ruby2d.com) ([gem repo](https://github.com/ruby2d/ruby2d)), which can run apps interpreted and be compiled using mruby (I gave a talk about it at [this year's RubyConf](http://rubyconf.org/program#session-189) — here are [my notes from the talk](http://www.blacktm.com/rubyconf), and the video should be posted mid-December-ish if interested). While implementing controller and mouse events where we convert C strings to symbols, I noticed some weird behavior with the function `mrb_check_intern_cstr`. The documentation has [this nice example](http://mruby.org/docs/api/headers/mruby.h.html#mrb_check_intern_cstr-function) which works perfectly, but if you change `"Symbol"` to any other string (except single characters), it will return `nil`, for example:

```c
mrb_p(mrb, mrb_check_intern_cstr(mrb, "a"));        // prints :a
mrb_p(mrb, mrb_check_intern_cstr(mrb, "ab"));       // prints nil
mrb_p(mrb, mrb_check_intern_cstr(mrb, "Symbo"));    // prints nil
mrb_p(mrb, mrb_check_intern_cstr(mrb, "Symbol"));   // prints :Symbol
mrb_p(mrb, mrb_check_intern_cstr(mrb, "Symbols"));  // prints nil
```

I thought it might be a length issue, but lowercase `"symbol"` returns `nil` also. (Actually, pretty funny it only works with the example string in the docs 😆, besides the single chars that is.) Anyone else seeing this, or is it just late here and I'm going crazy (a very real possibility)?

Since `mrb_check_intern_cstr` is just a wrapper for `mrb_check_intern` ([definition here](https://github.com/mruby/mruby/blob/679dfd75a8aeb26ee4ff0d7c148e1f6e88e39c3d/src/symbol.c#L117)), that fails also. I'm trying to dig into that function, but my knowledge of mruby internals is a bit lacking (and maybe someone else can spot a solution much faster than I).

Also, just want to say I :heart: mruby so much! Thanks to all of you who have worked so hard on it!

**Comment by take-cheeze** [comment]
`mrb_check_intern_cstr` searches for already registered symbol so it's an expected behavior.
Use `mrb_intern_cstr` or `mrb_intern_lit` instead to register or get already registered symbol.

**Comment by take-cheeze** [comment]
(Though at least the document should be updated or someone should PR for fix...)

**Comment by blacktm** [comment]
D'oh! So _that's_ what "check" means in the function name. Thanks for the clarification @take-cheeze! (Maybe a small tweak to the docs, like "Returns an _existing_ Symbol..." or something and a code example where the symbol is being registered prior would be helpful.) I picked that function originally since it returns an `mrb_value`, which is what we need. Just tried...

```c
mrb_intern_cstr(mrb, "abc");
mrb_p(mrb, mrb_check_intern_cstr(mrb, "abc"));
```

...and that indeed works, prints `:abc`. Is there a more direct way to create a symbol from a C string as a `mrb_value`, or convert/cast an `mrb_sym` to `mrb_value`? In MRI/CRuby, we're using `ID2SYM(rb_intern("abc"))` to get a `VALUE`.

**Comment by matz** [comment]
Use `mrb_symbol_value(mrb_sym)`.

**Comment by blacktm** [comment]
Ah, that's it, thanks @matz!
