### ISSUE TITLE
errno.h missing from source code and is expected by error.c

### ISSUE THREAD

**Issue by mistergibson** [mruby/mruby#3865]
While building using 'ruby minirake':

Everything was fine until:

CC    src/error.c -> build/android/src/error.o
/home/mistergibson/Documents/Development/mruby/src/error.c:7:10: fatal error: 'errno.h' file not found
#include <errno.h>
         ^~~~~~~~~
1 error generated.
/home/mistergibson/Documents/Development/mruby/src/error.c:7:10: fatal error: 'errno.h' file not found
#include <errno.h>
         ^~~~~~~~~
1 error generated.
rake aborted!
Command Failed: [/home/mistergibson/Documents/Development/AndroidNDK/android-ndk-r16/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -MMD -MP -D__android__ -DANDROID --sysroot="/home/mistergibson/Documents/Development/AndroidNDK/android-ndk-r16/platforms/android-27/arch-arm" -target armv5te-none-linux-androideabi -mtune=xscale -msoft-float -gcc-toolchain "/home/mistergibson/Documents/Development/AndroidNDK/android-ndk-r16/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64" -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -DDISABLE_GEMS -DDISABLE_GEMS -I"/home/mistergibson/Documents/Development/mruby/include" -MMD -o "/home/mistergibson/Documents/Development/mruby/build/android/src/error.o" -c "/home/mistergibson/Documents/Development/mruby/src/error.c"]

Did you miss including a header file?

Thanks,

G.

**Comment by matz** [comment]
`errno.h` is a header file defined in C standard.
So I guess your installation of C development environment is incomplete.

**Comment by mistergibson** [comment]
Thank you - I'll try to see that I get the proper headers installed.
