### ISSUE TITLE
build error with useing clang on FreeBSD 11.4R

### ISSUE THREAD

**Issue by yamori813** [mruby/mruby#3875]
I build this commit today.

commit e17092debda8eecb652916b8ba2a314e799dd96f

I have build error.

...
CC    mrbgems/mruby-bin-mirb/tools/mirb/mirb.c -> build/host/mrbgems/mruby-bin-m
irb/tools/mirb/mirb.o
/storage/home/hiroki/opensource/tmp/mruby/mrbgems/mruby-bin-mirb/tools/mirb/mirb
.c:499:5: error: 
      implicit declaration of function 'rl_free' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
    MIRB_LINE_FREE(line);
    ^
/storage/home/hiroki/opensource/tmp/mruby/mrbgems/mruby-bin-mirb/tools/mirb/mirb
.c:26:30: note: 
      expanded from macro 'MIRB_LINE_FREE'
#define MIRB_LINE_FREE(line) rl_free(line)
                             ^
/storage/home/hiroki/opensource/tmp/mruby/mrbgems/mruby-bin-mirb/tools/mirb/mirb
.c:499:5: note: 
      did you mean 'mrb_free'?
/storage/home/hiroki/opensource/tmp/mruby/mrbgems/mruby-bin-mirb/tools/mirb/mirb
.c:26:30: note: 
      expanded from macro 'MIRB_LINE_FREE'
#define MIRB_LINE_FREE(line) rl_free(line)
                             ^
/storage/home/hiroki/opensource/tmp/mruby/include/mruby.h:985:14: note: 
      'mrb_free' declared here
MRB_API void mrb_free(mrb_state*, void*);
             ^
1 error generated.
/storage/home/hiroki/opensource/tmp/mruby/mrbgems/mruby-bin-mirb/tools/mirb/mirb
.c:499:5: error: 
      implicit declaration of function 'rl_free' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
    MIRB_LINE_FREE(line);
    ^
/storage/home/hiroki/opensource/tmp/mruby/mrbgems/mruby-bin-mirb/tools/mirb/mirb
.c:26:30: note: 
      expanded from macro 'MIRB_LINE_FREE'
#define MIRB_LINE_FREE(line) rl_free(line)
                             ^
/storage/home/hiroki/opensource/tmp/mruby/mrbgems/mruby-bin-mirb/tools/mirb/mirb
.c:499:5: note: 
      did you mean 'mrb_free'?
/storage/home/hiroki/opensource/tmp/mruby/mrbgems/mruby-bin-mirb/tools/mirb/mirb
.c:26:30: note: 
      expanded from macro 'MIRB_LINE_FREE'
#define MIRB_LINE_FREE(line) rl_free(line)
                             ^
/storage/home/hiroki/opensource/tmp/mruby/include/mruby.h:985:14: note: 
      'mrb_free' declared here
MRB_API void mrb_free(mrb_state*, void*);
             ^
1 error generated.
rake aborted!
Command Failed: [clang -g -std=gnu99 -O3 -Wall -Werror-implicit-function-declara
tion -Wdeclaration-after-statement -Wwrite-strings -g3 -O0 -DMRB_DEBUG -DENABLE_
READLINE -DMRBGEM_MRUBY_BIN_MIRB_VERSION=0.0.0 -I"/storage/home/hiroki/opensourc
e/tmp/mruby/include" -MMD -o "/storage/home/hiroki/opensource/tmp/mruby/build/ho
st/mrbgems/mruby-bin-mirb/tools/mirb/mirb.o" -c "/storage/home/hiroki/opensource
/tmp/mruby/mrbgems/mruby-bin-mirb/tools/mirb/mirb.c"]

*** Error code 1

Stop.

**Comment by matz** [comment]
Can you check if FreeBSD use linenoise as readline library? If so, it's quite easy to fix.

**Comment by matz** [comment]
Probably we can use `RL_READLINE_VERSION` to determine `rl_free` existence.
I will commit the update. Reopen the issue if it doesn't solve the issue.

**Comment by yamori813** [comment]
I checked build on FreeBSD 10.4R. Now completed.

Thanks a lot.
