### ISSUE TITLE
Cannot call `Fiber.yield` in constructor

### ISSUE THREAD

**Issue by kazuho** [mruby/mruby#3879]
Calling `Fiber.yield` in a constructor results in `can't cross C function boundary` exception. Could this be classified as an error considering the fact that only pure ruby code is involved?

Steps to reproduce:
1. run the following code using `mruby`
```
class C
  def initialize
    Fiber.yield(1)
  end
end
fiber = Fiber.new do
  C.new
end
fiber.resume
```

see also: https://github.com/h2o/h2o/issues/1536; relates to https://github.com/mruby/mruby/issues/3056

**Comment by matz** [comment]
As the comments say, Fibers cannot cross C function boundary. 

```
mruby limitation: Fiber resume/yield cannot cross C function boundary.
thus you cannot yield from #initialize which is called by mrb_funcall().
```

We don't have any plant to relax this limitation since there's no portable way to implement fibers that cross C function boundaries.

**Comment by matz** [comment]
We can make the limitation stronger to prohibit fiber creation from `#initialize` (or any methods called via `mrb_funcall`). How do you think?

**Comment by kazuho** [comment]
Thank you for the prompt answer.

Actually, with the advices from @take-cheeze and @miura1729 on Twitter, I have written a workaround as a mrbgem; please see https://github.com/kazuho/mruby-class-new-fiber-safe.

I would appreciate it if you could consider adopting the approach in mruby.

Or if that not possible, I think that I would maintain and use the mrbgem as a separate library. In that case, may I ask if you could make `mrb_instance_alloc` an extern function (or even better expose it as `Class#allocate`)? The only issue with the mrbgem is that it has a dead copy of `mrb_instance_alloc`.
