### ISSUE TITLE
How to dump current memory usage

### ISSUE THREAD

**Issue by fourmond** [mruby/mruby#3909]
I am having memory problems in my program, and I think it may be a mruby memory leak, possibly  linked to #2955. To understand where the problem lies (is it related to mruby, or to the other C++ code in my program?), I wanted to know if there is any way to **dump the current mruby memory usage**. I've grepped through the source code and did not find anything interesting.

Many thanks !

**Comment by matz** [comment]
I usually use valgrind to find memory leaks.

If you tell me what kind of information you want, I can make a gem to dump memory usage.

**Comment by fourmond** [comment]
(I could try writing the gem, too, if I have an idea of where to find the information, thanks !)

**Comment by matz** [comment]
You may want to use `mruby-objectspace` gem. It provides the following methods:
* `ObjectSpace.count_objects` that returns number of objects of each type
* `ObjectSpace.each_object` that iterates over all live objects

**Comment by xor256** [comment]
@matz Can You show me Your way to checking memory leak in C extensions?

What parameters etc. I must using sanitize memory or not?

**Comment by matz** [comment]
I use `valgrind` to check memory leaks in C extensions. GCC (or Clang) `-fsanitize=address` also works.
If your _memory leak_ is Ruby level leaks (that means no leaks in C level, but some objects are accidentally referenced from GC root), I'd use `ObjectSpace.count_objects` periodically and checks what kind of object we have leaked. Although I seldom meet that kind of leaks.

@xor256, did I answer your question?

**Comment by letarg0** [comment]
No, this is not answer.

I create a small extension in C. I check it running a ruby script (for example test.rb include 'require_relative'). Script working.

But if i run my script on linux
`valgrind -v --tool=memcheck --leak-check=full ./test.rb`

I'm not get sumary information.
I get:
```
....
--22972-- REDIR: 0x4ee5d60 (libc.so.6:__strchrnul_sse2) redirected to 0x4c36eb0 (strchrnul)
--22972-- REDIR: 0x4ecc7a0 (libc.so.6:malloc) redirected to 0x4c2fafd (malloc)
--22972-- REDIR: 0x4ecd030 (libc.so.6:free) redirected to 0x4c30caa (free)
--22972-- REDIR: 0x4ef00a0 (libc.so.6:memcpy@GLIBC_2.2.5) redirected to 0x4c33ef0 (memcpy@GLIBC_2.2.5)
--22972-- REDIR: 0x4ee6400 (libc.so.6:__strnlen_sse2) redirected to 0x4c32b20 (strnlen)
--22972-- REDIR: 0x4ef0080 (libc.so.6:__mempcpy_sse2_unaligned) redirected to 0x4c36fc0 (mempcpy)
```
information from script and nothing more. Valgrind stoping. Not showing summary.

Please look this https://github.com/letarg0/Dziwne repo and type `make mem`

```
$uname -a
Linux 4.14.11.x86_64 #1 SMP x86_64 x86_64 x86_64  Linux Fedora
```

**Comment by matz** [comment]
1. Your repo `letarg0/Dziwne` is a CRuby extension that **should not** be covered here.
2. your description above is incomplete. describe what you expected and what you got in detail.
3. your valgrind output is clipped. I guess very important information was dropped from the log.

**Comment by letarg0** [comment]
3. Yes, it is clipped. This is my question why. I get clipped output and i can't read this important communicats. Can You run `make mem` and tell me why it is clipped? This is clue of my question

2. I need information: is or not is memory leak in my c extension.

1. Yes, I now know. If You would not answer i undestand.

**Comment by matz** [comment]
* it seems your valgrind output is corrupted. that indicates your valgrind installation or something must be wrong. it is out of our scope. we cannot help you here.
* I am not the right person for your **free** tutor.

**Comment by letarg0** [comment]
You are right, You not must helping for free for me.

Thanks for You work.
