### ISSUE TITLE
"register" keyword is not supported anymore in C++17

### ISSUE THREAD

**Issue by llothar** [mruby/mruby#3912]
When compiling with "enable_cxx_abi"  and setting the compiler options to use "-std=c++17" i get errors that there are still a handful of locations where this keyword  is defined.

I think we can safely remove them. No C or C++ compiler is using these hints anymore.

**Comment by llothar** [comment]
I just learned the basics of github in under 30min and create a pull request for my changes.

**Comment by matz** [comment]
Closed by #3913
