### ISSUE TITLE
Getting line numbers/file name when errors occurs with mrb_load_file

### ISSUE THREAD

**Issue by Vallantyn** [mruby/mruby#3914]
I'm embedding mruby scripts from c/cpp side using mrb_load_file (and the mruby-require mgem).
However, whenever an error occurs in the said file, I get only the error description, but no line number/file name.
I saw that it may related to the fact that the file is compiled to mrb during this process, but I found no way to generate debug information from load_file.

Am I missing something or is it actually not supported ?

**Comment by matz** [comment]
Probably you didn't use `-g` (debug option) when compiling your ruby files by `mrbc`.

**Comment by Vallantyn** [comment]
I'm fully aware of the `-g` option.
I'm not using mrbc, I'm embedding mruby scripts (not compiled .rb files) in a c/c++ application.
My question being, when an error occurs in one file I load from my c/c++ application, is there any way to get the line numbers/file name.
Knowing that mruby turn .rb files into bytecode when I load them using `mrb_load_file`, is there any way to reproduce `-g` option with `mrb_load_file` ?

**Comment by fourmond** [comment]
I found that using a combination of `mrb_generate_code` (with a call to `mrb_filename` to the context) and `mrb_run` was necessary for me to get context information.

**Comment by Vallantyn** [comment]
@fourmond Thanks, will try that !

**Comment by matz** [comment]
Hmm, `mrb_load_file` compiles a Ruby file into internal representation *with debug information*, so that you don't have to specify anything. Do you mean that you use something like the following code, and you don't get backtrace?

``` C
    v = mrb_load_file(mrb, path);
    if (mrb->exc) {
        mrb_print_error(mrb);
    }
```

**Comment by matz** [comment]
Note that `mrb_p(mrb, mrb_obj_value(mrb->exc));` does not print backtrace.

**Comment by Vallantyn** [comment]
@matz Your first exemple is exactly what I use.
This is what I get with a file containing errors:

```
NameError: uninitialized constant Foo
Press [ENTER] to quit...
```

I tried different methods to get a more explicit backtrace: `mrb_print_backtrace`, using the mruby-backtrace mgem, I always get the same result. I tried digging a bit in the `mrbc_context` to see if I was missing something, but no luck so far.

**Comment by matz** [comment]
I am sorry but I have no clue, if you are doing as you explained. Can I read your code?

**Comment by Vallantyn** [comment]
Thanks to @fourmond I found what was missing from the context.
I get the proper backtrace when I do this:

``` ruby
int e;
FILE* fp;
if ((e = fopen_s(&fp, "./Main.rb", "r")) != 0)
{
	puts("Failed to open File");
	puts("Press [ENTER] to quit...");
	getchar();
	return e;
}
	
mrb_state* mrb = mrb_open();
mrbc_context* cxt = mrbc_context_new(mrb);

mrbc_filename(mrb, cxt, "Main.rb");
mrb_value obj = mrb_load_file_cxt(mrb, fp, cxt);

fclose(fp);

if ((mrb)->exc)
{
	mrb_print_error(mrb);
}
```

Getting this result:
```
trace (most recent call last):
        [0] Main.rb:3
Main.rb:3: uninitialized constant Foo (NameError)
Press [ENTER] to quit...
```

So I'm thinking that maybe the filename isn't properly retrieved/passed to the context somewhere ?

@matz Just saw your reply, my former code was as follow:
``` ruby
int e;
FILE* fp;
if ((e = fopen_s(&fp, "./Main.rb", "r")) != 0)
{
	puts("Failed to open File");
	puts("Press [ENTER] to quit...");
	getchar();
	return e;
}
	
mrb_state* mrb = mrb_open();
mrb_value obj = mrb_load_file(mrb, fp);

fclose(fp);

if ((mrb)->exc)
{
	mrb_print_error(mrb);
}
```

**Comment by matz** [comment]
Ah, sorry for misleading comments. And I am glad that you have solved the issue.
May I close this issue?

**Comment by Vallantyn** [comment]
Sure !
