### ISSUE TITLE
safe and portable MRB_METHOD_TABLE_INLINE

### ISSUE THREAD

**Issue by miura1729** [mruby/mruby#3917]
MRB_METHOD_INLINE makes mruby effective for speed and memory.  (https://github.com/mruby/mruby/commit/8f2c62407c0659d84126545e19505a851059e750) But MRB_METHOD_INLINE is machine depend and no check system. I propose safe and portable MRB_METHOD_INLINE. (https://github.com/miura1729/mruby/commit/f65157e7810095419096d91079c3fdb245aaab32)
 Key idea of this patch is prepare a static variable to put the address of the function and store variable address in method table.This enable using 2bits as flag because the address of the variable is alined.
To make declaring and initializing static variable easy, I redefine mrb_define_method, mrb_define ... as macro.

**Comment by matz** [comment]
Please make a pull request instead of submitting an issue.

**Comment by miura1729** [comment]
I send pull request. Please check.
