### ISSUE TITLE
Unable to search constant in module

### ISSUE THREAD

**Issue by pyama86** [mruby/mruby#3919]
refs: https://github.com/mruby/mruby/pull/3757/commits/c7018ea9627efd9c6fe4ef6b6f459fefef01fc52

Since this commit, it seems that the behavior of `Module.const_get` has changed, is it the intended movement?

# ruby 2.6
```
% ruby -v
ruby 2.6.0dev (2018-01-03 trunk 61575) [x86_64-darwin16]
% irb 
irb(main):001:0> module Example;end;
=> nil
Module.const_get('Example')
irb(main):002:0> Module.const_get('Example')
=> Example
```

# mruby
```
% irb
> module Example;end;
 => nil
> Module.const_get('Example')
(mirb):43: uninitialized constant Module::Example (NameError)
```

**Comment by matz** [comment]
Since Ruby2.5 does not allow `Module::Example` any longer, I think CRuby should be fixed.

**Comment by pyama86** [comment]
I understand this matter.
thanks!
