### ISSUE TITLE
add option request

### ISSUE THREAD

**Issue by yamori813** [mruby/mruby#3922]
I do run mruby on RTL8196 bare metal module. This is mips big endian soc. I want two option for mruby.

One is in include/mrbconf.h. gcc defined __linux__ but this target must be not defeine MRB_METHOD_TABLE_INLINE.

#if !defined(MRB_METHOD_TABLE_INLINE) && defined(__linux__)
# define MRB_METHOD_TABLE_INLINE
#endif

Second is in mrblib/mrblib.rake. RTL8196 is Big endian. I want set -E option at mrbc. 

Regards.

**Comment by matz** [comment]
Can you elaborate bit more? Pull-request is even better.
(Japanese is OK if you prefer)

**Comment by yamori813** [comment]
MRB_METHOD_TABLE_INLINEについてはオプションで定義されないようにするのが良いかとおもうので、少し考えてみてPull-requestします。

mrblib/mrblib.rakeはビルドされるmrblib.cにBigEndianの場合は-Eを付けるとコメントにあるのですが、rake詳しくなくオプションの付け方など分かりません。-Eを付けなくても動作はするようなので、必要なかったでしょうか？

**Comment by matz** [comment]
I just added `big_endian` method to `MRuby::CrossBuild` that specifies `-E` option to `mrbc`.
It works even if you don't specify `-E` to `mrbc` but compiled binary uses less memory with it.

`MRuby::CrossBuild` に `big_endian` メソッドを追加しました。これを呼ぶと `mrbc` の呼び出しに `-E` オプションをつけるようになります。`-E` オプションを指定しなくても動作しますが、つけておいた方がコンパイルしたバイナリの実行時により少ないメモリを使用します。

**Comment by yamori813** [comment]
I set big_endian then mrblib.c is "dumped in big endian order."  It's work fine. Thanks.

**Comment by matz** [comment]
The original issue is covered by #3924 so I close this issue.
