### ISSUE TITLE
extension array

### ISSUE THREAD

**Issue by xor256** [mruby/mruby#3925]
I need write small extension in C++
I create array 
 VALUE arr;
    arr = rb_iv_get(self, "@name");
    rb_ary_push(arr, obj);

a) How I can check size of array?
b) how print each element in array?
similar @name.each{|e| p e}

I cant find any tutorial for creating extension and enumerator.
My extension get normal array data and modyfing it.

**Comment by matz** [comment]
You can use `mrb_array_p(arr)` to check if it's an array. Once you are sure it's an array, you can get the length of the array by `RARRAY_LEN(arr)`. So if you want to print each element in an array `arr` by the following code:

```C
mrb_int i;
for (i=0; i<RARRAY_LEN(arr); i++) {
  mrb_p(mrb, RARRAY_PTR[i]);
}
```

**Comment by xor256** [comment]
Yes this is working example

Thanks

**Comment by matz** [comment]
I updated the code.
