### ISSUE TITLE
How check type of obiect (Extension)

### ISSUE THREAD

**Issue by letarg0** [mruby/mruby#3928]
I create a extension. I use Check_Type or TYPE(x)

But how check not standard type?
for example I create class Cosik
how check the parameter is my type Cosik ? Is important to check type of obiect because i use my C structure  inside object

**Comment by matz** [comment]
`mruby-time` is a good example.  Check out sources under the `mrbgems/mruby-time` directory.

**Comment by letarg0** [comment]
You are nor reading my question.
I ask about checking type. But not type defined in ruby.h Only my own class.
For example mruby-time
...
mrb_define_class_method(mrb, tc, "specialconvert", mrb_time_convert, MRB_ARGS_NONE());

This function convert time from time.
t = Time.new
r = Time.new
t.specialconvert(r)

How checking (in cruby and mruby too) paramerets type functions 'specialconvert' ?
Is default T_FIXNUM T_SYMBOL etc. but how check this is type 'Time' or not?

How read struct mrb_time  from other obiect 'r' from obiect 't' ?
This is my question. How check type and read data from other obiect tis same type.

Please not closing my questions without answer. mruby-time is not answer on my question.

**Comment by matz** [comment]
Perhaps you didn't check `mruby-time/src/time.c` carefully enough. For example, `Time#-` (implemented by C function `mrb_time_minus`) takes a `Time` object as an argument. The type check and struct pointer retrieval are done using the macro ` DATA_CHECK_GET_PTR()` (line 475 of `time.c`).

**Comment by letarg0** [comment]
I'm not sure. In Cruby too?
In cruby exist similar function? 

I'm beginer in mruby and cruby.

**Comment by matz** [comment]
Ah, please do not ask CRuby question here. It's a totally separate issue.
And mruby and CRuby do not have C API compatibility.

We haven't finished documentation for `DATA_CHECK_GET_PTR` yet. Currently, `mruby-time` itself is an example.

**Comment by letarg0** [comment]
Ok, Where is Cruby issue?

In whitch file is documentation (source DATA_CHECK_GET_PTR)

Many thanks for You help. Now I think the issue is closed

**Comment by matz** [comment]
We usually use `ruby-talk` mailing list for that kind of questions.

We have small information under `doc` and `examples` directory. For more information, read the source code.  (and contribution is welcome).
