### ISSUE TITLE
About using a part of mruby code in my code

### ISSUE THREAD

**Issue by bamchoh** [mruby/mruby#3929]
Hi, I'm writing TOML parser written in C.
I'd like to use a part of mruby parser source code in the my code.
Can I use a part of mruby source code in my source code?
For instance, I'd like to use a part of source code for parsing unicode.
https://github.com/mruby/mruby/blob/master/mrbgems/mruby-compiler/core/parse.y#L3801

**Comment by shevegen** [comment]
Hello bamchoch,

matz may correct me if I am wrong.

mruby is licenced under the MIT licence:

https://github.com/mruby/mruby/blob/master/MITL

The licence gives you a lot of flexibility, more than the
GPL (although the GPL is also a fine licence IMHO).

So essentially, you can use the source code to mruby
in any way you wish, including modifications, provided
that you follow a few guidelines to it:

- In particular, you must retain the copyright and
permission notice (see that MITL file above).

It may also be useful to add a "no warranty" subsection,
even though I think it may depend on the interpretation
of jurisdiction (but I think it does not help if you mention
that there is simply no warranty and no guarantee of it).

So essentially, yes, as far as I understood it, you can use
the source code or parts of it. I don't think that you are
required to use ALL of mruby but can simply use parts
of it too provided that you comply with the licence (which,
in my opinion, is very simple - there is a reason why 
MIT/BSD style licence are among the most popular ones).

Hope this helped - I am sure if I am wrong, someone will
correct me. :)

**Comment by bamchoh** [comment]
Thank you for kindly answer. As you answered, I will use by following MIT license.
