### ISSUE TITLE
1.4.0 Changes

### ISSUE THREAD

**Issue by katzer** [mruby/mruby#3935]
@matz Could you please give us a changelog for 1.4.0?

**Comment by matz** [comment]
I am waiting for @bovi's blog entry he usually writes after releases. Probably I have to do it by myself.

**Comment by bovi** [comment]
I have already some notes written down. I will finally in the next one week and publish.

**Comment by matz** [comment]
@bovi Thank you!

**Comment by proyb6** [comment]
What is the link to @bovi blog?

I see some issues has been bug fixed just recently, is it possible to release 1.4.1?

**Comment by matz** [comment]
We are planning 1.4.1 hopefully around April.

**Comment by letarg0** [comment]
@bovi and update web page
