### ISSUE TITLE
on mruby.org

### ISSUE THREAD

**Issue by letarg0** [mruby/mruby#3958]
is still 1.3 as latest version

**Comment by proyb6** [comment]
Yes, assume they haven't released the summary of the 1.4 in their blog, to be waiting for 1.4.1 release and that would be important for H2O web server as well.

**Comment by shevegen** [comment]
It may be that the webpage should show 1.4, even without a changelog entry; the entry could be left as a stub for now and filled in at a later time when Daniel is finished. I assume he is very busy right now; matz also seems to be extremely busy. In MRI ruby, we have a NEWS entry at: https://github.com/ruby/ruby/blob/trunk/NEWS - perhaps something similar could be added to mruby though I guess several people may have to help adding news entry to mruby (MRI probably has more manpower than mruby; ideally we could merge both mruby and MRI one day but I suppose there are many other things to do, like mjit, ruby 3.x and so forth).
