### ISSUE TITLE
build_dir

### ISSUE THREAD

**Issue by letarg0** [mruby/mruby#3959]
I delete all section on **build_config.rb**

and i have only my own 
```
MRuby::Build.new('letarg') do |conf|
 toolchain :gcc
 conf.cc.flags << '-O3'
 conf.gembox 'letard'
end
```

The system forget create a directory ;-) **undefined method 'build_dir' for nil:NilClass**

```
$ make
ruby ./minirake
(in /home/letarg/experiment/mruby)
rake aborted!
undefined method `build_dir' for nil:NilClass
rakefile:26:in `load'
make: *** [all] Error 1
```
is possible to correct Rakefile ?
I need only my specyfic compilation.

**Comment by robfors** [comment]
I think I am having a similar problem. I want to separate the compilation process in to two build_config files. In one file I have the `MRuby::Build.new` section that I only want to have run once. This works with no problems. In a second file I have a `MRuby::CrossBuild.new('aaa')` and an accompanying `MRuby::Toolchain.new('bbb')`. If I put the Toolchain first, in the file I get 

> undefined method `build_dir' for nil:NilClass

If I put the CrossBuild first in the file I get
> Unknown bbb toolchain

Im I missing something?
Can I run a build process with only a CrossBuild?

**Comment by take-cheeze** [comment]
You need `'host'` `MRuby::Build` (which is `MRuby::Build` without name) since mruby requires `mrbc` to compile your ruby scripts to binary:
https://github.com/mruby/mruby/blob/097bfdcac573861567716e4247265becec6b249a/lib/mruby/build.rb#L228
There is no option to build without `host` currently.
Though error messages needs to be improved.

**Comment by take-cheeze** [comment]
Try `minirake -t` for stacktrace of build script error.

**Comment by robfors** [comment]
Thanks for the clarification.
