### ISSUE TITLE
How about allow mrb_get_args to skip args

### ISSUE THREAD

**Issue by tmshn** [mruby/mruby#3967]
## What I want to do

Sometimes I want `mrb_get_args` to skip some arguments, especially when it's better to split argument parser into multiple functions.

#### Example:

Say I have a method with to string args and keyworded options.

```c
mrb_value key, value, opt;
mrb_bool opt_given;
mrb_get_args(mrb, "SS|H?", &key, &value, &opt, &opt_given);
```

↓ I want split this this into two:

```c
// In basic-parser
mrb_value key, value;
mrb_get_args(mrb, "SS...", &key, &value);

// In xxx-option-parser
mrb_value opt;
mrb_bool opt_given;
mrb_get_args(mrb, "--|H?", &opt, &opt_given);
```

But instead, what I can do now is to parse same thing twice, which is very redundant and wasteful.

```c
// In basic-parser
mrb_value key, value, *rest;
mrb_int rest_cnt;
mrb_get_args(mrb, "SS*!", &key, &value, &rest, &rest_cnt);
// -> ignore `rest` and `rest_cnt`

// In xxx-option-parser
mrb_value key, value, opt;
mrb_bool opt_given;
mrb_get_args(mrb, "oo|H?", &key, &value, &opt, &opt_given);
// -> ignore `key` and `value`
```

#### 1. Define special format specifier for this purpose

This is what shown in above example. I propose `-` to skip single item and `...` to ignore rest of all.

```c
// Skip the first arg and parse second one.
mrb_get_args(mrb, "-o", &arg2);

// Parse only first arg and ignore rest.
mrb_get_args(mrb, "o...", &arg1);
```

#### 2. Allow passing `NULL`

Instead of defining new specifier, we can allow `NULL` in arguments.

```c
// Skip the first arg and parse second one.
mrb_get_args(mrb, "oo", NULL, &arg2);

// Parse only first arg and ignore rest.
mrb_get_args(mrb, "o*", &arg1, NULL, NULL);
```

I want hear from you guys; what do say for this?

**Comment by take-cheeze** [comment]
I don't feel good with undetermined argument types especially for API written in C since I don't like writing long C code.
`mrb_get_args` isn't a low cost API and has many error handling inside so you shouldn't call it multiple times as much as possible.

Use `mrb_get_argc` and `mrb_get_argv` instead for complex argument handling.
And you should write things in ruby if ruby is better handling it.

**Comment by matz** [comment]
I don't think this is a good idea. I might be misunderstanding you from this rather artificial example.
Feel free to reopen the issue, if you have a better explanation of what you want.

**Comment by tmshn** [comment]
@take-cheese @matz Thank you for your quick reply!
But sorry, I couldn’t get what you’ve said perfectly, so let me clarify.
What are the bad point, performance concern or design poorness?

**Comment by matz** [comment]
Primarily code complexity it would bring. Besides that, I couldn't imagine concrete situations where we need to separate `mrb_get_args` calls.

**Comment by tmshn** [comment]
Okay I got it. I will rethink of my code. Thanks anyway!
