### ISSUE TITLE
Not used MRB_FLAG_IS_INHERITED

### ISSUE THREAD

**Issue by dearblue** [mruby/mruby#3975]
``MRB_FLAG_IS_INHERITED`` is 22th bit from LSB, but ``flags`` field is allocated 21 bits in ``MRB_OBJECT_HEADER``.

  * from [include/mruby/object.h:10](https://github.com/mruby/mruby/blob/master/include/mruby/object.h#L10)

    ```c
    #define MRB_OBJECT_HEADER \
      enum mrb_vtype tt:8;\
      uint32_t color:3;\
      uint32_t flags:21;\
      struct RClass *c;\
      struct RBasic *gcnext
    ```

  * from [include/mruby/class.h:68](https://github.com/mruby/mruby/blob/master/include/mruby/class.h#L68)

    ```c
    #define MRB_FLAG_IS_INHERITED (1 << 21)
    ```

Therefore ``MRB_FLAG_IS_INHERITED`` is ignored always (same as constant zero).

  * test code (test_inherited_bit.c)

    ```c
    #include <mruby.h>
    #include <mruby/class.h>

    int test(void)
    {
      struct RClass c = { 0 };
      c.flags |= MRB_FLAG_IS_INHERITED;
      return c.flags;
    }
    ```

  * assembled result by ``gcc7 -I include -S -O -o - test_inherited_bit.c``

    ```s
    	.file	"test_inherited_bit.c"
    	.text
    	.globl	test
    	.type	test, @function
    test:
    .LFB16:
    	.cfi_startproc
    	movl	$0, %eax
    	ret
    	.cfi_endproc
    .LFE16:
    	.size	test, .-test
    	.ident	"GCC: (FreeBSD Ports Collection) 7.3.0"
    	.section	.note.GNU-stack,"",@progbits
    ```

Sorry to report only.

**Comment by take-cheeze** [comment]
Seems to be introduced in: https://github.com/mruby/mruby/commit/4c9a60487799b923ff905def46cb2497bcc1e4dd
It seems like this flag is used to clear method cache when inherited.
And out of range flag may cause method cache bug...
Bit 18 is used by frozen: https://github.com/mruby/mruby/blob/c3c882f681451c76ad6ffde984ec33432c5b579a/include/mruby/object.h#L26
so moving it with bit 17 should solve this.

Though this problem only occur on `MRB_METHOD_CACHE` enabled mruby.

**Comment by take-cheeze** [comment]
I wish this was a compiler warning...
Anyway valuable report!
