### ISSUE TITLE
In `MRB_INT32` enabled build, test fails.

### ISSUE THREAD

**Issue by take-cheeze** [mruby/mruby#3997]
Seems fallback to float isn't working because of `MRB_WITHOUT_FLOAT`.

This assertion get exception raise:
https://github.com/mruby/mruby/blob/1905091634a6a2925c911484434448e568330626/test/t/integer.rb#L161

From: https://github.com/mruby/mruby/blob/1905091634a6a2925c911484434448e568330626/src/string.c#L2170

**Comment by matz** [comment]
Can you elaborate?
My build with `MRB_INT32` works fine (`MRB_WITHOUT_FLOAT` disabled).
Do you mean tests failed when `MRB_WITHOUT_FLOAT` enabled?
I consider `MRB_WITHOUT_FLOAT` is a configuration for the very limited environment and is not matured enough to run through all tests, including this one.

**Comment by take-cheeze** [comment]
build_config.rb:
https://gist.github.com/take-cheeze/0b343f688dbde0d398f50da80004bad1
compile and test log:
https://gist.github.com/take-cheeze/23f274df779b09173a7be09d5fd35c62

**Comment by take-cheeze** [comment]
And seems to be called from:
https://github.com/mruby/mruby/blob/75c1fccd08a7cc529bcac5031ebc52176c6fd267/src/object.c#L557

**Comment by take-cheeze** [comment]
I mostly get this problem in mingw-w64 i686 environment:
https://103.128.221.202.static.iijgio.jp/jenkins/job/master-mruby-marshal/203/console

**Comment by matz** [comment]
I cannot reproduce the issue on my Linux box using your `build_config.rb`.
Is this specifuc to mingw-w64 compiler?
