### ISSUE TITLE
add optname SO_ORIGINAL_DST

### ISSUE THREAD

**Issue by takafan** [mruby/mruby#4002]
SO_ORIGINAL_DST is defined at
https://github.com/torvalds/linux/blob/master/include/uapi/linux/netfilter_ipv4.h

ruby missing it, but i can set 80 directly and worked fine: 

sock.getsockopt(Socket::SOL_IP, 80)

in mruby i got Errno::EINVAL

**Comment by matz** [comment]
It's not defined in CRuby either. Basically, mruby does not provide the original feature addition unless necessary. You had better proposed to CRuby first.
