### ISSUE TITLE
irep to proc

### ISSUE THREAD

**Issue by robfors** [mruby/mruby#4026]
Hello, I am wondering if it is possible to take the irep output from `mrbc` as the usual `uint8_t` array, convert it in to a Ruby `Proc` and pass it to a method implemented in Ruby so it can be called later.

This is what I tried:
```c
extern uint8_t app_irep[];

mrb_irep* app_mrb_irep = mrb_read_irep(_mrb, app_irep);
struct RProc* app_proc = mrb_proc_new(_mrb, app_mrb_irep);
app_proc->c = NULL;
mrb_irep_decref(_mrb, app_mrb_irep);
mrb_value app_proc_mrb_value = mrb_obj_value(app_proc);
RClass* esruby_module = mrb_module_get(_mrb, "ESRuby");
mrb_value esruby_module_mrb_value = mrb_obj_value(esruby_module);
mrb_funcall(_mrb, esruby_module_mrb_value, "run_app", 1, app_proc_mrb_value);
```
```ruby
module ESRuby
  def self.run_app(app_block)
    puts app_block.call => NoMethodError
    puts app_block.class => NoMethodError
    puts app_block.inspect => NoMethodError
  end
end
```
It appears that `app_block` in Ruby does not respond to any methods.

**Comment by matz** [comment]
You set `app_proc->c` to `NULL`. That means `app_proc` cannot behave as a Ruby object.
In addition, you should not call `mrb_irep_decrep` for a living proc object.

**Comment by dearblue** [comment]
It may be process force exit or occur SEGV after do `.call` if use `mrb_read_irep()` + `mrb_proc_new()`.

I think that it get the better results by use `mrb_load_irep()`.

```diff
--- temp.c~
+++ temp.c
@@ -1,10 +1,6 @@
 extern uint8_t app_irep[];
 
-mrb_irep* app_mrb_irep = mrb_read_irep(_mrb, app_irep);
-struct RProc* app_proc = mrb_proc_new(_mrb, app_mrb_irep);
-app_proc->c = NULL;
-mrb_irep_decref(_mrb, app_mrb_irep);
-mrb_value app_proc_mrb_value = mrb_obj_value(app_proc);
+mrb_value app_proc_mrb_value = mrb_load_irep(_mrb, app_irep);
 RClass* esruby_module = mrb_module_get(_mrb, "ESRuby");
 mrb_value esruby_module_mrb_value = mrb_obj_value(esruby_module);
 mrb_funcall(_mrb, esruby_module_mrb_value, "run_app", 1, app_proc_mrb_value);
```

**Comment by robfors** [comment]
@matz That works perfectly!
@dearblue I went with `mrb_read_irep` over `mrb_load_irep` because I need to run it in a Fiber.
Thanks for the suggestions everyone.

**Comment by robfors** [comment]
After working with it some more I may have found a bug.
I used `method` on a method that calls `#call` on my `app_proc`. When I then invoke the proc returned from `method` I get a segfault.
Sounds like the sort of problem @dearblue was referring to.

This is how to reproduce it if anyone is curious:
```ruby
# app.rb
puts 'app'
```

```ruby
# test_program.rb
def start_app
  $app_proc.call
end

#puts method(:start_app).call # calling this here will run the proc and then segfault

#start_app # calling this directly is not an issue

puts 'hello world'
```

```c
// test_stub.c
#include <stdio.h>
#include <mruby.h>
#include <mruby/class.h>
#include <mruby/proc.h>
#include <mruby/variable.h>
#include <mruby/irep.h>
#include <mruby/dump.h>

#include "test_program.c"
#include "app.c"

int main(void)
{
  mrb_state *mrb = mrb_open();
  
  // set up app_proc
  mrb_irep* app_mrb_irep = mrb_read_irep(mrb, app_irep);
  struct RProc* app_proc = mrb_proc_new(mrb, app_mrb_irep);
  mrb_value app_proc_mrb_value = mrb_obj_value(app_proc);
  mrb_gv_set(mrb, mrb_intern_lit(mrb, "$app_proc"), app_proc_mrb_value);
  
  mrb_load_irep(mrb, test_symbol);
  
  // invoke app_proc
  mrb_value code = mrb_str_new(mrb, "method(:start_app)", 20);
  mrb_value return_value = mrb_funcall_argv(mrb, mrb_top_self(mrb), mrb_intern_lit(mrb, "eval"), 1, &code);
  mrb_funcall_argv(mrb, return_value, mrb_intern_lit(mrb, "call"), 0, NULL);
  
  // running any other code after the app_proc will cause problems
  // running "tt = 88" will segfault
  code = mrb_str_new(mrb, "test = 88", 9);
  mrb_funcall_argv(mrb, mrb_top_self(mrb), mrb_intern_lit(mrb, "eval"), 1, &code);
  
  if (mrb->exc)
  {
    mrb_print_error(mrb);
    mrb->exc = NULL;
    return 1;
  }
  
  mrb_close(mrb);
  return 0;
}
```
Compile and run with:
```
mruby/bin/mrbc -Bapp_irep app.rb
mruby/bin/mrbc -Btest_symbol test_program.rb
gcc -std=c99 -Imruby/include test_stub.c -o test_program mruby/build/host/lib/libmruby.a -lm
./test_program
```

**Comment by dearblue** [comment]
@robfors 

`mrb_proc_new()` function is prototyped without `MRB_API`.
I look like a function for internal implementation.

https://github.com/mruby/mruby/blob/023070a6396233974785a8fd5735b9380a884f27/include/mruby/proc.h#L84

So instead of having a problem with `mrb_proc_new()`, I think there is a problem with using it.

**Comment by matz** [comment]
@robfors I have to investigate the issue further to determine where the bug is. But could you submit a new issue for better issue management, please?

**Comment by robfors** [comment]
@matz No problem see #4028 

The alternative solution to my original problem it to run `mrbc` with a prepended and appended file to enclose the code from the main file in a proc, so I will use that for now.
