### ISSUE TITLE
local variables gets broken

### ISSUE THREAD

**Issue by i110** [mruby/mruby#4029]
I'm totally not sure what's the real cause of this problem, but anyway something seems to be broken with proc and cyclic hash.

```ruby
class Foo
  def doit
    hash = { "foo" => nil }
    hash["foo"] = hash
  end
end

foo = Foo.new
1.times {
  puts foo.doit
  p foo
}
```

I expected `p foo` outputs like `#<Foo:0x7f936cbfe2b0>`, but the results are different, and even worse, different everytime.

```
$ build/host/bin/mruby repro.rb
{...}
"foo"
$ build/host/bin/mruby repro.rb
{...}
#<Proc:0x7ffc57834f60@/Users/i110/mruby/mrblib/enum.rb::61>
$ build/host/bin/mruby repro.rb
{...}
#<Proc:0x7f8093053190@/Users/i110/mruby/mrblib/hash.rb::199>
$ build/host/bin/mruby repro.rb
{...}
[]
$ build/host/bin/mruby repro.rb
{...}
[["foo", {...}]]
$ build/host/bin/mruby repro.rb
{...}
#<Proc:0x7f96b5053190@/Users/i110/mruby/mrblib/hash.rb::199>
```

What's happening?

**Comment by matz** [comment]
Unfortunately, I could not reproduce the issue on my machine. Could you provide more information (e.g. platform, the latest commit hash, etc.)? Does it happen on the latest?

**Comment by i110** [comment]
Platform: OSX 10.13.3
Commit: 3952607 (current latest)

Just now I tried on Linux and all things work well, so this might be a specific problem on osx. I'll take a further look..

**Comment by i110** [comment]
more concise repro code:

```ruby
x = 1
proc {
  puts proc {
    hash = { "foo" => nil }
    hash["foo"] = hash
  }.call
  puts x
}.call
```
