### ISSUE TITLE
const_get fails to resolve top-level scope

### ISSUE THREAD

**Issue by fundamental** [mruby/mruby#4070]
Last known good commit: e5b61d34f65cabfbe88f3f1709a1f9cff86585de

Test Case:

```
puts Kernel.const_get :Object
```

CRuby output:

```
Object
```

MRuby output:

```
trace (most recent call last):
	[0] test2.rb:1
test2.rb:1: uninitialized constant Kernel::Object (NameError)
```

**Comment by fundamental** [comment]
This appears to be intentional as per c96def7c96c50f3b8e22e47ce31a6c5a37939dfd .

Can someone confirm that "Object.const_get(:AnyClassName)" should be a suitable replacement?

**Comment by katzer** [comment]
@fundamental 
> Can someone confirm that "Object.const_get(:AnyClassName)" should be a suitable replacement?

Thats the way to go if `AnyClassName` is defined under the top level namespace, e.g. `Object::AnyClassName`

**Comment by matz** [comment]
It was intentional but Ruby2.5 doesn't behave like it. I misunderstood something. It should be fixed.

**Comment by fundamental** [comment]
In case this clarification changes anything, my typical use case is defining some arbitrary class at the highest level scope (top?) e.g.:

```
class AnyClassName
end
```

And then using "const_get :AnyClassName" to know if the class has been defined or not. If it has been defined then the class is used as a super class, otherwise it tries to see if "Namespace::AnyClassName" exists via another const_get call, and based upon that it either uses the namespaced version or it runs code generation routines to create the namespaced version.
