### ISSUE TITLE
mobiruby.org is hacked

### ISSUE THREAD

**Issue by shanko** [mruby/mruby#4082]
**WARNING:** Do NOT do this at work as it MAY get you a visit from HR

I was looking at the Wiki here  https://github.com/mruby/mruby/wiki and clicked on Mobiruby.org thinking that I would learn about mobiruby and was redirected to a **porn site.** 

Can someone please fix this?

**Comment by Hir0** [comment]
MobiRuby.org domain has been released long ago and now owed by another person.
I edited Wiki's URL.

**Comment by shanko** [comment]
Thanks! I have emailed @masuidrive and requested him to fix it on his Github repo also.

**Comment by masuidrive** [comment]
Sorry, This project was closed. so I leased mobiruby.org domain.
