### ISSUE TITLE
`[sealed]` annotation for methods - will disallow overriding a method by disabling dynamic dispatch

### ISSUE THREAD

**Issue by LemonAndroid** [mruby/mruby#4099]
```ruby

[sealed]
def method
  puts "call to this method will save the time spend on dynamic method lookup"
end
```

**Comment by matz** [comment]
Interesting idea, but we are not going to add our own language feature to Ruby language.
Propose to the Ruby language itself, not mruby.

FYI, `[sealed]` conflicts with existing Ruby syntax.
