### ISSUE TITLE
Marshal in C

### ISSUE THREAD

**Issue by asfluido** [mruby/mruby#4105]
For whoever is interested, I wrote some code to substitute the `c++` marshalling code that is current in mruby with one in pure `C`. It is just a couple of days' work, but it matches my needs.

You find it [here](http://www.github.com/asfluido/mruby-marshal-c). I did not run comparative tests, but having had to study the current `c++` code, I believe my code should compare favorably.

All comment is welcome

Carlo

**Comment by matz** [comment]
How can we compare it to `mruby-marshel` gem?
Do you want to add this gem to mgem list?

**Comment by asfluido** [comment]
Thanks for replying. In my repository I added a second version  of my exerciser script, called `exerciser2.rb`. I commented the testing at the end (because the current marshal code apparently does not marshal the class you wanted to marshal, but `Class` instead, so that the tests did not pass). 

Also: there are two differences that the c++ code has with MRI, regarding functions to allow a class to define its marshalled content:

* `marshal_dump` is passed an argument (I do not know exactly for  what reason: the argument is `nil`)
* `marshal_load` is a class method instead of an instance method.

This new script just does marshalling/unmarshalling of a fixed-complexity hash 100 times, and then prints the run time per each iteration.

MRI:

> Each dump_restore cycle lasted 0.00431532953s

Mruby with c++ marshal:

> Each dump_restore cycle lasted 0.09503945999999999s

Mruby with my code:

> Each dump_restore cycle lasted 0.00730794s

Yes, the MRI code is almost twice as fast as mine (compliments...!), but the current c++ code is an order of magnitude slower!

(that's on my machine, linux with Intel(R) Core(TM) i7-3840QM CPU @ 2.80GHz)

Anyway,  I know for sure that I haven't implemented the marshalling of regular expressions, for one, and there may still be missing things. Does there exist a reference validation script for marshalling?

My wish is that the existence of my code is known, so that people who find themselves in my situation can know about it. If you want to insert it in the mgem list, I certainly have nothing against it.

**Comment by matz** [comment]
If the performance is the biggest improvement of your gem, I think it should be named `mruby-marshal-fast` or anything similar.

**Comment by asfluido** [comment]
No problem for me, although the most important thing for me is that it is not written in c++. My original goal was to have a working mruby compiled under a cross-compile environment without c++, and te marshalling code was the only essential part (for me) that was written in c++. 

I have renamed the github repo to `mruby-marshal-fast`.

**Comment by matz** [comment]
You can send a pull-request to https://github.com/mruby/mgem-list

**Comment by asfluido** [comment]
Ok. I sent it, and also added a license, as requested by Daniel Bovensiepen. 

I also found the time to add regular expression marshalling to the code, but only when using the `mruby-onig-regexp` gem.

**Comment by matz** [comment]
Thanks. Now I close this issue.
