### ISSUE TITLE
DRb & Rinda modules in mruby

### ISSUE THREAD

**Issue by vclaud** [mruby/mruby#4109]
Hi all,

Are there any plans to include these modules in the mruby distribution? I would be happy to have dRuby available as an option for inter-device communication. Moreover, Rinda provides a nice clean model for async communication that is easy to understand.

Thoughts?

**Comment by matz** [comment]
Currently, we have no plan to implement the official dRuby&Rinda gems. If someone is working on it, it is more than welcome, and we are glad to help.

**Comment by vclaud** [comment]
Thank you for the feedback! I plan to work on this.
