### ISSUE TITLE
mruby-io: `fork()` and `execl()` unavailable on tvOS

### ISSUE THREAD

**Issue by blacktm** [mruby/mruby#4113]
Hi everyone. I use mruby on iOS and tvOS and have a [project to build the Apple frameworks](https://github.com/ruby2d/mruby-frameworks). I just noticed in the latest tvOS 11.4.1 SDK, both `fork()` and `execl()` are unavailable, which are used in the `mruby-io` gem. Here's the output:

```
CC    mrbgems/mruby-io/src/io.c -> build/tvos/mrbgems/mruby-io/src/io.o
mruby-frameworks/mruby/mrbgems/mruby-io/src/io.c:253:3: error: 
      'execl' is unavailable: not available on tvOS
  execl("/bin/sh", "sh", "-c", pname, (char *)NULL);
  ^
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS11.4.sdk/usr/include/unistd.h:440:6: note: 
      'execl' has been explicitly marked unavailable here
int      execl(const char * __path, const char * __arg0, ...) __WATCHOS_PROHIBITED __TVOS...
         ^
mruby-frameworks/mruby/mrbgems/mruby-io/src/io.c:362:17: error: 
      'fork' is unavailable: not available on tvOS
  switch (pid = fork()) {
                ^
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS11.4.sdk/usr/include/unistd.h:446:8: note: 
      'fork' has been explicitly marked unavailable here
pid_t    fork(void) __WATCHOS_PROHIBITED __TVOS_PROHIBITED;
         ^
2 errors generated.

...and so on...
```

Looks like we're not allowed to create processes on iOS and tvOS. Might there be an alternative to using `fork()` and `execl()` here? Thanks!

**Comment by matz** [comment]
They are excluded on WIN32. So we can change the compilation condition to exclude iOS, tvOS.
Can you check the symbols for those OSes?

**Comment by blacktm** [comment]
Certainly, all platform targets are defined in `TargetConditionals.h` (for example in the directory: `/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS.sdk/usr/include/`). Since iOS, tvOS, and watchOS are all subsets of `TARGET_OS_IPHONE`, we could simply do something like:

```c
// mruby.h
#ifdef __APPLE__
  #ifndef __TARGETCONDITIONALS__
  #include "TargetConditionals.h"
  #endif
#endif

// source files
#if TARGET_OS_IPHONE
  // iOS, tvOS, watchOS hardware and simulators
#endif
```

Also defined and mutually exclusive are `TARGET_OS_IOS`, `TARGET_OS_TV`, `TARGET_OS_WATCH` if needed. Here's the diagram from the header that shows the symbol relationships:

```
+------------------------------------------------+
|                TARGET_OS_MAC                   |
| +---+  +-------------------------------------+ |
| |   |  |          TARGET_OS_IPHONE           | |
| |OSX|  | +-----+ +----+ +-------+ +--------+ | |
| |   |  | | IOS | | TV | | WATCH | | BRIDGE | | |
| |   |  | +-----+ +----+ +-------+ +--------+ | |
| +---+  +-------------------------------------+ |
+------------------------------------------------+
```

Hope this is helpful!

**Comment by matz** [comment]
I try to address the issue with 2661ac7. Could you check?
If any problem remains, please reopen the issue.

**Comment by blacktm** [comment]
That's great, thanks! There's just one more place to exclude, where `execl()` is called. I created PR #4122 to amend it and tested compilation on these platforms.
