### ISSUE TITLE
Translating the API - Brazilian Portuguese

### ISSUE THREAD

**Issue by pedroslab** [mruby/mruby#4123]
Hello Everyone

Is there anyone working on translations ? If not , I'd like to apply for the Brazilian Portuguese version. I have some experience in Ruby and recently I've been using Ruby on Rails on a personal project.

Best Regards

Pedro

**Comment by matz** [comment]
There's no translation plan.

**Comment by pedroslab** [comment]
I see.
Thank you.

**Comment by matz** [comment]
If you want to contribute, send the pull request to `mruby/mruby.github.io`.
But we might need to write more English document first. Sorry for my laziness.
