### ISSUE TITLE
Blocks created in Fiber are not garbage collected

### ISSUE THREAD

**Issue by bamark** [mruby/mruby#4143]
When creating a block inside a Fiber.new block and resuming, it doesn't appear the block is garbage collected.
- Comparing the number of objects before and after, there always seems to be T_ENV objects left over.

- The number of T_ENV objects after an even and odd number of garbage collections initiated adds up to the total number that would have been created.

It looks similar to #3998, but the workaround `GC.generational_mode = false` didn't make a difference with the issue.
```
GC.generational_mode = false
$start_counts = ObjectSpace::count_objects

#GC.disable

1000.times {
  fib = Fiber.new {
    1.times {}
  }
  fib.resume
}

#GC.enable

GC.start
GC.start
GC.start
#GC.start

$stop_counts = ObjectSpace::count_objects

puts("objspace diff #{$stop_counts.merge($start_counts) { |k, v1, v2| v1 - v2}}")
```
Output for running garbage collection 3 and 4 times
```
objspace diff {:TOTAL=>5120, :FREE=>4203, :T_OBJECT=>0, :T_CLASS=>0, :T_MODULE=>0, :T_ICLASS=>0, :T_SCLASS=>0, :T_PROC=>0, :T_ARRAY=>0, :T_HASH=>1, :T_STRING=>0, :T_EXCEPTION=>0, :T_ENV=>916, :T_DATA=>0}
objspace diff {:TOTAL=>5120, :FREE=>5033, :T_OBJECT=>0, :T_CLASS=>0, :T_MODULE=>0, :T_ICLASS=>0, :T_SCLASS=>0, :T_PROC=>0, :T_ARRAY=>0, :T_HASH=>1, :T_STRING=>0, :T_EXCEPTION=>0, :T_ENV=>86, :T_DATA=>0}
```

I tried this on the stable version of 1.4.1 and the latest development version (mruby-mruby-1.4.1-292-gb3a181a).

**Comment by matz** [comment]
Ah, we forget to mark freed env objects as `MRB_TT_FREE`.
