### ISSUE TITLE
ArgumentError not raised when at least one argument is passed to a method expecting none

### ISSUE THREAD

**Issue by robfors** [mruby/mruby#4144]
Consider `Array#index` defined with `MRB_ARGS_REQ(1)`
```ruby
a = []
a.index(1,1) # =>  ArgumentError:  wrong number of arguments (2 for 0)
```
Raises error as it should.
As an aside, I believe the `0` found in the error message is another bug.

Now consider `Array#clear` defined with `MRB_ARGS_NONE()`
```ruby
a = []
a.clear(1) # =>  []
a.clear(1,1) # =>  []
```
Should raise an `ArgumentError` error.

**Comment by matz** [comment]
Thank you for the report. FYI, `MRB_ARGS_NONE` etc. are currently not used for checks.
