### ISSUE TITLE
Embedding symbol index seems to be unnecessary

### ISSUE THREAD

**Issue by take-cheeze** [mruby/mruby#4150]
https://github.com/mruby/mruby/blob/eebb56713e27cde27a7b899da8636a0634704863/include/mruby/ops.h#L73-L83

**Comment by matz** [comment]
They are used when forwarding to `OP_SEND`. I didn't want to call `mrb_intern` each time forwarding.

**Comment by take-cheeze** [comment]
Is it possible to reserve symbols used in language features in the symbol table like:

| ID | String |
|---|---|
| 1 | `+` |
| 2 | `-` |
| 3 | `*` |
| ... | ... |
| 10 | `method_missing` |
| ... | ... |
| XXX | user defined symbols |
| ... | ... |

So that we can always access the reserved symbol with constant.

**Comment by matz** [comment]
Ah, they will not be required when embedded symbols are available. OK, remove them from the `OP` code.

**Comment by matz** [comment]
We can use `mrb_intern` for now.

**Comment by take-cheeze** [comment]
Moving to #4151
