### ISSUE TITLE
Assertion failure in tr_find_character

### ISSUE THREAD

**Issue by clayton-shopify** [mruby/mruby#4156]
If mruby is built with `enable_debug` in build_config.rb, then each of the following inputs can trigger an assertion failure in `tr_find_character`:
```ruby
'a'.count('')
'a'.delete('')
'a'.delete!('')
'a'.squeeze('')
'a'.squeeze!('')
'a'.tr('', '')
'a'.tr!('', '')
```
It looks like `tr_find_character` does not expect the pattern type to be `TR_UNINITIALIZED`.
```
Assertion failed: (0), function tr_find_character, file /Users/clayton/git/mruby/mrbgems/mruby-string-ext/src/string.c, line 371.
Abort trap: 6
```
This issue was reported by Dinko Galetic & Denis Kasak (https://hackerone.com/dgaletic).

**Comment by take-cheeze** [comment]
Seems it needs specialization for empty pattern.

**Comment by matz** [comment]
I fixed it. Soon to be committed.
