### ISSUE TITLE
TypeError: uninitialized ExampleClass (expected ExampleClass)

### ISSUE THREAD

**Issue by robfors** [mruby/mruby#4169]
I have some cpp code that includes the following:
```cpp
namespace DataObject
{

  RClass* class_mrb;
  
  struct mrb_data_type _internal_data_type = {"DataObject", gc_callback};
  

  void gc_callback(mrb_state* mrb, void* ptr)
  {
    printf("gc start\n");
  }


  mrb_value initialize(mrb_state* mrb, mrb_value data_object)
  {
    printf("initialize %p\n", (void *)mrb_ptr(data_object));

    char* str_ptr = (char*)mrb_data_get_ptr(mrb, data_object, &_internal_data_type);
    printf("made it here\n");
    return data_object;
  }

  
  void setup(mrb_state* mrb)
  {
    printf("setup\n");
    class_mrb = mrb_define_class(mrb, "DataObject", mrb->object_class);
    MRB_SET_INSTANCE_TT(class_mrb, MRB_TT_DATA);
    mrb_define_method(mrb, class_mrb, "initialize", initialize, MRB_ARGS_NONE());
  }

}
```
When I run the Ruby code
```ruby
DataObject.new
```
I get
```
setup
initialize 0x56192430e880
TypeError: uninitialized DataObject (expected DataObject)
```
The class `DataObject` must exist, otherwise I would not be able to call `::new` on it. Does someone know what is going on here?

**Comment by robfors** [comment]
I figured it out. From [this comment](https://github.com/mruby/mruby/issues/9#issuecomment-147686740) it looks like `DATA_PTR` can be used safely in this case.

**Comment by matz** [comment]
`mrb_data_get_ptr` requires *initialized* data pointer. In `initialize`, the data object is uninitialized thus `DATA_PTR(data_object)` is `NULL`. You can initialize your `data_object` by using macros `Data_Wrap_Struct` or `Data_Make_Struct`.

**Comment by robfors** [comment]
Even better, ill give that a try.
Thanks

**Comment by robfors** [comment]
If my only goal of the `initialize` method was to clear any existing data (all examples show clearing any existing data) such as
```cpp
mrb_value initialize(mrb_state* mrb, mrb_value data_object)
{
  Data_Wrap_Struct(mrb, class_mrb, &_internal_data_type, nullptr);
  return data_object;
}
```
do I even need to have this method explicitly defined or is this the default?
I intend to call `mrb_data_init` then `mrb_data_get_ptr` on the object later in the program.

**Comment by matz** [comment]
You need to deallocate data struct at the beginning of `#initialize`. `mrbgem/mruby-time/src/time.c` should be the best example for writing an extension with data objects.
