### ISSUE TITLE
When passing object that responds to #to_str to String, #to_str is ignored

### ISSUE THREAD

**Issue by robfors** [mruby/mruby#4172]
In _MRB_:
```ruby
c = Class.new { def to_str; 'abc'; end }
String(c.new) #=> 'abc'
```
In _mruby_
```ruby
c = Class.new { def to_str; 'abc'; end }
String(c.new) #=> "#<#<Class:0x555a266155d0>:0x555a266154b0>"
```
This is a new issue with _mruby_ so it likely arose when '#to_str` and other such methods were removed.
Looks like ff08856 broke it.

It would also make sense if `Float()` considered `to_int` but not even _MRB_ does that.

**Comment by matz** [comment]
Those implicit conversion methods are not defined in ISO. In addition, they have caused:
* more memory consumption
* tricky behavior
* and even bugs by recursive VM calls
So we removed from mruby 2.0 for stability and simplicity. It's an incompatible change.

**Comment by robfors** [comment]
Ok, Thanks.
I just figured it was unsafe to define implicit conversion methods on the core types, I can understand how that could cause recursive calls. If it is also unsafe to have core/ext methods accept implicit conversion methods on my own objects, I will just refactor my code.
