### ISSUE TITLE
MRB_DISABLE_STDIO: mruby-compiler requires snprintf

### ISSUE THREAD

**Issue by ebkalderon** [mruby/mruby#4173]
The mruby parser in `parse.y` in the `mruby-compiler` mrbgem implicitly requires `snprintf` and doesn't isn't guarded by the `MRB_DISABLE_STDIO` define ([see line 3063](https://github.com/mruby/mruby/blob/762f682b80460929d9c69b1957bcb2aad108ec93/mrbgems/mruby-compiler/core/parse.y#L3063)). This program compiles, but generates the following warning:

```
warning: /private/tmp/mruby/mruby-latest/mrbgems/mruby-compiler/core/parse.y:3063:23: warning: implicitly declaring library function 'snprintf' with type 'int (char *, unsigned long, const char *, ...)' [-Wimplicit-function-declaration]
warning:                       snprintf(buf, sizeof(buf), "%d", p->lineno);
warning:                       ^
warning: /private/tmp/mruby/mruby-latest/mrbgems/mruby-compiler/core/parse.y:3063:23: note: include the header <stdio.h> or explicitly provide a declaration for 'snprintf'
warning: 1 warning generated.
```

Other uses of `snprintf` etc. in this file are protected by `MRB_DISABLE_STDIO`, but not this one.

**Comment by graf0** [comment]
Same problem here
