### ISSUE TITLE
crash by hash access on mips baremetal

### ISSUE THREAD

**Issue by yamori813** [mruby/mruby#4182]
I use master code on mips baremetal. I have problem that is crash on hash access.

日本語ですみません。

MIPSのbaremetalでmrubyを実行していて、mruby-simplehttpを改造したmrbgemを使っているのですが、これの以下の処理でCPUエクセプションが発生して、落ちてしまいます。

https://github.com/yamori813/mruby-simplehttp/blob/master/mrblib/simplehttp.rb#L124

クロスコンパイルの設定はこのファイルの下の方のrealtekです。

https://github.com/yamori813/rtlbm-mruby/blob/master/build/mruby/build_config.rb

**Comment by matz** [comment]
Can you show us the failing script?
実際に失敗する simplehttp を使ったスクリプトを見せてもらえませんか？

**Comment by yamori813** [comment]
This is script.

https://github.com/yamori813/bcmbm-mruby/blob/master/test/simplehttp.rb

**Comment by yamori813** [comment]
Execution log is this.

Hello Bear Metal mruby on BCM/mipssimple http 1
EXC!**Exception 32: EPC=8002463C, Cause=1080002C (CoProcUnuArithOvflTrapExc  VCE
I     FPUExc   CP2Exc   Exc17    Exc18    Exc19    Exc20    Exc21    Exc22    Wa
tchpt  Exc24    Exc25    Exc26    Exc27    Exc28    Exc29    Exc30    VCED     )
                RA=800256C4, VAddr=00000000

8002463C is here.

8002461c <segment_alloc>:
8002461c:       27bdffe8        addiu   sp,sp,-24
80024620:       afbf0014        sw      ra,20(sp)
80024624:       14a00003        bnez    a1,80024634 <segment_alloc+0x18>
80024628:       afb00010        sw      s0,16(sp)
8002462c:       080091c3        j       8002470c <segment_alloc+0xf0>
80024630:       24100004        li      s0,4
80024634:       94a50000        lhu     a1,0(a1)
80024638:       3c028009        lui     v0,0x8009
8002463c:       44850000        mtc1    a1,$f0
80024640:       00000000        nop
80024644:       468000a1        cvt.d.w $f2,$f0
80024648:       c4404120        lwc1    $f0,16672(v0)

**Comment by take-cheeze** [comment]
Seems like floating point number operation is causing this.
Does replacing
```
    size = seg->size*HT_SEG_INCREASE_RATIO + 1;
```
with
```
    size = seg->size * 6 / 5 + 1;
```
fix the problem?

**Comment by yamori813** [comment]
I try your fix at hash.c. Now work fine my script.  Thanks.
