### ISSUE TITLE
suspect legacy code of removed Hash's khash implementation and a question

### ISSUE THREAD

**Issue by jasl** [mruby/mruby#4186]
In mruby 2.0 release note, it said "Hash implementation replaced from khash",
but in current master branch, [include/mruby/khash.h](https://github.com/mruby/mruby/blob/master/include/mruby/khash.h) still there, and included in [include/mruby/hash.h#L11](https://github.com/mruby/mruby/blob/master/include/mruby/hash.h#L11) but it seems no longer in use (I used keyword `kh_ht` to search the repo), does it mean it can be cleaned?

And I have a question:

I'm trying to to upgrade [Shopify ESS](https://github.com/Shopify/ess) to mruby 2.0  but blocked by the change of Hash.

(Disclamation: I'm not staff of Shopify, just a fanboy, and not know too much in C),

In previous mruby, `kh_ht` relates functions are in `hash.h` so [ESS can use them to fetch keys and values and the size of whole Hash object](https://github.com/Shopify/ess/blob/master/ext/enterprise_script_service/data.cpp#L152-L173), but in new implementation, the Hash's low-level APIs are hidden in `hash.c`, is there any equivalent way to do the job in mruby 2.0?

**Comment by jasl** [comment]
And mruby 2.0 don't have an API to get the Hash's size currently

**Comment by jasl** [comment]
Looks `mrb_hash_foreach` and #4188 can solve my problem

**Comment by matz** [comment]
Just merged #4188. Hash size can be obtained by `mrb_hash_size()` now.
