### ISSUE TITLE
About corrected patches for mruby core initialization

### ISSUE THREAD

**Issue by dearblue** [mruby/mruby#4239]
If out of memory occurs with `mrb_open()`, the process will be crashed by `SIGABRT` or `SIGSEGV`.

This behavior is undesirable for me as I try to generate multiple `mrb_state`.

[This patch set](https://github.com/mruby/mruby/compare/mruby:b83e4df...dearblue:6797ebf) corrects problems that occurred by simulating out of memory.
(branch is in [fix-mrb_open-with-nomem](https://github.com/dearblue/mruby/tree/fix-mrb_open-with-nomem))

However, it is divided into 18 steps commit, and some can be made independent.

Should it be better to divide the pull requests for each, or may they be a single pull request at once?

Thanks.

## Potential issue

If `mrb_XXX_gem_final()` is called while initialization processing is not completed, problems may arise there.

**Comment by matz** [comment]
No, you don't have to split the PR. But longer (or bigger) PR might take time to review.

**Comment by dearblue** [comment]
Ok. Thank you.
We will `git rebase` in this form and make a pull request.
