### ISSUE TITLE
How printf from C     Array Object?

### ISSUE THREAD

**Issue by letarg0** [mruby/mruby#4289]
- How get information the global or normal variable exist
- How get everything value from Array
- How get size

i get error: **gcc -Wall -pedantic -O0 -I ~/mruby/include/ y.c ~/mruby/build/host/lib/libmruby.a -o y -lm**
```
a.c:20:6: warning: implicit declaration of function 'mrb_gv_defined' is invalid in C99
      [-Wimplicit-function-declaration]
 b = mrb_gv_defined(mrb, mrb_intern_lit(mrb, "$aa"));
     ^
a.c:26:14: warning: implicit declaration of function 'RARRAY_LEN' is invalid in C99 [-Wimplicit-function-declaration]
 mrb_int m = RARRAY_LEN(a);
             ^
a.c:32:8: warning: implicit declaration of function 'RARRAY_PTR' is invalid in C99 [-Wimplicit-function-declaration]
   e = RARRAY_PTR(a);
       ^
a.c:32:6: error: assigning to 'mrb_value' (aka 'struct mrb_value') from incompatible type 'int'
   e = RARRAY_PTR(a);
     ^ ~~~~~~~~~~~~~
3 warnings and 1 error generated.
make: *** [a] Error 1

```
and this is source.

```
#include <stdlib.h>
#include <stdio.h>

#include <mruby.h>
#include <mruby/class.h>
#include <mruby/variable.h>

MRB_API mrb_value mrb_load_string(mrb_state *mrb, const char *s);

int main(void)
{
 mrb_value a,e;
 mrb_bool  b;
 int i;

 mrb_state *mrb = mrb_open();
  if (!mrb) { printf("Problemy z inicjowanie programu"); return 1; }

 mrb_load_string(mrb, "$aa=Array.new(3,'a')" );
 b = mrb_gv_defined(mrb, mrb_intern_lit(mrb, "$aa"));
 printf(" czy istnieje $aa? %d\n", b);

 a = mrb_gv_get(mrb, mrb_intern_lit(mrb, "$sc"));
 mrb_p(mrb, a);

 mrb_int m = RARRAY_LEN(a);
 printf(" $aa.size= %lld\n",m);
 if (m != 0)
  {
  for (i=0; i<m; i++)
   {
   e = RARRAY_PTR(a);
   mrb_p(mrb,e);
   }
  }

 mrb_close(mrb);

return 0;
}
```

**Comment by matz** [comment]
* you have to include `mruby/array.h` to access array internals.
* we don't have `mrb_gv_defined` since global variables always exist on access.
* you need to fix some errors in your code (debugged version follows):
``` c
#include <stdlib.h>
#include <stdio.h>

#include <mruby.h>
#include <mruby/class.h>
#include <mruby/variable.h>
#include <mruby/array.h>

MRB_API mrb_value mrb_load_string(mrb_state *mrb, const char *s);

int main(void)
{
  mrb_value a, *e;
  mrb_bool  b;
  int i;

  mrb_state *mrb = mrb_open();
  if (!mrb) { printf("Problemy z inicjowanie programu"); return 1; }

  mrb_load_string(mrb, "$aa=Array.new(3,'a')" );
 a = mrb_gv_get(mrb, mrb_intern_lit(mrb, "$aa"));
  mrb_p(mrb, a);

  mrb_int m = RARRAY_LEN(a);
  printf(" $aa.size= %ld\n",m);
  if (m != 0) {
    for (i=0; i<m; i++) {
      e = RARRAY_PTR(a);
      mrb_p(mrb, e[i]);
    }
  }

  mrb_close(mrb);
  return 0;
}
```
The output from the code was:
```
["a", "a", "a"]
 $aa.size= 3
"a"
"a"
"a"
```

**Comment by letarg0** [comment]
Many thanks, You are great!

I have 2 small questions:
- Is possible to check the $aa exist or not? I dont know user create it.
- How check type ? Similar **$aa.class.to_s**

Is possible get normal 'aa' variable? When i mrb_iv_get() from self or kernel i get error.

**Comment by matz** [comment]
* Don't check the existence of global variables. Just call `mrb_gv_get()` and check if its value is `nil` by `mrb_nil_p()`.
* Use type check predicates, e.g. `mrb_array_p()`, `mrb_string_p()` , `mrb_nil_p()`, etc.
* `mrb_load_string()` returns the value from the last expression.

**Comment by letarg0** [comment]
**! mrb_string_p()** are eqvivalent
```
 if (mrb_type(n) != MRB_TT_STRING) {
     puts("this is not a String");
   }
```

everything else i undestand. Many thanks

**Comment by mikolaj24** [comment]
>     for (i=0; i<m; i++) {
>       e = RARRAY_PTR(a);

The code not compiling

`gcc -Wall -O0 -std=c11 -pedantic -pedantic-errors -I ~/mruby/include/ a.c ~/mruby/build/host/lib/libmruby.a -o a -lm`

a.c: In function ‘main’:
a.c:32:9: error: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
       e = RARRAY_PTR(a);
         ^
make: *** [Makefile:9: a] Błąd 1
