### ISSUE TITLE
Environment variable CC is ignored

### ISSUE THREAD

**Issue by interkosmos** [mruby/mruby#4292]
Forcing a specific C compiler by setting the environment variable `CC` does not work as intended, as the following error occurs at compilation stage:

    $ make CC=gcc8
    [...]
    CC    build/host/mrblib/mrblib.c -> build/host/mrblib/mrblib.o
    AR    build/test/mrbgems/mruby-test/mrbtest.a 
    ar: warning: creating /tmp/mruby/build/test/mrbgems/mruby-test/mrbtest.a
    AR    build/test/lib/libmruby.a 
    ar: warning: creating /tmp/mruby/build/test/lib/libmruby.a
    AR    build/host-debug/lib/libmruby.a 
    ar: warning: creating /tmp/mruby/build/host-debug/lib/libmruby.a
    AR    build/host/lib/libmruby.a 
    ar: warning: creating /tmp/mruby/build/host/lib/libmruby.a
    LD    build/test/bin/mruby-strip 
    sh: gcc: not found
    rake aborted!
    Command Failed: ["gcc"  -o "/tmp/mruby/build/test/bin/mruby-strip" "/tmp/mruby/build/test/mrbgems/mruby-bin-strip/tools/mruby-strip/mruby-strip.o" "/tmp/mruby/build/test/lib/libmruby.a"  -lm -lreadline -lncurses ]

As a workaround, occurances of `gcc` in `tasks/toolchains/gcc.rake` have to be changed to the desired compiler executable, for instance `gcc8`.

**Comment by shuujii** [comment]
How about as follows?

~~~
$ make CC=gcc8 LD=gcc8
~~~

Another idea is the following change:

~~~diff
diff --git a/tasks/toolchains/gcc.rake b/tasks/toolchains/gcc.rake
index 4929811c..f304b2a0 100644
--- a/tasks/toolchains/gcc.rake
+++ b/tasks/toolchains/gcc.rake
@@ -22,7 +22,7 @@ MRuby::Toolchain.new(:gcc) do |conf, _params|
   end

   conf.linker do |linker|
-    linker.command = ENV['LD'] || 'gcc'
+    linker.command = ENV['LD'] || ENV['CC'] || 'gcc'
     linker.flags = [ENV['LDFLAGS'] || %w()]
     linker.libraries = %w(m)
     linker.library_paths = []
~~~

**Comment by interkosmos** [comment]
Setting the linker as you describe does the job. Thank you.
