### ISSUE TITLE
Inline packed symbol breaks symbol name immutability

### ISSUE THREAD

**Issue by shuujii** [mruby/mruby#4342]
Symbol name of inline packed symbol share `mrb_state::symbuf`. Therefore codes like `mrb_sym2name_len()` + `mrb_str_new_static()` are broken (e.g. `mrb_sym_to_s()`).

#### Example:

```ruby
a = :a.to_s
b = :b.to_s
p a  #=> "b"
p b  #=> "b"
```

**Comment by shuujii** [comment]
Another example:

```shell
$ bin/mruby -e 'p :a<=>:b'  #=> 0
```

Sharing buffers may be prone to such a problem. At least, it's better to specify return value of `mrb_sym2name_len()` expire when next `mrb_sym2name_len()` is called in comment, I think.

**Comment by matz** [comment]
Thank you for the report!

**Comment by shuujii** [comment]
The following example does not work too:

```
$ echo '$a = __FILE__' > a
$ bin/mruby -ra -e 'p $a'  #=> "-e"
```

**Comment by shuujii** [comment]
Sorry, this example seems other cause.
