### ISSUE TITLE
`Mrbtest::FLOAT_TOLERANCE` differs from `Math::TOLERANCE`

### ISSUE THREAD

**Issue by shuujii** [mruby/mruby#4345]
`Mrbtest::FLOAT_TOLERANCE`(`1e-6` in `mrbgems/mruby-test/driver.c`) differs from `Math::TOLERANCE`(`1e-5` in `mrbgems/mruby-math/src/math.c`) when `MRB_USE_FLOAT` is enabled.

Is this intentional?

**Comment by matz** [comment]
It should be consistent. I fixed them by the above commits, I think.
