### ISSUE TITLE
compile error 2.0.1 relase file by gcc 4.2 mips

### ISSUE THREAD

**Issue by yamori813** [mruby/mruby#4365]
I build 2.0.1 release file. I have compile error on FreeBSD/mips gcc 4.2 cross compile.

CC    src/numeric.c -> build/zrouter/src/numeric.o
/usr/home/hiroki/zobj/usr/home/hiroki/ZRouter/ports/usr/home/hiroki/ZRouter/port
s/lang/mruby/mruby-2.0.1/src/numeric.c: In function 'flo_to_s':
/usr/home/hiroki/zobj/usr/home/hiroki/ZRouter/ports/usr/home/hiroki/ZRouter/port
s/lang/mruby/mruby-2.0.1/src/numeric.c:215: error: 'for' loop initial declaratio
n used outside C99 mode
rake aborted!

**Comment by shuujii** [comment]
Do you specify `-std=gnu99` compiler option?

**Comment by dearblue** [comment]
It seems that `src/variable.c` will also need to be modified.

```
% gcc8 -std=gnu89 -I include -c src/*.c
src/variable.c: In function 'mrb_ident_p':
src/variable.c:1119:3: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
   for (mrb_int i = 0; i < len; i++) {
   ^~~
```

**Comment by shuujii** [comment]
Are there compilers that don't support 'for' loop initial declarations in C99 mode?

**Comment by matz** [comment]
I've heard old VC and some compilers for embedded systems do not support the new style declaration. That's the reason we still use the old style in mruby source. I am not sure this is the case yet.
