### ISSUE TITLE
mismatched shift functions

### ISSUE THREAD

**Issue by akasong** [mruby/mruby#4380]
In src/numeric.c, left and right shift functions name were mismatched.
There are no problem with functions, but the name seems to be wrong.

```
1611:  mrb_define_method(mrb, fl,      ">>",        flo_lshift,     MRB_ARGS_REQ(1));
1612:  mrb_define_method(mrb, fl,      "<<",        flo_rshift,     MRB_ARGS_REQ(1));
```

**Comment by matz** [comment]
Thank you for the report. Since the fix is so easy, next time you can send us pull-request and put your name to the commit log.
