### ISSUE TITLE
Compilation error with "MRB_ARY_EMBED_LEN_MAX" in "array.h"

### ISSUE THREAD

**Issue by jr4qpv** [mruby/mruby#4382]
Hello!
I'm sorry I'm not good at English.

I built it on an ARM CPU (32 bit) device using IAR's EWARM compiler.
Then the following error occurs.

`` `
array.c
Error [Pe070]: incomplete type is not allowed C: \ work \ tk-optsys \ appl \ mruby_porting \ mruby \ include \ mruby \ array.h 37
Error while running C / C ++ compiler
`` `
The following #define line seems to be the problem.
> #define MRB_ARY_EMBED_LEN_MAX ((mrb_int) (sizeof (void *) * 3 / sizeof (mrb_value)))
> mrb_value embed [MRB_ARY_EMBED_LEN_MAX];

As it is 32bit CPU,
sizeof (void *) * 3 ==> 12
sizeof (mrb_value) ==> 16
So 12/16 ==> 0 and it seems to be an error.

For now, if you write this #define in a constant, compilation is OK.
What value do you expect for "MRB_ARY_EMBED_LEN_MAX" here?
How many values ​​should I set?

Thank you.

**Comment by shuujii** [comment]
In this environment, it is correct that `MRB_ARY_EMBED_LEN_MAX` is
zero. However zero size array is not C standard.

For now, can you compile via the following patch?

```diff
diff --git a/include/mruby/array.h b/include/mruby/array.h
index 2e6951c0..563d2da7 100644
--- a/include/mruby/array.h
+++ b/include/mruby/array.h
@@ -33,7 +33,6 @@ struct RArray {
       } aux;
       mrb_value *ptr;
     } heap;
-    mrb_value embed[MRB_ARY_EMBED_LEN_MAX];
   } as;
 };
 
@@ -46,7 +45,7 @@ struct RArray {
 #define ARY_UNSET_EMBED_FLAG(a) ((a)->flags &= ~(MRB_ARY_EMBED_MASK))
 #define ARY_EMBED_LEN(a) ((mrb_int)(((a)->flags & MRB_ARY_EMBED_MASK) - 1))
 #define ARY_SET_EMBED_LEN(a,len) ((a)->flags = ((a)->flags&~MRB_ARY_EMBED_MASK) | ((uint32_t)(len) + 1))
-#define ARY_EMBED_PTR(a) (&((a)->as.embed[0]))
+#define ARY_EMBED_PTR(a) ((mrb_value*)(&(a)->as))
 
 #define ARY_LEN(a) (ARY_EMBED_P(a)?ARY_EMBED_LEN(a):(a)->as.heap.len)
 #define ARY_PTR(a) (ARY_EMBED_P(a)?ARY_EMBED_PTR(a):(a)->as.heap.ptr)
```

**Comment by jr4qpv** [comment]
Hello!
It is OK with the application of the patch you contacted.
The VM on the actual machine also worked.

Thank you very much.

**Comment by matz** [comment]
Probably I made this issue resurrected by 4c00167. Sorry.

**Comment by matz** [comment]
By the way, I recommend using `MRB_WORD_BOXING` instead of `MRB_NO_BOXING` (default), especially on 32bit architectures.

**Comment by jr4qpv** [comment]
Thank you for your report. I haven't tried it on a newer version yet, but if you have anything else please let me know.

**Comment by matz** [comment]
I addressed this issue in the `mruby3` branch.
- Array embedding is disabled on 32bit platforms with `MRB_NO_BOXING`
- The default `mrb_value` representation is changed to `MRB_WORD_BOXING`

**Comment by shuujii** [comment]
> I addressed this issue in the `mruby3` branch.
> 
> * Array embedding is disabled on 32bit platforms with `MRB_NO_BOXING`

Even with `MRB_32BIT` and `MRB_NO_BOXING`, if `sizeof(mrb_value) == 12`, one element can be embedded, but it seems that it is no longer embedded by this change. Is this change intentional?

**Comment by matz** [comment]
It's too hard to detect `sizeof(mrb_value) < sizeof(void*)*3` in C preprocessor. So I will allow the case `MRB_32BIT` and `MRB_NO_BOXING` and `MRB_USE_FLOAT32`.
