### ISSUE TITLE
How to call `mrb_load_string` recursively

### ISSUE THREAD

**Issue by keroro520** [mruby/mruby#4384]
I wanna implement a function like `eval`, which accepts and executes ruby codes. So I write a simple mrbgem:

```
static mrb_value
mrb_simple_eval(mrb_state *mrb, mrb_value self)
{
    char code[] = "i = 1 + 2";
    mrb_load_string(mrb, code);
    return self;
}
```

But `segmentation fault` will be reported when call `mrb_simple_eval`. I cannot figure out the reason. And could anyone tell me what the better ways to implement `eval` idea ? Thanks ~

**Comment by matz** [comment]
You've found a bug! Thank you!
