### ISSUE TITLE
Unexpected error: `Can't get cfunc env from non-cfunc proc.`

### ISSUE THREAD

**Issue by take-cheeze** [mruby/mruby#4389]
Seems this causes unexpected error: https://github.com/mruby/mruby/commit/79fd986bcb2c6bc056a08669664c0024d77725f9
Found in mruby-marshal:
- https://ci.mruby.org/jenkins/job/master-mruby-marshal/lastFailedBuild/console
- https://github.com/take-cheeze/mruby-marshal/blob/bfc9d0cd49275132fd89f8c8a65345b861d28f10/src/marshal.cpp#L261

Reproduced in `mrb_funcall` inside C function.

**Comment by matz** [comment]
I think e9f302 fixed the issue. If not, please reopen it.
