### ISSUE TITLE
segmentation fault for String#to_i

### ISSUE THREAD

**Issue by u2** [mruby/mruby#4394]
```
➜  mruby git:(023070a) ✗ bin/mirb
mirb - Embeddable Interactive Ruby Shell

> "0a".to_i(16)
 => 10
> "0c".to_i(16)
 => 12
> "0e".to_i(16)
 => 14
> "0f".to_i(16)
 => 15
> "0b".to_i(16)
[1]    17209 segmentation fault  bin/mirb
➜  mruby git:(023070a) ✗ bin/mruby -version
mruby 1.4.1 (2018-4-27) 
```

**Comment by 16Bitt** [comment]
What platform are you running on? I built 1.4.1 on OSX Mojave and tested this in mirb, and I could not reproduce

**Comment by u2** [comment]
I use ubuntu16.04, install ruby by rvm. Because of running the `minirake` needs cruby, so I use ruby 2.5.1 as default. 

If I run mrib or mruby, it will occur `segmentation fault`, but the `make test` will pass. If I use mruby as default, mirb/mruby works well. I think it's the problem of environment infection. But we only can use cruby run minirake.

**Comment by 16Bitt** [comment]
I switched my local ruby version to 2.5.1 (mruby can't run minirake as far as I can tell), and I'm still seeing a successful build without a segfault in `mirb`. When you say that you set mruby as default, are you referring to the global rvm ruby?

```
➜  mruby git:(023070a6) ✗ bin/mirb 
mirb - Embeddable Interactive Ruby Shell

> '0b'.to_i(16)
 => 11
> 
```

**Comment by u2** [comment]
> I switched my local ruby version to 2.5.1 (mruby can't run minirake as far as I can tell), and I'm still seeing a successful build without a segfault in `mirb`. When you say that you set mruby as default, are you referring to the global rvm ruby?
> 
> ```
> ➜  mruby git:(023070a6) ✗ bin/mirb 
> mirb - Embeddable Interactive Ruby Shell
> 
> > '0b'.to_i(16)
>  => 11
> > 
> ```
When I set ruby as default, it would occur. It's strange.

**Comment by matz** [comment]
Strange. It didn't happen on my Linux box (Ubuntu 18.10).

**Comment by chasonr** [comment]
Are you using any third party gems? I can reproduce the bug, but it occurs in mruby-bignum (and not in mruby-gmp-bignum).

This appears to be my bug, not Matz's.

**Comment by chasonr** [comment]
I've locally committed a fix to mruby-bignum, but Github went catatonic when I tried to push. I'll be back when that finally goes through.

**Comment by chasonr** [comment]
The fix is pushed. Can you do git pull on mruby-bignum and try again?

**Comment by u2** [comment]
thanks.
