### ISSUE TITLE
String iteration broken for unicode symbols?

### ISSUE THREAD

**Issue by tohya-ryu** [mruby/mruby#4404]
Iterating a string string with symbols that aren't part of the ascii standard returns garbage for these glyphs.
`
test = "t0thgsdkg7524309あいうえお"
test.each_char do |c|
  puts c # japanese characters are now garbage
end
`

**Comment by shuujii** [comment]
Probably same as #3725.

**Comment by tohya-ryu** [comment]
> Probably same as #3725.
Yes that solved my problem, thanks!
