### ISSUE TITLE
How to pass string to C?

### ISSUE THREAD

**Issue by tohya-ryu** [mruby/mruby#4421]
Can't figure out what I'm doing wrong here. Trying to properly get a string passed to a function in ruby to c.

```
mrb_define_method(mrb, mrb->object_class, "load", load, MRB_ARGS_NONE());

mrb_value load(mrb_state *mrb, mrb_value_self)
{
  char string[5] = { 0 };
  mrb_int c = 0;
  mrb_get_args(mrb, "s", string, &c);
  printf("string: %s\n", string);
  // in ruby
  load "test"
}
```

This prints garbage glyphs. Inspecting the char array yields different numbers everytime the program is run. Disabled  MRB_UTF8_STRING because I thought it might a unicode thing I'm not considering, but the result is the same.

**Comment by shuujii** [comment]
#### Points:

- Use `z` for NUL terminated string.
- Pass address of `char*` variable.
- Use `MRB_ARGS_REQ(1)` for requiring one argument.

#### Example:

```c
static mrb_value load(mrb_state *mrb, mrb_value self)
{
  char *string;
  mrb_get_args(mrb, "z", &string);
  printf("string: %s\n", string);
  return self;
}
```
```c
mrb_define_method(mrb, mrb->object_class, "load", load, MRB_ARGS_REQ(1));
```
```sh
$ bin/mruby -e 'load "test"'  #=> string: test
```

**Comment by tohya-ryu** [comment]
Replacing MRB_ARGS_NONE is the one thing I forgot to try out. Works. Thank you!

**Comment by matz** [comment]
The issue is caused by passing a string pointer (`char*`) instead of a pointer to the string variable (`char**`).
