### ISSUE TITLE
output of "int div int" should be int, not float

### ISSUE THREAD

**Issue by IK-O** [mruby/mruby#4464]
In CRuby, 

p (1 / 2 )

its output is 0 (int)

In current MRuby

p (1 / 2)

its output is 0.5 (float)

I think mruby should output integer value if the args are inteter value.; otherwise MRuby cannot run rb code which is written for CRuby.

**Comment by matz** [comment]
I am sorry it is by design. I am trying to make CRuby behave like this in the long run.
