### ISSUE TITLE
Enumerable#detect has different behavior than CRuby's counterpart

### ISSUE THREAD

**Issue by okuramasafumi** [mruby/mruby#4484]
https://github.com/mruby/mruby/blob/master/mrblib/enum.rb#L75
It looks like `Enumerable#detect` return `ifnone` itself when nothing is detected.
However, CRuby's counterpart `call`s `ifnone` in the same situation.
https://docs.ruby-lang.org/en/trunk/Enumerable.html#method-i-detect

Is it intended or a bug?

**Comment by matz** [comment]
JIS/ISO definition of `Enumerable#detect` returns `ifnone` without calling it.
Let me investigate a little bit (could be an error in ISO).

**Comment by matz** [comment]
It has been this behavior since pre 1.8, so it must be an ISO error.  Will be fixed.
