### ISSUE TITLE
How to protect mruby object in C++ from GC?

### ISSUE THREAD

**Issue by IK-O** [mruby/mruby#4515]
This is too complex to me to write in English, so let me write in Japanese.

C++でmrubyの拡張機能を作っています。
C++内でmrubyのオブジェクトを作成し、それをC++内で暫く保持したいのですが、
ruby側でGC.startを行うとC++内で保持しているmrubyオブジェクトまでGCに回収されてしまいます。

C++側は以下のようになっており、C++のクラスとMRubyのクラスが1対1で対応しています。

    class A
    {
        mrb_value mrb_object;
    };

    class B
    {
        A* a;
        mrb_value mrb_object;
    };

BクラスのaはBクラスのコンストラクタでmrb_mallocとData_Wrap_Structを使用してC++内で作られます。

これをRuby側で
```
    b = B.new
    p b.a            # OK
    GC.start
    p b.a            # Crash
```

とすると、GC.startでb.aが回収されてしまい、アクセス違反になってしまいます。
GCに回収されないようにmrb_gc_mark_valueとmrb_gc_protectをb.aのmrb_objectに掛けてみましたが、それでも回収されてしまいます。

これをGCに回収されないようにするにはどうすれば良いのでしょうか？

**Comment by IK-O** [comment]
一応完全なソースコードを掲載します。
C++

    #include <new>
    #include <mruby.h>
    #include <mruby/class.h>
    #include <mruby/data.h>
    #include <mruby/dump.h>

    class A
    {
    public:
        mrb_value mrb_object;
    };

    class B
    {
    public:
        A* a;
        mrb_value mrb_object;
    };

    RClass *aKlass, *bKlass;

    void AFree(mrb_state *mrb, void* ptr);
    void BFree(mrb_state *mrb, void* ptr);

    struct mrb_data_type AType = { "A", AFree };
    struct mrb_data_type BType = { "B", BFree };

    mrb_value AInitialize(mrb_state *mrb, mrb_value self)
    {
        A* p = (A*)mrb_malloc(mrb, sizeof(A));

        DATA_TYPE(self) = &AType;
        DATA_PTR(self) = p;

        new(p) A();
        p->mrb_object = self;

        return self;
    }

    void AFree(mrb_state *mrb, void* ptr)
    {
        ((A*)ptr)->~A();

        mrb_free(mrb, ptr);
    }


    mrb_value BInitialize(mrb_state *mrb, mrb_value self)
    {
        B* p = (B*)mrb_malloc(mrb, sizeof(B));

        DATA_TYPE(self) = &BType;
        DATA_PTR(self) = p;

        new(p) B();
        p->mrb_object = self;

        A* a = (A*)mrb_malloc(mrb, sizeof(A));
        new(a) A();
        mrb_value v = mrb_obj_value(Data_Wrap_Struct(mrb, aKlass, &AType, a));
        mrb_gc_mark_value(mrb, v);
        mrb_gc_protect(mrb, v);
        a->mrb_object = v;

        p->a = a;

        return self;
    }

    void BFree(mrb_state *mrb, void* ptr)
    {
        ((B*)ptr)->~B();

        mrb_free(mrb, ptr);
    }

    mrb_value BGetA(mrb_state *mrb, mrb_value self)
    {
        B* b = (B*)DATA_PTR(self);
        return b->a->mrb_object;
    }

    void Install(mrb_state* mrb)
    {
        aKlass = mrb_define_class(mrb, "A", mrb->object_class);
        mrb_define_method(mrb, aKlass, "initialize", AInitialize, MRB_ARGS_NONE());

        bKlass = mrb_define_class(mrb, "B", mrb->object_class);
        mrb_define_method(mrb, bKlass, "initialize", BInitialize, MRB_ARGS_NONE());
        mrb_define_method(mrb, bKlass, "a", BGetA, MRB_ARGS_NONE());
    }


    int main()
    {
        mrb_state* mrb = mrb_open();
        Install(mrb);

        FILE* rubyFile = fopen("test.rb", "r");

        mrb_load_file(mrb, rubyFile);

        fclose(rubyFile);

        mrb_close(mrb);
    }

Ruby

    b = B.new
    p b.a            # OK
    GC.start
    p b.a            # Crash

**Comment by dearblue** [comment]
`mrb_iv_set()` 関数を使って、オブジェクト `b` がオブジェクト `a` に対する参照があることを明示しましょう。  
参考: [mrb_data_type with mark function #2605](https://github.com/mruby/mruby/issues/2605#issuecomment-58277520)

mruby は GC のマークフェイズにおける利用者がオブジェクトをマークするための仕組みを (意図的に) 用意していません。  
そのため、インスタンス変数を用いてオブジェクト間に参照があることを示す必要があります。

この時にインスタンス変数名として `@` から始める必要はありません。  
例えば小文字や `@` 以外の記号などで名前を始めると mruby 空間から見えなくなるので、利用者定義の構造体にオブジェクトを置きたい場合は打って付けです。  
逆に mruby 空間から見えなければならない時は、`@` から始まる正しいインスタンス変数名を使って下さい (この場合は構造体にオブジェクトを置くのはやめましょう)。

掲載されたソースコードを修正し、オブジェクト `b` の隠しインスタンス変数としてオブジェクト `a` が設定される場合を次に例示します:

```diff
--- sample.cc~
+++ sample.cc
@@ -59,8 +59,8 @@ mrb_value BInitialize(mrb_state *mrb, mrb_value self)
     A* a = (A*)mrb_malloc(mrb, sizeof(A));
     new(a) A();
     mrb_value v = mrb_obj_value(Data_Wrap_Struct(mrb, aKlass, &AType, a));
-    mrb_gc_mark_value(mrb, v);
-    mrb_gc_protect(mrb, v);
+    mrb_sym ivar_name = mrb_intern_lit(mrb, "private-honyarara");
+    mrb_iv_set(mrb, self, ivar_name, v);
     a->mrb_object = v;

     p->a = a;
```

これで GC が発生しても、オブジェクト `b` が生きている限りオブジェクト `a` も生き残ることが出来ます。

----

`mrb_gc_mark_value()` は mruby の内部関数で、GC のマークフェイズで使われます。  
利用者が使っても意味のあるものではありません (バグの原因になるかもしれません)。

`mrb_gc_protect()` 関数は、`mrb_gc_arena_restore()` の後で使うことが想定されています。

どちらの関数を使っても、期待する結果を得ることは出来ません。

**Comment by IK-O** [comment]
回答ありがとうございます。
MRubyではC側にRubyオブジェクトを直接持たせてはいけないようですね。

代わりに
mrb_internとmrb_iv_set/mrb_iv_getを使ってその都度参照、書き込みを行うと。

Matz氏の投稿も見つけました
https://twitter.com/yukihiro_matz/status/194679863473471489

ようやくGCに回収されなくなりました。

**Comment by matz** [comment]
You can also use `mrb_gc_register()` and `mrb_gc_unregister()` to protect objects permanently. When an object is referenced from C/C++, you can call `mrb_gc_register()` and when the reference is terminated, you can call `mrb_unregister()`.
