### ISSUE TITLE
float object recognition is defference to CRuby

### ISSUE THREAD

**Issue by IK-O** [mruby/mruby#4547]
In CRuby
```
    a = 1.0
    b = 1.0
    p a.equal?(b)  # false
```

In MRuby
```
    a = 1.0
    b = 1.0
    p a.equal?(b)  # true
```

Mruby recognize defferenct float variables as same object if the value is same.

I think this deference is design of MRuby.
However, I want Mruby to perform same as CRuby in this case.

How can I do it?
Do I have to fix vm.c or other souces by myself?
If so, which part of source code should I fix?

**Comment by dearblue** [comment]
CRuby's results could not be reproduced on FreeBSD 12.0 amd64.
I checked with ruby-2.4.6, ruby-2.5.5 and ruby-2.6.3, but all return `true`.

```irb
irb(main):001:0> a = 1.0
=> 1.0
irb(main):002:0> b = 1.0
=> 1.0
irb(main):003:0> a.equal?(b)
=> true
```

**Comment by IK-O** [comment]
I checked CRuby's result in some environments.

Win7 x64: ruby 2.5.3p105[i386-mingw32]: => false
ubuntu18.04 x64: ruby 2.5.3p105: => true
macOS 10.14.5: ruby 2.4.0p0: => true

Maybe this is not issue of MRuby but CRuby on Windows.
