### ISSUE TITLE
String#unpack does not support 'm0' template

### ISSUE THREAD

**Issue by lopopolo** [mruby/mruby#4556]
From what I can gather, `mruby-pack` is not part of the ISO standard, so I hope CRuby compliance is a goal of this mrbgem. Per the CRuby docs for [String#unpack](https://ruby-doc.org/core-2.6.3/String.html#method-i-unpack):

```
m            | String  | base64 encoded string (RFC 2045) (default)
             |         | base64 encoded string (RFC 4648) if followed by 0
```

Parsing each component of the template string is done in a `while (count != 0)` loop, but for the `m` template, count determines encoding version.

https://github.com/mruby/mruby/blob/519f3963654d01ddc0c810cda1c5be365bc21f87/mrbgems/mruby-pack/src/pack.c#L1256-L1300

CRuby:

```
[2.6.3] > "MQ==".unpack1('m0')
=> "1"
```

mruby:

```
>>> "MQ==".unpack1('m0')
=> nil
```

**Comment by lopopolo** [comment]
I think this means that this line of code accesses uninitialized memory

https://github.com/mruby/mruby/blob/519f3963654d01ddc0c810cda1c5be365bc21f87/mrbgems/mruby-pack/src/pack.c#L1302

**Comment by matz** [comment]
#4557 merged
