### ISSUE TITLE
Document that mrb_raise message arg must be a static string

### ISSUE THREAD

**Issue by lopopolo** [mruby/mruby#4558]
This is makes sense to me now that I understand what is going on:

- `mrb_raise` unwinds the stack with `longjmp`
- there is no opportunity to free a heap-allocated string

The chatter in some issues to reuse specialized raise call sites while worrying about binary size makes much more sense in this context. Every call to raise results in more rodata embedded in an executable.

In the absence of this understanding, I had a fairly massive leak in the program I'm working on. Embedding mruby in a non-C context means this is something extra important to keep in one's head before calling `mrb_raise`.

This is a sharp edge that should probably be documented.

**Comment by take-cheeze** [comment]
- In C++ the unwinder shoulder run the C++ destructor so no need to worry if you are using things like `std::string` (I don't know about rust)
- Pre-allocated string doesn't have problem since they should be alive until VM exits or some lifetime
- Wrap with `RString` before raising the exception

**Comment by take-cheeze** [comment]
As long as you are touching C API you are responsible for managing the memory you allocated until you wrap it as mruby object so I don't think it's a thing to document.
Though there is many code out there with bad memory management so please run with [leak sanitizer](https://clang.llvm.org/docs/LeakSanitizer.html) to check your memory leakage.

**Comment by lopopolo** [comment]
@take-cheeze thanks for your guidance. The hint about the C++ unwinder is useful. I think I need to reimplement the mruby-error mrbgem in Rust using Rust's panic unwinder, which will guarantee that stack frames get cleaned up.

Thanks! I was holding it wrong. I'll close out this issue.
