### ISSUE TITLE
Segmentation fault in `mrb_hash_get` with gcc but not with clang

### ISSUE THREAD

**Issue by katzer** [mruby/mruby#4596]
Hi, I encountered a segfault when running my tests with gcc while with clang everything works fine.

I've a method that is defined like this:

```c
mrb_define_method(mrb, cls, "gets", mrb_ssh_f_gets, MRB_ARGS_OPT(2));
```

And the relevant impl:

```c
static mrb_value
mrb_ssh_f_gets (mrb_state *mrb, mrb_value self)
{
    mrb_bool arg_given = FALSE;
    mrb_value arg, opts;

    mrb_get_args(mrb, "|o?H!", &arg, &arg_given, &opts);

    // Clang says, that opts is NULL and does not point to a hash struct
    // GCC thinks, its a hash even `mrb_get_args` returns 1 and not 2
    if (mrb_hash_p(opts)) {
        // GCC fails here with a segfault (opts is not null)
        mrb_hash_get(mrb, opts, KEY_CHOMP);
    }
```

Now if I invoke that method there will be a segfault with GCC:

```ruby
io.get(chomp: true)
```

I fixed that in my code with a tiny different approach. But I think it's a bug in mruby's `mrb_get_args`:

```c
mrb_get_args(mrb, "|o?H!?", &arg, &arg_given, &opts, &opts_given);

if (opts_given && mrb_hash_p(opts)) {
    // ...
}
```

I tested it with GCC 4 up to 8 and also with mruby-head and 2.0.1. It's always the same.

**Comment by dearblue** [comment]
The arguments obtained by `mrb_get_args()` are assigned to variables in order.
If you put the `?` Specifier, it will not be skipped.

Also, if an optional argument is not given, no value is assigned to the corresponding variable.

For your code, the hash object given by `io.get(chomp: true)` is assigned to the `arg` variable.
The `opt` variable is undeclared, so it is uninitialized (therefore occurs segmentation fault).

----

When `mrb_get_args()` takes an optional argument, one of the following means should be selected.

  - Use a `?` Specifier on all optional arguments (as your shown)

  - Use a `*` specifier

  - The return value of `mrb_get_args()` returns the number of arguments given to the method, so initialize variables for the arguments not given or separate the subsequent processing

    ```c
    mrb_int argc = mrb_get_args(mrb, "|o?H!", &arg, &arg_given, &opts);
    switch (argc) {
      case 0:
        arg = mrb_nil_value();
        opts = mrb_nil_value();
        break;
      case 1:
        /* arg was initialized by mrb_get_args() */
        opts = mrb_nil_value();
        break;
      case 2:
        /* arg and opts were initialized by mrb_get_args() */
        break;
    }
    ```

  - Initialize the variables for optional arguments before calling `mrb_get_args()`

    ```c
    arg = mrb_nil_value();
    opts = mrb_nil_value();
    mrb_get_args(mrb, "|o?H!", &arg, &arg_given, &opts);
    ```

    However, in this case, it is impossible to distinguish `io.get(any_object)` and `io.get(any_object, nil)`.
    So if you want to strictly distinguish the arguments given, initializing with `mrb_undef_value()` instead of `mrb_nil_value()`, and check whether an argument is given with `mrb_undef_p()`.

**Comment by matz** [comment]
`mrb_get_args()` does not support keyword arguments yet. So my recommendation is to implement the front-end method (that takes keyword arguments) in Ruby and forward to the C implemented method.

**Comment by katzer** [comment]
@dearblue @matz Thanks for your reply.

> For your code, the hash object given by `io.get(chomp: true)` is assigned to the `arg` variable. The opt variable is undeclared, so it is uninitialized (therefore occurs segmentation fault).

Correct. Thats why I am surprised why `mrb_hash_p(opts)` returns `true` in this case. But only with GCC, with Clang it's `false`.

**Comment by matz** [comment]
The first program does not initialize the local variable `opts`. When the corresponding actual argument is not given, `mrb_get_args()` does not touch the C variable. `opts` remains uninitialized (thus holds arbitrary random value). Accessing uninitialized local variable my cause crash as you had.

The workaround is providing `given` argument to `mrb_get_args()` or initialize `opts` beforehand like `mrb_value opts = mrb_nil_value()`.
