### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by lopopolo** [mruby/mruby#4616]
Hi @matz, I wanted to say thank you for mruby. I'm not sure if you know what I've been up to, but I've been using mruby to bootstrap the development of [Artichoke](https://github.com/artichoke/artichoke).

With a combination of existing mruby, patches I've upstreamed, some patches  to mruby in Artichoke, and some Core reimplementations in Artichoke, the mruby backend can run ruby/spec to completion, even though it does not pass it fully.

    $ pushd spec-runner/vendor/ruby/language
    $ cargo run --bin spec-runner **/*.rb
    Passed 1078, skipped 35, not implemented 2, failed 476 specs.
    $ popd; pushd spec-runner/vendor/ruby/core
    $ cargo run --bin spec-runner **/*.rb
    Passed 5412, skipped 998, not implemented 201, failed 8629 specs.

Eventually, I'll replace all of Ruby Core in mruby with the Artichoke runtime. https://github.com/artichoke/artichoke/issues/32
And next, eventually I'll replace the parser and the VM, too. https://github.com/artichoke/artichoke/issues/69

But I would not have made it this far without mruby.
Thank you. 🙏 💎

**Comment by matz** [comment]
You're welcome.
