### ISSUE TITLE
`mrb_gc_unregister()` may access freed memory

### ISSUE THREAD

**Issue by shuujii** [mruby/mruby#4618]
`mrb_gc_unregister()` may be called from `mrb_gc_destroy()` in `mrb_close()`, but the registered list (global variable) has already freed by previous `mrb_gc_free_gv()`.

**Comment by matz** [comment]
I didn't find the call path from `mrb_gc_destroy` to `mrb_gc_unregister`.  Did I miss something?

**Comment by shuujii** [comment]
Sorry for the lack of explanation.

This is a problem when we create custom class and call `mrb_gc_unregister()` in `mrb_data_type::dfree`.

```text
mrb_gc_destroy
-> free_heap
  -> obj_free
    -> mrb_data_type::dfree
      -> mrb_gc_unregister
```

There seems to be such a usage in H2O:

https://github.com/h2o/h2o/blob/af171560cfa21d16a65da61f91bb7201d094e20e/lib/handler/mruby/channel.c#L37-L45

**Comment by matz** [comment]
I clear `mrb->globals` in `mrb_gc_free_gv` so that access to the global variables should not cause any errors. It should cover this issue too.

**Comment by shuujii** [comment]
`mrb_intern_lit` is called from `mrb_gc_unregister`, but `mrb_free_symtbl` is called before `mrb_gc_destroy`. This seems to be a similar problem.
