### ISSUE TITLE
Expressions with modifier unless return true if the condition is true

### ISSUE THREAD

**Issue by lopopolo** [mruby/mruby#4644]
This causes `Array#find` and `Array#detect` to return `true` when no match is found and no callable is supplied.

MRI returns `nil`.

```console
[23:33] [~/dev/repos/mruby] $ git rev-parse HEAD
1961059330a47ea6030e2247b2bb2d9eea428205
```

## mruby

```console
$ ./bin/mirb
> [].find { |v| v == 'found' }
 => true
> ['g'].find { |v| v == 'found' }
 => true
> ['found'].find { |v| v == 'found' }
 => "found"
```

## MRI

```console
$ irb
[2.6.0] > [].find { |v| v == 'found' }
=> nil
[2.6.0] > ['g'].find { |v| v == 'found' }
=> nil
[2.6.0] > ['found'].find { |v| v == 'found' }
=> "found"
```

**Comment by lopopolo** [comment]
I think this bug is introduced by https://github.com/mruby/mruby/commit/b4cdced22fe1f25d8cf6fc499a2e2c9875f17e9e

**Comment by lopopolo** [comment]
This boils down to a difference between mruby and MRI with regard to the return value of modifier `unless`.

## mruby

```
> nil.call unless nil.nil?
 => true
> nil.call if 7.nil?
 => nil
```

## MRI

```
[2.6.0] > nil.call unless nil.nil?
=> nil
[2.6.0] > nil.call if 7.nil?
=> nil
```

**Comment by matz** [comment]
Sorry, it was caused by a bug in the recent optimization (13eaff4). Wil fix.
