### ISSUE TITLE
Discussion of lock files

### ISSUE THREAD

**Issue by take-cheeze** [mruby/mruby#4658]
(There is many issue about it but it's difficult to discuss in multiple issue so I'm making this)

https://github.com/mruby/mruby/pull/4656
https://github.com/mruby/mruby/pull/4180
https://github.com/mruby/mruby/issues/4652

## Taking lock of mruby itself
https://github.com/mruby/mruby/pull/4654

Actually this is only tracking the commit hash and doesn't do any `git reset` yet.

About `release_no` and `version` string (ref: https://github.com/mruby/mruby/pull/4654#issuecomment-523790931 ):
I just don't like to process string to compare version so I've added number that can compare easily.
I know the concern but processing string is hard in many way so we should use `version` for printing and `release_no` for processing version compares.

## Lock file must be always generated
There is some comment about whether to generate lock file by default.
From an operation view we MUST generate it and keep it possible in repository if possible.
We change a lot and to make those build stable we must track it with lock file.
In a bug reporting it helps the investigator.

I agree it changes how we develop mruby stuff and this should be done in some big release timing.
Though rails developers are used to `Gemfile.lock` and we should follow the good part of them.

**Comment by shuujii** [comment]
> I just don't like to process string to compare version so I've added number that can compare easily.
I know the concern but processing string is hard in many way so we should use version for printing and release_no for processing version compares.

Sorry, maybe my expression was not good. It means that the top level key seems better to be `mruby`, etc. because duplicated `version` seems to be redundant.

#### Current

```yaml
mruby_version:
  version: ...
  release_no: ...
  git_commit: ...
```

#### Proposed

```yaml
mruby:
  version: ...
  release_no: ...
  git_commit: ...
```

**Comment by take-cheeze** [comment]
I've tried `mruby` only but seems obscure so I've added `_version` suffix.
And with `mruby` only we could abuse it too much and I don't want that.
Though `version` key should be `version_string` or somewhat.

**Comment by Reckordp** [comment]
I have tried using a lockfile for the needs of a comparable version of the product with source code #4964 
expect the `.lockfile` file's purpose to be like that
