### ISSUE TITLE
Defining Integer class causes mruby to segfault

### ISSUE THREAD

**Issue by lopopolo** [mruby/mruby#4660]
Executing this code causes mruby to segfault:

```c
mrb_state mrb = mrb_open();
mrb_define_class(mrb, "Integer", mrb->object_class);
```

**Comment by matz** [comment]
Don't define existing class via C API, especially with different superclass.
Use `mrb_class_get()` instead.

It shouldn't segfault though.

**Comment by lopopolo** [comment]
It looks like I actually got a SIGABORT. Maybe that is expected?

**Comment by matz** [comment]
It's caused by assertion. The superclass of `Integer` is `Numeric`, but you tried to define `Integer` as a subclass of `Object`. That caused an exception, and since your definition is not wrapped by exception handler, it causes `SIGABORT`.
