### ISSUE TITLE
Is it possible to do dynamic recompilation?

### ISSUE THREAD

**Issue by Mav7** [mruby/mruby#4676]
Is it possible to recompile an .mrb file on a running process and see the changes instantly? If so how is it done?

**Comment by matz** [comment]
To compile Ruby program to .mrb file, you can use `mrb_load_file_cxt` then `mrb_dump_irep_binary`.
To load .mrb file, you can use `mrb_load_irep_file_cxt`. There're several varietion for those functions.
Refer `mrbgems/mruby-bin/tools/mrbc.c` for compilation and `mrbgems/mruby-bin-mruby/tools/mruby.c` for loading.
