### ISSUE TITLE
No API for getting the raw byte content of a Symbol

### ISSUE THREAD

**Issue by lopopolo** [mruby/mruby#4684]
Symbols can have arbitrary byte content. `mrb_sym2name` returns symbols as C strings that are:

- Wrapped in quotes.
- With UTF-8 escape sequences for non-ASCII characters.

To convert a Symbol to its name as a `char *`, one must do:

```c
  mrb_value sym = mrb_sym2str(mrb, mrb_symbol(value));
  return mrb_str_to_cstr(mrb, sym);
```

This is suboptimal because:

- It might require an extra allocation.
- It was hard to figure out.

Can we add a `mrb_sym_to_cstr` API?

I ran into this when implementing https://github.com/artichoke/artichoke/pull/242, specifically https://github.com/artichoke/artichoke/pull/242/commits/f75f7d2e7299cb903432709f5d8c44eef1c8a482.

**Comment by shuujii** [comment]
We can use `mrb_sym2name_len` for this purpose.

`mrb_sym2name` and `mrb_sym2name_len` similar names but are very confused because the return contents are different. The former may not a good name.

**Comment by matz** [comment]
Any name candidate for `mrb_sym2name()`?
