### ISSUE TITLE
Allow "mixed declarations and code" and "`for` loop initial declarations"

### ISSUE THREAD

**Issue by shuujii** [mruby/mruby#4685]
[mruby requires C99](https://github.com/mruby/mruby/blob/master/CONTRIBUTING.md#comply-with-c99-isoiec-98991999), but ["mixed declarations and code (declaration after statement)" doesn't seem to be allowed](https://github.com/mruby/mruby/blob/148fffa21ad5cbf42526ce393d24cb214167a82e/tasks/toolchains/gcc.rake#L4), ["`for` loop initial declarations" too](https://github.com/mruby/mruby/commit/6cec0c9f62c176e9bd926d12551b384315e98388).

The reason seems to be that it cannot be compiled by older Visual Studio and GCC. However, I think both have been solved as follows.

### Visual Studio

Visual Studio >= 2013 supports both syntaxes. And [Visual Studio <= 2012 should be deprecated in mruby](https://github.com/mruby/mruby/issues/3134#issuecomment-199863003). Since the comment ["VS2010/2012 support will be dropped after the next release!"](https://github.com/cremno/mruby/blob/30b0100e6cffe12d09e497f609b174d819d04014/tasks/toolchains/visualcpp.rake#L57) was added, it has been released multiple times including major version up.

I think it should be added in the document that the target of support is Visual Studio >= 2013.

### GCC

Old GCC may not compile these syntaxes because the default C standard conformance level is less than C99. However, these can be compiled if change the conformance level by specifying `-std=gnu99`. According to [Status of C99 features in GCC](https://gcc.gnu.org/c99status.html), both syntaxes seem to be supported since GCC 3.0 (released in 2001).

> | Feature                                                 | Version |
> | ------------------------------------------------------- | ------- |
> | mixed declarations and code                             | GCC 3.0 |
> | new block scopes for selection and iteration statements | GCC 3.0 |

This option is set automatically when using `tasks/toolchains/gcc.rake`. But does not set when `CFLAGS` environment variable, thus it should be fixed so that always set, I think. Also, it should be added in the document that this option must be specified when using old GCC without `tasks/toolchains/gcc.rake`, I think.

**Comment by matz** [comment]
we prohibit mixed declaration because we are told some compilers on embedded environments did not understand it. If it's no longer true, we are glad to remove the restriction. But it's hard to prove.

**Comment by shuujii** [comment]
Thank you for your comment.

Is my understanding that Visual Studio <= 2012 is not supported is right? If it is correct, the reason to disallow these syntaxes is not Visual C++, so may I change the following contents?

> \
> Although we target C99, Visual C++ is also an important target for mruby. For this reason a declaration of a local variable has to be at the beginning of a scope block.

**Comment by matz** [comment]
Yes. Old VC is no longer supported. The document should be updated like:

> Although we target C99, we've heard some compilers in the embedded environment still requires declarations of local variables to be at the beginning of a scope. Until we confirm the situation has changed, we use the old-style variable declaration.

**Comment by shuujii** [comment]
Thank you for showing the example.

I think it is better to include the following points:

- Supported VC version is 2013 or later.
- Features that are not supported by VC may not be used (e.g. `%z` of `strftime()`).
- Old GCC requires `-std=gnu99` option.

I made a draft of the additional part for now:

> Visual C++ is also an important target for mruby (supported version is 2013 or later). For this reason features that are not supported by Visual C++ may not be used (e.g. `%z` of `strftime()`).
>
> NOTE: Old GCC requires `-std=gnu99` option to enable C99 support.

English correction is welcome :)

**Comment by matz** [comment]
The update looks good go me (although I don't trust my English ability).

**Comment by matz** [comment]
Fixed by #4685
