### ISSUE TITLE
mruby does not raise ArgumentError when method called with mismatched argspec

### ISSUE THREAD

**Issue by lopopolo** [mruby/mruby#4688]
I thought mruby would raise an argument error before invoking the bound C function if the given args did not match the pattern allowed by the argspec.

In practice, mruby invokes the C function and only unwinds when calling `mrb_get_args`.

Applying this diff to master:

```diff
diff --git a/mrbgems/mruby-hash-ext/src/hash-ext.c b/mrbgems/mruby-hash-ext/src/hash-ext.c
index e6112667..2e21a7a7 100644
--- a/mrbgems/mruby-hash-ext/src/hash-ext.c
+++ b/mrbgems/mruby-hash-ext/src/hash-ext.c
@@ -69,6 +69,12 @@ hash_slice(mrb_state *mrb, mrb_value hash)
   return result;
 }

+static mrb_value
+hash_foo(mrb_state *mrb, mrb_value hash)
+{
+  return mrb_nil_value();
+}
+
 void
 mrb_mruby_hash_ext_gem_init(mrb_state *mrb)
 {
@@ -77,6 +83,7 @@ mrb_mruby_hash_ext_gem_init(mrb_state *mrb)
   h = mrb->hash_class;
   mrb_define_method(mrb, h, "values_at", hash_values_at, MRB_ARGS_ANY());
   mrb_define_method(mrb, h, "slice",     hash_slice, MRB_ARGS_ANY());
+  mrb_define_class_method(mrb, h, "foo", hash_foo, MRB_ARGS_REQ(1));
 }

 void
```

Exhibits this behavior:

```
$ ./bin/mirb
mirb - Embeddable Interactive Ruby Shell

> Hash.foo
 => nil
> Hash.foo(1,2,3)
 => nil
```

**Comment by matz** [comment]
I am sorry but currently, argument spec is not checked. It's a limitation of the implementation.
If you want to raise an error, you need to call `mrb_get_args` explicitly.

**Comment by lopopolo** [comment]
Unfortunately I want the opposite. I was hoping that I could rely on these APIs not unwinding so I could use RAII’d heap allocated objects. With the unwind, these references don’t get cleaned up.

**Comment by matz** [comment]
I am not sure what you want. But currently, we have no slots in proc object structs to save spec without consuming too much memory. Do you have any idea?

**Comment by lopopolo** [comment]
Sorry @matz I did not mean to be so terse.

I'm using mruby in an FFI environment (Rust) where I cannot use C++ exceptions to clean up during an unwind. I've found several functions in the C API that unwind where I did not expect them to, which has caused memory leaks or memory corruption in Rust because longjmp unwinds past the function exit routines that clean up acquired resources.

In Rust, I would expect a function that unwinds (panics) to document this behavior as part of its API. It seems the only way for me to find out which mruby APIs can unwind is by reading the source. Or is it expected that callers of mruby C APIs ensure that all variables on the stack are `Copy` before calling _any_ C API?

**Comment by matz** [comment]
I'm sorry I still don't understand the situation due to my lack of knowledge about Rust and FFI. When Rust calls a Ruby method with arguments that do not match with its arg spec, it doesn't do anything (no error, no longjmp). So it might not be your expected behavior, but it shouldn't panic (so no unwinding and no leak) at least.  But you face the panicking problem. Hmm.

**Comment by lopopolo** [comment]
I was hoping that mruby would unwind if there was a mismatched argspec _before_ calling into a the C function registered with the VM. This would enable me to safely call `mrb_get_args` with a arg format string that is valid according to the argspec _without getting an unwind_.

Because I was not expecting an unwind from `mrb_get_args`, I had acquired some resources that Rust would normally clean up when the function returns. These resources not getting cleaned up caused a panic in my program similar to how a null pointer exception in Java can show up far away from the original source of the null.

**Comment by lopopolo** [comment]
I have found a way to make this work in Rust now 🦀. I was mostly surprised and confused by the disconnect between argspecs supplied via `mrb_define_method`/`mrb_define_class_method` and the arg format strings.

Would it be possible to document this limitation in the `limitations.md` document?
