### ISSUE TITLE
invalid identifiers can be used in unquoted symbol literals

### ISSUE THREAD

**Issue by lopopolo** [mruby/mruby#4689]
```console
$ echo -ne “puts :\xFF.inspect” | mruby
:”\xff”
```

**Comment by matz** [comment]
```ruby
mruby -e "puts :\xFF.inspect"
```
causes a syntax error. That means mruby does not accept `:\xFF`, but the shell converts `\xFF` into `"\377"` (binary). Thus it's not a bug in mruby.

**Comment by lopopolo** [comment]
@matz the shell is converting that sequence into a byte with the value 255, which is not a valid identifier.
