### ISSUE TITLE
mrb_funcall returns odd value

### ISSUE THREAD

**Issue by IK-O** [mruby/mruby#4696]
Sorry, this is Japanese.

mruby 2019/09/02版ですが、C側でmrb_funcall を呼び出すと、ごく稀に戻り値のmrb_valueが壊れる場合があります。

今、C側でRubyのFileオブジェクトを受け取って、readメソッドを呼び出してデータの読み込みを行おうとしています。

■1バイトのデータを読み込むサンプルコード

    char ReadChar(mrb_state* mrb, mrb_value port)
    {
        mrb_value buf = mrb_funcall(mrb, port, "read", 1, mrb_fixnum_value(1));
        return RSTRING_PTR(buf)[0];
    }

手元の実際のファイル上のデータは0x1Aが入っているのですが、上記のコードを実行すると
buf.value.p = 0
buf.tt = MRB_TT_FALSE
というデータになります。

こちらのMRuby Marshal mgemでMarshal.loadした場合も全く同じ現象が起こります。
[take-cheeze/mruby-marshal](https://github.com/take-cheeze/mruby-marshal)

厄介なことに全てのデータで発生するわけではなく、原因が解りません。
mrb_intern、vm、gc、io-gemなどが絡んでると思うのですが、何か解決の糸口はあるでしょうか。

不具合が出る環境は以下の通りです。
・Windows7 64bit
・Visual Studio 2017

何かありましたら宜しくお願い致します。

**Comment by matz** [comment]
Japanese:
全体のコードを見ないとなんとも言えませんが、
```C
buf.value.p = 0
buf.tt = MRB_TT_FALSE
```
ということは`nil`が返っているということです。で、なぜ`nil`が返るかですが、

* メソッドが`nil`を返している
* VMの途中で値が書き換わっている

の両方が考えられますが、前者を疑っています。デバッガ(またはデバッグプリント)で確認することはできませんか？

全体のソースコードなしではこれ以上の考察は困難ですね。

**Comment by IK-O** [comment]
Japanese:

デバッガで解析したところ、
`mruby-io` の `io.c` の `mrb_io_sysread()` で `read()` がEOFエラーになります。
これで戻り値が`nil`になってるようです。

35KBあるデータに対して、`mrb_funcall(mrb, port, "read")`で読み込んでるのは500バイト程度なので
EOFエラーになるのはおかしいです。


`io.rb`のバッファリングがうまくいってないかもしれません。

**Comment by matz** [comment]
そうですね(もう、言えることはほとんどない)。

もうちょっとデバッガで追いかけて、`mrb_io_sysread`は初回の読み込みでEOFエラーを出しているのかとか、バッファに値は入っているのかとか確認してみると良いかもしれません。

**Comment by dearblue** [comment]
@IK-O
ちょっと確認なのですが、mruby は `MRB_UTF8_STRING` を付けてビルドしているのでしょうか？
その場合、現在の実装において `io.read(1)` は1バイトではなく1文字となります。
もしかしたらそのあたりに起因しているように思います。

**Comment by matz** [comment]
え？ CRuby では `io.read(1)` は１バイト読みます。もし、mruby-io が１バイトでなく１文字読み込むのであれば、それは非互換であり直すべきでは？

**Comment by matz** [comment]
試したら、mruby-io は文字単位で読み込みますね。直すか

**Comment by IK-O** [comment]
@dearblue 
`MRB_UTF8_STRING`は定義されてないはずですが、
今回の不具合は`File.open`で`"r"`だった箇所を、`"rb"`にすると発生しなくなりました。
rとrbで`read(バイト数)`の挙動変化するのでしょうか？

**Comment by matz** [comment]
いや、`rb`だと改行の変換(`\r\n` → `\n`)が抑制されるだけだと思うのですが。謎。

**Comment by dearblue** [comment]
@IK-O
Windows では開いたファイルがテキストモードかバイナリモードかで挙動が変わってきます。
テキストモードでは読み込み・書き出しにおける改行の変換が行われ、さらに読み込みでは "\x1a" (標準入力時の Ctrl+Z) でファイルの読み込みを打ち切ります。
35 KB を読み込んで500バイトで EOF ということなので、テキストモードで "\x1a" を読み込んだためかと思います。
CRuby でもテキストモードで読み込んでみて、結果が同じかどうかを確認してみるのが良いかもしれません。

**Comment by IK-O** [comment]
@dearblue 
まさにご指摘の通り、0x1Aを読み込んだところでEOFになってました。
Windowsにこんな仕様があるのは知りませんでした。

ただ、CRubyのほうは`"r"`で0x1Aを読み込んでもEOFにはなりませんでした。
WindowsだとCRubyの`File.open`は`msvrct._wopen()`に繋がるのですが、テキストモードフラグが指定されていなかったので、
一度バイナリで読み込んで、Ruby内部でテキスト関係の処理をしてるっぽいです。
他のOSとの互換性の為にそういう細工がなされてるかもしれません。

そうすると、現状のMRubyはCRubyとのWindows上での互換性が無いことになってしまいますね。
どうしましょう。

**Comment by matz** [comment]
CRubyの現在の仕様は親切心からそうなってますが、必須の挙動ではないと思います。Windowsを使ってる以上、バイナリファイルの読み込みには `rb` が必要なのは(OSの)仕様です。こちらで対処する必要はないと思います。ということで、本件クローズします。

**Comment by dearblue** [comment]
Windows 版 CRuby の挙動は知りませんでした。
おかしな誘導をしてしまったようで申し訳ないです。

**Comment by matz** [comment]
おかげでC-zの問題がわかったわけですから(私も忘れていた)、感謝しかありません。
