### ISSUE TITLE
Do not call `git clone` from within rake in mrbgems/mruby-sleep

### ISSUE THREAD

**Issue by fpesari** [mruby/mruby#4702]
Hello,

mrbgems/mruby-sleep calls `git clone` from within its Rakefile. 

This is undesirable when packaging software, because software is often built on virtualized environments without access to the Internet.

Please, follow the same structure as the other mrbgems in mruby-sleep so that it does not connect to the Internet at any point.

**Comment by matz** [comment]
It's a leftover from `mruby-sleep` as an independent mrbgem. I will delete `Rakefile`.
