### ISSUE TITLE
module_function not found from the module

### ISSUE THREAD

**Issue by IK-O** [mruby/mruby#4708]
# test.rb

    module TestModule
      module_function
      def test_func
        p 'test_func called'
      end

      test_func
    end

    p 'ok'

CRuby done with no error, but latest MRuby raise error.

> C:\\mruby\bin>mruby test.rb
> 
> trace (most recent call last):
>         [0] test.rb:1
>         [1] test.rb:8
> test.rb:8: undefined method 'test_func' (NoMethodError)

**Comment by matz** [comment]
The declaration version of `module_function` is not implemented. You have to call `module_function :test_func`.

**Comment by shuujii** [comment]
You can also use `module_function def test_func ...`.
