### ISSUE TITLE
Some core mrbgems that do not included "mruby developers" in "author"

### ISSUE THREAD

**Issue by dearblue** [mruby/mruby#4709]
Is this intended?

```console
% git grep -e 'author' --and --not -e 'mruby developers' -- 'mrbgems/*/*.rake'
mrbgems/mruby-io/mrbgem.rake:  spec.authors = 'Internet Initiative Japan Inc.'
mrbgems/mruby-pack/mrbgem.rake:  spec.authors = 'Internet Initiative Japan Inc.'
mrbgems/mruby-sleep/mrbgem.rake:  spec.authors = 'MATSUMOTO Ryosuke'
mrbgems/mruby-socket/mrbgem.rake:  spec.authors = 'Internet Initiative Japan'
```

If this is not desirable, you might want to rewrite some `mrbgems/*/RAEDME.md` as well.

**Comment by matz** [comment]
I asked the authors to bundle their gems, but we didn't ask for contribution. So unless they are willing, we would keep author names as they are. I'd like to hear the opinion of the original authors.

How do you think? @matsumotory @tsahara

**Comment by tsahara** [comment]
You can rewrite `spec.authors` if you wish because we (IIJ) are one of the authors of the mruby as well (our name is in AUTHORS file).

But I don't think "just rewriting the name of the copyright holder" is a good idea because "mruby developers" was not a copyright holder of mruby-io in 2013.  To make license terms simple, it is better to remove the copyright notice specific to mruby-io (and mruby-pack/mruby-socket), as I said in https://github.com/iij/mruby-io/issues/95#issuecomment-344792171.

**Comment by dearblue** [comment]
The easiest and safest way is to simply add it after the original author:

```diff
diff --git a/mrbgems/mruby-io/README.md b/mrbgems/mruby-io/README.md
index ccf56f97..2c5b762d 100644
--- a/mrbgems/mruby-io/README.md
+++ b/mrbgems/mruby-io/README.md
@@ -171,6 +171,7 @@ Add the line below to your `build_config.rb`:
 ## License
 
 Copyright (c) 2013 Internet Initiative Japan Inc.
+Copyright (c) 2017 mruby developers
 
 Permission is hereby granted, free of charge, to any person obtaining a 
 copy of this software and associated documentation files (the "Software"), 
diff --git a/mrbgems/mruby-io/mrbgem.rake b/mrbgems/mruby-io/mrbgem.rake
index e4f0b7bb..bd20f6d2 100644
--- a/mrbgems/mruby-io/mrbgem.rake
+++ b/mrbgems/mruby-io/mrbgem.rake
@@ -1,6 +1,6 @@
 MRuby::Gem::Specification.new('mruby-io') do |spec|
   spec.license = 'MIT'
-  spec.authors = 'Internet Initiative Japan Inc.'
+  spec.authors = ['Internet Initiative Japan Inc.', 'mruby developers']
   spec.summary = 'IO and File class'
 
   spec.cc.include_paths << "#{build.root}/src"
```

If the licenses are different, the new license is written next to the original.

And, @tsahara is mentioned, so you can rewrite to `spec.authors = 'mruby developers'`.

It also mentions the removal of the license terms.
Does this mean that you have already accepted that if your mruby license changes in the future, your `mruby/mrbgems/mruby-io` (not `iij/mruby-io`) license will change as well?
If you don't intend to do that, you should leave the license terms.

----

I want to ask to make the actual change by @matz or the original authors (@tsahara, @matsumotory).
Or should I PR?

**Comment by matz** [comment]
Sorry for being late to reply. @dearblue could you send us a PR, and we'd ask permission for changes.

**Comment by dearblue** [comment]
Thanks for reply. I propose as #4859.
