### ISSUE TITLE
How to check if class is defined or not?

### ISSUE THREAD

**Issue by IK-O** [mruby/mruby#4711]
I want to check some class is defined or not.
`defined?` method haven't implemented yet, and doc says use `const_defined?` method instead.

I tried follow code, but it raises error.

    # test.rb

    class TestClass
    end

    p const_defined?(:TestClass)

> test.rb:4: undefined method 'const_defined?' (NoMethodError)

How can I check it?

**Comment by shuujii** [comment]
You can use `Object.const_defined?`

**Comment by IK-O** [comment]
@Shokuji 
Thanks, I got it.
