### ISSUE TITLE
behavior of alias is defferent from CRuby

### ISSUE THREAD

**Issue by IK-O** [mruby/mruby#4718]
```
# test.rb
class Base
  def start
    p 'Base'
  end
end

class Patch < Base
  def start
    p 'Patch A'
    super
  end
end

class Patch < Base
  alias patch_start start
  def start
    p 'Patch B'
    patch_start
  end
end

a = Patch.new
a.start
```

In CRuby, it outputs

> "Patch B"
> "Patch A"
> "Base"

On the other hand, In MRuby, it outputs error

> "Patch B"
> "Patch A"
> trace (most recent call last):
>         [0] test.rb:23
>         [1] test.rb:18:in start
>         [2] test.rb:10:in patch_start
> test.rb:10: undefined method 'patch_start' (NoMethodError)

I want MRuby to perform same as CRuby as much as possible.
How can I do it?

**Comment by matz** [comment]
It's a known issue, e.g. #1457, #1531
Those fixes consume more memory, which is more precious than minor compatibility.
