### ISSUE TITLE
Feature Request: Custom gc mark functions per mrb_data_type

### ISSUE THREAD

**Issue by lopopolo** [mruby/mruby#4721]
I’m trying to override mruby with a custom `Array` implementation as an `MRB_TT_DATA` type `mrb_value`.

`DATA` values only support marking instance variables during GC which means they cannot take ownership of `mrb_value`s in native code.

Does mruby support implementing custom collection types? I’d like to hook into the GC mark phase similar to how the `mrb_free` function pointer type lets me hook into the GC free phase.

**Comment by lopopolo** [comment]
One possible solution I can think of is to call `mrb_gc_protect` when taking ownership, but this does not play nicely with a constrained arena size.

**Comment by matz** [comment]
Custom GC mark function only works with simple mark&sweep GC. But mruby has far more complicated generational incremental mark&sweep GC, which requires write barriers that cannot be represented by simple mark functions.

Instead, `MRB_TT_DATA` objects are able to hold instance variables, so if you want to reference mruby objects from `MRB_TT_DATA` you can maintain references from their instance variables as well, using functions like `mrb_iv_set`.
