### ISSUE TITLE
Segmentation fault when calling mrb_define_method with a NULL class.

### ISSUE THREAD

**Issue by lopopolo** [mruby/mruby#4743]
I know I'm a little off the beaten trail here with the example, but this segfault should affect all uses of `mrb_define_method`.

I do not call `mrb_init_array` which means `mrb->array_class` is `NULL`.

This call in `mruby-pack` segfaults because the class passed to `mrb_define_method` is `NULL`.

```
 mrb_define_method(mrb, mrb->array_class, "pack", mrb_pack_pack, MRB_ARGS_REQ(1));
```

From LLDB:

```
Process 55959 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x10)
    frame #0: 0x0000000100213700 airb`mrb_define_method_raw + 32
airb`mrb_define_method_raw:
->  0x100213700 <+32>: movl   0x10(%rax), %ecx
    0x100213703 <+35>: shrl   $0xb, %ecx
    0x100213706 <+38>: andl   $0x80000, %ecx            ; imm = 0x80000
    0x10021370c <+44>: cmpl   $0x0, %ecx
Target 0: (airb) stopped.
(lldb) frame select 3
frame #3: 0x00000001001f49e6 airb`mrb_mruby_pack_gem_init(mrb=&0x101800400) at pack.c:1332:3
   1329	  check_little_endian();
   1330	  make_base64_dec_tab();
   1331
-> 1332	  mrb_define_method(mrb, mrb->array_class, "pack", mrb_pack_pack, MRB_ARGS_REQ(1));
   1333	  mrb_define_method(mrb, mrb->string_class, "unpack", mrb_pack_unpack, MRB_ARGS_REQ(1));
   1334	  mrb_define_method(mrb, mrb->string_class, "unpack1", mrb_pack_unpack1, MRB_ARGS_REQ(1));
   1335	}
(lldb) p mrb->array_class
(RClass *) $0 = &0x0
```

**Comment by matz** [comment]
Hmm, the short answer is call `mrb_init_array` first, but there must be some reason behind. Could you elaborate?

**Comment by lopopolo** [comment]
I think this is a fundamental limitation of C. Uninitialized memory is something I need to deal with 😢 

One change I did make which might be upstreamable is to change this line in `mruby-pack`

https://github.com/mruby/mruby/blob/c33100c4f03b5f0e8d9034a7b82fabb0975e9a5a/mrbgems/mruby-pack/src/pack.c#L1328

 to call:

```c
mrb_class_get(mrb, "Array")
```

so that it doesn't need to rely on how the core is initialized.

**Comment by matz** [comment]
There are many places that use `mrb->array_class` for performance reason. I don't think we can modify them all.

**Comment by take-cheeze** [comment]
Maybe you can overwrite the `mrb->array_class` like
https://github.com/mruby/mruby/blob/c20dda4f4c72f2da10194a417bbca6cf6f5457c2/src/array.c#L1314
before initializing the pack gem.

**Comment by matz** [comment]
Did you solve the issue, or just abandon?

**Comment by lopopolo** [comment]
I figured out a work around. Modifying the semantics of the class fields on the `mrb_state` is not something I think is a good idea. I've kept the initialization of these fields.

**Comment by matz** [comment]
Nice. Thank you.
