### ISSUE TITLE
How can I call a method defined in ruby land from c land?

### ISSUE THREAD

**Issue by cyberarm** [mruby/mruby#4765]
I'm writing a [mruby gem](https://github.com/cyberarm/mruby-gosu) wrapper for the [Gosu](https://github.com/gosu/gosu) game library and am stuck trying to get the various callbacks implemented.

I need to pass a function for the callback to call, that function needs to call a user overridable method, e.g. `update`.

I've cobbled together this from what I could dig up, but it doesn't work (method is always null):
```c
static mrb_value
mrb_gosu_window_set_update(mrb_state *mrb, mrb_value self)
{
  mrb_method_t method;
  method = mrb_method_search_vm(mrb, mrb_gosu_window, "update");

  if (method != NULL) {
    mrb_funcall(mrb, self, "update", 0);
  }

  return self;
}
```
In context: https://github.com/cyberarm/mruby-gosu/blob/46de13519fd7ecd7567145842d9aa3eb2ec312d7/src/window.c#L34-L45

The ruby method should be defined by this subclass: https://github.com/cyberarm/mruby-gosu/blob/46de13519fd7ecd7567145842d9aa3eb2ec312d7/examples/window.rb#L8

**Comment by matz** [comment]
I'd define empty `update` method for `mrb_gosu_window`, then just call `mrb_funcall`.
If you want to check the existence of the `update` method, use `mrb_obj_respond_to()`.
