### ISSUE TITLE
Unable to load rb file

### ISSUE THREAD

**Issue by lk-eternal** [mruby/mruby#4766]
When I run mruby on the mbed board, I want to read the mruby code from the file and run it, but I got an error, what am I doing wrong?

**c++**
```
mrb_define_method(mrb, mrb->kernel_module, "require", mrb_load, MRB_ARGS_REQ(1));

mrb_value mrb_load(mrb_state *mrb, mrb_value)
{
	char* filepath;
	mrb_get_args(mrb, "z", &filepath);
	pc.printf("mrb_require:%s\n",filepath);
	int ai = mrb_gc_arena_save(mrb);
	mrbc_context* mrbc_ctx = mrbc_context_new(mrb);
	mrbc_filename(mrb, mrbc_ctx, filepath);
#if 0
	mrb_load_string_cxt(mrb, getFileContent(filepath), mrbc_ctx);
#else
	FILE* fp = fopen(filepath, "r");
	if (fp == NULL) {
		pc.printf("cannot load such file");
		return mrb_false_value();
	}
	mrb_load_file_cxt(mrb, fp, mrbc_ctx);
	fclose(fp);
#endif
	mrb_gc_arena_restore(mrb, ai);
	mrbc_context_free(mrb, mrbc_ctx);
	return mrb_true_value();
}
```

**app.rb**
```

puts 'Run in mruby'

puts 'Go to require'
require '/sd/require.rb'
puts 'Back to app'

```

**require.rb**
```
puts '321'
```

**result:**
```
start!
mrb_load_file!
Run in mruby
Go to require
mrb_require:/sd/require.rb
codegen error:/sd/require.rb:2: unexpected scope

++ MbedOS Fault Handler ++

FaultType: HardFault
```

**Comment by matz** [comment]
`unexpected scope` error only happens on memory allocation failure.

**Comment by lk-eternal** [comment]
Thank you for your reply
I am using FRDM-K64F | Mbed only 256KB memory
Does this mean out of memory?

Is 256KB of memory enough to support the development of the mruby project?

**Comment by matz** [comment]
256KB RAM is big enough to run VM but probably not enough to run the compiler. It highly depends on the size of the program, of course.

**Comment by texrg** [comment]
Or use mrubyc

**Comment by matz** [comment]
Or compile your program on the host (using `mrbc`) and execute only VM on the board.

**Comment by fab1an2** [comment]
How catch all errors in load mruby ? (similar https://github.com/mruby/mruby/issues/4991 )

**Comment by matz** [comment]
I will reply to #4991
