### ISSUE TITLE
mruby 2.1.0 release process

### ISSUE THREAD

**Issue by matz** [mruby/mruby#4768]
We are going to start preparing ~~2.2.0~~ 2.1.0 release soon. Not 2.0.2 as I said before since we have made some incompatible changes.

* Is anybody willing to assemble a release note since 2.0.1?
* Does anybody have an opinion for the thing to come before ~~2.2.0~~ 2.1.0? Note that we don't have much time to implement new things.
* Is there anything we have to drop for ~~2.2.0~~ 2.1.0?

**Comment by matz** [comment]
Refer #4663

**Comment by yurie** [comment]
Why not 2.1.0 but 2.2.0?

**Comment by matz** [comment]
Ah, no reason. Probably I screwed up and reorder `2.0.2` (originally planed version) to `2.2.0`.
I have no problem making it 2.1.0.

**Comment by udzura** [comment]
https://github.com/iij/mruby-process/blob/master/test/process.rb#L11

This syntax was parsed well in 2.0.1, but broken (and is CRuby's behavior) in master. This is good fix IMO, but where is the fix commit?

And I want this change officially announced (some gems seems affected; including this mruby-process) .

**Comment by matz** [comment]
`Process.pid is_a? Integer` is always correct Ruby statement, although the meaning might be different from your expectation.  It's parsed as  `Process.pid(is_a?(Integer))`.

**Comment by udzura** [comment]
Yes! I got it. This may be because of strictening in `MRB_ARGS_NONE()`

**Comment by matz** [comment]
And you have to remember the value from `assert` blocks are not used in mruby tests. You have to call `assert_true` etc. for tests.

**Comment by matz** [comment]
2.1.0 has been released for a long time.
