### ISSUE TITLE
Memory leak when assigning an MRB_TT_DATA to a constant

### ISSUE THREAD

**Issue by lopopolo** [mruby/mruby#4782]
I am assigning an `mrb_value` with type tag `MRB_TT_DATA` to a top-level constant.

I've observed that this object does not have its free function called when closing the interpreter.

This causes a leak.

**Comment by matz** [comment]
Hmm, I experimented and free functions are called from `mrb_close`, even when `MRB_TT_DATA` object assigned to a top-level constant.

`mrb_close` calls `mrb_gc_destroy` that calls `free_heap` that calls `mrb_obj_free` for every objects allocated, and `mrb_obj_free` for `MRB_TT_DATA` calls free functions. As far as I see there's no chance to miss calling free functions.

Probably you have a different condition.
