### ISSUE TITLE
Is there a propper way to redefine MRB_THROW?

### ISSUE THREAD

**Issue by dmajkic** [mruby/mruby#4794]
Right now only C style `longjmp`, and C++ `throw` are baked in. When binding to other languages, it would be great to leverage their native solutions for error handling and recovery. 

For example, MS supports `try` in plain C as language extenesion; Delphi uses it's own Exception which are close to MRuby Exceptions. 

In Go,  longjmps crash Go stack. Go prefers returning error as last value, and it's own panic() - recover() workflow.

It would be great if there could be a documented way to supply `MRB_TRY`, `MRB_CATCH`, `MRB_END_EXC` and `MRB_THROW`

**Comment by matz** [comment]
The only way to support new raise is to modify `include/mruby/throw.h`.
Send us a pull-request once you have updated the header file.

**Comment by dmajkic** [comment]
I opted to returning Exceptions as mrb_value back to C, and handle exception on C side. 

Closing this issue.
