### ISSUE TITLE
Rakefile in mruby build emits warnings with Windows paths

### ISSUE THREAD

**Issue by lopopolo** [mruby/mruby#4817]
This code constructs a Regexp literal using string interpolation without first calling `Regexp::escape`.

https://github.com/mruby/mruby/blob/067c11f65d1eecbe53b247661aabbb00f0ba9a13/Rakefile#L65

This means paths like `C:\Program Files\foo` are interpreted as escape sequences.

**Comment by matz** [comment]
By the way, mixing two kinds of file separator (`\` and `/`) is OK
 We see code like `"#{build_dir}/mrbgems"` everywhere.

**Comment by lopopolo** [comment]
So long as the windows paths are not canonicalized UNC paths, I think it is OK
