### ISSUE TITLE
How to get current filename (a la $0)?

### ISSUE THREAD

**Issue by Widdershin** [mruby/mruby#4829]
Hi there!

Thanks for this awesome project. It's made my project, [Prism](https://github.com/prism-rb/prism), possible.

I've run into an issue where I'm trying to get the name/path of the currently executing file, a la `$0` in cruby. The behaviour of `__dir__` would also meet my needs.

Is there a way to get this information in `mruby`, either from the Ruby or C side? Note, I'm loading my files with `mrb_load_file_cxt` and `mrbc_filename` so the information is definitely there, since it shows up in backtraces.

I tried `mrb->c->filename` but clearly I've misunderstood how the implementation of `mrbc_filename` works.

Thanks for any help you can provide!

**Comment by take-cheeze** [comment]
`__FILE__` ?

**Comment by Reckordp** [comment]
Are you need refrerence?
https://github.com/Reckordp/mruby_debug_example/blob/master/src/ProsesNative.c

**Comment by Widdershin** [comment]
Thank you both for you responses, this should be more than enough for me to work with when I return to this problem 🙏
