### ISSUE TITLE
Getting arguments other than mrb_get_args() ?

### ISSUE THREAD

**Issue by CDR2003** [mruby/mruby#4832]
Hi there! I'm writing a C# wrapper for mruby, and hoping to use it in my Unity project. Since dealing with varargs is so difficult in C#, I turned to using mrb_get_argc() and mrb_get_argv(). I exported them to my DLL:

```csharp
[DllImport( "mruby" )]
internal static extern int mrb_get_argc( IntPtr mrb );

[DllImport( "mruby" )]
internal static extern IntPtr mrb_get_argv( IntPtr mrb );
```

I defined a simple function that should work like this:

```csharp
void DebugLog( string message )
```

However, as I called `mrb_get_argv()`, I got a nullptr. I checked the `mrb_get_args()`, and realized that I should use `mrb->c->stack[1]` for the first argument if a nullptr is returned from `mrb_get_argv()`. But getting `mrb->c->stack[1]` in C# is a little bit complicated and also inefficient, like this:

```csharp
IntPtr arg = MrbLib.mrb_get_argv( mrb );
if( arg == IntPtr.Zero )
{
	MrbLib.mrb_state state = (MrbLib.mrb_state)Marshal.PtrToStructure( mrb, typeof( MrbLib.mrb_state ) );
	MrbLib.mrb_context context = (MrbLib.mrb_context)Marshal.PtrToStructure( state.c, typeof( MrbLib.mrb_context ) );
	arg = (IntPtr)( (int)context.stack + Marshal.SizeOf( typeof( MrbLib.mrb_value ) ) );
}
```

Is there any other way better than this?

**Comment by matz** [comment]
I will fix `mrb_get_argv()` so you don't have to access `mrb->c->stack[1]` from C#.

**Comment by CDR2003** [comment]
Thanks! That'll be a big help!
