### ISSUE TITLE
Some information on mruby.org has not been updated to 2.1.0

### ISSUE THREAD

**Issue by shuujii** [mruby/mruby#4844]
The following information has not been updated:

* https://mruby.org/
  * Link to _"Download x.x.x Source"_
* https://mruby.org/downloads/
  * Link to _"Current stable"_
* https://mruby.org/docs/api/
  * The contents.
* https://mruby.org/team/
  * The contents of _"Term"_ and _"mruby developers"_ (also [matsumoto-r](https://github.com/matsumoto-r) is dead link).

**Comment by matz** [comment]
Fixed by mruby/mruby.github.io@6b5b3e3
