### ISSUE TITLE
undefined method `Pathname' for MRuby::Toolchain::Android

### ISSUE THREAD

**Issue by IK-O** [mruby/mruby#4895]
the newest version of MRuby and 2.10 cannot build for Android.
It raises follow error.

 "NoMethodError: undefined method `Pathname' for #<MRuby::Toolchain::Android:0x0000557558125f48>
/home/pc/mruby-newest/tasks/toolchains/android.rake:70:in `home_path'"

How can I make for Android?
It could be made till v2.01

build_android.rb

    MRuby::Build.new do |conf|
      conf.toolchain :clang
      conf.gem core: 'mruby-bin-mrbc'
    end

    MRuby::CrossBuild.new('android_arm64') do |conf|
      api = 21
      conf.toolchain :android, arch: "arm64-v8a", platform: "android-#{api}"
      conf.gem core: 'mruby-print'
      conf.gem core: 'mruby-bin-mruby'
      conf.gem 'mrbgems/mruby-io'
      conf.gem 'mrbgems/mruby-zlib'
      conf.gem 'mrbgems/mruby-dir'
      conf.cc do |cc|
        cc.defines << "__ANDROID_API__=#{api}"
        cc.flags << "--sysroot=#{ENV['ANDROID_NDK_HOME']}/sysroot"
      end
    end`

build command

      rake MRUBY_CONFIG=build_android.rb ANDROID_NDK_HOME=/home/pc/android-ndk-r20/

**Comment by shuujii** [comment]
Thank you for your report. I will fix soon.
