### ISSUE TITLE
undefined method 'call' when yielding from method accepting kwargs

### ISSUE THREAD

**Issue by fcheung** [mruby/mruby#4921]
The following program raises an error on mruby 2.1.0 (on both OS X and on a esp32 based device). I can also reproduce with mruby head ( d6b89868 )

```
class Foo
  def run(bar:)
    yield 1
  end
end

b = Foo.new
b.run(bar:1000) {|value| puts value}
```

The error raised is
```
trace (most recent call last):
	[0] test.rb:8
	[1] test.rb:3:in arun
test.rb:3: undefined method 'call' (NoMethodError)
```
and is triggered by the `yield` line.

The error goes away I change the signature of run method to `def run(bar)`  or `def run(**args)`.

Please ask if there anymore information I can provide to help reproduce this.

**Comment by dearblue** [comment]
It is a good report!
I am using FreeBSD 12.1 and could reproduce it (with mruby head d82e918).

```console
% mruby -e 'def run(x:); yield; end; run(x:10) { }'
trace (most recent call last):
        [1] -e:1
-e:1:in run: undefined method 'call' (NoMethodError)

% mruby -e 'def run(x:, &b); yield; end; run(x:10) { }'
trace (most recent call last):
        [1] -e:1
-e:1:in run: undefined method 'call' (NoMethodError)
```

When I `.call` the block directly, it succeeded.

```console
% mruby -e 'def run(x:, &b); b.call x; end; run(x:10) { |xx| p xx }'
10
```

This issue was reproducible with mruby-2.0.0 too.

**Comment by fcheung** [comment]
Thank you @dearblue for the super quick fix!
