### ISSUE TITLE
mruby -v hangs in macos 10.14.6

### ISSUE THREAD

**Issue by scalefree** [mruby/mruby#4922]
Just installed mruby 2.1.0 via rbenv, set it to global. Running `ruby -v` gives me `mruby 2.1.0 (2019-11-19)` then hangs.  If I `^Z `then `fg` it terminates & I get the following message:

> 00001 NODE_SCOPE:
00001   NODE_BEGIN:
irep 0x7fdc134073a0 nregs=2 nlocals=1 pools=0 syms=0 reps=0 iseq=5
file: -
    1 000 OP_LOADNIL	R1
    1 002 OP_RETURN	R1
    1 004 OP_STOP

**Comment by shuujii** [comment]
mruby 2.1.0 does not quit immediately even if `-v` is specified and waits for input (It is similar to `ruby -v --dump p -` on CRuby). mruby quits immediately if `--version` is specified.

FYI, in master branch, mruby quits immediately if only `-v` is specified.

**Comment by matz** [comment]
Thank you for the right answer @shuujii
