### ISSUE TITLE
Top level local variable is not file scope with `mruby` command

### ISSUE THREAD

**Issue by shuujii** [mruby/mruby#4931]
Is the following behavior intentional?

#### Files

  ```ruby
  # a.rb
  a = 1
  ```

  ```ruby
  # b.rb
  p a
  ```

#### mruby

  ```console
  $ bin/mruby -r ./a.rb b.rb
  1
  ```

#### Ruby

  ```console
  $ ruby -r ./a.rb b.rb
  Traceback (most recent call last):
  b.rb:1:in `<main>': undefined local variable or method `a' for main:Object (NameError)
  ```

**Comment by dearblue** [comment]
I tried to fix it as #4933, but @shuujii pointed out a new problem.
https://github.com/mruby/mruby/pull/4933#issuecomment-576067873

Based on that, I discovered and commented on a problem that occurred in mruby binary and will leave it here too.
https://github.com/mruby/mruby/pull/4933#issuecomment-576284995
https://github.com/mruby/mruby/pull/4933#issuecomment-576666008

```ruby
# c.rb
a, b, c = 1, 2, 3
A = -> { b = -2; [a, b, c] }
```

```ruby
# d.rb
a, b = 5, 6
p A.call
p a, b
```

```console
% bin/mrbc c.rb
% bin/mrbc d.rb
% bin/mruby -b -r c.rb d.rb
[5, -2, main]
5
-2
```

This result can also be confirmed at <https://travis-ci.com/dearblue/mruby/jobs/281490648#L1473>.
