### ISSUE TITLE
Multithreaded TCPServer crashes immediately 

### ISSUE THREAD

**Issue by Gundolf68** [mruby/mruby#4949]
I'm running this 

```
server = TCPServer.open(8000)    
loop do                          
	Thread.start(server.accept) do |client|
		client.write "HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\nConnection: close\r\nContent-Length: 11\r\n\r\nHello world"
		client.close                  
	end
end

```

on Ubuntu 18.04. At the first request, the program exits. 
Since I'm new to ruby: Am I doing something wrong or is this a bug?

**Comment by matz** [comment]
The plain mruby does not support `Thread`. You must be using `mruby-thread` gem, and it's far more restricted than `Thread` in CRuby. For example, threads in mruby cannot share objects.

You have to file an issue to https://github.com/mattn/mruby-thread first.

My guess is that it failed to copy the return value from `server.accept` to the child thread.
