### ISSUE TITLE
how spliting utf-8 string?

### ISSUE THREAD

**Issue by 0xtrzy** [mruby/mruby#4967]
How correct this code?
```
#include <mruby.h>
#include <mruby/compile.h>

int main(void)
{
  mrb_state *mrb = mrb_open();
  if (!mrb) { /* handle error */ printf("Nie działa mruby\n"); }
  mrb_load_string(mrb, "p 'żółw'.split('') ");
  mrb_close(mrb);
  return 0;
}
```
How setup default UTF-8 in string? I uncoment in mruby/include/mrbconf.h and type $make

> #define MRB_UTF8_STRING

------

Second

I have trouble with error.

>   mrb_load_string(mrb, "a = 8; b=1; p a / (b-1) ");

How catch error in C code? When in my code are error (any error) my program is hanging

**Comment by matz** [comment]
If you set `MRB_UTF8_STRING`, the result was `["ż", "ó", "ł", "w"]`. Probably it is what you expect.
When an error happens in `mrb_load_string`, `mrb->exc` is not `NULL` (the error object).

**Comment by texrg** [comment]
How setup **MRB_UTF8_STRING** ?
I uncoment this and I have this same error. 

I linking mruby/build/host/lib/libmruby.a 
is possible check corectnes lib? for example nm ./libmruby.a | grep good_string ?

**Comment by matz** [comment]
Edit `include/mrbconf.h` and uncomment `MRB_UTF8_STRING` or add `-DMRB_UTF8_STRING` to `CFLAGS`. It worked on my box (I did the latter). You can find `mrb_utf8_len` in `nm libmruby.a` when your configuration supports UTF-8.

**Comment by matz** [comment]
If any error happens during `mrb_funcall`, it globally exits with the exception. You should wrap your program with a `rescue` statement (in Ruby level) if you want to catch the exception.

**Comment by 0xtrzy** [comment]
Thanks for You reply. 
I'm not thinking about mrb_funcall() but this are very interesting. Can You show me a code? 

the mrb context not working? Whole mruby will be exit?

**Comment by dearblue** [comment]
I uncommented `MRB_UTF8_STRING` in `mrbconf.h` and tried it.
The result is that the string was split as expected.

```console
% rake -m clean all
...snip...
% cc -Iinclude -Lbuild/host/lib xxx.c -lmruby -lm && ./a.out
["ż", "ó", "ł", "w"]
```

**Comment by dearblue** [comment]
@matz
> If any error happens during mrb_funcall, it globally exits with the exception.

`mrb_funcall()` is enclosed by `MRB_TRY ~ MRB_CATCH` in the indirect call `mrb_funcall_with_block()`.
It should not be terminated by the occurrence of an exception.

**Comment by matz** [comment]
@0xtrzy `mrb_funcall` exception handling is not related to utf-8 splitting. So it's not sufficient to discuss here. Submit a new issue.
