### ISSUE TITLE
Cannot call nil.dup/nil.clone

### ISSUE THREAD

**Issue by LanzaSchneider** [mruby/mruby#4974]

**Comment by matz** [comment]
Ruby ISO spec, which mruby conforms, clearly describe:
> If the receiver is an instance of one of the following classes: `NilClass`, `TrueClass`, `FalseClass`, `Integer`, `Float`, or `Symbol`, then raise a direct instance of the class `TypeError`.
But the behavior has changed since 2016 in CRuby.
