### ISSUE TITLE
Which is the preferred implementation of `ecall()` deletion?

### ISSUE THREAD

**Issue by dearblue** [mruby/mruby#4989]
The `ecall()` function is currently in the process of being removed.
The work itself is now roughly in sight.

There are two directions, but which is the preferred implementation for mruby?

 1. One implementation of the C++ exception by GCC, like setjmp/longjmp (sjlj)
 2. One of the C++ exception implementations in GCC, like the exception handler using DWARF.

\# It's a branch of (2), but also includes (1).
\# It's still a work in progress, so there's some doodles left.
https://github.com/mruby/mruby/compare/mruby:master...dearblue:catchtable
(or https://github.com/mruby/mruby/compare/mruby:84aad39...dearblue:1405c2b)

### (1) One implementation of the C++ exception by GCC, like setjmp/longjmp (sjlj)

  - The rescue/ensure handler is reserved in the heap (RAM).
  - I'm wondering how to implement ensure by OP_JMP in a loop (not an immediate thought). 
  - I was going to do this when I commented at #4980.

### (2) One of the C++ exception implementations in GCC, like the exception handler using DWARF.

  - The rescue/ensure handlers are generated at compile time and can be reserved in ROM.
  - The ensure is executed by a jump instruction in a loop (a new instruction `OP_JUW` is added).
  - The `OP_PUSHERR`, `OP_POPERR`, `OP_EPUSH` and `OP_EPOP` instructions are removed.
  - The mruby binary format is extended.
    The position is after the symbol table of the IREP record, but before the children IREPs.

    The data structure will be (2 + 7n) bytes.
    https://github.com/mruby/mruby/commit/76d552789c138b1adc83d47b60a529bbeca5489f#diff-9db60d37b2f9b24669eeff1b28634ab7R39-R44

    ```c
    struct {
      uint8_t len[2];      /* convert to uint16 */
      struct {
        uint8_t type;
        uint8_t start[2];  /* convert to uint16 */
        uint8_t end[2];    /* convert to uint16 */
        uint8_t target[2]; /* convert to uint16 */
      } entries[];
    }
    ```

    Reading is just a simple memcpy or receiving a pointer.
    https://github.com/mruby/mruby/commit/76d552789c138b1adc83d47b60a529bbeca5489f#diff-04323737e1efd784854c30ab83651c9c

**Comment by matz** [comment]
I am not sure I understand thoroughly the second option. But it sounds very interesting.

**Comment by dearblue** [comment]
Here's one URL that I found helpful about the C++ exception mechanism by GCC.

(It's in Japanese)
g++の例外を捕まえよう！！（素手で） - w_o’s diary
https://w0.hatenablog.com/entry/20051104/p1

Also, CRuby now has a catch-table unwind from YARV.
In branch (2), referring to CRuby, `mruby -v` prints `catch type: ~~~` in the bytecode.

```console
% ./bin/mruby -ve 'begin; 1; rescue; 2; ensure; 3; end' | tail -n+15
00001         NODE_BEGIN:
00001           NODE_INT 3 base 10
irep 0x800d52180 nregs=3 nlocals=1 pools=0 syms=1 reps=0 iseq=34
catch type: ensure   begin: 0000 end: 0027 target: 0027
catch type: rescue   begin: 0000 end: 0002 target: 0005
file: -e
    1 000 OP_LOADI_1    R1
    1 002 OP_JMP                027
    1 005 OP_EXCEPT     R1
    1 007 OP_GETCONST   R2      :StandardError
    1 010 OP_RESCUE     R1      R2
    1 013 OP_JMPIF      R2      020
    1 017 OP_JMP                025
    1 020 OP_LOADI_2    R1
    1 022 OP_JMP                027
    1 025 OP_RAISE      R1
    1 027 OP_EXCEPT     R2
    1 029 OP_RAISE      R2
    1 031 OP_RETURN     R1
    1 033 OP_STOP
```

When the specified register is `nil`, `OP_RAISE` was changed to do nothing like `OP_NOP`.

Which instruction raised the exception can be found by doing a linear catch table search on a PC that has already moved to the next instruction.
https://github.com/dearblue/mruby/blob/76d552789c138b1adc83d47b60a529bbeca5489f/src/vm.c#L785-L815

**Comment by matz** [comment]
I don't see `OP_LOADI_3` from the `ensure` clause. But probably I understand the concept.

**Comment by dearblue** [comment]
This is not my intention, but because of my lack of understanding of `codegen()`.
The use of method calls and such as break doesn't seem to be a problem, so it's left alone for now.

**Comment by dearblue** [comment]
I proposed the second as #5060.

Here are the changes:
- The fields for the `catch handler table` have been removed from `struct mrb_irep`.
- A `catch handler` is placed after `iseq`. The `catch handler` starts with `&iseq[ilen]`.
