### ISSUE TITLE
example error detecting

### ISSUE THREAD

**Issue by fab1an2** [mruby/mruby#4991]
```
#include <mruby.h>
#include <mruby/compile.h>

int main(void)
{
  mrb_state *mrb = mrb_open();
  if (!mrb) { printf("Nie działa mruby\n"); }
  mrb_load_string(mrb, "100.times.each{|i| p (1 .0 / rand(10)) } ");
  mrb_close(mrb);
  return 0;
}
```

error is in line **"100.times.each{|i| p (1 .0 / rand(10)) } "** (extra space between 1.0)
How detecting error in function object and in running (divide zero)

I read a mruby code from user. I dont know what user write.

**Comment by matz** [comment]
`mrb->exc` is set after `mrb_load_string`. The return value should be an exception object (or `undef`). See `mrbgems/mruby-bin-mruby/tools/mruby/mruby.c` for example:

```C
    v = mrb_load_string(mrb, str);
    if (mrb->exc) { /* error happens */
      if (!mrb_undef_p(v)) {
        mrb_print_error(mrb); /* print exception object */
      }
      n = EXIT_FAILURE;
    }
```

**Comment by 0xtrzy** [comment]
Thanks for reply @matz but how check error in run separately?

` mrb_funcall(mrb, my_obj, "function", MRB_ARGS_NONE());`
If I load good and without error but next in running?
This are intentions of autors '_How detecting error in function object and in running (divide zero)_'

**Comment by matz** [comment]
Are you asking how to check errors in `mrb_funcal()`? It's the same (if you are at the top-level).
Check `mrb->exc` after calling `mrb_funcall()`.  If you call `mrb_funcall()` from the method, exceptions will jump to the nearest handler (`rescue`).
