### ISSUE TITLE
Are strings passed by reference?

### ISSUE THREAD

**Issue by pulsejet** [mruby/mruby#4994]
I am encountering some strange behavior, where if I pass a string to a function call from an eval call, the string gets garbage collected later. I have a class definition like:
```ruby
class MyClass
  attr_accessor :myval

  def initialize
    @myval = ""
  end

  def v=(str)
    @myval = str
  end
end
```
On running eval with the core gem on an instance `$myclass` as
```ruby
$myclass.v = "abc"
```
I have the string `"abc"` in the `$myclass.myval` but apparently its memory gets garbage collected (and so it becomes garbage) after some time. Is this behavior expected?

**Comment by shuujii** [comment]
If you are trying it with v2.1.0, it may be a fixed issue in master. Could you try it with the master?

**Comment by pulsejet** [comment]
Seems fixed in master, thanks! @shuujii can you point me to the change that might have fixed this for academic purposes?

**Comment by shuujii** [comment]
It was originally working correctly, but I made a wrong optimization at 75949836, so I reverted it at 40b8490f.
