### ISSUE TITLE
Effective ways on running Ruby code from within C without leaking Proc objects?

### ISSUE THREAD

**Issue by RoryO** [mruby/mruby#5001]
Short summary 
===

`mrb_load_string`, related functions and the typical run mruby code from C patterns create an RProc object on every call which is never marked for GC. There's an easy reproduction case with a simple C program

```c
#include "stdio.h"
#include "ext/mruby.h"
#include "ext/mruby/compile.h"
#include "ext/mruby/gc.h"

int main() {
    mrb_state *mrb = mrb_open();
    for(int i = 0; i < 100000; ++i) {
        mrb_load_string(mrb, "nil");
        if(i % 100 == 0) {
            printf("%zi\n", mrb->gc.live);
        }
    }
    
    return 0;
}
```

Longer explanation
===

I'm working on embedding mruby in a GUI. The C portion of program sets up all the initial rendering, then passes control to the mruby VM, then renders the frame after the VM finishes. I call the ruby VM exactly once each frame from C with one entry point. My main program loop looks roughly like

```c
while(!done) {
  setup_frame();
  mrb_load_string(mrb, "World.render");
  render_frame();
}
```

And this works wonderfully! The fast C code path does the intensive graphics calculations and rendering, and I have one entry point which kicks off processing the VM every 'tick' with `World.render` Leaving out a lot of unnecessary surrounding context here to get at the heart of the matter. 

After being so happy for a couple days on how easy this was going I left my program overnight, coming back the program taking up multiple gigabytes of memory where it usually only takes a few hundred kb. Tell tale memory leak of some kind. I did a lot of digging within my own C code as that's the most likely answer and came up with nothing.

Looking at the live object count every frame I noticed the live object count never decreases. I started digging in the Ruby code thinking I created object islands and came up with nothing. Finally I changed my loop to do ` mrb_load_string(mrb, "nil");` and much to my surprise the object count increased linearly infinitely just as before when the mruby VM shouldn't do anything at all!

Digging some more into ObjectSpace while simply calling `nil` every frame I found that `T_PROC` objects grow indefinitely. After a few minutes of running

```ruby
{:TOTAL=>73728, 
:FREE=>206, 
:T_OBJECT=>2, 
:T_CLASS=>59, 
:T_MODULE=>10, 
:T_ICLASS=>14, 
:T_SCLASS=>75, 
:T_PROC=>73285, 
:T_ARRAY=>2, 
:T_HASH=>2, 
:T_STRING=>23, 
:T_EXCEPTION=>2, 
:T_ENV=>44, 
:T_DATA=>3, 23=>1}
```

Looking at the definition of `mrb_load_string` and others related it it's usually the same sequence of function calls: creating a new parser context, parsing the string, generating a proc object, run the code in the vm, free the parser and context. I replicated this replacing `mrb_load_string` in my loop

```c
mrbc_context* ctx = mrbc_context_new(state->ruby_state);
mrb_parser_state *parser = mrb_parse_string(state->ruby_state, "World.render", ctx);
RProc *proc = mrb_generate_code(state->ruby_state, parser);
mrb_value retval = mrb_vm_run(state->ruby_state, proc, mrb_top_self(state->ruby_state), 0);

mrb_pool_close(parser->pool);
mrbc_context_free(state->ruby_state, ctx);
```

And realized there are the infinitely growing Proc objects created. Digging through old issues I had the idea of calling `mrb_gc_arena_save/mrb_gc_arena_restore` before and after the loop... and this works! The object count stabilizes over time. Hurray, problem solved!

However I'm not completely satisfied. Going back to the old 'principle of least surprise' I found it highly surprising that the typical patterns used in functions like `mrb_load_string` leak objects.

Some questions

- It feels like a mistake that functions like `mrb_load_string` and it's relatives leak Proc objects on every call. Should we do a gc save/restore within these functions?
- Is there a better way to invoke a Ruby method from C without creating a new RProc object? 
- Alternately, is there a way we could mark the RProc used for execution as black immediately after running it in the VM so it becomes GC'd next cycle? This feels like it's crossing too many boundaries however.

**Comment by matz** [comment]
It should be GCed. I will investigate.

**Comment by matz** [comment]
Wrap your `mrb_load_string()` by `mrb_gc_arena_save()` and `mrb_gc_arena_restore)`,  i.e.
```C
        mrb_int ai = mrb_gc_arena_save(mrb);
        mrb_load_string(mrb, "nil");
        mrb_gc_arena_restore(mrb, ai);
```
By doing this, you can clear the GC protection from the internally generated proc object. 

First I thought this arena manipulation should be done in `mrb_load_string()` but it could cause another GC bug. So please add the arena save/restore to your code. Thank you.

**Comment by RoryO** [comment]
Thank you! Do you feel it's helpful adding comments in the header file explaining the object leak behavior when using related functions? I will absolutely create a PR for you doing that if you feel so.

**Comment by matz** [comment]
Yes! PR will be **very** helpful.
