### ISSUE TITLE
Creating an mrb_value from a C structure outsid of a contructor

### ISSUE THREAD

**Issue by mdorier** [mruby/mruby#5025]
Hi, I followed a code example [here](https://dev.to/roryo/storing-c-data-in-an-mruby-class-50k4) illustrating how to create a custom datatype associated with a C structure, and define its constructor as well as member functions.

Something I couldn't figure out, however, is how to create an `mrb_value` of an instance of such a class from outside of a constructor, e.g. the C equivalent of the following Ruby function:

```
def f()
  foo = Foo.new
  return foo
end
```

I try something that looks like the following:

```
mrb_value f(mrb_state* mrb, mrb_value self) {
  // ...
  // allocate pointer foo here
  // ...
  mrb_value v;
  mrb_data_init(v, foo, &Foo_type);
  return v;
}
```

But this is giving me segfaults in `mrb_data_init`.
I suppose I need to call `mrb_data_object_alloc`, but this function returns an `RData*`, not an `mrb_value`, and I haven't found any ways of converting the `RData*` into an `mrb_value`.

**Comment by matz** [comment]
To convert `RData*` (or any other subtype of `RBasic*`) to `mrb_value`, use `mrb_obj_value(data)`.

To allocate data object, there are 2 utility macros:
- `Data_Make_Struct` that allocates data structure along with `RData*` object
- `Data_Wrap_Struct` that creates `RData*` wrapping existing data structure
