### ISSUE TITLE
Exposing dependencies between C objects to the garbage collector

### ISSUE THREAD

**Issue by mdorier** [mruby/mruby#5027]
I was wondering if mruby natively had a solution to the following problem:
Imagine two C structures as follows:

```c
struct Foo { ... };
struct Bar {
    struct Foo foo;
}
```
Both have mruby equivalent classes.

An instance of `Bar` is created via `Data_Make_Struct` and exposed to mruby, with a datatype that includes a function for the GC to properly free the instance when it is not referenced anymore. The `Bar` ruby class is given a member function 'foo', programmed in C, acting as an attribute reader to return the `foo` member. The address of this `foo` member is exposed using `Data_Wrap_Struct`. Since it hasn't been allocated by itself, the datatype of the `Foo` class doesn't have a function to free the structure. The GC is not supposed to free the Foo object, it will simply disappear when the enclosing Bar structure is freed. Now consider the following Ruby code:

```ruby
b = Bar.new
f = b.foo
```

All good, until we write those two lines in a function and have this function return `f`. Now the GC may delete `b` (as far as it knows, `b` isn't referenced anywhere anymore), making `f` pointing to some invalid memory.

Is there a way to inform mruby that as long as`f` is referenced, it needs `b` to stay alive?

(In the meantime I'm trying to figure out a workaround with some sort of wrapper structures similar to C++ shared pointers, with a reference count).

**Comment by RoryO** [comment]
It looks to me given this example the C implementation is irrelevant here. If the code was pure Ruby you'd have the same issue. If you also think of it in pure Ruby if `f` belongs to `b` then `b` has an ivar of type `f`. That way when the GC comes for `b` it will also delete `f`. Therefore if `f` depends on `b` it should be contained within `b` as an ivar.

**Comment by dearblue** [comment]
> ```c
>   mrb_iv_set(state, self, mrb_intern_lit("@foo"), foo);
> ```

This serves as a cache for bar object to foo object.

In order to keep a reference from the foo object to the bar object, it is necessary to specify the object is reversed.

```c
mrb_iv_set(state, foo, mrb_intern_lit("@bar"), self);
```

**Comment by RoryO** [comment]
Terribly sorry yes I had the signature backwards.

**Comment by mdorier** [comment]
@RoryO the code you proposed for `Bar_foo` does not quite capture my use-case. In your code, `foo` is an instance variable set in Ruby as a Ruby object, while in my use case, it's a member of the C structure. If I were to use your code, the Bar instance could be cleaned up by the GC, it would not matter for the Foo instance, since all objects in Ruby are related by reference.

Here is an example in Ruby:

```
class Foo
    def initialize
        @x = 42
    end
    attr_reader :x
end

class Bar
    def initialize
        @foo = Foo.new
    end
    def foo
        return @foo
    end
end

def myfunction()
    bar = Bar.new
    p bar
    return b.foo
end

foo = myfunction()
p foo
p foo.x
GC.start
p foo.x
```

In a ruby code, the Foo object could be anywhere in memory, and the Bar object only has a reference to it; foo is not contained within the memory allocated for the Bar object. So when the `bar` object is destroyed by the GC, it doesn't affect `foo`.

**Comment by mdorier** [comment]
I think this solution would work, and is pretty elegant, thanks!

But I don't think the problem would ever occur in pure Ruby, as in Ruby instance variables are references to objects that live somewhere else in memory. There is no risk of invalidating an object's memory by having the GC destroy another object.

**Comment by matz** [comment]
Since `RData` types can have instance variables. So you can protect `Bar` object from GC by referencing it from `Foo` object, e.g.
```C
mrb_iv_set(mrb, foo_obj, mrb_intern_lit("bar"), bar_obj);
```
