### ISSUE TITLE
block_given? returns wrong result for mruby-2.1.2-rc

### ISSUE THREAD

**Issue by katzer** [mruby/mruby#5035]
If you try to yield a code block within `ensure` part,  mruby-2.1.2-rc does not see the block anymore.

`yield` won't work and `block_given?` returns false even a block is given.

Only with `&block` and `block.call` it works like before.

**Comment by dearblue** [comment]
I didn't know the specific code, so when I tried it myself, `yield` worked, but `block_given?` didn't.

```ruby
def f
  p [yield(1, 2), block_given?]

  begin
    p [yield(3, 4), block_given?]
    raise "!"
  rescue
    p [yield(5, 6), block_given?]
  ensure
    p [yield(7, 8), block_given?]
  end
end

f { |a, b| a + b }
```

```console
% mruby-2.1.1/bin/mruby a.rb
[3, true]
[7, true]
[11, true]
[15, true]

% mruby-2.1.2-rc/bin/mruby a.rb
[3, true]
[7, false]
[11, false]
[15, false]

% mruby.git/bin/mruby a.rb
[3, true]
[7, false]
[11, false]
[15, false]
```

**Comment by katzer** [comment]
The code that fails can be seen here: https://github.com/katzer/mruby-ssh/blob/master/test/stream.rb#L27

**Comment by katzer** [comment]
Thanks!
