### ISSUE TITLE
mruby 2.1.1 fails to build on Mac OS X - private method `verbose' called for Rake:Module

### ISSUE THREAD

**Issue by programmingkidx** [mruby/mruby#5043]
I am trying to build mruby 2.1.1 on Mac OS 10.8.5. When I do try to build it I see this error message:

rake aborted!
private method `verbose' called for Rake:Module
/mruby-2.1.1/Rakefile:8
(See full trace by running task with --trace)
make: *** [all] Error 1

This is the line of code that causes the problem:

Rake.verbose(false) if Rake.verbose == Rake::DSL::DEFAULT

**Comment by matz** [comment]
Which version of `rake` (and `ruby`) are you using? Try `rake -V` and `ruby --version`.

**Comment by programmingkidx** [comment]
rake, version 0.8.7
ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin12.0]

**Comment by matz** [comment]
Ah, could you please upgrade? Rake < 1.0 is just too old (Ruby < 2.0 too).

**Comment by programmingkidx** [comment]
Could a test be added that determines if the correct version of Ruby and Rake are being used. A simple message telling the user what requirements are not met would making things more user friendly.
