### ISSUE TITLE
Wrong behavior in `while false`

### ISSUE THREAD

**Issue by kaz0505** [mruby/mruby#5044]
Wrong bytecode is generated in `while false`.

```
begin
  puts "in loop"
end while false
```

In CRuby, it outputs `in loop`, however, not in in mruby.

Generated bytecodes were,

```
    3 000 OP_JMP		012
    2 003 OP_LOADSELF	R1		
    2 005 OP_STRING	R2	L(0)	; "in loop"
    2 008 OP_SEND	R1	:puts	1
    3 012 OP_LOADF	R1		
    3 014 OP_JMPIF	R1	003	
    3 018 OP_LOADNIL	R1		
    3 020 OP_RETURN	R1		
    3 022 OP_STOP
```

thus, `3 000 OP_JMP		012` is not needed.

**Comment by dearblue** [comment]
It seems to be treated as a "while modifier".
As far as I can see `mrbgems/mruby-compiler/core/parse.y`, I probably need a definition for the `begin ~ end while ...` syntax.

**Comment by matz** [comment]
You found that. It's a mruby behavior. According to ISO 12.5

> b) If S is a 《begin-expression》, the behavior is implementation-defined.

So, the current behavior still conforms ISO. Maybe we will change the behavior in the future.

**Comment by matz** [comment]
Maybe we will support this syntax in the near future. Stay tuned.
