### ISSUE TITLE
Introduce malloc_trim on linux to fix dirty page leak

### ISSUE THREAD

**Issue by RoryO** [mruby/mruby#5047]
To begin please understand that mruby is not doing anything incorrectly. There is no issue with the way mruby allocates and releases memory and does not have a memory leak. This is a discussion on using the glibc malloc/realloc/free as default will not return dirty allocated pages back to the kernel managed heap automatically. This issue exists on any dynamic language using glib allocator. 

Summary
===

- The glib allocator doesn't return dirty pages back to the OS heap automatically until the program allocations meet rare conditions
- Calling glib specific `malloc_trim` forces glib allocator to return dirty heap pages
- I propose adding a call to `malloc_trim` on a major GC and as a final step in `mrb_close`
- Asking for advice on the lowest impact way of adding this code

Research
===

Following up on @FooBarWidget [absolutely wonderful research about the glibc allocator](https://www.joyfulbikeshedding.com/blog/2019-03-14-what-causes-ruby-memory-bloat.html) I wanted to test the same with mruby. The short summary from his research is by default glibc `free` does not automatically mark free pages as unused with `madvise` without hitting a frankly absurd page usage threshold. 

This is not a new discovery. It is obscure though discussed elsewhere through the years, and on C Ruby
- https://stackoverflow.com/a/47061458
- https://stackoverflow.com/a/3860495
- https://bugs.ruby-lang.org/issues/15667

We can force marking the free pages by calling the glib specific `malloc_trim`. The results I observed with mruby are the same as presented with C Ruby, which is not a surprise.

Here is what I used for a test program along with a Rake file for automation. First, I built `libmruby.a` from master using defaults, and then `libmruby-gcpatched.a` using this patch. It calls `malloc_trim` on a major GC cycle

```patch
diff --git a/src/gc.c b/src/gc.c
index fd4fb240..8d653dfb 100644
--- a/src/gc.c
+++ b/src/gc.c
@@ -19,6 +19,7 @@
 #include <mruby/gc.h>
 #include <mruby/error.h>
 #include <mruby/throw.h>
+#include <malloc.h>

 /*
   = Tri-color Incremental Garbage Collection
@@ -1314,7 +1315,7 @@ mrb_full_gc(mrb_state *mrb)
     gc->majorgc_old_threshold = gc->live_after_mark/100 * MAJOR_GC_INC_RATIO;
     gc->full = FALSE;
   }
-
+  malloc_trim(0);
   GC_TIME_STOP_AND_REPORT;
 }
```

I also used the [excellent heap analyzer tool](https://github.com/FooBarWidget/heap_dumper_visualizer) from @FooBarWidget, placing `ptmallocdump.c` and `visualize_heap.rb` along side.

```c
// main.c
#include <stdlib.h>
#include <stdint.h>
#include <sys/types.h>
#include <unistd.h>
#include <mruby.h>
#include <mruby/compile.h>
#include <malloc.h>

#include "./ptmallocdump.c"

int main(int argc, char **argv) {
  uint64_t base_address = 0;
  uint64_t pid_offset = 0;
  uint64_t total = 0;
  char cmd[255];
  char buf[255];
  FILE *f;
  struct malloc_state* ptr = 0;
  uint64_t trim = 0;
  memset(cmd, 0, 255);
  memset(buf, 0, 255);
  if(argc > 1 && (strcmp(argv[1], "trim") == 0)) {
    trim = 1;
  }

  // debug libc in a different place depending on platform
  // debian buster kind of hides it in a non obvious location
  // /usr/lib/debug/.build-id/ef/dd27c16f5283e5c53dcbd1bbc3ef136e312d1b.debug
  // use objdump or gdb on libc.so to find the real location
  // these use 2.27 on ubuntu x64, 2.28 on ARM also works so far
  f = popen("objdump -t /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.27.so | grep ' main_arena' | awk '{ print $1 }'", "r");
  while(fgets(buf, sizeof(buf), f) != NULL) {
    base_address = strtoull(buf, 0, 16);
    break;
  }

  memset(buf, 0, 255);
  sprintf(cmd, "grep '/libc-2.27.so$' /proc/%i/maps | grep ' r-xp ' | cut -d- -f 1", getpid());;
  f = popen(cmd, "r");
  while(fgets(buf, sizeof(buf), f) != NULL) {
    pid_offset = strtoull(buf, 0, 16);
    break;
  }

  total = base_address + pid_offset;
  ptr = (struct malloc_state*) total;

  mrb_state *mrb = mrb_open();

  // create a lot of 'heavy' objects, then free half of them
  // we want contigious segments of memory demonstrating how the default glib
  // allocator does not mark empty pages back to the OS without triggering absurdly
  // high thresholds defaults or forcing the allocator using malloc_trim
  mrb_load_string(mrb, "$a = []; $b = []; $c = []; $d = []; 2_500.times { $a.push(Fiber.new {}) }; 2_500.times { $b.push(Fiber.new {})}; 2_500.times { $c.push(Fiber.new {})}; 2_500.times { $d.push(Fiber.new {})}; $b = nil; $d = nil; GC.start;");

  if(trim) {
    malloc_trim(0);
    remove("trimmed.dmp");
    dump_main_heap("trimmed.dmp", ptr);
  }
  else {
    remove("default.dmp");
    dump_main_heap("default.dmp", ptr);
  }


  mrb_close(mrb);
  // chance for viewing mem usage before exit
  getchar();
  printf("exit\n");
  return 0;
}
```

```ruby
task :default do
  sh 'cc -I../mruby/include -lm -g -o unpatched main.c libmruby.a'
  sh 'cc -I../mruby/include -lm -g -o patched main.c libmruby-gcpatched.a'
  rm_rf 'trimmed'
  rm_rf 'default'
  rm_rf 'default-patched'
  mkdir 'trimmed'
  mkdir 'default'
  mkdir 'default-patched'
  sh './unpatched'
  sh './unpatched trim'
  sh 'ruby visualize_heap.rb trimmed.dmp trimmed/'
  sh 'ruby visualize_heap.rb default.dmp default/'
  sh './patched'
  sh 'ruby visualize_heap.rb default.dmp default-patched/'
end
```

It finds the base address of glibc and then finds the base address of the shared glibc within the current program and uses it as the base address of the memory heap. Then, after creating a new `mrb_state`, creates 10,000 empty Fiber objects within the VM, partitioned into four global arrays. Then remove the second and fourth arrays and forcing garbage collection. After, code takes two paths. One is entirely default behavior with no changes from mruby master and then dumps the heap layout. The second when passed a `trim` parameter. When passed `trim` it calls `malloc_trim(0)` before dumping the heap layout. This gives us an indication on how mruby behaves and whether calling `malloc_trim` helps here.

The visualization divides the OS heap pages used by the program. Red dots are usage within the heap page. Grey dots are usage within the heap page marked as 'free, dirty' and not yet reclaimed by the kernel. White is previously allocated dirty pages marked as unused to the kernel.

This is the result of default behavior on a standard Ubuntu 18.04 system

<img width="1289" alt="default" src="https://user-images.githubusercontent.com/19547/88337782-1f6ff300-ccec-11ea-9ee2-11389f79092d.png">

The result of calling `malloc_trim` before dumping the heap.

<img width="1289" alt="malloc-trim" src="https://user-images.githubusercontent.com/19547/88337844-40384880-ccec-11ea-8134-c04e1fc62869.png">

And finally, default behavior with the patch, which calls `malloc_trim` after every major GC cycle.

<img width="1289" alt="patched" src="https://user-images.githubusercontent.com/19547/88337853-44fcfc80-ccec-11ea-8a3e-44edf2c50536.png">

We can also observe this by looking at heap memory usage as reported by the kernel. We can see that the defaults consume 19MB of heap memory reported by the kernel, while calling `malloc_trim` consumes 10mb of memory reported.

Since all of the VM is encapsulated in `mrb_state` we can go further with our research than observing C Ruby's global VM state. Moving the call to `mrb_close` in the above program to right after the `mrb_load_string` call we see some major results, like this

```c
mrb_load_string(mrb, "$a = []; $b = []; $c = []; $d = []; 2_500.times { $a.push(Fiber.new {}) }; 2_500.times { $b.push(Fiber.new {})}; 2_500.times { $c.push(Fiber.new {})}; 2_500.times { $d.push(Fiber.new {})}; $b = nil; $d = nil; GC.start;");
mrb_close(mrb);
```

Calling `mrb_close` on the default path

<img width="1863" alt="clsoe-no-trim" src="https://user-images.githubusercontent.com/19547/88339105-4f1ffa80-ccee-11ea-869e-b177f5c3e0b0.png">

Calling it on the trimmed path

<img width="1863" alt="close-trim" src="https://user-images.githubusercontent.com/19547/88339111-521aeb00-ccee-11ea-8baa-425d98f7634d.png">

Heap difference reported by the kernel.

<img width="696" alt="close-trim-report" src="https://user-images.githubusercontent.com/19547/88339119-56470880-ccee-11ea-8757-0562e635c187.png">

I also replicated all results on the standard Raspberry Pi raspbian distribution. The results are 100% identical, so they're not worth including. It does give more evidence that in Linux systems with more of a focus on low power do not change glib defaults.

For fun I repeated the same experiment except I created 500,000 Fiber objects, then freed all of them using `mrb_close` with and without trim. The results are similar. Even at program exit without calling `malloc_trim` the program consumes 900 mb of memory, whereas calling `malloc_trim` right after `mrb_close` memory usage drops back to 0.3 mb.

<img width="510" alt="high-object-count" src="https://user-images.githubusercontent.com/19547/88338240-ef751f80-ccec-11ea-9032-9fb63c6b6281.png">

(The heap visualizer as it is right now does not function well with this amount of memory usage)

Even after allocating 933MB of memory and marking all of it free, as the `mrb_close` function correctly does, that _still_ does not trigger glibc defaults on marking memory as unused to the kernel! This is a major problem! 

And finally, changing the code for using 4 mrb_states and closing half of them. Given the previous knowledge it also provides a predictable pattern. Changing the test program a bit

```c
mrb_state *states[] = { mrb_open(), mrb_open(), mrb_open(), mrb_open() };

for(uint32_t i = 0; i < 4; ++i) {
  mrb_load_string(states[i], "$a = []; $b = []; $c = []; $d = []; 2_500.times { $a.push(Fiber.new {}) }; 2_500.times { $b.push(Fiber.new {})}; 2_500.times { $c.push(Fiber.new {})}; 2_500.times { $d.push(Fiber.new {})}; $b = nil; $d = nil; GC.start;");
}

mrb_close(states[0]);
mrb_close(states[2]);
```

Full defaults

<img width="1863" alt="state-array-no-trim" src="https://user-images.githubusercontent.com/19547/88338109-ba68cd00-ccec-11ea-80dc-f6f23a676c97.png">

Using `malloc_trim`

<img width="1863" alt="state-array-trim" src="https://user-images.githubusercontent.com/19547/88338151-c9e81600-ccec-11ea-8991-cfe4656ebf9f.png">

Knowing this I tried `mruby-thread`. Because it reads the parent `mrb_state` from the parent thread, copies that state into a child thread, and then deletes the child thread on `join`, the kernel reclaims the memory on joining the child thread.

About the glib defaults. We can control them through [documented parameters](https://www.gnu.org/software/libc/manual/html_node/Malloc-Tunable-Parameters.html#index-M_005fTRIM_005fTHRESHOLD), either through env vars or glibc compile time defines. I followed the research done with C Ruby by setting `M_ARENA_MAX=2` and running the default program. An interesting difference is I do not observe a change in behavior running with that env var set with the default program, the heap output is the same as the default unpatched program. I also don't think it's responsible to make the end user set some obscure system parameters anyway.

It's a common scenario using linux and default glib even for linux systems destined for lower power devices. The default glibc allocator behavior defaults are dramatically out of line for this situation. This situation is obscure enough that I strongly suspect other embedded linux systems do not change any defaults either.

Because of that I feel we should introduce `malloc_trim` into mruby. The conditions for usage are if the compilation target uses glibc and mrb_malloc uses the default glibc allocator. I observed that calling `malloc_trim` after a major GC produces the same results as calling it outside of the VM execution. C Ruby reports the same behavior. I think that calling `malloc_trim` after a full GC is the most appropriate place as I'm not sure what the performance implications are if we call on every mruby page free. Also, because a host program can open and close `mrb_state` at will we should also call `malloc_trim` after freeing all the memory used.

I think the detection should go into the Rake tasks and set a define for the compiler, say `MRB_GLIB_MALLOC_TRIM`, and then within the C code do `#ifdef MRB_GLIB_MALLOC_TRIM` on that. These are simple additions that I will make a PR for. I am providing extensive documentation as to why here. I am also asking if there are ideas for a different way of detecting the environment for glibc and calling from the code.

**Comment by matz** [comment]
Thank you for the report.
I just wonder how much `malloc_trim(0)` affects performance.

**Comment by RoryO** [comment]
That's a great question! My hypothesis is it's imperceptible. If the research on C Ruby is correct calling `malloc_trim` is actually _faster_.

I don't know of a large project with mruby so I used the mrbtest program. I patched `mrb_full_gc` and `mrb_close` to call `malloc_trim` just before returning. I used callgrind for dumping function call weight, and KCachegrind for investigating. With my first analysis I discovered nothing in the the mrbtest causes a full GC cycle! So all of the work is looking at mrbtest with `MRB_GC_STRESS` and `GC_PROFILE` set.

![gc-malloc-trim](https://user-images.githubusercontent.com/19547/88445602-879c0300-cdd8-11ea-92cc-ba22b1c5d121.png)

When looking at call weight, `malloc_trim` is about 0.6% of the total x64 CPU instruction count in the `mrb_full_gc` function. Within malloc_trim are a couple low level kernel calls, `sbrk` and `madvise` (which is what the allocator should be doing anyway).

If we use the GC report time with `GC_PROFILE` and `MRB_GC_STRESS` enabled with the `mrbtest` program, running 5 times sequentially the last entry reported with the`malloc_trim` patch is

```
gc_total_time:         4.27906966209411621094
gc_total_time:         4.29512357711791992188
gc_total_time:         4.27969479560852050781
gc_total_time:         4.30843663215637207031
gc_total_time:         4.30021381378173828125
```

And default master

```
gc_total_time:         4.04845476150512695312
gc_total_time:         4.03771066665649414062
gc_total_time:         4.04702949523925781250
gc_total_time:         4.08767271041870117188
gc_total_time:         4.05192518234252929688
```

Interestingly a ~2% increase of time in conditions where there is a full GC every object allocation, the worst condition.

This is all synthetic in a way. I don't know of any long lived programs for murby I can use. If you do know of something I want to analyze it. My current mruby project is only Windows currently. I'm making it work on linux due to these investigations making me curious, I could use that when I have it working.

**Comment by matz** [comment]
Send us pull-request.

**Comment by RoryO** [comment]
Yes, it is on my list! I became sidetracked getting my mruby project working on Linux first.

Do you agree that a compile time flag is a good solution?

**Comment by matz** [comment]
I think so. We don't use `autoconf` so there's no way to detect `malloc_trim` automagically (no, if I write new `Rakefile` task, it's possible. But it doesn't work for cross-compiling anyway).

**Comment by RoryO** [comment]
I like the simplicity of being away from tools like autoconf. I’ll look at this now.
