### ISSUE TITLE
Question - Is there a module in mruby or third part lib to disassemble bytecode?

### ISSUE THREAD

**Issue by 00Kai0** [mruby/mruby#5054]
Hi @matz , I am learning virtual machine in mruby. Sometimes I want to see assembly instructions from source code, but I don't find a module for it. Like RubyVM::InstructionSequence.disasm() in CRuby or dis.dis() in CPython.
Whether this module already exists, but I didn't find it.
If not, I think I have to try to do it myself.
Waiting for your answer :)

**Comment by matz** [comment]
There's C function named `mrb_codedump_all(mrb, proc)`  to print disasm of the proc.
For the print format, see `mruby -v <your-program>`, e.g:

```
mruby -v -e 'puts "Hello"'                                                                                       ─╯
mruby 2.1.1 (2020-06-04)
00001 NODE_SCOPE:
00001   NODE_BEGIN:
00001     NODE_FCALL:
00001       NODE_SELF
00001       method='puts' (2710)
00001       args:
00001         NODE_STR "Hello" len 5
irep 0x5569c7813da0 nregs=4 nlocals=1 pools=1 syms=1 reps=0 iseq=12
file: -e
    1 000 OP_LOADSELF	R1		
    1 002 OP_STRING	R2	L(0)	; Hello
    1 005 OP_SEND	R1	:puts	1
    1 009 OP_RETURN	R1		
    1 011 OP_STOP

Hello
````
The lines after `irep ...`  are the output from `mrb_codedump_all`.

**Comment by 00Kai0** [comment]
Thanks, it's very useful. I will close this issue.
