### ISSUE TITLE
$-w style globals and symbols raise SyntaxError

### ISSUE THREAD

**Issue by lopopolo** [mruby/mruby#5055]
mruby as of 1517d77e936ed5bbe176eb78c6f3308ef98a6047. mruby built with `rake` and no special flags.

## mruby

```console
$ ./bin/mirb
mirb - Embeddable Interactive Ruby Shell

> $-w
line 1: syntax error, unexpected tIDENTIFIER, expecting $end
> :$-w
line 2: syntax error, unexpected tIDENTIFIER, expecting $end
```

Interstingly, calling `Symbol#inspect` on `:$-w` prints without the wrapping quotes:

```console
$ ./bin/mirb
mirb - Embeddable Interactive Ruby Shell

> :"$-w"
 => :$-w
```

## MRI

```console
$ irb
[2.6.6] > $-w
=> false
[2.6.6] > :$-w
=> :$-w
```

**Comment by matz** [comment]
Those special global variables are not described in ISO spec. So mruby does not support them.
If you really need it, show us your use-case. At the moment, I feel we have a better solution to the issue.
