### ISSUE TITLE
[mruby3] Using `-S` by default in mrbc phase would mess up ecosystem

### ISSUE THREAD

**Issue by udzura** [mruby/mruby#5075]
After https://github.com/mruby/mruby/commit/0049b1e0a4a01a6476c588aeb6e408f1a1f8eb2f, mrbc compiler uses options with `-S` by default.

This structured byte-code has many merits, I guess. But after this change, a lot of mgems (especially ones which of symbols cannot be detected properly) aren't loaded successfully. 

In my trial, mgems such as `mruby-onig-regexp`, `mruby-digest` and `mruby-httpsimpleserver` wouldn't start up.

Can the core team change this feature off by default, or making it pick-able?

DSL idea for example:

```ruby
MRuby::Build.new do |conf|
  conf.mrbc do |mrbc|
    mrbc.use_structured_bytecode = true # false by default
  end
end
```

Consider if you'd like to. Thanks!

**Comment by takahashim** [comment]
How about:

* In `conf.gem`, add an option to use `-S` or not ( like `conf.gem github: 'foo/bar', mrb_format: cstruct` or `mrb_format: bytecode` )
* If there are warnings `undefined symbol` or `no static symbol` in build system, build failed.

**Comment by udzura** [comment]
I'd like to understand about detailed use cases of `-S` format! Maybe one of the important ones is reducing overhead.

Can somebody explain or write docs?

**Comment by matz** [comment]
It reduces RAM consumption by half for many cases. It is a significant effect on micro controllers.

**Comment by matz** [comment]
I change the build process to avoid `-S` for test code. After I checked some gems:

* `mruby-onig-regexp` : OK
* `mruby-digest` : OK
* `mruby-simplehttpserver` : NG because dependent `mruby-r3` does not support `MRB_WORD_BOXING`.

So as far as I checked it's OK to build all gems (except test code) using `-S`. Any opinon?

**Comment by udzura** [comment]
Thanks for your investigation!
I'm going to check my codes (on book "mruby systems programming": https://www.amazon.co.jp/dp/4863543298/) using current mruby3 branch!

**Comment by matz** [comment]
I consider this is covered by 5b40bb8d159c1432bb87973b2b5f42473dd0c623. Reopen if you find any problem.

**Comment by udzura** [comment]
Still some of mgems cannot be built...
e.g. https://github.com/matsumotory/mruby-mrbgem-template seems not to be successful

```console
./mruby/bin/mruby "/private/tmp/mrbgem-template-20201018-16393-ehufnu/mruby-mrbgem-template-0.2.1/template_config.rb"
undefined method 'AF_MAX' for class OptionParser (NameError)
rake aborted!
```

**Comment by matz** [comment]
* Non core gems use traditional mrb dump by default
* Unless it specifies `spec.cdump` which is available since `mruby3`
