### ISSUE TITLE
[RFC] Support startless/endless `Range` (`N..`, `..N`)

### ISSUE THREAD

**Issue by wataash** [mruby/mruby#5085]
This RFC proposes:

1. Let mruby follow the Ruby's behavior of `Range` with `nil` argument:

```rb
                                # ruby 2.7.1p83   mruby-latest (2020-09-19)
puts(Range.new(1, 2))           # 1..2            1..2
puts(Range.new(1, nil))         # 1..             mruby: bad value for range (ArgumentError)
puts(Range.new(nil, 2))         # ..2             mruby: undefined method '<=>' (NoMethodError)
puts(Range.new(nil, nil))       # .. (!)          mruby: undefined method '<=>' (NoMethodError)

puts(Range.new(1, 2, true))     # 1...2           1...2
puts(Range.new(1, nil, true))   # 1...            mruby: bad value for range (ArgumentError)
puts(Range.new(nil, 2, true))   # ...2            mruby: undefined method '<=>' (NoMethodError)
puts(Range.new(nil, nil, true)) # ... (!)         mruby: undefined method '<=>' (NoMethodError)
```

Japanese Industrial Standards (JIS) X3017:2013 (which is equivalent to ISO/IEC 30170:2012) _5.2.14 Range_ section doesn't define this behavior.

2. If 1. is accepted, implement the startless/endless `Range` literal.

```rb
            # ruby 2.7.1p83                 mruby-latest (2020-09-19)
puts(1..2)  # 1..2                          1..2
puts(1..)   # 1..                           syntax error, unexpected ')'
puts(..2)   # ..2                           syntax error, unexpected tDOT2, expecting ')'
puts(1...2) # 1...2                         1..2
puts(1...)  # 1...                          syntax error, unexpected ')'
puts(...2)  # ...2                          syntax error, unexpected tDOT2, expecting ')'

# just for reference:
puts(..)    # syntax error, unexpected ')'  syntax error, unexpected tDOT2, expecting ')'
puts(...)   # unexpected ...                unexpected argument forwarding ...
```

Though startless/endless syntax is *NOT* allowed in JIS X3017:2013.

## Why?

Just to mitigate the cost of Ruby->mruby porting. Currently we have to do the following conversions:

- `arr[1..]` -> `arr[1..-1]`
- `arr[..2]` -> `arr[0..2]`

As my personal opinion, implementing this RFC could be accepted because it doesn't much increase the complexity of sources (just adding about 10 lines?).

## References

- https://bugs.ruby-lang.org/issues/12912
- https://bugs.ruby-lang.org/issues/14799

**Comment by matz** [comment]
Accepted. I have a plan to support these features. But the priority was low.
