### ISSUE TITLE
Build system compatibility

### ISSUE THREAD

**Issue by shuujii** [mruby/mruby#5096]
### Default build configuration file

It seems that default build configuration file has changed from `MRUBY_ROOT/build_config.rb` to `MRUBY_ROOT/target/host.rb`, but I think this is unnecessary incompatibility and has a large impact.

For compatibility, I think it's better to use `MRUBY_ROOT/build_config.rb` if it exits when `MRUBY_CONFIG` or `MRUBY_TARGET` is not specified.

### `enable_debug` and `enable_test`

`enable_debug` and `enable_test` were not specified in `host` target in mruby2's default build configuration file, but they are specified in mruby3's default build configuration file. I think it is better not to specify these for the following reasons.

* `enable_debug` is turned off at #4045.
* Since default configurations are used in `ruby-build` etc., it is better not to have unnecessary options.
* `target/host-debug.rb` can be used for debugging. We may prepare `target/host-test.rb` for testing.

### The term "target"

I think the term "target" has been used mainly for things that can be obtained by `MRuby.each_target` and `MRuby.targets` (instance name of `MRuby::Build`). However, `MRUBY_TARGET` is used as name of build configuration file, which is a bit confusing.

Especially the following points are confusing.

* Multiple `MRuby::Build` instances can be specified in the build configuration file, so there is no one-to-one connection with `MRUBY_TARGET`.
* The required name `host` as instance name of `MRuby::Build` is the same as default value for `MRUBY_TARGET`.

**Comment by matz** [comment]
`enable_debug` was turned off by default by 3c55cb0. `enable_test` was kept as it was turned on by default in mruby2's `build_config.rb`.
Regarding the term "target", I have no strong opinion. Do you have any idea? "config"? "build"?

**Comment by shuujii** [comment]
> `enable_debug` was turned off by default by [3c55cb0](https://github.com/mruby/mruby/commit/3c55cb089514d40ff17e9f29f9195c85111e0c10). `enable_test` was kept as it was turned on by default in mruby2's `build_config.rb`.
> Regarding the term "target", I have no strong opinion. Do you have any idea? "config"? "build"?

**Comment by shuujii** [comment]
I'm sorry, I made a wrong comment and closed this issue. I will comment again later.

**Comment by shuujii** [comment]
> `enable_test` was kept as it was turned on by default in mruby2's `build_config.rb`.

`enable_test` was turned on in the `test` target, but off in the `host` target.

**Comment by shuujii** [comment]
> Regarding the term "target", I have no strong opinion. Do you have any idea? "config"? "build"?

I wish there was a good term to replace `MRUBY_TARGET`, but I can't think of it.

However, I don't think it is necessary to introduce a new mechanism because the `MRUBY_TARGET` mechanism can be realized by the existing mechanism in the first place.

For example, I think the following two have almost the same meaning and ease of use.

```console
$ rake MRUBY_TARGET=boxing
```
```console
$ rake MRUBY_CONFIG=target/boxing.rb
```

And to avoid the term "target", the `target/` directory should be changed to `build_config/` and so on.

**Comment by shuujii** [comment]
> It seems that default build configuration file has changed from MRUBY_ROOT/build_config.rb to MRUBY_ROOT/target/host.rb

In explanation of mruby, the expression `build_config.rb` is frequently used including official documents, so I think that it will not make sense if the file is no longer used.

The `MRUBY_TARGET` mechanism seems to have little improvement, so I don't think it should be changed to avoid unnecessary confusion.

> ```console
> $ rake MRUBY_TARGET=boxing
> ```
> ```console
> $ rake MRUBY_CONFIG=target/boxing.rb
> ```

If this difference is also unacceptable, you can change it to use `build_config/${MRUBY_CONFIG}.rb` if the path specified in `MRUBY_CONFIG` does not exist.

I will create a PR in this direction later.

**Comment by matz** [comment]
#5098 was merged.
