### ISSUE TITLE
iso c99 error

### ISSUE THREAD

**Issue by 0xtrzy** [mruby/mruby#5107]
```bash
In file included from /home/user/mruby-3.0.0/include/mruby/value.h:168,
                 from /home/user/mruby-3.0.0/include/mruby.h:90,
                 from edi.c:10:
/home/user/mruby-3.0.0/include/mruby/boxing_word.h:84:4: error: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
   84 |   };
      |    ^
In file included from edi.c:10:
/home/user/mruby-3.0.0/include/mruby.h:72:38: error: ISO C99 does not support ‘_Static_assert’ [-Wpedantic]
   72 | # define mrb_static_assert(exp, str) _Static_assert(exp, str)
      |                                      ^~~~~~~~~~~~~~
/home/user/mruby-3.0.0/include/mruby/array.h:29:1: note: in expansion of macro ‘mrb_static_assert’
   29 | mrb_static_assert(MRB_ARY_EMBED_LEN_MAX > 0, "MRB_ARY_EMBED_LEN_MAX > 0");
      | ^~~~~~~~~~~~~~~~~

```

i use -Wpedantic and get this trouble, with old 2.1.0 all working ok.

**Comment by matz** [comment]
I tried to fix this issue, but
* the former could cause source incompatibility which is worse than conforming `-Wpedantic`.
* the latter disables `_Static_assert()` which is very useful.e
* we will get so many warnings from `vm.c`
* and `__FUNCTION__` which is used in `gem_init.c` would be disabled too.
So I gave up `-Wpedantic` until we find a way to distinguish warning level in compile time.

I fixed a few harmless warnings.

**Comment by dearblue** [comment]
When compiling with `gcc -Wpedantic`, the warning disappeared by making the following settings.

  - Specify `conf.cc.flags << "-std=c11"`.
    This is because of "support unnamed structs/unions" and `_Static_assert()`.
  - Specify `conf.cc.defines << "MRB_DISABLE_DIRECT_THREADING"`.
  - Specify `conf.cc.defines << "__FUNCTION__=__func__"`.

When compiling with clang, `build/presym.h` warned me, so I needed` conf.cc.flags << "-Wno-newline-eof" `.

Finally, compared to `-std = gnuXX`,` -std = cXX` seems to define a `__STRICT_ANSI__` macro constant (both gcc and clang).
Therefore, if `-std=c11` is specified, it seems that the preprocessor can branch.

```console
% diff -u <(echo | gcc -E -dM -std=gnu11 -o- - | sort) <(echo | gcc -E -dM -std=c11 -o- - | sort)
--- /tmp/zshAMVYAW      2020-11-03 14:51:49.810327000 +0900
+++ /tmp/zshuDkCHF      2020-11-03 14:51:49.828562000 +0900
@@ -284,6 +284,7 @@
 #define __STDC_UTF_16__ 1
 #define __STDC_UTF_32__ 1
 #define __STDC_VERSION__ 201112L
+#define __STRICT_ANSI__ 1
 #define __UINT_FAST16_MAX__ 0xffffffffU
 #define __UINT_FAST16_TYPE__ unsigned int
 #define __UINT_FAST32_MAX__ 0xffffffffU
@@ -332,4 +333,3 @@
 #define __x86_64 1
 #define __x86_64__ 1
 #define _LP64 1
-#define unix 1
```

**Comment by matz** [comment]
Both `-std=c99` and `-std=gnu99` warn on `_Static_assert()` with `-Wpedantic` so `__STRICT_ANSI__` does not help us.
I replaced `__FUNCTION__` with C99 conforming `__func__`.
