### ISSUE TITLE
mruby-io doesn't work in process started as Windows service

### ISSUE THREAD

**Issue by kou** [mruby/mruby#5114]
#4968 added file descriptor check in `IO#initialize`.
It raises an exception at `IO.open(0, "r")` https://github.com/mruby/mruby/blob/master/mrbgems/mruby-io/mrblib/io.rb#L363 when a process is started as Windows service. Because a process started as Windows service doesn't have a valid standard input. `fstat(0, buf)` returns non-zero.

Here are solutions I think:

  1. Don't check file descriptor for `0`, `1` and `2`.
  2. Open an internal pipe for `0`, `1` and `2` when they are invalid.

Which solution do you like?

I think that 1. is enough.

FYI: CRuby uses 2.: `fill_standard_fds()` https://github.com/ruby/ruby/blob/master/ruby.c#L2556-L2584

**Comment by matz** [comment]
I agree that (1) is sufficient. Could you prepare a pull-request? Or shall I work on it?

**Comment by kou** [comment]
OK. I'll do it.

**Comment by matz** [comment]
Hmm. Are you going to make a pull-request from the above commit? Or shall I merge it?

**Comment by kou** [comment]
Sorry for not sharing the status of the commit.
I don't have an environment that can reproduce this problem. I need to ask our customer to confirm the commit fixes this problem.
It'll be done in a few days.

But the patch is simple and it'll fix this problem. So we can merge it without waiting the confirmation. (I'll share the result of the confirmation later.)
I've opened #5119.

**Comment by kou** [comment]
We've confirmed that #5119 this problem.

**Comment by matz** [comment]
Does this fix migw crash issue?

**Comment by kou** [comment]
I think that this is unrelated to the MinGW crash issue.
But I don't know why the issue was occurred and fixed...
