### ISSUE TITLE
[build error] aarch64-linux-android-ld: -Wl,-rpath=/data/data/com.termux/files/usr/lib: unknown option.

### ISSUE THREAD

**Issue by kcubeterm** [mruby/mruby#5123]
Trying to building mruby for termux,, i encountered this error with android toolchain.

```
aarch64-linux-android-ld: -Wl,-rpath=/data/data/com.termux/files/usr/lib: unknown option
aarch64-linux-android-ld: use the --help option for usage information
aarch64-linux-android-ld: -Wl,-rpath=/data/data/com.termux/files/usr/lib: unknown option
aarch64-linux-android-ld: use the --help option for usage information

```
After researching, I found using cooma instead of = can solve error with rpath argument,but how I specify that things I didn't find such options in Rakefile.

**Comment by matz** [comment]
Could you show us your build_config script? None of bundled build_config script for Android uses `-Wl,`.

**Comment by kcubeterm** [comment]
Ah, that is used by termux build system. [Refrence](https://github.com/termux/termux-packages/blob/5c4598faafa0fc8acf55c205c9db026398b73bc8/scripts/build/termux_step_setup_toolchain.sh#L27)
Thanks for quick reply.

**Comment by matz** [comment]
Can I close the issue as the third-party (termux) issue?
