### ISSUE TITLE
MinGW on GitHub Actions sometimes fail

### ISSUE THREAD

**Issue by shuujii** [mruby/mruby#5133]
MinGW on GitHub Actions sometimes fails, what is the cause? 

The changes in mruby3 are having an effect on it because it never failed until the mruby3 branch was merged, I think.

**Comment by matz** [comment]
We have noticed the crash problem. Have no time to investigate it yet.

**Comment by matz** [comment]
Using `__builtin_setjmp()` and `__builtin_longjmp()` on MinGW seems to stop the accidental crash.
