### ISSUE TITLE
Possible NULL pointer dereference in mrb_proc_parameters

### ISSUE THREAD

**Issue by hifoolno** [mruby/mruby#5140]
https://github.com/mruby/mruby/blob/68cebb63314f10171fd21c5adde31415155bc748/mrbgems/mruby-proc-ext/src/proc.c#L106-L118

Hello, I am a little confused. Do you think there is a possible NULL pointer dereference in `mrb_proc_parameters()` in mrbgems/mruby-proc-ext/src/proc.c and need to check if `proc` is `NULL` before `MRB_PROC_CFUNC_P(proc)`？

Looking forward to your reply~

**Comment by matz** [comment]
I don't think so. The `proc` is retrieved from the receiver (`self`), and you can assume it is not `NULL`.
