### ISSUE TITLE
`presym` files under gem directories

### ISSUE THREAD

**Issue by shuujii** [mruby/mruby#5151]
Currently, `presym` file is only output to `build` directory. However, `psfiles` in `Rakefile` also includes `presym` files under gem directories.

https://github.com/mruby/mruby/blob/5dc9a8249fc92de089627cad17b5d5b7a5f0a505/Rakefile#L104

Are these `presym` files supposed to be created manually, for example for dynamically interned symbols?

**Comment by matz** [comment]
It is supposed to be created manually. It's to specify symbols that cannot be found by the scanner in `Rakefile`. If symbol scanning using `mrbc`, those `presym` files will be obsolete.
