### ISSUE TITLE
`MRB_ENABLE_` -> `MRB_USE_` and `MRB_DISABLE_` -> `MRB_NO_`?

### ISSUE THREAD

**Issue by shuujii** [mruby/mruby#5163]
Some macro names in `mrbconf.h` have been unified to use `MRB_USE_` or `MRB_NO_`. So should we change `MRB_ENABLE_` and `MRB_DISABLE_` to `MRB_USE_` and` MRB_NO_`, respectively?

**Comment by matz** [comment]
Agreed, as far as we provide a migration path. People who have already define `MRB_ENABLE_` should not face any error.

**Comment by shuujii** [comment]
Okey then, I will create pull-request later.

**Comment by takahashim** [comment]
@shuujii Why introduce such incompatible changes?

**Comment by matz** [comment]
The old configuration should work with compatible definitions in `mrbconf.h`. If it doesn't it's a bug.

**Comment by shuujii** [comment]
> Why introduce such incompatible changes?

I have no intention of breaking compatibility. Feel free to report any problems other than #5187.
