### ISSUE TITLE
optcarrot does not work on mruby master

### ISSUE THREAD

**Issue by mame** [mruby/mruby#5192]
The current master (6dedd6a940194881c3b66124ff277c4cb14d08bd) fails to run [optcarrot](https://github.com/mame/optcarrot/) as follows:

```
root@e46d3b702d39:~# mruby/bin/mruby --version && mruby/bin/mruby tools/shim.rb --benchmark
mruby 3.0.0preview (2020-10-16)
[shim] Array#flat_map
[shim] Hash#compare_by_identity
[shim] String#b
[shim] String#sum
[shim] String#%
[shim] Fixnum#[]
[shim] Fixnum#even?
[shim] Kernel#__dir__
[shim] Kernel#require
[shim] Kernel#require_relative
[shim] File.binread (by using open)
[shim] Process.clock_gettime for mruby (MRB_WITHOUT_FLOAT)
[shim] Module#module_function
trace (most recent call last):
        [9] tools/shim.rb:433
        [8] (eval):4:in eval
        [7] tools/shim.rb:280:in require_relative
        [6] tools/shim.rb:269:in require
        [5] ./lib/optcarrot.rb:11:in eval
        [4] tools/shim.rb:280:in require_relative
        [3] tools/shim.rb:269:in require
        [2] ./lib/optcarrot/ppu.rb:3:in eval
        [1] ./lib/optcarrot/ppu.rb:5
./lib/optcarrot/ppu.rb:223: '@all?' is not allowed as an instance variable name (NameError)
```

There is no instance variable named `@all?` in optcarrot. By tweaking code, I see other exception like `./lib/optcarrot/cpu.rb:144: 'ord' is not allowed as an instance variable name (NameError)`. So, I guess that mruby has a bug in handling symbols and/or GC.

How to reproduce:

1. compile mruby with [this config](https://github.com/mame/optcarrot/blob/master/tools/mruby_optcarrot_config.rb).
2. `git clone https://github.com/mame/optcarrot.git` and then run `/path/to/mruby/bin/mruby tools/shim.rb --benchmark`

**Comment by matz** [comment]
After applying 63d4e8e, the result become:

```
[shim] Array#flat_map
[shim] Hash#compare_by_identity
[shim] String#b
[shim] String#sum
[shim] String#%
[shim] Fixnum#[]
[shim] Fixnum#even?
[shim] Kernel#__dir__
[shim] Kernel#require
[shim] Kernel#require_relative
[shim] File.binread (by using open)
[shim] Process.clock_gettime for mruby (MRB_WITHOUT_FLOAT)
[shim] Module#module_function
[FATAL] ROM file is not given
```

With adding `mruby-exit` to `optcarrot.rb`. Is this correct behavior?

**Comment by mame** [comment]
> Is this correct behavior?

I think so. I'll give it a try again later. Thank you very much!
