### ISSUE TITLE
Linker options when building gem's binary commands

### ISSUE THREAD

**Issue by shuujii** [mruby/mruby#5210]
When gem's binary commands are built, all gem's linker options are specified as below. What is the intent of this?

https://github.com/mruby/mruby/blob/f6ad16384146afa7ec875697c80e200c23cb5b12/Rakefile#L71-L82

I think they may not build as intended if other gem's linker options are specified. For example, the following example cannot be built on Mac because an unintended library is linked.

  ```ruby
  # mruby-foo/mrbgem.rb
  MRuby::Gem::Specification.new('mruby-foo') do |spec|
    spec.license = 'MIT'
    spec.author  = 'mruby developers'
    spec.summary = 'example'
    spec.bins << "foo"
    spec.linker.library_paths << "/usr/lib"
  end
  ```

  ```c
  // mruby-foo/tools/foo/main.c
  int main(){return 0;}
  ```

  ```ruby
  # config.rb
  MRuby::Lockfile.disable
  MRuby::Build.new() do |conf|
    conf.toolchain :clang
    conf.gem path: "mruby-foo"
    conf.gem core: "mruby-bin-mirb"
    conf.enable_debug
  end
  ```

  ```console
  $ rake CONFIG=config.rb -mv
  (snip)
  LD    build/host/bin/mirb
  clang -L/usr/lib -L/usr/local/lib -o "/mruby/build/host/bin/mirb" "/mruby/build/host/mrbgems/mruby-bin-mirb/tools/mirb/mirb.o" "/mruby/build/host/lib/libmruby.a"  -lm -lreadline -lncurses
  Undefined symbols for architecture x86_64:
    "_rl_free", referenced from:
        _main in mirb.o
  ld: symbol(s) not found for architecture x86_64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  rake aborted!
  ```

**Comment by shuujii** [comment]
It may not be good to specify linker options of gems that don't depend on itself because I think that linker options of dependent gems must be specified.

**Comment by matz** [comment]
Hmm, probably we have to distinguish linker options from binary gems and options from library gems. The former should be specific to the binary (`foo` and `mirb`) for the above example. The latter should be included in global linker options and should be printed from `mruby-config --ldflags`. It's harder than I first think. Maybe we should dispatch according to `gem.bin` contents.
