### ISSUE TITLE
Automatic creation of the `host` build in cross-compilation

### ISSUE THREAD

**Issue by shuujii** [mruby/mruby#5213]
From mruby3, if there is no the `host` build when cross-compiling, it will be created automatically. Is this feature necessary?

I'd like to be able to specify pre-built `mrbc` in the future as shown in https://github.com/mruby/mruby/pull/5084#issuecomment-722191466, and then this feature will hinder because the `host` build is unnecessary if pre-built `mrbc` is specified.

I think it's possible not to create the `host` build if pre-built `mrbc` is specified, but to do that, `super` must be called before the `host` build is created in the following. Is this change acceptable?

https://github.com/mruby/mruby/blob/6e5a0f623fdc848339ce33091b7857c57ba238c7/lib/mruby/build.rb#L392-L408

**Comment by matz** [comment]
It's intentinally for cross-compiling. Cross compiler requires `mrbc` runs on the host.

**Comment by shuujii** [comment]
The `host` build is currently required, but I think it will be unnecessary once pre-built `mrbc` can be specified.

**Comment by matz** [comment]
Agreed.
