### ISSUE TITLE
Missing HTTPS on mruby link

### ISSUE THREAD

**Issue by jbampton** [mruby/mruby#5240]
<img width="1035" alt="Screen Shot 2020-12-21 at 8 12 16 pm" src="https://user-images.githubusercontent.com/418747/102765964-1bdeb600-43c9-11eb-8aea-3a421ff3aab7.png">

**Comment by matz** [comment]
Fixed. But it's redirected to http anyway.

**Comment by jbampton** [comment]
Hey @matz set the link to `https://mruby.org/` it will work 👍

**Comment by Hir0** [comment]
I think we need to enforce https on at mruby.github.io setting’s Github Pages to redirect https.
But some error message are shown and can't activate. Something wrong ?
