### ISSUE TITLE
Passing arguments to a method with `MRB_ARGS_NONE` does not raise an error

### ISSUE THREAD

**Issue by shuujii** [mruby/mruby#5257]
#### Before 397b0057

```console
$ bin/mruby -e 'p to_s(1)'
trace (most recent call last):
-e:1: 'to_s': wrong number of arguments (1 for 0) (ArgumentError)
```

#### After 397b0057

```console
$ bin/mruby -e 'p to_s(1)'
"main"
```

It seems that `MRB_METHOD_NOARG_FL` is not saved when registering to the method table in `mrb_define_method_raw`.

**Comment by matz** [comment]
Indeed! I need to think of the idea for room to preserve `MRB_METHOD_NOARG` info.

**Comment by dearblue** [comment]
How about adding a bitmap to `struct mt_tbl`?

```c
/* src/class.c */

/* method table structure */
typedef struct mt_tbl {
  size_t size;
  size_t alloc;
  struct mt_elem *table;
  uintptr_t *bitmap_noargs; // ⬅ NEW!
} mt_tbl;
```

**Comment by matz** [comment]
I am trying to pack symbols in 30 bits so that we can save `ARGS_NONE` info can be saved in `mt_elem`.

**Comment by shuujii** [comment]
IMHO, I don't think inline symbols are often used when presym is enabled, so it feels like they don't have to.
