### ISSUE TITLE
`.quo` behavior differs from Ruby

### ISSUE THREAD

**Issue by niconii** [mruby/mruby#5268]
| Expression     | ruby  | mruby                                         |
| -------------- | ----- | --------------------------------------------- |
| `6   .quo 5`   | (6/5) | 1                                             |
| `6   .quo 5.0` | 1.2   | 1                                             |
| `6   .quo 5r`  | (6/5) | can't convert Rational to Integer (TypeError) |
| `6.0 .quo 5`   | 1.2   | 1.2                                           |
| `6.0 .quo 5.0` | 1.2   | 1.2                                           |
| `6.0 .quo 5r`  | 1.2   | non float value (TypeError)                   |
| `6r  .quo 5`   | (6/5) | undefined method 'quo' (NoMethodError)        |
| `6r  .quo 5.0` | 1.2   | undefined method 'quo' (NoMethodError)        |
| `6r  .quo 5r`  | (6/5) | undefined method 'quo' (NoMethodError)        |

In the API docs of both Ruby and mruby, the `.quo` method is described as returning the "most exact division". For Ruby, this makes sense. However, in mruby, `.quo` may be less exact than `/`, because `6.quo(5.0) == 1` but `6 / 5.0 == 1.2`.

**Comment by matz** [comment]
Thank you for the report.  I will fix this issue. But since rational is not built-in to `mruby`, `6.quo(5)` and `6.quo(5r)` would be `1.2` not `(6/5)`. That will be `mruby` limitation.
