### ISSUE TITLE
Getting "too many nested blocks/methods" error when building mruby-specinfra gem

### ISSUE THREAD

**Issue by shuujii** [mruby/mruby#5310]
Getting the following error when building [mruby-specinfra](https://github.com/itamae-kitchen/mruby-specinfra) gem.

```console
codegen error:/mruby/build/repos/host/mruby-specinfra/mrblib/specinfra/version.rb:8: too many nested blocks/methods
```

**Comment by matz** [comment]
`mruby-specinfra` defines more than 500 classes/modules inside. It's far beyond the limitation after byte-wise instructions introduced.
