### ISSUE TITLE
error: ISO C99 doesn’t support unnamed

### ISSUE THREAD

**Issue by ojej** [mruby/mruby#5354]
````
~/mruby/include/mruby/boxing_word.h:84:4: error: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
   84 |   };
      |    ^
````

Please change this for -std=c99

**Comment by matz** [comment]
Out of curiosity, why do you want to use `-std=c99` instead of `-std=gnu99`? Is there any particular reason?

**Comment by ojej** [comment]
reason: embeded in microcontroler

**Comment by matz** [comment]
Do you mean there's C compiler for microcontrollers that does support only C99?

**Comment by ojej** [comment]
yes, and old compilers on unix not linux

**Comment by matz** [comment]
Thank you. May I ask the name of the controller? Just for curiosity.
