### ISSUE TITLE
static warning

### ISSUE THREAD

**Issue by ojej** [mruby/mruby#5358]
> /usr/bin/ld: ~/mruby/build/host/lib/libmruby.a(file.o): in function `mrb_file__gethome':
> ~/mruby-3.0.0/mrbgems/mruby-io/src/file.c:362: warning: Using 'getpwnam' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
> 

linux fedora

**Comment by matz** [comment]
I need more information to reproduce the issue. As far as I can tell from the warning message, your operating system does not allow static link of `getpanam`. Google told me rebuilding glibc with `--enable-static-ns` would resolve the issue.
I don't think there's any workaround except for rebuilding glibc or avoiding `mruby-io` gem.

**Comment by ojej** [comment]
simple i download mruby (3) compile it normal make
and compiling with -static

`gcc -W -Wall -O0 -std=c11 -pedantic -pedantic-errors -static -I ~/mruby/include/ nice.o superhiper.o ~/mruby/build/host/lib/libmruby.a -o my_prog -lm`

nothing more. Meybe add options to build specific mruby-static lib?

**Comment by matz** [comment]
As I told you, it's caused by Fedora's glibc configuration. Ubuntu uses the same configuration. I don't think I can fix it by mruby side. Please follow the instruction in the warning message.

**Comment by mix127** [comment]
I have similar problem.
Is possible setup mruby to remove  **mrb_file__gethom** function?

**Comment by dearblue** [comment]
It is possible to remove the `mrb_file__gethome()` function if understanding that the `File.expand_path` method will not be available.

But I question that is really necessary.

The fedora and RedHat documentation clearly states that they do not support static linking with the GNU C Library (glibc).

  - https://fedoraproject.org/wiki/C_and_C%2B%2B_v2#Static_Linking
  - https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/html/developing_c_and_cpp_applications_in_rhel_8/creating-c-or-cpp-applications_developing-applications#static-and-dynamic-linking_using-libraries-with-gcc

Is a static link to glibc really necessary?
Shouldn't the application just provide a dummy `getpwnam()` function?

**Comment by mix127** [comment]
> Is a static link to glibc really necessary?

mruby is beautiful precisely because you can turn off many things.
having a configuration that could not touch files, create directories and even read files is more secure. 
I think static linking is needed (for example, for me) for embedded projects (also concerning hardware)

Yes! please be able to cut out some functions or replace them with something that works statically (such as getenv() )

**Comment by matz** [comment]
`File._gethome` updated. Define `MRB_IO_NO_PWNAM` if it's not available on your platform.
