### ISSUE TITLE
Bignum literals result in codegen failures with mruby 3.0.0

### ISSUE THREAD

**Issue by lopopolo** [mruby/mruby#5376]
This code fails parsing in mruby 3.0.0, which is a regression from mruby 2.1.2.:

```ruby
0x8000_0000_0000_0000
```

## 3.0.0

```console
$ ./bin/mruby -e 'puts 0x8000_0000_0000_0000'
codegen error:-e:1: integer overflow
```

## 2.1.2

```console
$ ./bin/mruby -e 'puts 0x8000_0000_0000_0000'
9.223372036854776e+18
```

This looks to be caused by this change to codegen which aborts on an integer overflow: https://github.com/mruby/mruby/commit/68cebb63314f10171fd21c5adde31415155bc748.

I would like to support `Bignum` with mruby and am also OK with integer overflow being promoted to a float. Is it possible to add a more permissive codegen behind a compiler flag?

**Comment by lopopolo** [comment]
This codegen error prevents mruby 3.0.0 from loading `MSpec`.

**Comment by matz** [comment]
I have a plan to support `Bignum` in mruby. I will fix the codegen soon.
