### ISSUE TITLE
まつもと　ゆきひろ　さんへ

### ISSUE THREAD

**Issue by takuyatahata** [mruby/mruby#5380]
@matz 
練馬区の創価学会員の田畑拓也といいます。
rubyが宗教法人日連正宗の慧妙のウェブサイトで使われているのですが、Shift-jisとUTF-８以外の文字が対応していなくて漢字や梵字が文字化けするんじゃないでしょうか？

**Comment by matz** [comment]
* ここはmrubyについてのレポートを受ける場所です(**この質問に適切な場所ではありません**)
* mrubyはUTF-8しか対応していません
* Ruby(CRuby)はUTF-8以外にもいろいろな文字コードに対応しています
* 「漢字や梵字が文字化けする」かどうかは、そのサイトの作りとブラウザの文字対応に依存します。**Rubyだから文字化けする**ということはほとんどないのではないかと思います。

**Comment by takuyatahata** [comment]
@matz 
失礼いたしました。
適当な連絡場所はどちらにございますか？

**Comment by matz** [comment]
正直、今回のレポートは技術的に不明瞭なことが多すぎるので、どこに連絡していただいても対応できないと思います。実際にどのようなデータでどのように文字化けしているか、それがどのような技術的問題によって発生しているか見てみないと対応しようがありません。その上で、もっとも適切な連絡先は実際にサービスを提供して問題を確認しうる「**宗教法人日連正宗の慧妙のウェブサイト**」の**管理者**ではないかと思います。

**Comment by takuyatahata** [comment]
@matz 
具体的に文字化けしているHTML　コードはShit-jis
http://toyoda.tv/hokekyo.htm
管理者に問い合わせしておりませんが、文字化けを面倒臭がって直さないのは、特殊なソフトウェアを使うと引用して公開するときに、権利上の問題が発生するので、部首の組み合わせや写真で代用して済ませているからだと多分思います。

全ての文字化けを解消できそうな具体的なソフトウェアの名前
文字鏡
超漢字

古い３ｇの携帯電話だと区点コードの①と②をテンキーで出力できますが、③と④はUNICODE文字なので閲覧できません。

ネット喫茶のパソコンからだと再起動できないことや管理者の権限でコマンドが使えないことが制約になっており、RUBYは使い勝手が悪いですね。RUBYの改良版を作るなら、実際に使っている人がどのような不便を感じているのか話を聞いたほうがいいと思います。

**Comment by takuyatahata** [comment]
@matz  
お忙しそうで返信していただけないかもしれませんが、
日経LINUX、ウェブプラスデータベースなどに載っている、まつもとゆきひろさんの記事はだいたい読んでいますのでそういう前提でコミュニケーションをとっていただけるとありがたいです。

**Comment by matz** [comment]
ありがとうございます。いずれにしてもその問題を解決するかどうかはサイト管理者の決心次第なので私からできることはありません。

**Comment by takuyatahata** [comment]
@matz 
はい、わかりました。返信いただいてこちらこそありがとうございました。

**Comment by takuyatahata** [comment]
@matz 
文字化け、外字問題は棚上げしてもらっても結構です。
qiitaのアカウントでわからないことを質問する記事を投稿したのですが、上級者の方からそういうことはＹａｈｏｏ知恵袋でやってくださいと言われたのですが、皮肉なことにそのあとに質問機能が実装されたんですね。
タグ付けしないと投稿できませんという表示が出て、投稿できずに先へ進めなくてそのまま質問できてません。
プロの方でもわからないこともあるかと思いますが、パソコン操作で困ったときにどうしたらいいんでしょうか？
プログラミングの講習会とかでも、表面的なことしか教えないでお金が無駄になってしまうので通ってはいないし、
参考書で調べても限界があります。

**Comment by matz** [comment]
私の場合はわからないことに関係するキーワードをいくつか検索すると答えにたどり着きますが、それは３０年以上のプログラミング経験と基礎知識があるので、「自分のわからないところがわかる」からだと思います。一番簡単なのは質問に答えて(一緒に調べて)くれるような人間関係を構築することだ思いますが、そうでない場合は地道に周辺から知識を身につけるしかないと思います。
これ以上はサイトの目的からズレすぎてしまうので、ここまでとします。
