### ISSUE TITLE
dump.c Does not emit debug information

### ISSUE THREAD

**Issue by fundamental** [mruby/mruby#5390]
So for a while I've wondered why backtraces were difficult to consistently get within MRuby, sometimes they'd be fine and other times they would be partial or missing entirely. This week I decided to track it down. Going into error.c and backtrace.c I noticed that backtrace frames were getting discarded as no debug info was available (i.e. debug_info was NULL) despite me turning on all the standard debug flags. That lead me back to the output of mrbc during the project's build phase. I could see in the build/host/... folders the compiled ruby code was being written out to. Unfortunately https://github.com/mruby/mruby/blob/master/src/dump.c#L1238 is where the debug_info field is emitted and with current versions that field is being set to NULL.

So, there would only be backtraces for code loaded when the application was running, which explained why backtraces sometimes worked. So far I've hacked in some simple dumping support for irep blocks with a single file with associated line info in the mrb_debug_line_ary format. Before trying to clean up the existing WIP, would it be correct to think that the debug_info _should_ have been in the mrbc/dump.c output previously when the -g/DUMP_DEBUG_INFO flag was set?

If so I can take a swing at turning the below diff into something more presentable such that everyone can enjoy working backtraces within mrbgems.

Current diff (based off 69482dbc8e590ed66f0944e9b48c4f9c2f83c873, but it should be close enough to HEAD):
[debug-dump-wip.txt](https://github.com/mruby/mruby/files/6214419/debug-dump-wip.txt)

**Comment by matz** [comment]
The original intention of `-S` (C dump) is to reduce ROM consumption. That's why `mrbc -S` does not produce debug information.
I have no strong opinion here, but do you really need debug info with `-S` option?

**Comment by fundamental** [comment]
So, I assumed that one of the general goals of mrbc would be to reduce ROM. At least trying to dig through docs related to build_config, mrbc's help, etc it made it look like 'enable_debug' along with adding '-g' to mrbc should have resulted in debug output getting dumped. It was also perplexing that backtraces did not have a <unknown-file>:<unknown-line> for each frame without debug information. At the start I assumed that backtrace.c/error.c were broken rather than the debug info never being written out by mrbc dumping them.

So I'd agree that "mrbc -S" shouldn't dump debug info by default. In my mind "mrbc -S -g" should dump debug info and perhaps documentation should point to ways of switching to the non-S mode of mrbc. My current application isn't particularly ROM constrained, so either should work. Digging through the build pipeline it looks like I'd have to iterate over each gem to "disable_cdump" or run "disable_presym". Is that right? Perhaps they're global options and I'm misreading part of the source. Are there any startup time ramifications of disabling the C dump style output?

Half of my goal of creating this issue is to help people discover an answer to "Why are my backtraces missing in MRuby".

**Comment by matz** [comment]
Send me the PR. I will review.

**Comment by fundamental** [comment]
Thanks for merging the updated behavior.
