### ISSUE TITLE
Problem：'mruby/presym/id.h' file not found

### ISSUE THREAD

**Issue by tailang** [mruby/mruby#5393]
I make a mruby iOS framework at tag 3.0.0 , when run  on iOS have a probem that 'mruby/presym/id.h' file not found. I try to read mruby source code ,but not found this file.

my 'build_config.rb'  file

``` ruby
CC = `xcrun -find clang`.strip

def sdk_path(device); `xcrun --sdk #{device} --show-sdk-path`.strip end

IOS_ARCHS = %W(armv7 arm64 arm64e)
IOSSIM_ARCHS = %W(i386 x86_64)

MRuby::Build.new do |conf|
  toolchain :clang
  conf.gembox 'default'
  conf.disable_presym
end

IOS_ARCHS.each do |arch|
  flags = %W(-Os -isysroot #{sdk_path 'iphoneos'})
  flags << "-arch"
  flags << arch
  MRuby::CrossBuild.new(arch) do |conf|
    conf.gembox 'default'
    conf.cc do |cc|
      cc.command = CC
      cc.flags = flags
    end
  
    conf.linker do |linker|
      linker.command = CC
      linker.flags = flags
    end
  end
  
end

IOSSIM_ARCHS.each do |arch|
  flags = %W(-O -isysroot #{sdk_path 'iphonesimulator'})
  flags << "-arch"
  flags << arch
  MRuby::CrossBuild.new(arch) do |conf|
    conf.gembox 'default'

    conf.cc do |cc|
      cc.command = CC
      cc.flags = flags
    end
  
    conf.linker do |linker|
      linker.command = CC
      linker.flags = flags
    end
  end

end
```

**Comment by matz** [comment]
Could you show use full error messages? I don't want to play a guessing game.

**Comment by shuujii** [comment]
Could you please try setting `toolchain` at the beginning of the `MRuby::CrossBuild.new` block as shown below?

```ruby
MRuby::CrossBuild.new(arch) do |conf|
  conf.toolchain :clang
  ...
end
```

**Comment by tailang** [comment]
> Could you show use full error messages? I don't want to play a guessing game.

I am sorry.

I make a mruby iOS [framework](https://github.com/tailang/MRubyFramework/tree/feature/3.0.0/ios/MRuby.framework),  I get an error from [Xcode](https://developer.apple.com/xcode/) like below. 

mruby : tag 3.0.0
Xcode : 12.4 (12D4e)
clang:  Apple clang version 12.0.0 (clang-1200.0.32.29)

```
While building module 'MRuby' imported from /Users/didi/other/github/MRubyFramework/Example/MRubyFramework/MRBViewController.m:10:
In file included from <module-includes>:1:
In file included from /Users/didi/other/github/MRubyFramework/ios/MRuby.framework/Headers/mruby-umbrella.h:7:
In file included from /Users/didi/other/github/MRubyFramework/ios/MRuby.framework/Headers/presym.h:13:
/Users/didi/other/github/MRubyFramework/ios/mruby.framework/Headers/presym/enable.h:10:10: fatal error: 'mruby/presym/id.h' file not found
#include <mruby/presym/id.h>
         ^~~~~~~~~~~~~~~~~~~
/Users/didi/other/github/MRubyFramework/ios/mruby.framework/Headers/presym/enable.h:10:10: note: did not find header 'presym/id.h' in framework 'mruby' (loaded from '/Users/didi/other/github/MRubyFramework/ios')
1 error generated.
/Users/didi/other/github/MRubyFramework/Example/MRubyFramework/MRBViewController.m:10:9: fatal error: could not build module 'MRuby'
@import MRuby;
 ~~~~~~~^~~~~
2 errors generated.
```

**Comment by tailang** [comment]
> Could you please try setting `toolchain` at the beginning of the `MRuby::CrossBuild.new` block as shown below?
> 
> ```ruby
> MRuby::CrossBuild.new(arch) do |conf|
>   conf.toolchain :clang
>   ...
> end
> ```

thanks, I try setting toolchain at the beginning of the MRuby::CrossBuild.new block but  has the same error.

**Comment by matz** [comment]
As far as I read from the error messages, it's not the error in building mruby, but in building your application. `mruby/presym/id.h` and `mruby/presym/table.h` are header files generated during the build under `build/<target>/include` directory. You have to specify the header directory as well. Use `mruby-config --cflags` for convenience.

**Comment by tailang** [comment]
> As far as I read from the error messages, it's not the error in building mruby, but in building your application. `mruby/presym/id.h` and `mruby/presym/table.h` are header files generated during the build under `build/<target>/include` directory. You have to specify the header directory as well. Use `mruby-config --cflags` for convenience.

I've learned，thank you very much.

**Comment by matz** [comment]
You are welcome.
