### ISSUE TITLE
Accidental Gitlab CI

### ISSUE THREAD

**Issue by suetanvil** [mruby/mruby#5409]
When I push a copy of this repository into the public Gitlab instance at [Gitlab](http://gitlab.com), the presence of the file `.gitlab-ci.yml` immediately launches a very expensive set of integration builds.  In my case, it consumed the 450 minutes/month provided to my free account almost instantly.  (I should disclose that I had created a number of branches on my copy resulting in multiple CI jobs and this added to the problem.  Also, since my account is not a paid one, this was merely inconvenient to me and not actually expensive.)

As far as I can tell, the only way to disable this without modifying the repository itself is to change the name of the CI configuration file Gitlab will use for this project in the project's configuration.  My admittedly quick search of the documentation found no other way to stop this while still keeping CI available for other projects.

Unfortunately, I created the project using Gitlab's push-to-create feature.  That is, I pushed the repository to a new URL I had write access to and it created the project automatically but with default configuration, so there was no way to pre-configure for this case even if I had known about it.

This is a nasty trap and it's absolutely Gitlab's fault.  However, it would be nice if the mruby sources worked around this.

I would like to suggest the Gitlab CI configuration file be modified in a way that will require explicit enabling by the repository owner before CI will run.  The simplest solution I can think of is to change the name of `.gitlab-ci.yml` but there may be more elegant options available to someone with more Gitlab experience than I.

**Comment by matz** [comment]
Sorry, it was configured when GitLab CI was free. I will rename/remove it.
