### ISSUE TITLE
mrb_load_irep mangles instance variable names

### ISSUE THREAD

**Issue by matthewwiese** [mruby/mruby#5452]
Hello,

I am compiling the following Ruby code using MRBC and loading the bytecode directly from a C header file:

```ruby
class Example
    attr_accessor :x
    def initialize
        @x = 0
    end
end

e = Example.new
e.x = 123
e
```

and using it this way:

```c
mrb_value example = mrb_load_irep(mrb, ircode);
mrb_iv_set(mrb, example, mrb_intern_lit(mrb, "@x"), mrb_int_value(mrb, 456));
mrb_p(mrb, mrb_inspect(mrb, example));
```
Where the Kernel#p output is something of the sort:
```
"#<\x80:0x563a84790c20 @x=456, \xe3\x04=123>"
```

Whereas, if I do the same using `mrb_load_string`, the behavior is how I expect:
```c
const char* ruby_str = R"(
  class Player
    attr_accessor :x
    def initialize
      @x = 0
    end
  end
  e = Example.new
  e.x = 123
  e)";
mrb_value example = mrb_load_string(mrb, ruby_str);
mrb_iv_set(mrb, example, mrb_intern_lit(mrb, "@x"), mrb_int_value(mrb, 456));
mrb_p(mrb, mrb_inspect(mrb, example));
```
Output:
```
"#<Player:0x560f13559bb0 @x=456>"
```

Have I missed documentation regarding this behavior? I would have expected the IR code to behave similarly to loading from a string (i.e. preserving the instance variable). Is this a bug?

Edit: I am using version `mruby 3.0.0 (2021-03-05)`

**Comment by matz** [comment]
The behavior described in the issue should be caused by a bug. But I cannot reproduce the issue on my platform (Linux Mate) with `3.0.0` (111e4e1ba8e4cfd098935d4ed1198327afd77194).

What I tried:

Prepare `c.c`:

```c
#include "mruby.h"
#include "mruby/irep.h"
#include "mruby/variable.h"
#include "/tmp/ir.inc"

int
main()
{
  mrb_state *mrb = mrb_open();
  mrb_value example = mrb_load_irep(mrb, ircode);
  mrb_iv_set(mrb, example, mrb_intern_lit(mrb, "@x"), mrb_int_value(mrb, 456));
  mrb_p(mrb, mrb_inspect(mrb, example));
  mrb_funcall(mrb, example, "xx", 0, NULL);
  mrb_close(mrb);
}
```

Prepare `c.rb`
```ruby
class Example
  attr_accessor :x
  def initialize
    @x = 0
  end
  def xx
    p self.x
  end
end

e = Example.new
e.x = 123
e
```
Compile Ruby code with `mrbc`:

```
$ mrbc -s -g -B ircode -o /tmp/ir.inc c.rb
```

Compile `c.c`:

```
$ gcc `mruby-config --cflags` c.c `mruby-config --ldflags` `mruby-config --libs`
```
Then execute the example program:

```
$ a.out
"#<Example:0x5608ac1e74f0 @x=456>"
456
```

**Comment by matthewwiese** [comment]
Hey matz, I've created a repository reproducing my issue, including the idiosyncrasies of my build process: https://github.com/matthewwiese/mruby-issue-5452

I am on commit [0f45836b5954accf508f333f932741b925214471](https://github.com/mruby/mruby/commit/0f45836b5954accf508f333f932741b925214471).

On naive reflection, perhaps it's a result of using g++? I may have missed documentation stating not to use mruby with C++. Regardless, I've included the output of `g++ -v` in the [README](https://github.com/matthewwiese/mruby-issue-5452/blob/master/README.md) in case it helps.

**Comment by matz** [comment]
Thank you for the reproducing example. In the function `issue_5452_c()`, you call `mrb_load_irep` with `ircode` that is function local, but it should be `static`. The symbol table refers memory region inside of `ircode` but the region is recycled after `issue_5452_c()` exited.

**Comment by matthewwiese** [comment]
Can't believe I overlooked that! Thanks for the effortless diagnosis.
