### ISSUE TITLE
Compile mruby with emscripten (or: how to include compiler in cross build)

### ISSUE THREAD

**Issue by sasq64** [mruby/mruby#5453]
I am trying to build mruby for the web using emscripten, but I get two undefined symbols;
```
wasm-ld: error: CMakeFiles/toy.html.dir/src/toy.cpp.o: undefined symbol: mrb_load_string
wasm-ld: error: CMakeFiles/toy.html.dir/src/toy.cpp.o: undefined symbol: mrb_load_file
```
Emscripten works differently than normal c-compilers so errors like this are not too uncommon, but I just wonder;

Is there anything special about those two functions compared to other mrb-functions, since those are the only ones giving me trouble ?

**Comment by sasq64** [comment]
Examining the contents og `librmuby.a` and `libmruby_core.a` I see that they contain the same files, whereas in the PC build `libmruby.a` contains a lot more files, including `y.tab.o`. So something in the build process for emscripten figures that all those other obj files are not needed...

**Comment by sasq64** [comment]
Ok so it seems this use case is no really supported ? A cross build does not include the compiler and can not load code dynamically ?
I think I solved it by building a non-cross build and copying over the bin tools from my non emscripten build.

What would be involved with supporting a cross build that included the compiler ?

**Comment by dearblue** [comment]
Is #4486 useful to you?
The build config file is https://github.com/mruby/mruby/pull/4486/files#diff-2cf92ce08f99cccec9dfb77b4e322228fef3e4d0624ebab89dad1cd08b7cefe4

**Comment by sasq64** [comment]
No, that PR does not include the compiler, like I noticed.

By the way, I am now running successfully running an mruby REPL in the browser, so the compiler in included, but I have to do the manual step mentioned above.

**Comment by zzak** [comment]
I think compiler has to be built using host environment, but it should be possible to build only the compiler as a separate build target and copy them like you suggested.

**Comment by sasq64** [comment]
Yes, and I wonder what needs to change in the build environment to allow this behavior.

**Comment by YunzheZJU** [comment]
Hi, Have you solved your problem?

Several months ago I successfully compiled the mruby compiler into WASM. It can execute ruby scripts which are dynamically inputted by the user (like `p 'Hello world'` which eventually log a string in the console) in the browser env. 

Basically it first 
* cross-builds mruby library targeting WebAssembly(which outputs lib/libmruby.a), 
* then compiles mruby library (included with my own c source files) to wasm(which outputs mruby.mjs and mruby.wasm) 
* and finally bundles mruby wasm and Javascript sources files of my own.

I don't quite understand the meaning of your `include the compiler` but if you are going to achieve a similar target as mine, I'd like to share more details about my build config.

**Comment by sasq64** [comment]
Right now I my mruby.cfg contains both a _Build_ and a _CrossBuild_, and will fail when it tries to run the binaries in the host/bin dir (like `mrbc`) because it was built for emscripten. So then I just copy over the binaries from the PC build and build again, and I get a complete emscripten build.

If you have a config that allows me to skip this hack that wold be great.

But it's working, you can test it at http://apone.org/toy/

(It even supports blocking IO, like
`name = gets() ; puts "hello #{name}"`
 ... can you guess how that works ? :)

**Comment by sasq64** [comment]
Thank you, this worked perfectly.

**Comment by sasq64** [comment]
I just replaced the gem line with
` conf.gembox 'default'`
which game me a full build

**Comment by matz** [comment]
FYI, 'p' is in the `mruby-print` gem.
