### ISSUE TITLE
Unsigned literal conversion

### ISSUE THREAD

**Issue by sasq64** [mruby/mruby#5454]
Could we allow literals that would fit in an unsigned int be allowed and converted to it's signed counter part ?

ie `a = 0xffffffff` on a 32-bit build should be allowed and yield `-1`.

The reason I need it personally is because I deal with RGBA color values, which started causing overflow exceptions when I
build mruby for 32-bit.

**Comment by zzak** [comment]
@sasq64 I'm not sure but I wonder if nan-boxing would help here? I may not be understanding the problem correctly tho.

**Comment by shuujii** [comment]
Integer literals cannot be treated as unsigned, but it is possible to specify `MRB_INT64` to make an integer 64-bit.

Alternatively, you may use string, byte sequence, integer array, and so on.

```ruby
str = "abffeeff"
byte_seq = [str].pack("H*")  #=> "\xab\xff\xee\xff"
int_array = byte_seq.bytes   #=> [171, 255, 238, 255]
```

**Comment by shuujii** [comment]
It doesn't matter if it's already resolved, but mruby can use `MRB_INT64` on 32-bit platform (if it supports `int64_t`). I'm not familiar with Emscripten, but Emscripten seems to support int64.

https://github.com/emscripten-core/emscripten/blob/main/ChangeLog.md

> v1.36.12: 10/20/2016
> --------------------
>  - Improved Emscripten toolchain profiler with more data. (#4566)
>  - Export dlmalloc() and dlfree() as emscripten_builtin_malloc() and
>    emscripten_builtin_free() to allow user applications to hook into memory
>    allocation (#4603)
>  - Improved asm.js -s USE_PTHREADS=2 build mode compatibility when
>    multithreading is not supported.
>  - Improved WebGL support with closure compiler (#4619)
>  - Improved Bianaryen WebAssembly support
>  - Added support for GL_disjoint_timer_query extension (#4575)
>  - Improved Emscripten compiler detection with CMake (#4129, #4314, #4318)
>  - Added support for int64 in wasm.

**Comment by sasq64** [comment]
That's strange, when I try to build with MRB_INT64 I hit several static asserts,
I can paste them here when I try it again...

**Comment by shuujii** [comment]
Ah, I'm sorry. It may not work in some cases due to bugs. On master, #5456 may fix it.

**Comment by sasq64** [comment]
Actually I had missed the defined somewhere, now that I define it both for host, build and my own app it works. Thanks!

I still think hex literals should be assumed to be unsigned and converted to signed for convenience, but maybe it's
hard to change.

**Comment by matz** [comment]
I am sorry but I am not going to introduce `0xffffffff` to be `-1` on 32bit configuration.
* it's not desirable that the script behavior will be highly dependent on the configuration
* it's against the ISO defined behavior of Ruby integers

Instead, I am going to introduce big integers to mruby in the future. For the time being, try using 64bit integers.

**Comment by sasq64** [comment]
I totally understand. I guess my use case is not that common.

**Comment by matz** [comment]
@sasq64 I understand. The background motivation behind the original Ruby was similar. Trying to use integers with MSB set.

**Comment by sasq64** [comment]
Just in case anyone else needs this and finds this ticket; this is a simple way to hack out the overflow check for unisgned hex literals only;
```
-- a/mrbgems/mruby-compiler/core/codegen.c
+++ b/mrbgems/mruby-compiler/core/codegen.c
@@ -1479,7 +1479,7 @@ readint_mrb_int(codegen_scope *s, const char *p, int base, mrb_bool neg, mrb_boo
       result -= n;
     }
     else {
-      if ((MRB_INT_MAX - n)/base < result) {
+      if (base != 16 && (MRB_INT_MAX - n)/base < result) {
         *overflow = TRUE;
         return 0;
       }
```
