### ISSUE TITLE
Constants set from C gets incorrect top bits (in 32bit)

### ISSUE THREAD

**Issue by sasq64** [mruby/mruby#5455]
```c
    mrb_define_const(ruby, ruby->kernel_module, "A0", mrb_fixnum_value(-2000000000));
    mrb_define_const(ruby, ruby->kernel_module, "B0", mrb_fixnum_value(0x7fffffff));
    mrb_load_string(ruby, "module Kernel ; A1 = -2000000000 ; B1 = 0x7fffffff ; end");
    mrb_load_string(ruby, "p A0 ; p B0 ; p A1 ; p B1");
```
outputs
```
147483648
-1
-2000000000
2147483647
```
The last two (set from ruby) are correct, the top two (set from C) are incorrect.

Could there be some bitwise operations happening that depends on int (or related types) being 64 bit ? Like shifting outside the 32bit range ?

**Comment by shuujii** [comment]
I think you will get the expected result if you use `mrb_int_value` instead of` mrb_fixnum_value`.

These values can be represented as integers, but in the case of 32-bit word-boxing they cannot be represented as fixnums (immediate values), so you must use `mrb_int_value`.

**Comment by sasq64** [comment]
Actually fixnums and integers are treated the same in mruby
```c
#define SET_INT_VALUE(mrb,r,n) BOXNIX_SET_VALUE(r, MRB_TT_INTEGER, value.i, (n))
#define SET_FIXNUM_VALUE(r,n) BOXNIX_SET_VALUE(r, MRB_TT_INTEGER, value.i, (n))
```
```c
MRB_INLINE mrb_value mrb_int_value(struct mrb_state *mrb, mrb_int i)
{
  mrb_value v;
  SET_INT_VALUE(mrb, v, i);
  return v;
}

MRB_INLINE mrb_value mrb_fixnum_value(mrb_int i)
{
  mrb_value v;
  SET_FIXNUM_VALUE(v, i);
  return v;
}
```

**Comment by shuujii** [comment]
The implementation of `SET_INT_VALUE` and` SET_FIXNUM_VALUE` is different because wrod boxing is enabled by default unless you specify boxing configuration explicitly.

https://github.com/mruby/mruby/blob/07c847027875a955ba64d3c84f8f456e96155b31/include/mruby/boxing_word.h#L180-L181

**Comment by sasq64** [comment]
Ah, I was looking at the wrong implementation. Thanks!
... but what is difference between fixnum and integer then?

**Comment by matz** [comment]
Fixnums are integers boxed in `mrb_value` (31bit width on Word Boxing). Integers are .. integers. Some integers are inlined fixnums, some are allocated in the GC-managed heaps.
