### ISSUE TITLE
`to_ary()` does not seem to be implemented.

### ISSUE THREAD

**Issue by sasq64** [mruby/mruby#5462]
I would like to implement `to_ary` to be able to "unpack" my custom class as multiple arguments when I return it from a method.

**Comment by matz** [comment]
I am sorry but mruby does not provide implicit conversion by `to_ary`, `to_str`, and `to_int` (698f5f707c2db334a15c605bf1b0d0cff42b1224, ff08856fe314faa4d16b4502c0960a3475387846, afca99a40b8a3415b3a9a0e8fc41c93ddcbb11d8).

* it used to be implemented but caused so many vulnerabilities (like #4120)
* it consumes both time and space
* they are not in the ISO standard

Sorry again for the inconvenience. Use explicit conversion instead.
