### ISSUE TITLE
MRB_WORD_BOXING is broken

### ISSUE THREAD

**Issue by Asmod4n** [mruby/mruby#5470]
For integer values, MRB_WORD_BOXING isn't working.
INT64_MIN as a mruby value is -1
INT64_MAX is 0

tested on linux 5.12.8 with gcc 11.1 and mruby master on a ryzen 2 CPU.
Works fine with MRB_NO_BOXING

**Comment by Asmod4n** [comment]
Found the issue, mrb_fixnum_value doesn't work as expected, you have to use mrb_int_value in c code.

**Comment by matz** [comment]
Use `mrb_fixnum_value()` only when you are sure the value fits in `fixnum` (i.e. boxable integer: `MRB_FIXNUM_MAX > i > MRB_FIXNUM_MIN`). `INT64_MAX` is bigger than `MRB_FIXNUM_MAX` so that it's crippled by `mrb_fixnum_value()`.
