### ISSUE TITLE
negative value problem

### ISSUE THREAD

**Issue by yamori813** [mruby/mruby#5499]
I make cairo binding mrbgems. This class have return framebuffer pointer method.

static mrb_value mrb_cairo_get_data(mrb_state *mrb, mrb_value self)
{
  mrb_cairo_data *data = DATA_PTR(self);

  unsigned char *ptr = cairo_image_surface_get_data(data->cs);
printf("cairo addr %x\n", ptr);

  return mrb_fixnum_value((int)ptr);
}

cairo addr 4124ee80

But mruby code value is this.

ptr = c.get_data 
p ptr

-1054544256

Why make negative value ?

This code work fine 2.1.1. But I change to 3.0.0 then I have this problem.

If you have advice, please let me know.

**Comment by matz** [comment]
Short answer: use `mrb_int_value(mrb, int)`.

Longer answer: Since 3.0.0, the default value representation became Word Boxing, in which fixnum occupies 31 bits (not 32 bits).
In 31 bit signed integer, `4124ee80` is negative.
