### ISSUE TITLE
Module.instance_eval not working

### ISSUE THREAD

**Issue by sasq64** [mruby/mruby#5528]
The following code fails with 
`uninitialized constant #<Class:0x68fa70>::A (NameError)`

```ruby
     m = Module.new
     m.instance_eval("
     class A end
     class B
         def initialize()
             p A
         end
     end
     B.new
")

```

**Comment by sasq64** [comment]
Also, after you get this error, plain `eval()` also breaks for the same code...

**Comment by sasq64** [comment]
Shorter repro:
```ruby
 Module.new.class_eval("
 class A end
 class B
     p A
 end
") 
```

**Comment by matz** [comment]
It's caused by #5497. Shall I revert it @dearblue?

**Comment by matz** [comment]
#5497 reverted. @dearblue please retry.

**Comment by dearblue** [comment]
@sasq64 Thank you for reporting the issue.
@matz Thank you for revert #5497. If done well, I'll PR again.
