### ISSUE TITLE
Aliasing a method from a class in oldgen on a short-lived singleton class that is collected at the next GC causes a segfault via a type confusion

### ISSUE THREAD

**Issue by lopopolo** [mruby/mruby#5534]
I've been investigating a reproducible segfault. My findings are here: https://github.com/artichoke/artichoke/pull/1327#issuecomment-902893229.

Unfortunately, I do not have a minimized reproduction.

## Dataflow

I think this is what's happening:

- A `-@` method is defined in Ruby for the `Numeric` class.
- `Numeric` is moved to the old generation.

- Sometime later and all before the subsequent GC:

  - An object `obj` is created from a subclass of `Numeric`.
  - `obj.respond_to? :-@` is called which pulls the proc for `Numeric#-@` into the method cache.
  - `obj.singleton_class.alias_method :some_other_symbol, :-@` is called, which converts the `RProc *` for `Numeric#-@` to have `e` be an `REnv` variant. When attaching the proc to `obj`'s singleton class, a write barrier is called on the newly allocated `REnv *`.

- Then the object and its singleton class become unreachable.

- Then a minor GC occurs:

  - Because the GC is minor, a `root_scan_phase` does not occur, which means `Numeric` and the `RProc *`s in its method table are not marked.
  - This causes the `REnv *` from the prior alias call to not be painted black.
  - The `REnv *` is freed.
  - The `REnv *`'s `RBasic *` is returned to the freelist in the GC heap to be reused.

- Sometime later but before the next full GC, the `RBasic *` is reallocated as a `RProc*`.
  - This means the `proc->e` field on the `Numeric#-@` proc is now an `RProc *` instead of the expected `REnv *`.

- The newly allocated proc is then involved in an `mrb_alias_method` call which writes to `e->mid` and corrupts the `Numeric#-@` Proc's `env`.

- When a full GC finally occurs, the `RProc`'s in the `Numeric` method table are added to the gray list. When the GC attempts to mark the `Numeric#-@` proc's `REnv` in `gc_mark_children`, a type confusion occurs causing an invalid memory access.

## Proposed fix

When aliasing a method, the `RProc`'s target class should be marked with write barrier so it is used for marking in the next GC.

**Comment by lopopolo** [comment]
Further investigation shows that when building mruby with `-DMRB_GC_TURN_OFF_GENERATIONAL`, the bug does not occur.

**Comment by lopopolo** [comment]
I investigated this by using an `rr` recording in Pernosco of this command:

    ./target/debug/spec-runner --quiet --format tagger all-core-specs.toml > /dev/null

As of https://github.com/artichoke/artichoke/commit/8a2dafe80b473e93c7f18cd1dfbabf429bf45e3d.

Built with this workflow https://github.com/artichoke/artichoke/blob/8a2dafe80b473e93c7f18cd1dfbabf429bf45e3d/.github/workflows/crash.yaml.

**Comment by lopopolo** [comment]
@matz if you'd like access to an `rr` debugging shell to observe this segfault, you can use https://pernos.co/debug/ckckYeQYH_xxvmI4mrZ4dQ/index.html.

This is the session I used and it contains my notes and bookmarks on the most interesting points in the program's execution: https://pernos.co/debug/nE4yYzcs9eyNF6t0STPATA/index.html.

**Comment by matz** [comment]
Thank you. I'll investigate the issue.

**Comment by matz** [comment]
By investigating using `pernos.co` (very interesting tool), the complied source does not seem to have `mrb_field_write_barrier()` line adde on May 24th 2021 by e323cd0c6ebdeeb42c267a5fe28cec87ae2f00a0. I hope this fix the issue.

**Comment by lopopolo** [comment]
> By investigating using `pernos.co` (very interesting tool), the complied source does not seem to have `mrb_field_write_barrier()` line adde on May 24th 2021 by e323cd0c6ebdeeb42c267a5fe28cec87ae2f00a0. I hope this fix the issue.

I'll cherry pick this commit to the PR I'm running these tests on and report back. Thanks for investigating @matz 💎

**Comment by lopopolo** [comment]
> [...] the complied source does not seem to have `mrb_field_write_barrier()` line adde on May 24th 2021 by https://github.com/mruby/mruby/commit/e323cd0c6ebdeeb42c267a5fe28cec87ae2f00a0.

That's right. Artichoke vendors mruby as of the 3.0.0 tag with a few cherry picks – https://github.com/mruby/mruby/compare/3.0.0...artichoke:artichoke-vendor.

It does look like I'm about 800 commits behind master. I'd prefer to update to a released version of mruby. Are there plans for a 3.x.y release soon?

At least locally, cherry-picking e323cd0c6ebdeeb42c267a5fe28cec87ae2f00a0 has fixed the segfault. I'm pushing up a build now.

**Comment by lopopolo** [comment]
Cherry picking https://github.com/mruby/mruby/commit/e323cd0c6ebdeeb42c267a5fe28cec87ae2f00a0 resolved the issue. Thanks for the investigation.

Successful run: https://github.com/artichoke/artichoke/runs/3528590522?check_suite_focus=true
