### ISSUE TITLE
Link error for REALTEK Bare Metal

### ISSUE THREAD

**Issue by yamori813** [mruby/mruby#5547]
I use REALTEK SDK gcc for Bare Metal port. This gcc defined __linux__ but not make Linux binary.

I seem cause of this error is include/mruby/value.h.

Please consider check method.

./mruby/build/rtl8196/lib/libmruby.a(load.o): In function `mrb_read_irep':
/usr/home/hiroki/rtlbm-mruby/mruby/src/load.c:(.text+0x244c): undefined reference to `__ehdr_start'
/usr/home/hiroki/rtlbm-mruby/mruby/src/load.c:(.text+0x2450): undefined reference to `__ehdr_start'
/usr/home/hiroki/rtlbm-mruby/mruby/src/load.c:(.text+0x24b4): undefined reference to `__init_array_start'
/usr/home/hiroki/rtlbm-mruby/mruby/src/load.c:(.text+0x24b8): undefined reference to `__init_array_start'

**Comment by matz** [comment]
Could you show me your system-specific predefined macros, by following steps, please?

```
touch /tmp/c.c
cpp -dM /tmp/c.c
```

You may have to replace `cpp` by your cross-compiling C preprocessor.

**Comment by yamori813** [comment]
% ./mips-linux-cpp -dM /tmp/c.c
#define __DBL_MIN_EXP__ (-1021)
#define __FLT_MIN__ 1.17549435e-38F
#define __CHAR_BIT__ 8
#define R3000 1
#define __WCHAR_MAX__ 2147483647
#define __DBL_DENORM_MIN__ 4.9406564584124654e-324
#define __FLT_EVAL_METHOD__ 0
#define __unix__ 1
#define _MIPS_ISA _MIPS_ISA_MIPS1
#define __LANGUAGE_C 1
#define __DBL_MIN_10_EXP__ (-307)
#define __FINITE_MATH_ONLY__ 0
#define _MIPS_TUNE "4181"
#define __GNUC_PATCHLEVEL__ 5
#define __DEC64_MAX_EXP__ 385
#define __RSDK__ 1
#define _ABIO32 1
#define __SHRT_MAX__ 32767
#define __LDBL_MAX__ 1.7976931348623157e+308L
#define __mips_abicalls 1
#define __LANGUAGE_C__ 1
#define __UINTMAX_TYPE__ long long unsigned int
#define __linux 1
#define __DEC32_EPSILON__ 1E-6DF
#define __unix 1
#define __LDBL_MAX_EXP__ 1024
#define __linux__ 1
#define __SCHAR_MAX__ 127
#define __m4181 1
#define __DBL_DIG__ 15
#define __SIZEOF_INT__ 4
#define __SIZEOF_POINTER__ 4
#define __USER_LABEL_PREFIX__ 
#define __STDC_HOSTED__ 1
#define __LDBL_HAS_INFINITY__ 1
#define __mips_fpr 32
#define __FLT_EPSILON__ 1.19209290e-7F
#define __mips__ 1
#define __LDBL_MIN__ 2.2250738585072014e-308L
#define __DEC32_MAX__ 9.999999E96DF
#define MIPSEB 1
#define __SIZEOF_LONG__ 4
#define __DECIMAL_DIG__ 17
#define __gnu_linux__ 1
#define __LDBL_HAS_QUIET_NAN__ 1
#define __GNUC__ 4
#define __FLT_HAS_DENORM__ 1
#define __SIZEOF_LONG_DOUBLE__ 8
#define _R3000 1
#define __BIGGEST_ALIGNMENT__ 8
#define _MIPS_TUNE_4181 1
#define __DBL_MAX__ 1.7976931348623157e+308
#define __DBL_HAS_INFINITY__ 1
#define _RSDK_ 1
#define __DEC32_MIN_EXP__ (-94)
#define __LDBL_HAS_DENORM__ 1
#define __DEC128_MAX__ 9.999999999999999999999999999999999E6144DL
#define __DEC32_MIN__ 1E-95DF
#define __DBL_MAX_EXP__ 1024
#define __R3000__ 1
#define __DEC128_EPSILON__ 1E-33DL
#define mips 1
#define __LONG_LONG_MAX__ 9223372036854775807LL
#define __SIZEOF_SIZE_T__ 4
#define __SIZEOF_WINT_T__ 4
#define __GXX_ABI_VERSION 1002
#define __FLT_MIN_EXP__ (-125)
#define __MIPSEB__ 1
#define _MIPSEB 1
#define __DBL_MIN__ 2.2250738585072014e-308
#define _MIPS_ARCH "4181"
#define __DEC128_MIN__ 1E-6143DL
#define __REGISTER_PREFIX__ 
#define __DBL_HAS_DENORM__ 1
#define __NO_INLINE__ 1
#define __R3000 1
#define __RSDK__v15__ 1
#define __FLT_MANT_DIG__ 24
#define __VERSION__ "4.4.5-1.5.5p4"
#define _RSDK_v15_ 1
#define __DEC64_EPSILON__ 1E-15DD
#define __DEC128_MIN_EXP__ (-6142)
#define unix 1
#define __SIZE_TYPE__ unsigned int
#define __ELF__ 1
#define __FLT_RADIX__ 2
#define __LDBL_EPSILON__ 2.2204460492503131e-16L
#define __SIZEOF_PTRDIFF_T__ 4
#define _MIPS_ARCH_4181 1
#define __DEC32_SUBNORMAL_MIN__ 0.000001E-95DF
#define _MIPS_SZPTR 32
#define __FLT_HAS_QUIET_NAN__ 1
#define __FLT_MAX_10_EXP__ 38
#define __LONG_MAX__ 2147483647L
#define __DEC128_SUBNORMAL_MIN__ 0.000000000000000000000000000000001E-6143DL
#define __FLT_HAS_INFINITY__ 1
#define __DEC64_MAX__ 9.999999999999999E384DD
#define __CHAR16_TYPE__ short unsigned int
#define __DEC64_MANT_DIG__ 16
#define _mips 1
#define __DEC32_MAX_EXP__ 97
#define linux 1
#define _MIPS_SZINT 32
#define __LDBL_MANT_DIG__ 53
#define __DBL_HAS_QUIET_NAN__ 1
#define __MIPSEB 1
#define __WCHAR_TYPE__ int
#define __SIZEOF_FLOAT__ 4
#define __pic__ 1
#define __DEC64_MIN_EXP__ (-382)
#define __FLT_DIG__ 6
#define __INT_MAX__ 2147483647
#define __FLT_MAX_EXP__ 128
#define _MIPS_SIM _ABIO32
#define __DBL_MANT_DIG__ 53
#define __DEC64_MIN__ 1E-383DD
#define __WINT_TYPE__ unsigned int
#define __SIZEOF_SHORT__ 2
#define __LDBL_MIN_EXP__ (-1021)
#define _MIPS_FPSET 16
#define __LDBL_MAX_10_EXP__ 308
#define __DBL_EPSILON__ 2.2204460492503131e-16
#define __SIZEOF_WCHAR_T__ 4
#define __DEC_EVAL_METHOD__ 2
#define __mips_soft_float 1
#define __INTMAX_MAX__ 9223372036854775807LL
#define __FLT_DENORM_MIN__ 1.40129846e-45F
#define __PIC__ 1
#define __CHAR32_TYPE__ unsigned int
#define __FLT_MAX__ 3.40282347e+38F
#define LANGUAGE_C 1
#define __SIZEOF_DOUBLE__ 8
#define __FLT_MIN_10_EXP__ (-37)
#define __INTMAX_TYPE__ long long int
#define _LANGUAGE_C 1
#define __DEC128_MAX_EXP__ 6145
#define __GNUC_MINOR__ 4
#define __DEC32_MANT_DIG__ 7
#define __DBL_MAX_10_EXP__ 308
#define __LDBL_DENORM_MIN__ 4.9406564584124654e-324L
#define __STDC__ 1
#define __PTRDIFF_TYPE__ int
#define __mips 1
#define _MIPS_SZLONG 32
#define __DEC64_SUBNORMAL_MIN__ 0.000000000000001E-383DD
#define __DEC128_MANT_DIG__ 34
#define __LDBL_MIN_10_EXP__ (-307)
#define __SIZEOF_LONG_LONG__ 8
#define __LDBL_DIG__ 15
#define __GNUC_GNU_INLINE__ 1

**Comment by matz** [comment]
Could you try the following patch?

```
diff --git a/include/mruby/value.h b/include/mruby/value.h
index 22a826385..67be1e18f 100644
--- a/include/mruby/value.h
+++ b/include/mruby/value.h
@@ -413,3 +413,3 @@ mrb_undef_value(void)
 mrb_bool mrb_ro_data_p(const char *p);
-#elif (defined(__linux__) && !defined(__KERNEL__))
+#elif (defined(__linux__) && defined(__ELF__))
 #define MRB_LINK_TIME_RO_DATA_P
```

**Comment by yamori813** [comment]
still link fail. __ELF__ is defined in REALTEK SDK gcc because of use ELF object.

hiroki@kani:~ % echo | mips-cc -dM -E -
#define __DBL_MIN_EXP__ (-1021)
#define __FLT_MIN__ 1.17549435e-38F
#define __CHAR_BIT__ 8
#define R3000 1
#define __WCHAR_MAX__ 2147483647
#define __DBL_DENORM_MIN__ 4.9406564584124654e-324
#define __FLT_EVAL_METHOD__ 0
#define __unix__ 1
#define _MIPS_ISA _MIPS_ISA_MIPS1
#define __LANGUAGE_C 1
#define __DBL_MIN_10_EXP__ (-307)
#define __FINITE_MATH_ONLY__ 0
#define _MIPS_TUNE "4181"
#define __GNUC_PATCHLEVEL__ 5
#define __DEC64_MAX_EXP__ 385
#define __RSDK__ 1
#define _ABIO32 1
#define __SHRT_MAX__ 32767
#define __LDBL_MAX__ 1.7976931348623157e+308L
#define __mips_abicalls 1
#define __LANGUAGE_C__ 1
#define __UINTMAX_TYPE__ long long unsigned int
#define __linux 1
#define __DEC32_EPSILON__ 1E-6DF
#define __unix 1
#define __LDBL_MAX_EXP__ 1024
#define __linux__ 1
#define __SCHAR_MAX__ 127
#define __m4181 1
#define __DBL_DIG__ 15
#define __SIZEOF_INT__ 4
#define __SIZEOF_POINTER__ 4
#define __USER_LABEL_PREFIX__ 
#define __STDC_HOSTED__ 1
#define __LDBL_HAS_INFINITY__ 1
#define __mips_fpr 32
#define __FLT_EPSILON__ 1.19209290e-7F
#define __mips__ 1
#define __LDBL_MIN__ 2.2250738585072014e-308L
#define __DEC32_MAX__ 9.999999E96DF
#define MIPSEB 1
#define __SIZEOF_LONG__ 4
#define __DECIMAL_DIG__ 17
#define __gnu_linux__ 1
#define __LDBL_HAS_QUIET_NAN__ 1
#define __GNUC__ 4
#define __FLT_HAS_DENORM__ 1
#define __SIZEOF_LONG_DOUBLE__ 8
#define _R3000 1
#define __BIGGEST_ALIGNMENT__ 8
#define _MIPS_TUNE_4181 1
#define __DBL_MAX__ 1.7976931348623157e+308
#define __DBL_HAS_INFINITY__ 1
#define _RSDK_ 1
#define __DEC32_MIN_EXP__ (-94)
#define __LDBL_HAS_DENORM__ 1
#define __DEC128_MAX__ 9.999999999999999999999999999999999E6144DL
#define __DEC32_MIN__ 1E-95DF
#define __DBL_MAX_EXP__ 1024
#define __R3000__ 1
#define __DEC128_EPSILON__ 1E-33DL
#define mips 1
#define __LONG_LONG_MAX__ 9223372036854775807LL
#define __SIZEOF_SIZE_T__ 4
#define __SIZEOF_WINT_T__ 4
#define __GXX_ABI_VERSION 1002
#define __FLT_MIN_EXP__ (-125)
#define __MIPSEB__ 1
#define _MIPSEB 1
#define __DBL_MIN__ 2.2250738585072014e-308
#define _MIPS_ARCH "4181"
#define __DEC128_MIN__ 1E-6143DL
#define __REGISTER_PREFIX__ 
#define __DBL_HAS_DENORM__ 1
#define __NO_INLINE__ 1
#define __R3000 1
#define __RSDK__v15__ 1
#define __FLT_MANT_DIG__ 24
#define __VERSION__ "4.4.5-1.5.5p4"
#define _RSDK_v15_ 1
#define __DEC64_EPSILON__ 1E-15DD
#define __DEC128_MIN_EXP__ (-6142)
#define unix 1
#define __SIZE_TYPE__ unsigned int
#define __ELF__ 1
#define __FLT_RADIX__ 2
#define __LDBL_EPSILON__ 2.2204460492503131e-16L
#define __SIZEOF_PTRDIFF_T__ 4
#define _MIPS_ARCH_4181 1
#define __DEC32_SUBNORMAL_MIN__ 0.000001E-95DF
#define _MIPS_SZPTR 32
#define __FLT_HAS_QUIET_NAN__ 1
#define __FLT_MAX_10_EXP__ 38
#define __LONG_MAX__ 2147483647L
#define __DEC128_SUBNORMAL_MIN__ 0.000000000000000000000000000000001E-6143DL
#define __FLT_HAS_INFINITY__ 1
#define __DEC64_MAX__ 9.999999999999999E384DD
#define __CHAR16_TYPE__ short unsigned int
#define __DEC64_MANT_DIG__ 16
#define _mips 1
#define __DEC32_MAX_EXP__ 97
#define linux 1
#define _MIPS_SZINT 32
#define __LDBL_MANT_DIG__ 53
#define __DBL_HAS_QUIET_NAN__ 1
#define __MIPSEB 1
#define __WCHAR_TYPE__ int
#define __SIZEOF_FLOAT__ 4
#define __pic__ 1
#define __DEC64_MIN_EXP__ (-382)
#define __FLT_DIG__ 6
#define __INT_MAX__ 2147483647
#define __FLT_MAX_EXP__ 128
#define _MIPS_SIM _ABIO32
#define __DBL_MANT_DIG__ 53
#define __DEC64_MIN__ 1E-383DD
#define __WINT_TYPE__ unsigned int
#define __SIZEOF_SHORT__ 2
#define __LDBL_MIN_EXP__ (-1021)
#define _MIPS_FPSET 16
#define __LDBL_MAX_10_EXP__ 308
#define __DBL_EPSILON__ 2.2204460492503131e-16
#define __SIZEOF_WCHAR_T__ 4
#define __DEC_EVAL_METHOD__ 2
#define __mips_soft_float 1
#define __INTMAX_MAX__ 9223372036854775807LL
#define __FLT_DENORM_MIN__ 1.40129846e-45F
#define __PIC__ 1
#define __CHAR32_TYPE__ unsigned int
#define __FLT_MAX__ 3.40282347e+38F
#define LANGUAGE_C 1
#define __SIZEOF_DOUBLE__ 8
#define __FLT_MIN_10_EXP__ (-37)
#define __INTMAX_TYPE__ long long int
#define _LANGUAGE_C 1
#define __DEC128_MAX_EXP__ 6145
#define __GNUC_MINOR__ 4
#define __DEC32_MANT_DIG__ 7
#define __DBL_MAX_10_EXP__ 308
#define __LDBL_DENORM_MIN__ 4.9406564584124654e-324L
#define __STDC__ 1
#define __PTRDIFF_TYPE__ int
#define __mips 1
#define _MIPS_SZLONG 32
#define __DEC64_SUBNORMAL_MIN__ 0.000000000000001E-383DD
#define __DEC128_MANT_DIG__ 34
#define __LDBL_MIN_10_EXP__ (-307)
#define __SIZEOF_LONG_LONG__ 8
#define __LDBL_DIG__ 15
#define __GNUC_GNU_INLINE__ 1

**Comment by matz** [comment]
Could you wrap the output by triple backquotes?

**Comment by matz** [comment]
So that means your platform differs from the standard Linux but there's no way to distinguish it. Sad news.

**Comment by yamori813** [comment]
I use on REALTEK SDK on FreeBSD Linux emuration. But I do check on debian same result on gcc define.

**Comment by yamori813** [comment]
SOC maker provide gcc by SDK. It's use make Linux and bootloader. bootloader is same as bare metal program. I think can't determine target executable binary type from gcc define.

**Comment by matz** [comment]
Could you try following c program (taken from Linux man page) compiles on the machine?

```C
#include <stdio.h>
#include <stdlib.h>

extern char etext, edata, end; /* The symbols must have some type,
                                  or "gcc -Wall" complains */

int
main(int argc, char *argv[])
{
  printf("First address past:\n");
  printf("    program text (etext)      %10p\n", &etext);
  printf("    initialized data (edata)  %10p\n", &edata);
  printf("    uninitialized data (end)  %10p\n", &end);
  exit(EXIT_SUCCESS);
}
```

**Comment by yamori813** [comment]
sorry japanese.

日本語ですいません。

REALTEKのポートはBare Metalなのでmainはアセンブラから呼び出してます。上のコードはBSSなどを拾うコードのようですが、この環境ではBSSの設定はこのldスクリプトで設定されています。

https://github.com/yamori813/rtlbm-mruby/blob/master/main.ld

アセンブラはこちらです。

https://github.com/yamori813/rtlbm-mruby/blob/master/start.S

呼び出されるmainはこれです。

https://github.com/yamori813/rtlbm-mruby/blob/master/main.c

私のポートしてるmruby on YABMは4つのアーキテクチャがあり、ほぼほぼ他も同じような処理になります。

今回の問題はFlash内のデータをそのまま利用しようというアプローチに起因する問題と思われますがいかがですか。

私のターゲットはCFI FlashとSPI Flashを使ったものがあります。

CFI Flashの場合RAM同様に見えるのでそのままコードが実行可能ですが、SPI Flashの場合は一度RAMに貼り付けないと実行できません。ただCFIの場合でも実行イメージは圧縮されているので、u-bootなどのブートローダーがRAMに展開してから実行する形になります。

mruby on YABMはRam 8M,Flash 2M以上になるのですべてRAM上で処理するので問題ありません。

**Comment by matz** [comment]
「Flash内のデータをそのまま利用しよう」というよりはRAMへのコピーを避けるためにアドレスでreadonlyデータを判別したい(RAMを節約したい)というのが意図です。ldスクリプトの読み方がよくわからないのですが、`__init_array_start`はコメントアウトされていますが、`edata`とかは使えそうです。
[２つ上のコメント](https://github.com/mruby/mruby/issues/5547#issuecomment-914089736)のサンプルプログラムをコンパイルしてみてもらえませんか。手元にマシンがないので手探りが必要です。ご協力していただけるとありがたいです。

**Comment by yamori813** [comment]
蟹さんのBSSなどのメモリ配置についてはここですこし書きました。

https://qiita.com/yamori813/items/c1d8111a3f45c5a74655

BSSの_fbssからendはstart.Sで0クリアしてます。

main.ldにあるシンボルを蟹さんのmain.cでprintしてみました。

```
        xprintf("MEMORY _gp %x\n", &_gp);
        xprintf("MEMORY _edata %x\n", &_edata);
        xprintf("MEMORY _fbss %x\n", &_fbss);
        xprintf("MEMORY end %x\n", &end);
```

結果

```
MEMORY _gp 800f5840
MEMORY _edata 800f6c74
MEMORY _fbss 800f6c74
MEMORY end 80105560
```

main.ldをいじるのは可能なのですが、私もあまりldスクリプトは詳しくなくて、かなり行き当たりばったりで作ったものなので、あまり気が進みません。

**Comment by matz** [comment]
見た感じだとetextが定義されていないようですね。`main.ld` で `.rdata : { *(.rdata) }`の直前に`PROVIDE (etext  =  .);`を置いてみてもらえませんか。
それで `xprintf("MEMORY etext %x\n", &etext);` でアドレスが取れるはずですが、確認していただけると嬉しいです。
あと、`xprintf("MEMORY edata %x\n", &edata);` (アンダースコアなし)も確認できるとありがたいです。

**Comment by yamori813** [comment]
diff

```
diff --git a/main.c b/main.c
index 710892f..e40500a 100644
--- a/main.c
+++ b/main.c
@@ -12,6 +12,7 @@
 #define        MRBOFFSET       0x180000
 
 extern char version[];
+extern char etext,edata,_gp, _edata, end, _fbss;
 
 unsigned long memend();
 
@@ -35,6 +36,12 @@ int i;
        timer_init();
 
        xprintf("MEMORY %dM\n", (memend() - 0x80000000) >> 20);
+       xprintf("MEMORY _gp %x\n", &_gp);
+       xprintf("MEMORY _edata %x\n", &_edata);
+       xprintf("MEMORY _fbss %x\n", &_fbss);
+       xprintf("MEMORY end %x\n", &end);
+       xprintf("MEMORY etext %x\n", &etext);
+       xprintf("MEMORY edagta %x\n", &edata);
 
        spi_probe();
 
diff --git a/main.ld b/main.ld
index a594e49..a9312fd 100644
--- a/main.ld
+++ b/main.ld
@@ -11,6 +11,7 @@ SECTIONS
   .fini : {
     KEEP (*(.fini))
   }
+  PROVIDE (etext = .);
   .rdata : { *(.rdata) }
   .data : { *(.data) }
   _gp = ALIGN(16);
```

結果

```
MEMORY _gp 800f5880
MEMORY _edata 800f6cb4
MEMORY _fbss 800f6cb4
MEMORY end 801055a0
MEMORY etext 800f5220
MEMORY edagta 800f6cb4
```

**Comment by matz** [comment]
わかりました。これで対応できると思います。最後に `_edata` の前の `&` を外した結果を見せてくださると助かります。
つまり、`xprintf("MEMORY _edata %x\n", _edata);`ということですね。

**Comment by yamori813** [comment]
diff

```
diff --git a/main.c b/main.c
index 710892f..35973d9 100644
--- a/main.c
+++ b/main.c
@@ -12,6 +12,7 @@
 #define        MRBOFFSET       0x180000
 
 extern char version[];
+extern char etext,edata,_gp, _edata, end, _fbss;
 
 unsigned long memend();
 
@@ -35,6 +36,13 @@ int i;
        timer_init();
 
        xprintf("MEMORY %dM\n", (memend() - 0x80000000) >> 20);
+       xprintf("MEMORY _gp %x\n", &_gp);
+       xprintf("MEMORY _edata %x\n", &_edata);
+       xprintf("MEMORY _fbss %x\n", &_fbss);
+       xprintf("MEMORY end %x\n", &end);
+       xprintf("MEMORY etext %x\n", &etext);
+       xprintf("MEMORY edata %x\n", &edata);
+       xprintf("MEMORY _edata %x\n", _edata);
 
        spi_probe();
 
diff --git a/main.ld b/main.ld
index a594e49..a9312fd 100644
--- a/main.ld
+++ b/main.ld
@@ -11,6 +11,7 @@ SECTIONS
   .fini : {
     KEEP (*(.fini))
   }
+  PROVIDE (etext = .);
   .rdata : { *(.rdata) }
   .data : { *(.data) }
   _gp = ALIGN(16);
```

result

```
MEMORY _gp 800f58a0
MEMORY _edata 800f6cd4
MEMORY _fbss 800f6cd4
MEMORY end 801055c0
MEMORY etext 800f5240
MEMORY edata 800f6cd4
MEMORY _edata 0
```
