### ISSUE TITLE
Invalid codegen for multiple instance variable setting

### ISSUE THREAD

**Issue by fundamental** [mruby/mruby#5550]
Test case:

```
class Cls
    def initialize()
        @a = 0
        @b = 1

        set_values
        check_state
    end

    def set_values(c=2)
      @a = @b = c
    end
    
    def check_state
      if(@a != @b)
        puts "Invalid state"
      end
    end
end 

Cls.new()
```

Expected behavior (and CRuby 3.0.1p64 behavior): Nothing is output

Actual behavior MRuby git HEAD: "Invalid state" is output

mrbc output:

```
irep 0x1d6e7e0 nregs=4 nlocals=3 pools=0 syms=2 reps=0 ilen=20
local variable names:
  R1:c
  R2:&
file: util.rb
   10 000 OP_ENTER      0:1:0:0:0:0:0
   10 004 OP_JMP                010
   10 007 OP_JMP                012
   10 010 OP_LOADI_2    R1                      ; R1:c
   11 012 OP_SETIV      @b      R1              ; R1:c
   11 015 OP_SETIV      @a      R3
   11 018 OP_RETURN     R3
```

Note that `@a` is getting set by R3 which is uninitialized in the scope of this routine.

This bug does not exist for non-IV a/b and it does not exist if the variables are set sequentially. I have not checked for class variables or global variables if a similar issue exists.

**Comment by fundamental** [comment]
Thanks for the quick bug fix :+1:

**Comment by matz** [comment]
Sorry for the silly bug.
