### ISSUE TITLE
instance of descendant of Array cannot set instance variable

### ISSUE THREAD

**Issue by mangoducksparkles** [mruby/mruby#5572]
```
#main.rb
class A < Array
	def initialize(z)
		super()
		@z = z
	end
end
$a = A.new(:z)
```
throws error `main.rb:8: cannot set instance variable (ArgumentError)`

Does not affect descendants of Hash. Seems to occur regardless of variable name and value.

**Comment by matz** [comment]
I am sorry, it's mruby limitation. Array, String and some other classes (Hashes and Data classes are exceptions) are unable to hold instance variables.
