### ISSUE TITLE
Name clashes in mgem-list entries

### ISSUE THREAD

**Issue by suetanvil** [mruby/mruby#5574]
When checking out the git repository associated with an item in `mgem-list`, the checked-out repository takes its name from the source repository, **not** the mgem itself and the build system does not enforce that the names are consistent.

In my specific example, `mgem-process.gem` points to repository `https://github.com/iij/mruby-process.git` while `mgem-process2.gem` points to `https://github.com/katzer/mruby-process.git`.  If I include them in the same `buld_config.rb` file:

```ruby
MRuby::Build.new do |conf|
  conf.toolchain

  conf.gem :mgem => 'mruby-process'
  conf.gem :mgem => 'mruby-process2'  

  conf.enable_bintest
  conf.enable_test
end
```

`rake` will only check out one of them. 

(In this specific case, this often passes its tests because `mruby-process2` is derived from `mruby-process`.  However, the build will sometimes fail after a `rake clean` because the `.lock` file points to a commit ID that is only in the other repository.  However, the potential for hard-to-diagnose bugs in this case is pretty high.)

My initial idea for a fix is to name the checkout after the `.gem` file instead of the originating repository but I haven't yet looked into what that entails.

**Comment by katzer** [comment]
Hi, I am the author of `mruby-process2`. I wonder why you're adding both gems to your build. Even if the build system would pick the right repo, both mgems override each other in terms of functionality.

**Comment by suetanvil** [comment]
Hi @katzer,

The above example is contrived.  However, I've run into the case where
I explicitly use `mruby-process2` but several dependencies use
`mruby-process` (specifically `mruby-dir-glob` and `mruby-open3` in my
case.)  This results in the whole build using either `mruby-process`
or `mruby-process2` with no clear way to specify which one wins.
Currently, my dependency order seems to get yours first so everything
works as expected (**and** none of the dependencies are incompatible
with it), but there doesn't seem to be a way to guarantee that.

(As an aside, I seem to have run into a related issue in the
`mruby-process2` gem as well, which I'll file with you later.  I
mention it because it's possible that I've mistaken that for this
issue in some cases.)

PS: Thanks for your ongoing maintenance of `mruby-process2`; it's a
really useful gem.

**Comment by suetanvil** [comment]
(@katzer: it turns out I was adding the dependency incorrectly, so the apparent other issues is my mistake.  I still maintain that the mruby rakefiles should handle duplicate repository names correctly, though.)

**Comment by dearblue** [comment]
If a distinction is made between clone directories for the purpose of addressing this issue, using the name of mgem-list is not sufficient.
The reason is that there are other cases where `git clone` is needed.

  - `gem mgem: "gem-name"`
  - `gem git: "uri"`
  - `gem github: "account/gem-name"`
  - `gem bitbucket: "account/gem-name"`

Ref. https://github.com/mruby/mruby/blob/3.0.0/doc/guides/mrbgems.md#usage

So my idea is to combine the gem directory name with the git-uri converted to CRC-32 code.

```ruby
diff --git a/lib/mruby/build/load_gems.rb b/lib/mruby/build/load_gems.rb
index 6609a5c8e..8d74548e5 100644
--- a/lib/mruby/build/load_gems.rb
+++ b/lib/mruby/build/load_gems.rb
@@ -1,3 +1,5 @@
+autoload :Zlib, "zlib"
+
 module MRuby
   module LoadGems
     def gembox(gemboxfile)
@@ -79,7 +81,8 @@ module MRuby
         gemdir = "#{root}/mrbgems/#{params[:core]}"
       elsif params[:git]
         url = params[:git]
-        gemdir = "#{gem_clone_dir}/#{url.match(/([-\w]+)(\.[-\w]+|)$/).to_a[1]}"
+        gemcode = "%08x" % Zlib.crc32(url)
+        gemdir = "#{gem_clone_dir}/#{url.match(/([-\w]+)(\.[-\w]+|)$/).to_a[1]}@#{gemcode}"
 
         # by default the 'master' branch is used
         branch = params[:branch] ? params[:branch] : 'master'
```

I tried this patch, and now clone directories are distinguished and commit hashes can be applied.

```ruby
# build_config

MRuby::Build.new do |conf|
  conf.toolchain
  conf.gem mgem: "mruby-dir-glob"
  conf.gem github: "iij/mruby-process"
  conf.gem github: "katzer/mruby-process" # uses this gem
  #conf.gem mgem: "mruby-process2"
end
```

I'm not sure if there is another concern.

**Comment by suetanvil** [comment]
I like the simplicity of this solution.  However, it occurred to me earlier today that there are times where I **want** this collision to happen, only in a controlled way.

For example, in my initial example, I was using `mruby-process` from the `mruby-process2` mgem.  In this case, `mruby-process2` is a drop-in replacement for `mruby-process` and (crucially) other gems have `mruby-process` as a dependency.  What I really want is for the build to use `mruby-process2` and for it to satisfy the other gems' dependency on `mruby-process`.  That is, replace `mruby-process` with `mruby-process2` everywhere.

The behaviour I'm currently envisioning is something like:

1. The build system maintains a hash that maps repository directory names (e.g. `mrgem-process`) names to their URLs (e.g. `https://github.com/katzer/mruby-process.git`).
2. If a gem dependency tries to add a repository that is already present and the URL is different, it is a build error and the user needs to change their `build_config.rb`.
3. `conf.gem` gets an extra named argument that tells rake to treat this as the canonical version of this dependency and to silently ignore any attempt to check this out from a different source. My initial thought is to call it `gemdir:` to let the user override the gem directory but also flag it as being the canonical remote repository associated with the name.

So in the above case, rake would fail with an error until I explicitly set `mruby-process2` as belonging to `mruby-process`.  This lets me control what is being used explicitly but will fail with an error instead of providing surprising behaviour.

**Comment by matz** [comment]
Probably recently merged #5638 fixed the issue. @suetanvil could you confirm?

**Comment by suetanvil** [comment]
This change fixes the problem.  The given example now fails with a helpful error message reporting the name collision.

Note that https://github.com/mruby/mruby/pull/5638 seems to have introduced an error, however: code in `load_gems.rb` sometimes uses module `YAML` without first loading the dependency.  I've submitted a pull request to fix this:

https://github.com/mruby/mruby/pull/5656

**Comment by matz** [comment]
#5656 is merged. Can we close this issue now?

**Comment by suetanvil** [comment]
Yes.  It works for me, in any case.
