### ISSUE TITLE
Question - Haskell FFI

### ISSUE THREAD

**Issue by synth-me** [mruby/mruby#5582]
I'm currently working on a project where i may mix both mruby and haskell but i've been facing lots of errors while trying to embed mruby in haskell code using FFI (basically not recognizing libraries and paths), is that possible nowadays ? thanks in advance

**Comment by matz** [comment]
I don't know about Haskell FFI, but I suspect you failed to specify the library path to the FFI. At least mruby can be available from C FFI. If you find any problem on the mruby side, feel free to reopen this issue.
