### ISSUE TITLE
mrb_symbol_value() gives empty string

### ISSUE THREAD

**Issue by sasq64** [mruby/mruby#5583]
Not sure if this is a bug or me mistaking the API if I return a symbol like this:

```cpp
return mrb_symbol_value(mrb_intern_lit(mrb, "dummy"));
```
I always get an empty symbol on the Ruby side ?

**Comment by matz** [comment]
Sounds like a bug, but I need more info, especially reproducing code.

**Comment by sasq64** [comment]
```ruby
    auto* ruby = mrb_open();
    auto sym = mrb_intern_cstr(ruby, "testing");
    mrb_define_global_const(ruby, "TEST", mrb_symbol_value(sym));
    mrb_load_string(ruby, "p TEST.class ; p TEST ; TEST = :testing ; p TEST"); 
```
prints
```
Symbol
:""
:testing
```
```

**Comment by sasq64** [comment]
However, replacing the third line with 
```ruby
mrb_define_global_const(ruby, "TEST", mrb_check_intern_cstr(sym, "testing"));
```
works. But I can only use that workaround when I know the string representation of the symbol.

**Comment by sasq64** [comment]
Actually, this seems to be fixed in the latest version... sorry :)
