### ISSUE TITLE
mruby throw any error with RuntimeError and how can I grab out the 'errno'

### ISSUE THREAD

**Issue by jakitliang** [mruby/mruby#5609]
IO.read() -> error -> **RuntimeError** <- IOError is expected
IO.recv_nonblock() -> error -> **RuntimeError** <- IO::WAIT_READ_EAGAIN is expected
IO.send_nonblock() ~> _setnonblock -> write -> error -> **RuntimeError** <- IO::WAIT_WRITE_EAGAIN is expected

Why did everything thew into `RuntimeError`?

And `SystemCallError` is not found:

```
> SystemCallError
uninitialized constant SystemCallError (NameError)
```

So poor implementation, **how do I code on such an interpreter🙀?**

Okay, I know what the real POSIX error traps, but give me an entry to find out the errono.

Just give me the SystemCallError because there is a method named `errno` with SystemCallError.

I want to pick up the errno and process by my self, just manually.

Otherwise, IO errors should be implemented soon.

If not, the classes of Sockets seems unusable. mruby is not ready for networking programming in pure ruby just now.

--------

Although I can done everything with C, why do I bring this ruby interpreter into mobile Apps? Seems useless and strange.

**Comment by dearblue** [comment]
mruby has a mechanism to allow third parties to provide `SystemCallError`.
It's not fully compatible with CRuby, but you might want to try `mruby-errno`, which is registered at https://github.com/mruby/mgem-list.

```ruby
# build_config

MRuby::Build.new do |conf|
  conf.toolchain
  gembox "default"
  gem mgem: "mruby-errno"
end
```

```console
% bin/mirb
mirb - Embeddable Interactive Ruby Shell

> TCPSocket.open("127.0.0.1", 14142)
Connection refused - connect (Errno::ECONNREFUSED)
> TCPSocket.open("127.0.0.1", 80) { |tcp| tcp.recv_nonblock(200) }
Resource temporarily unavailable - recv (Errno::EWOULDBLOCK)
>
```

**Comment by jakitliang** [comment]
> mruby has a mechanism to allow third parties to provide `SystemCallError`. It's not fully compatible with CRuby, but you might want to try `mruby-errno`, which is registered at https://github.com/mruby/mgem-list.
> 
> ```ruby
> # build_config
> 
> MRuby::Build.new do |conf|
>   conf.toolchain
>   gembox "default"
>   gem mgem: "mruby-errno"
> end
> ```
> 
> ```
> % bin/mirb
> mirb - Embeddable Interactive Ruby Shell
> 
> > TCPSocket.open("127.0.0.1", 14142)
> Connection refused - connect (Errno::ECONNREFUSED)
> > TCPSocket.open("127.0.0.1", 80) { |tcp| tcp.recv_nonblock(200) }
> Resource temporarily unavailable - recv (Errno::EWOULDBLOCK)
> >
> ```

Thank you!

**Comment by matz** [comment]
I will ask the author of `mruby-errno` to allow bundling it in the standard.

**Comment by matz** [comment]
`mruby-errno` is now bundled by 0a6d57ab3c3f2c09bb5471834b615a21693f7033

**Comment by jakitliang** [comment]
> `mruby-errno` is now bundled by [0a6d57a](https://github.com/mruby/mruby/commit/0a6d57ab3c3f2c09bb5471834b615a21693f7033)

Great! Good news!
