### ISSUE TITLE
build error at ssize_t

### ISSUE THREAD

**Issue by yamori813** [mruby/mruby#5617]
I have build error by gcc4 and newlib-3 for realtek soc.

/usr/home/hiroki/rtlbm-mruby/mruby/src/class.c: In function 'mt_put':
/usr/home/hiroki/rtlbm-mruby/mruby/src/class.c:98: error: 'ssize_t' undeclared (first use in this function)
/usr/home/hiroki/rtlbm-mruby/mruby/src/class.c:98: error: (Each undeclared identifier is reported only once
/usr/home/hiroki/rtlbm-mruby/mruby/src/class.c:98: error: for each function it appears in.)
/usr/home/hiroki/rtlbm-mruby/mruby/src/class.c:98: error: expected ';' before 'dpos'
/usr/home/hiroki/rtlbm-mruby/mruby/src/class.c:120: error: 'dpos' undeclared (first use in this function)
rake aborted!

**Comment by matz** [comment]
Fixed by #5616

**Comment by yamori813** [comment]
I have still error. I use gcc4 not MSC.

**Comment by yamori813** [comment]
I seem it's must be include sys/types.h at newlib-3.
