### ISSUE TITLE
Question: Object#instance_exec from C

### ISSUE THREAD

**Issue by dmlary** [mruby/mruby#5631]
I'm trying to do the equivalent of the following ruby code in C, with the body of the block being provided by the user:

```ruby
actor = Actor.new
o = Actor.new
actor.instance_exec(o) do |other|
  pp other: other    # this line (and possibly others come from user)
end
```

I've been able to compile the body `pp other: other` into an `RProc *` with `mrb_generate_code()`, and run it in the context of `actor` with `mrb_top_run(mrb, proc, actor, 0)`, but I hit a dead-end trying to provide the local variables (in this case `other`).

So I tried another approach, generating a Proc using `mrb_load_string()` on:
```ruby
proc do |other|
  pp other: other
end
```

Then used `mrb_yield_cont()` as is done in `mrb_obj_instance_exec()` on the `mrb_value` returned, I got an exception that the `mrb_value` returned from `mrb_load_string()` was not a block.

So I'm kind of stumped, and have been unable to find the right approach in the docs or in the repo source.

So two questions:
* How do I generate a block from a c string that can be passed to `mrb_yield_cont()`, or `mrb_obj_instance_exec()`
* How do I set local variables for an RProc to access when run via `mrb_top_run()`

My goal here is to be able to pre-compile the user provided block bodies, then execute them with the appropriate local variables as events occur.

**Comment by dearblue** [comment]
What you want to do is:

> I'm trying to do the equivalent of the following ruby code in C, with the body of the block being provided by the user:

So, please note that I am avoiding answering the last two questions.

> ```ruby
> actor = Actor.new
> o = Actor.new
> actor.instance_exec(o) do |other|
>   pp other: other    # this line (and possibly others come from user)
> end
> ```

If you want to do this `actor.instance_exec` in C, try `mrb_yield_with_class()`.

```c
mrb_value actor = ...;
mrb_value o = ...;
mrb_int argc = 1;
mrb_value argv[] = { o };
mrb_value block = ...;
struct RClass *tc = mrb_class_ptr(mrb_singleton_class(mrb, actor));
mrb_value ret = mrb_yield_with_class(mrb, block, argc, argv, actor, tc);
```

NOTE:
  - The reason to use `mrb_singleton_class()` instead of `mrb_singleton_class_ptr()` is to raise an exception if the object cannot be made a singleton object.
  - If `actor` is not to be made into a singleton object, use `mrb_obj_class()` instead of `mrb_singleton_class()`.

    ```c
    struct RClass *tc = mrb_obj_class(mrb, actor);
    ```

**Comment by dmlary** [comment]
That worked perfectly.  Thank you.

I was able to use the proc I had created with `mrb_load_string()` as `block` in the example above:
```c
snprintf(buf, sizeof(buf), "proc do |other|\n%s\nend", user_script);
mrb_value block =  mrb_load_string(mrb, buf);
```
