### ISSUE TITLE
mrb_kwargs documentation is outdated

### ISSUE THREAD

**Issue by RazrFalcon** [mruby/mruby#5649]
This line:

https://github.com/mruby/mruby/blob/a8f0e7910707194feee1d41db1a6915fb7cf26f4/include/mruby.h#L968

assumes that `kw_names` are `const char **` while they are `const mrb_sym *` since recently. 

Also, maybe `mrb_kwargs` documentation should use `mrb_intern_lit` instead `MRB_SYM`, because the later one doesn't work out of the box (or at least requirers some additional work).

**Comment by dearblue** [comment]
Thank you for the report. It was a good opportunity for me to rethink.
I'm suggesting an improvement as #5653.
