### ISSUE TITLE
Question - How to migrate module/class objects to new VM

### ISSUE THREAD

**Issue by lemmuh** [mruby/mruby#5655]
The mruby library 'mruby-thread' is emulating a new thread by using a new mruby VM. That works pretty well. 

However the module/class objects are not migrated. 

How can this be done ?

**Comment by matz** [comment]
Currently, it's not possible. You can define all shared classes and module in the ruby programs and load them from each VM.
Or define your library as a mrbgem, so that all features can be accessed from all VMs.
