### ISSUE TITLE
Remove bitfields

### ISSUE THREAD

**Issue by dantecatalfamo** [mruby/mruby#5657]
Hello,

I'm trying to write a wrapper for mruby that would allow you to embed it into a zig program.

Unfortunately because many of the structs in mruby use bitfields, the structs can only be opaque types. This is a huge limit since it means you can't access any fields on `mrb_state` or many other important structs.

Would it be possible to remove the usage of bitfields in the mruby codebase?

Thank you,
Dante

**Comment by dantecatalfamo** [comment]
I've been able to work around this by writing C wrapper functions

**Comment by matz** [comment]
Removing bitfields are too much pain for us. I close this issue since you have a workaround.
