### ISSUE TITLE
mrbc with compile switch -O0 

### ISSUE THREAD

**Issue by kaz0505** [mruby/mruby#5661]
Is it possible to add a compile switch to suppress mrbc optimization?

```
mrbc -O0 sample.rb 
```

**Comment by matz** [comment]
Peephole optimization? Hmm, let me think.

**Comment by matz** [comment]
We will add `--no-optimize` option to `mrbc`. Soon to be committed.

**Comment by kaz0505** [comment]
Thank you!

**Comment by matz** [comment]
`--no-optimize` option turns off both constant folding (`1+2` → `3`) and peephole optimization (`LOADI R4 10; MOVE R2 R4` → `LOADI R2 10`). Is it OK?

**Comment by kaz0505** [comment]
That's good.

Mainly, no optimizations switch is useful for mruby/c VM development.

Thank you.
