### ISSUE TITLE
/code/mruby/include/mruby/presym/enable.h:10:10: fatal error: 'mruby/presym/id.h' file not found

### ISSUE THREAD

**Issue by pschrammel** [mruby/mruby#5685]
Hi,

I'm currently having trouble to compile a project. I get the error above. It seems id.h is not created. Following the calls I can't find where Presym's write_id_header is ever called. I was able to compile the project some time ago and didn't have this issue. Perhaps I misconfigured it.

mruby version: 3.0.0

Thx

**Comment by dearblue** [comment]
Is this helpful?
  - https://github.com/mruby/mruby/issues/5393#issuecomment-810852316
  - https://github.com/mruby/mruby/blob/3.1.0-rc2/doc/guides/link.md#normal-compilation-process
