### ISSUE TITLE
No "make install" ?

### ISSUE THREAD

**Issue by mdorier** [mruby/mruby#5712]
Unless I missed something, there is no `rake install` or `make install` command available to install mruby once it's built. Looking at the homebrew formula (here: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/mruby.rb), I see that some directories are "manually" copied to the destination.

Any reason for not providing an "install" target? Any chance it could be added (with a prefix that can be changed)?

**Comment by matz** [comment]
We consider the real product of `mruby` project is `libmruby.a` library and header files to embed Ruby VM in the application.
So the executable binary `mruby` is only a sample program for the project. That is the reason we don't have `install` target in the `rakefile`.

But we are open for the opinion. What do you really want to install, and where do you want to install?

**Comment by mdorier** [comment]
I think what needs to be installed is everything that is in `build/host` after calling `rake`, as well as the  content of the `include` directory in the source tree (paying attention to the fact that `build/host` also has an `include/mruby` with a few generated header files).

This is what homebrew does. I also made mruby available as a package for the Spack package manager for high-performance computing (https://github.com/mdorier/mdorier-spack-packages/blob/main/packages/mruby/package.py) and this is what my package file does as well.
