### ISSUE TITLE
mrb_type segfaults when passing a symbol

### ISSUE THREAD

**Issue by mdorier** [mruby/mruby#5715]
I'm getting some problems with symbols, which can be reproduced with the code herafter:

```cpp
#include <mruby.h>
#include <mruby/value.h>
#include <mruby/compile.h>

static mrb_value f1(mrb_state* mrb, mrb_value self);
static mrb_value f2(mrb_state* mrb, mrb_value self);

int main() {
    mrb_state* mrb = mrb_open();
    mrb_define_module_function(mrb, mrb->kernel_module, "f1", f1,  MRB_ARGS_ANY());
    mrb_define_module_function(mrb, mrb->kernel_module, "f2", f2,  MRB_ARGS_ANY());

    auto script = R"ruby(
        def g()
          return :aaa
        end
        p f1()  # this prints 8.4367031112691e-299, why???
        p f2()
    )ruby";

    mrb_load_string(mrb, script);
    mrb_close(mrb);
}

mrb_value f1(mrb_state* mrb, mrb_value self) {
    // create a symbol, check its type, print it, and return it
    mrb_sym my_sym = mrb_intern_cstr(mrb, "abc");
    mrb_value my_val = mrb_symbol_value(my_sym);
    mrb_p(mrb, my_val); // prints 8.4367031112691e-299, why???
    mrb_type(my_val);
    return my_val;
}

mrb_value f2(mrb_state* mrb, mrb_value self) {
    mrb_value obj = mrb_obj_new(mrb, mrb->object_class, 0, NULL);
    mrb_value ret = mrb_funcall(mrb, obj, "g", 0);
    mrb_p(mrb, ret); // prints :aaa
    mrb_type(ret); // segfaults
    return ret;
}
```

(it's in C++, hence the raw string to define the script variable)

In `f1`, I create a symbol using `mrb_intern_cstr`, then convert it into an `mrb_value`, and print it using `mrb_p`, but instead of printing the symbol, `mrb_p` prints a floating point number.

In `f2`, the symbol is obtained by falling a function `g` which was defined in ruby. `mrb_p` correctly displays the symbol, however `mrb_type` segfaults.

**Comment by dearblue** [comment]
I tried with "master" and "3.1.0", but could not reproduce the problem.

```console
% git checkout 3.1.0
% rake -m clean all
% c++ `bin/mruby-config --cflags --ldflags` -std=gnu++11 topic5715.cc `bin/mruby-config --libs`
% ./a.out
:abc
:abc
:aaa
:aaa
```

Can you tell me the "build_config.rb" file when you build mruby and the command line options when you turn your code into an executable?

**Comment by mdorier** [comment]
Thanks for looking into it. Your answer made me suspect an installation problem on my side and indeed, when my project was linking against a libmruby.a version 3.1.0 but was relying on headers for 3.0.0. (To be more precise, I was asking my project to look for the mruby lib/header in the build/host directory of the mruby 3.1.0 source, but since mruby headers are not actually copied there during installation, my project failed to find them and was relying on what it found in /usr/local/include, which corresponded to an old installation of 3.0.0).

I'm closing the issue.

**Comment by matz** [comment]
Probably addressing #5712 help you?

**Comment by mdorier** [comment]
> 

Yes, it definitely will.
