### ISSUE TITLE
Suggestion: add auxiliary data field (void*) to RClass

### ISSUE THREAD

**Issue by mdorier** [mruby/mruby#5721]
The `mrb_state` structure has a `void* ud` auxiliary data that can be used to attach user-data to the `mrb_state`. It would be nice if other structures, in particular `RClass` (or more generally `MRB_OBJECT_HEADER`) had this as well.

In a project of mine I implement a mapping between various C++ classes and corresponding `RClass`s , so that I know how to convert an `mrb_value` into the right C++ type, do type checking, and so on. I do so by maintaining the mapping in the `ud` field of the `mrb_state`. This requires for instance an `std::unordered_map` mapping an `RClass` pointer to a C++ structure containing type information. So any operation on such a mapping requires a lookup in a hash table. With a `void* ud` field in `RClass`, I would be able to associate my C++ type information structure directly with the corresponding `RClass`.

**Comment by matz** [comment]
That would be nice but the change could make mruby consume more memory. Considering mruby's memory constraints, and how often `ud` would be used, the addition does not seem to be a fair trade.

**Comment by mdorier** [comment]
Maybe it could be optionally enabled via a macro?

**Comment by dearblue** [comment]
:smiley_cat: I want to use it too, so get two `ud`s ready! This is a joke.

It seems difficult to determine if one is sufficient and who the owner of each object is.
Given that, I think a combination of "instance variable" and `mrb_data_object_alloc()` would be sufficient.

**Comment by mdorier** [comment]
I think you're right, and even using the `ud` field associated with the `mrb_state` seems dangerous retrospectively: if I write a gem that uses it, I can't guarantee that another gem won't be using it as well for something different.

I'm closing the issue.
