### ISSUE TITLE
Removing element from an array at specified index

### ISSUE THREAD

**Issue by mdorier** [mruby/mruby#5723]
This issue is really 2 questions about doing the same kind of thing:
- I couldn't find a function in `mruby/array.h` to remove an element from an array at a specific index. Is there such a function?
- Assuming that I don't care about the order of elements and I want to be efficient, would it be valid to rely on `RARRAY_PTR` and `RARRAY_LEN` to assign the last element of the array at the place to erase, then use `ARY_SET_LEN` to decrease the size by 1?
Something like the following:
```
RARRAY_PTR(a)[index] = RARRAY_PTR(a)[RARRAY_LEN(a)-1];
ARY_SET_LEN(RARRAY(a), RARRAY_LEN(a)-1)
```

**Comment by mdorier** [comment]
Thanks! Regarding the second method, would that code be correct?

**Comment by matz** [comment]
The code in the first post? Yes, basically. `mrb_ary_pop()` does slightly more complex though.

**Comment by swagtoy** [comment]
I am also just going to do it similar to OP. But is there a reason there is not an API call for this in array.h?
