### ISSUE TITLE
codegen error when assigning to a fully qualified constant

### ISSUE THREAD

**Issue by lopopolo** [mruby/mruby#5752]
This reproduces on 3.1.0 branch and the latest master.

```console
$ ./bin/mruby -e '::MyClass = Class.new'
-e:1: unknown lhs
$ ./bin/mruby -e '::MyConst = 7'
-e:1: unknown lhs
```

**Comment by lopopolo** [comment]
one thing that is a bit weird here is codegen failures behave somewhat like exceptions but they do not have a class associated with them and are uncatchable.

**Comment by dearblue** [comment]
> one thing that is a bit weird here is codegen failures behave somewhat like exceptions but they do not have a class associated with them and are uncatchable in `mirb`. They are not, for example, `SyntaxError`s.

It seems that even in CRuby, `ScriptError` exceptions cannot be caught within the same compilation unit.
In the presented example, the `eval` method can be used to catch the part where the `ScriptError` exception occurs.
The `ScriptError` exception does not fit into the `StandardError` exception, so the exception class must be explicitly specified.

```console
% bin/mirb
mirb - Embeddable Interactive Ruby Shell

> begin; eval("::MyClass = Class.new") ; rescue ScriptError => e ; p e ; end
(eval):1: unknown lhs
codegen error (ScriptError)
 => codegen error (ScriptError)
```

However, it forces unnecessary output to `stderr` and I can't get the details in `Exception#message`. I would like to change this behavior (in the future).

**Comment by matz** [comment]
The original issue was fixed. Thank you for the report.
The issue regarding `ScriptError` should be the independent issue.
