### ISSUE TITLE
Add RUBY_VERSION, RUBY_PLATFORM and RUBY_ENGINE constants.

### ISSUE THREAD

**Issue by postmodern** [mruby/mruby#576]
mruby should at a bare minimum define `RUBY_VERSION`. Maybe `RUBY_PLATFORM` and `RUBY_ENGINE` could also be defined? I'm interested in implementing this, would `mrb_init_object` (`src/object.c:268`) be the right place to define these top-level constants?

**Comment by slashmili** [comment]
How about `MRUBY_PLATFORM`? Is there any plan to add it?

**Comment by matz** [comment]
Without autoconf etc, having RUBY_PLATFORM is more difficult than it looks.
