### ISSUE TITLE
A exception in fiber corrupses call-stack. Only when using mrb_funcall().

### ISSUE THREAD

**Issue by haramako** [mruby/mruby#5781]
Hi.

I encountered a problem in Fiber.

When call Fiber#resume by mrb_funcall() and fiber raise a exception.
Stack is broken.

But call Fiber#resume in mrb_load_string() is OK. (So in ruby scripting, no problem)

I wrote a reproduct code of this problem.

```c
// fiber_problem.c in mruby directory.
#include "mruby.h"
#include "mruby/compile.h"

int main(int argc, char **argv)
{
    int n = 0; // Change to n = 1, no error occured.

    struct mrb_state *mrb = mrb_open();

    mrb_value fiber = mrb_load_string(mrb, "$f = Fiber.new { raise 'err' }"); // raise in fiber

    if( n == 0 ){
        mrb_funcall(mrb, fiber, "resume", 0); // NG
    }else{
        mrb_load_string(mrb, "$f.resume"); // OK
    }

    mrb_load_string(mrb, "1"); // # segv in mrb_vm_ci_target_class() when n == 0

    mrb_close(mrb);

    return 0;
}
```

```
$ gcc -I include fiber_problem.c build/host/lib/libmruby.a -lm && ./a.out
zsh: segmentation fault (core dumped)  ./a.out
```

I read fiber's code and try to fix this problem, but not yet.

Regard,

**Comment by dearblue** [comment]
If my understanding is correct, we cannot call the `Fiber#resume` method in `mrb_funcall()`.
It should lead to an exception (`can't cross C function boundary (FiberError)`).

May need to do `fiber_check_cfunc()` with `fiber_resume()`?

```diff
diff --git a/mrbgems/mruby-fiber/src/fiber.c b/mrbgems/mruby-fiber/src/fiber.c
index 4fca6cae0..d4d872d18 100644
--- a/mrbgems/mruby-fiber/src/fiber.c
+++ b/mrbgems/mruby-fiber/src/fiber.c
@@ -267,6 +267,7 @@ fiber_resume(mrb_state *mrb, mrb_value self)
   mrb_int len;
   mrb_bool vmexec = FALSE;
 
+  fiber_check_cfunc(mrb, mrb->c);
   mrb_get_args(mrb, "*!", &a, &len);
   if (mrb->c->ci->cci > 0) {
     vmexec = TRUE;
```

**Comment by haramako** [comment]
Thank you for your advice!

I'll call `Fiber#resume` from ruby.

**Comment by haramako** [comment]
And I confirmed your code make this problem safe. I'll make PR

**Comment by dearblue** [comment]
I just remembered something.
We can also use `mrb_fiber_resume()` before entering the mruby VM (e.g. from `main()`).

**Comment by matz** [comment]
#5782 merged.
