### ISSUE TITLE
In some cases `MRB_PROC_ORPHAN` is not set

### ISSUE THREAD

**Issue by dearblue** [mruby/mruby#5786]
1. when an exception occurs

    ```console
    % cat ophan1.rb
    def a(&b)
      $b = b
      raise "!"
    end

    begin
      a { break 1 }
    rescue
      p $b.call
    end

    % bin/mruby ophan1.rb
    1

    % ruby31 ophan1.rb
    ophan1.rb:7:in `block in <main>': break from proc-closure (LocalJumpError)
            from ophan1.rb:9:in `rescue in <main>'
            from ophan1.rb:6:in `<main>'
    ophan1.rb:3:in `a': ! (RuntimeError)
            from ophan1.rb:7:in `<main>'
    ```

 2. when the block is received as `&blk` and the variable is changed

    ```console
    % cat ophan2.rb
    def a(&b)
      c = b
      b = nil
      c
    end

    p a { break 1 }.call

    % bin/mruby ophan2.rb
    1

    % ruby31 ophan2.rb
    ophan2.rb:7:in `block in <main>': break from proc-closure (LocalJumpError)
            from ophan2.rb:7:in `<main>'
    ```

The fix I came up with for now is to separate the block variables placed on the stack into two.
One of the block variables would be immutable and invisible within the method, and would be set with `OP_ENTER`, and `MRB_PROC_ORPHAN` would be set with `cipop()`.
Another of the block variables, accessible as a variable as before, will be copied by `OP_ENTER`.

The C functions are treated as before, but `MRB_PROC_ORPHAN` is set in `cipop()`.

However, it would consume extra stack and I couldn't decide if semantics should be preferred.
Therefore, I am leaving this as an issue in the hope that there is another solution that is more preferable.

**Comment by matz** [comment]
Consuming more space is not preferable. I will think about another way.

**Comment by matz** [comment]
The "space" above means stack space.  Maybe we should add a reference to a block (Proc object) to mrb_callinfo.

**Comment by matz** [comment]
Fixed. Keeping block information in the stack is more memory efficient, but more complex. This time, I take simplicity over efficiency. Maybe we will address later.
