### ISSUE TITLE
    l

### ISSUE THREAD

**Issue by xor256** [mruby/mruby#5807]
error: implicit declaration of function ‘RSTRING_PTR’ [-Wimplicit-function-declaration]
   32 |  const char *return_c_string = RSTRING_PTR(napis);
      |                                ^~~~~~~~~~~
error: initialization of ‘const char *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]

example from https://mrubybyexample.fazibear.me/

```
 napis = mrb_str_new_cstr(mrb, "żółw");
 const char *return_c_string = RSTRING_PTR(napis);
 printf("retrun_c_string: %s\n", return_c_string);

```
I run 

**gcc -Wall -pedantic -pedantic-errors -Os -std=c99 -I ~/mruby/include/ -o program program.c ~/mruby/build/host/lib/libmruby.a -lm**

**Comment by matz** [comment]
I assume this issue was solved. OK?
