### ISSUE TITLE
Unaligned address error on MIPS R3000

### ISSUE THREAD

**Issue by vivi168** [mruby/mruby#5847]
Hello

I'm encountering a memory alignement bug, happening randomly, when running mruby code on the playstation.

I'm using `mipsel-none-elf-gcc` and I've compiled mruby and the final executable with the following options `-g -O2 -G0 -ffreestanding -nostdlib -mno-unaligned-access`. I also use `MRB_NO_FLOAT` and `MRB_NO_STDIO`

The bug originates from the `mrb_object_dead_p` function of the garbage collector. I can't reproduce it every time I run my program. Sometimes it crashes right at the beginning, sometimes, I can't reproduce it at all. Since it comes from the garbage collector, maybe it has to do with the frequency that it runs at.

the error is about an unaligned address used for the `lw` instruction. I tried recompiling with `-mno-unaligned-access` to no avail.

```
Unaligned address 0x00000007 in LW from 0x8001d350
First chance exception: LoadAddressError from 0x8001d350
```

Here is the disassembly of the function

```
8001d324 <mrb_object_dead_p>:
8001d324:       8c860058        lw      a2,88(a0)
8001d328:       00000000        nop
8001d32c:       10c0000c        beqz    a2,8001d360 <mrb_object_dead_p+0x3c>
8001d330:       00000000        nop
8001d334:       24c20018        addiu   v0,a2,24
8001d338:       24c36000        addiu   v1,a2,24576
8001d33c:       00a2102b        sltu    v0,a1,v0
8001d340:       14400003        bnez    v0,8001d350 <mrb_object_dead_p+0x2c>
8001d344:       0065182b        sltu    v1,v1,a1
8001d348:       10600007        beqz    v1,8001d368 <mrb_object_dead_p+0x44>
8001d34c:       00000000        nop
8001d350:       8cc60008        lw      a2,8(a2)                        ; <============== crash right here
8001d354:       00000000        nop
8001d358:       14c0fff6        bnez    a2,8001d334 <mrb_object_dead_p+0x10>
8001d35c:       00000000        nop
8001d360:       03e00008        jr      ra
8001d364:       24020001        li      v0,1
8001d368:       8c830078        lw      v1,120(a0)
8001d36c:       8ca20008        lw      v0,8(a1)
8001d370:       38630003        xori    v1,v1,0x3
8001d374:       00021202        srl     v0,v0,0x8
8001d378:       00431024        and     v0,v0,v1
8001d37c:       30420003        andi    v0,v0,0x3
8001d380:       1440fff7        bnez    v0,8001d360 <mrb_object_dead_p+0x3c>
8001d384:       00000000        nop
8001d388:       90a20008        lbu     v0,8(a1)
8001d38c:       00000000        nop
8001d390:       38420004        xori    v0,v0,0x4
8001d394:       03e00008        jr      ra
8001d398:       2c420001        sltiu   v0,v0,1
```

I don't know what could be the cause of the misalignment. I wonder if it's mruby fault.

Please tell me I you need more details.

**Comment by matz** [comment]
It seems `heap->next` is uninitialized or broken. Do you have a Ruby program to reproduce the error (on playstation)?

**Comment by vivi168** [comment]
I think I found the source of the bug.

It isn't mruby after all, but the memory allocation implementation of Psy-Q SDK (the playstation SDK)

There is a bug with malloc and free not correctly releasing memory. And one should use the suffixed version `malloc3`, `free3` etc.

I commented out the un-suffixed declarations and declared aliases in the library `malloc.h` header.
After recompiling mruby with these changes, I wasn't able to reproduce the bug.

```
#define InitHeap InitHeap3
#define free free3
#define malloc malloc3
#define calloc calloc3
#define realloc realloc3
```

I thought that mruby implemented its own malloc, realloc, free, etc through `mrb_malloc`, `mrb_free` etc.
It turns out it isn't the case: I found that mruby uses system `realloc` and `free` behind the scene, through `mrb->allocf` and `mrb_default_allocf`.

After declaring the aliases above, mruby now jumps to the correct functions. I also modified my code to use the version 3.

```
800281cc <mrb_default_allocf>:
800281cc:       10c00003        beqz    a2,800281dc <mrb_default_allocf+0x10>
800281d0:       00a02025        move    a0,a1
800281d4:       08015978        j       800565e0 <realloc3>
800281d8:       00c02825        move    a1,a2
800281dc:       27bdffe8        addiu   sp,sp,-24
800281e0:       afbf0014        sw      ra,20(sp)
800281e4:       0c015810        jal     80056040 <free3>
800281e8:       00000000        nop
800281ec:       8fbf0014        lw      ra,20(sp)
800281f0:       00001025        move    v0,zero
800281f4:       03e00008        jr      ra
800281f8:       27bd0018        addiu   sp,sp,24
```

Thank you for your quick reply. When you mentionned `heap->next` it made me realize where the bug could come from.

I think I can close the ticket.

**Comment by matz** [comment]
Nice. Thank you for the report.
