### ISSUE TITLE
`mrb_bug()` may raise an exception

### ISSUE THREAD

**Issue by dearblue** [mruby/mruby#5852]
`mrb_bug()` calls `exit()`, which is not caught by mruby.
However, it calls `mrb_vformat()` before that, which may raise an exception `NoMemoryError` or `RuntimeError`.

It may be desirable to replace `mrb_vforamt()` with a structure that directly outputs a compatible format to `stderr`, or some other mechanism.

\# :thinking:

  - Compatible format specifiers should not output `inspect` results (?)
  - Should not use `mrb_any_to_s()` to get the class name of an instance internally (?)
  - Should not call `mruby_vm_exec()`, create objects, etc (?)
  - How should parameter compatibility with `mrb_warn()` (?)

**Comment by matz** [comment]
Addressed by 82a48bd
