### ISSUE TITLE
3.2.0-rc build error on FreeBSD

### ISSUE THREAD

**Issue by yamori813** [mruby/mruby#5909]
I have build error on FreeBSD/mips 12. This environment use gcc 4. I use ZRouter for build tool.

FreeBSD/amd64 have no error. I think because of clang.

CC    build/repos/zrouter/mruby-socket/src/socket.c -> build/zrouter/mrbgems/mruby-socket/src/socket.o
/usr/home/hiroki/obj/usr/home/hiroki/ZRouter/ports/usr/home/hiroki/ZRouter/ports/lang/mruby/mruby-3.2.0-rc/build/repos/zrouter/mruby-socket/src/socket.c: In function 'mrb_mruby_socket_gem_final':
/usr/home/hiroki/obj/usr/home/hiroki/ZRouter/ports/usr/home/hiroki/ZRouter/ports/lang/mruby/mruby-3.2.0-rc/build/repos/zrouter/mruby-socket/src/socket.c:911: error: implicit declaration of function 'mrb_mod_cv_get'
/usr/home/hiroki/obj/usr/home/hiroki/ZRouter/ports/usr/home/hiroki/ZRouter/ports/lang/mruby/mruby-3.2.0-rc/build/repos/zrouter/mruby-socket/src/socket.c:911: error: incompatible types in assignment
rake aborted!

**Comment by dearblue** [comment]
I am guessing from the error that you are referring to https://github.com/iij/mruby-socket.

  - In mruby-3.2.0.rc, line 911 does not reference `mrb_mod_cv_get`.
    <https://github.com/mruby/mruby/blob/3.2.0-rc/mrbgems/mruby-socket/src/socket.c#L911>
  - In iij/mruby-socket, line 911 references `mrb_mod_cv_get`.
    <https://github.com/iij/mruby-socket/blob/a725ac4617da447957de1b0c7c5173b640083238/src/socket.c#L911>

I think that some of the gems dependencies imported by your build configuration file specify iij/mruby-socket.

Try putting `conf.gem core: "mruby-socket"` in front of every `conf.gem` or `conf.gembox`.

**Comment by matz** [comment]
@dearblue Thank you!
