### ISSUE TITLE
An issue with IO#gets method in mruby-3.2.0-rc2

### ISSUE THREAD

**Issue by masahino** [mruby/mruby#5913]
I am experiencing an issue with the IO#gets method in mruby-3.2.0-rc2.
When running the following script 'test.rb':

```ruby
File.open('test.txt') do |f|
  while line = f.gets
    puts line
  end
end
```

test.txt:
```
a
bb
ccc
dddd
eeeee
```

output:
```
$ bin/mruby test.rb
a
bb
cc
c
dddd
ee
eee
```

**Comment by matz** [comment]
Sorry, this is a blocker. I will fix soon.
