### ISSUE TITLE
Could we provide a glossary?

### ISSUE THREAD

**Issue by ccmywish** [mruby/mruby#5916]
Last year, I tried to read the source code of mruby. However, I only managed to handle the parser part, the VM part is more difficult to understand.  So, could we provide a glossary like @tenderlove 's https://github.com/tenderlove/ruby-glossary ?

And I suggest maintaining a [dictionary](https://github.com/ccmywish/CRuby-Source-Code-Dictionary) using this [cr.rb](https://github.com/cryptic-resolver/cr.rb) cli tool.

Although the issue https://github.com/tenderlove/ruby-glossary/issues/1 is denied, I still think using a cli tool as a dictionary tool to understand our code is helpful. In fact, we can make the glossary just a `README.md` file for the dictionary repo.

## images example

![image](https://user-images.githubusercontent.com/63459097/215270072-2a60148e-438b-4e1f-af4a-0307c2278020.png)

![image](https://user-images.githubusercontent.com/63459097/215270084-af376e1d-23d6-4acf-a3ad-008a56256848.png)

**Comment by dearblue** [comment]
I think it is a good idea that a glossary exists.
But what about adding it as `mruby/doc/glossary.md` instead of a separate repository?
I believe it is not difficult to convert to another format (`.toml` in cr.rb?) even if it is markdown, as long as we set some rules.

For example (?),

```markdown
## Internal Implements <!-- category -->

### callinfo <!-- wording -->

<!-- text -->
It means "Call Information".
Manages control information about running methods or blocks.

acronyms: ci <!-- attribute for acronyms -->

see also: ... <!-- attribute for relational wordings -->
```

**Comment by rubyFeedback** [comment]
I agree it would be nice to have it into doc/ - it can be kept in a variant others can then use to e. g. generate other format/variants. Biggest first issue is always getting people to commit to documentation - everyone wants to prefer on the code. :)

**Comment by ccmywish** [comment]
Hi @dearblue and @rubyFeedback,

I agree with you.

I think it is really better to save it in to `/doc`. tenderlove's ruby glossary has been merged into [official ruby repo](https://github.com/ruby/ruby/blob/master/doc/contributing/glossary.md).

I've updated `cr.rb` and now manually maintain two repos to keep track both of them irregularly. And welcome contributions!

1. https://github.com/ccmywish/CRuby-Source-Code-Dictionary
2. https://github.com/ccmywish/mruby-Source-Code-Dictionary

**Usage:**
```bash
gem install cr.rb
cr -a ccmywish/CRuby-Source-Code-Dictionary
cr -a ccmywish/mruby-Source-Code-Dictionary
````

**Comment by matz** [comment]
Is [cr.rb](https://github.com/cryptic-resolver/cr.rb) removed?

**Comment by ccmywish** [comment]
Just now I made `cr.rb` and the dictionary data private. Because I've collected 2 years of data of 2000+ acronyms. There are no any feedbacks from anyone, so I just thought it's no use to be in public.

Are you interested in it? I can make it public again. @matz

**Comment by matz** [comment]
I am interested. I am an open-source fundamentalist. I wish every software to be open if possible.

**Comment by ccmywish** [comment]
@matz  I've got it back haha. Try `gem install cr.rb`

I've tested it on Windows and Ubuntu

New organization: https://github.com/CrypticResolver.  Data is here.
