### ISSUE TITLE
Incorrect checksum error in malloc. by mruby3.2.0-rc4.

### ISSUE THREAD

**Issue by HirohitoHigashi** [mruby/mruby#5929]
I'm trying mruby3.2.0-rc4. When I use mrbc command, my system (MacOS) detected error about memory allocation.

```
$ mrbc test_op_basic.rb
mrbc(9967,0x7ff858363680) malloc: Incorrect checksum for freed object 0x7fae2000b400: probably modified after being freed.
Corrupt value: 0x3100620100610100
mrbc(9967,0x7ff858363680) malloc: *** set a breakpoint in malloc_error_break to debug
```

I try run mrbc in lldb (debugger), below.
```
$ lldb mrbc test_op_basic.rb
(lldb) target create "mrbc"
Current executable set to '/Users/hirohito/work/mruby/bin/mrbc' (x86_64).
(lldb) settings set -- target.run-args  "test_op_basic.rb"
(lldb) run
Process 10012 launched: '/Users/hirohito/work/mruby/bin/mrbc' (x86_64)
mrbc(10012,0x7ff858363680) malloc: Incorrect checksum for freed object 0x10080b400: probably modified after being freed.
Corrupt value: 0x3100620100610100
mrbc(10012,0x7ff858363680) malloc: *** set a breakpoint in malloc_error_break to debug
Process 10012 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00007ff8149ee22a libsystem_kernel.dylib`__pthread_kill + 10
libsystem_kernel.dylib`:
->  0x7ff8149ee22a <+10>: jae    0x7ff8149ee234            ; <+20>
    0x7ff8149ee22c <+12>: movq   %rax, %rdi
    0x7ff8149ee22f <+15>: jmp    0x7ff8149e7ce2            ; cerror_nocancel
    0x7ff8149ee234 <+20>: retq
Target 0: (mrbc) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x00007ff8149ee22a libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007ff814a25f7b libsystem_pthread.dylib`pthread_kill + 263
    frame #2: 0x00007ff81496fca5 libsystem_c.dylib`abort + 123
    frame #3: 0x00007ff814885637 libsystem_malloc.dylib`malloc_vreport + 888
    frame #4: 0x00007ff81489a897 libsystem_malloc.dylib`malloc_zone_error + 178
    frame #5: 0x00007ff81487e686 libsystem_malloc.dylib`small_free_list_remove_ptr_no_clear + 1000
    frame #6: 0x00007ff81487bbb0 libsystem_malloc.dylib`free_small + 847
    frame #7: 0x00007ff814913860 libsystem_c.dylib`fclose + 140
    frame #8: 0x0000000100002824 mrbc`main(argc=<unavailable>, argv=<unavailable>) at mrbc.c:353:3 [opt]
    frame #9: 0x00007ff8146f3310 dyld`start + 2432
```

However, this error does not always occur.
Do you have any idea?

My environment.
MacOS Ventura 13.2.1 intel
$ cc -v
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin22.3.0
Thread model: posix

[test_op_basic.rb](https://github.com/mruby/mruby/files/10740117/test_op_basic.rb.txt)

**Comment by matz** [comment]
I cannot reproduce the issue on my MacOS (M1 Macbook Air; Ventura 13.1; clang 12.0.5). Any info please?
Probably on Intel Mac only?

**Comment by mimaki** [comment]
I tried it on 2 Intel Macs and it didn't reproduce.
- Intel Macbook Pro; Monterey 12.5.1; clang 13.1.6
- Intel Macbook Pro; Big Sur 11.6.2; clang 13.0.0

It doesn't seem to be because it's an Intel Mac.
Is this an effect of clang's version?

**Comment by Hir0** [comment]
M1 mac
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.3.0
Thread model: posix

I cannot reproduce the issue.

**Comment by HirohitoHigashi** [comment]
Thanks for the additional tests.
My other intel mac installed only command line tools did not causes same error. But on my regular using mac with Xcode fully installed, I still get a same error.
So I think I shot a very minor bug in the clang lib or Xcode lib for intel processor.

I close this issue.
Thank you.
