### ISSUE TITLE
How do you set an attr_accssor from the C API?

### ISSUE THREAD

**Issue by neet93** [mruby/mruby#5930]
All I see this this function `mrb_attr_get()`.

**Comment by matz** [comment]
In principle, it's mruby's policy to write in Ruby if it is easier to write in Ruby. Creating accessors is one of them.
If you really want to do it in C, you will have to write your own accessor manually.

If you really see the need for writing accessors in C, persuade me to prepare helper functions.

**Comment by neet93** [comment]
Okay, thank you. That makes sense.
