### ISSUE TITLE
TCPSocket#write is failed

### ISSUE THREAD

**Issue by bamchoh** [mruby/mruby#5943]
Hi, thank you very much for development of mruby

I found a issue. I executed below script (`test.rb`) by command prompt like `mruby.exe test.rb`

```ruby
TCPServer.open("127.0.0.1", 0) { |serv|
  c = TCPSocket.new(*serv.addr.values_at(3,1))
  s = serv.accept

  c.send "foo", 4
  p s.recv(10)

  c.write "bar"
  p s.recv(10)
}
```

Then an below exception happens

```
trace (most recent call last):
        [3] test.rb:1
        [2] test.rb:1:in open
        [1] test.rb:8
test.rb:8:in write: Bad file descriptor - syswrite (Errno::EBADF)
```

* I don't face this issue with 3.1.0. When I use 3.2.0, this issue occurs.

* I'm Windows user. I'm using Windows 10 Pro or Windows 11. I found this issue with both Windows version.

* I'm building `mruby.exe` by using `ridk` which is installed by Ruby installer for Windows (`3.1.2p20 ) like below command.
```
ridk exec rake all test
```

**Comment by matz** [comment]
I got it. I re-implemented IO methods in C, so that dynamic binding does not work for Windows.
I will address the issue somehow soon.

**Comment by bamchoh** [comment]
Thank you very much for quick fix. I could write with TCPSocket#write method.

**Comment by matz** [comment]
Probably we will release 3.2.1 soon.
