### ISSUE TITLE
Behavior of calling method with a hash varaible

### ISSUE THREAD

**Issue by bamchoh** [mruby/mruby#5944]
Excuse me, I'd like to know if this is a specification for mruby or not.

When I executed below code, mruby raises exception.

Code:
```ruby
def foo(bar)
    p bar
end

foo :var1 => :a
```

Output:
```
trace (most recent call last):
        [1] ..\..\scripts\test2.rb:5
..\..\scripts\test2.rb:1:in foo: wrong number of arguments (given 1, expected 1) (ArgumentError)
```

However, in ruby 3.2.0, it works

Output (ruby 3.2.0):
```
{"var1"=>"a"}
```

Is this behavior mruby's specification?

**Comment by matz** [comment]
It's a bug. But I recommend wrapping hash arguments with braces, e.g. `foo({:var1=>:a})`, to disambiguate with keyword arguments.

**Comment by bamchoh** [comment]
Thank you for response. I understood my code is ambiguate and revised my code with your suggestion, then it works fine. Thank you very much :)

**Comment by matz** [comment]
It's still a bug to be fixed.
