### ISSUE TITLE
kwarg default in terms of another kwarg

### ISSUE THREAD

**Issue by jabamaus** [mruby/mruby#5952]
Hi,

Continuing to port my codebase to mruby I've come across this:

    def m(a: 0, b: a) = puts b
    m(a: 1) # prints 1 with ruby but fails with undefined method 'a' with mruby

Is this a policy decision or a bug?

Thanks,
James

**Comment by matz** [comment]
I am sorry, but it's mruby limitation. It's documented as a restriction for optional arguments, the same is true for keyword arguments as well.

**Comment by jabamaus** [comment]
Ok thanks. I should have read that doc. I have read it now 😃
