### ISSUE TITLE
Question on overall ability to use mruby

### ISSUE THREAD

**Issue by shreeve** [mruby/mruby#5953]
@matz is a phenom and Ruby is an amazing, powerful, and fun language from which to create solutions and solve problems.

I have recently done some work in the embedded space, with ESP32 devices, Arduino, ESP-IDF, Micropython, OpenWRT, and others and have been completely underwhelmed. Everything is extremely janky, hard to get to work, and the developer experience has been really bad.

I would **love** to be able to use `mruby` for embedded device development. I know @matz has put in years of effort into `mruby` and I would love to see if those efforts can help make the embedded device world easier to work with.

My question is what is the ability today, to use `mruby` for development on embedded devices. All efforts that I have come across seem fragmented or they haven't been updated for several years. Isn't this the perfect opportunity for `mruby` to shine and be a great tool?

What is the current status of being able to use `mruby` for embedded device development?

**Comment by rubyFeedback** [comment]
> Isn't this the perfect opportunity for mruby to shine and be a great tool?

I think one issue is that the embedded segment is smaller than, say, general purpose use - for instance, web-related use (see the rise of JavaScript). Fewer people using something also means less code and fewer projects.

Another issue for entry, as a barrier, is knowledge. The embedded space often targets solely people who are very good already at C/C++ mostly (perhaps a bit of Java when it comes to arduino). This already limits the number of people using language xyz (in this context ruby + mruby).

There are then some chicken/egg problems - fewer people using something means fewer documentation too. This is especially problematic in ruby, in general. Others are very good at figuring out something, but I absolutely depend on documentation. Perhaps that was also one reason why the Pickaxe book was rather important: it gave people an entry point in ruby back in the days.

Personally I think it would be ideal if mruby would not "exist" as a separate part of ruby, but instead mruby and MRI be the same, and we can "assemble" it according to our needs, a bit like the linux kernel (or the busybox software) can be adjusted to different use cases. So to have one unified code base, and we simply select what we want to have it. But I assume lack of resources may be one obstacle here (time is a finite resource).

I guess your question may be best asked to devs who used mruby, or have used it in the past, whether they still use it or not. And if not, why not.
