### ISSUE TITLE
how to get Variadic arguments using mrb_get_args

### ISSUE THREAD

**Issue by neet93** [mruby/mruby#5963]
I want a ruby function like this:
```ruby
foo('foo', 'bar', 'baz')
```
But in this case I want it implemented in C. So I wrote this:
```c
// Define the foo method.
mrb_define_method(mrb, mrb->kernel_module, "foo", foo_method, MRB_ARGS_REST());
// Implement the foo method
static mrb_value foo_method() {
        mrb_value argv[MAX] = { 0 };
        mrb_int   argc      = 0;

        mrb_get_args(mrb, "*", &argv, &argc);

        printf("%d\n", argc);
        mrb_p(mrb, argv[0]);
        mrb_p(mrb, argv[1]);
        mrb_p(mrb, argv[2]);
}
```
I expect to get the number of arguments passed in using *argc*, followed by each string I passed-in.
Like this:
```
3
foo
bar
baz
```
But when I build this I get this instead: 
```
3
```
What's going on here? What am I missing?
I used ```mrb_f_send``` in [vm.c](https://github.com/mruby/mruby/blob/5265e35ad214c37f74033f6bb8cd66c252d06e7d/src/vm.c#L804) as an example and I seem to be doing this right.
but I get no output.
The full code of my example can be found [here](https://gist.github.com/neet93/c52a7884bd9651e2573ce9f76fc89d25).

**Comment by matz** [comment]
Did you solve your issue by yourself?

**Comment by neet93** [comment]
Yes. I founded out that it should be:
```c
mrb_value *argv;
```
and not
```c
mrb_value argv[MAX] = { 0 };
```
Thank you for your response.
