### ISSUE TITLE
How to properly free an allocated object

### ISSUE THREAD

**Issue by D3nX** [mruby/mruby#5983]
Hi,

Sorry if I'm just being dumb, but I really don't get how I am suppose to tell the mruby interpreter to free an allocated object.
In the following code, the function "mrb_potato_free" is never being called, and I don't get why.

If someone knows why I'd be thankful!

Compiler : Visual C++ (VS2019)
Platform : x64

```cpp
#include <mruby.h>
#include <mruby/data.h>
#include <iostream>

struct mrb_potato {
    int value;
};

static void mrb_potato_free(mrb_state* mrb, void* ptr) {
    std::cout << "value is freed!" << std::endl;
    mrb_potato* potato = static_cast<mrb_potato*>(ptr);
    delete potato;
}

static const struct mrb_data_type mrb_potato_type = {
    "Potato", mrb_potato_free
};

static mrb_value create_potato(mrb_state* mrb, mrb_value self) {
    // tried this: mrb_potato* potato = (mrb_potato*)mrb_malloc(mrb, sizeof(mrb_potato));
    mrb_potato* potato = new mrb_potato;
    potato->value = 42;

    mrb_data_init(self, potato, &mrb_potato_type);

    return self;
}

int main() {
    mrb_state* mrb = mrb_open();
    struct RClass* potato_class = mrb_define_class(mrb, "Potato", mrb->object_class);

    mrb_define_method(mrb, potato_class, "initialize", create_potato, MRB_ARGS_NONE());
    mrb_value potato_obj = mrb_obj_new(mrb, potato_class, 0, nullptr);
    mrb_potato* potato = static_cast<mrb_potato*>(DATA_PTR(potato_obj));

    std::cout << "potato->value: " << potato->value << std::endl;

    // tried this: mrb_full_gc(mrb);
    mrb_free(mrb, potato);
    mrb_close(mrb);

    return 0;
}
```

**Comment by dearblue** [comment]
The type when the instance is allocated can be changed with `MRB_SET_INSTANCE_TT()`.
The default is `MRB_TT_OBJECT`, which should be changed to `MRB_TT_CDATA`.

```diff
 int main() {
     mrb_state* mrb = mrb_open();
     struct RClass* potato_class = mrb_define_class(mrb, "Potato", mrb->object_class);
+    MRB_SET_INSTANCE_TT(potato_class, MRB_TT_CDATA);

     mrb_define_method(mrb, potato_class, "initialize", create_potato, MRB_ARGS_NONE());
     mrb_value potato_obj = mrb_obj_new(mrb, potato_class, 0, nullptr);
```

- - -

:black_cat: Perhaps we need further documentation.......

**Comment by D3nX** [comment]
> The type when the instance is allocated can be changed with `MRB_SET_INSTANCE_TT()`. The default is `MRB_TT_OBJECT`, which should be changed to `MRB_TT_CDATA`.
> 
> ```diff
>  int main() {
>      mrb_state* mrb = mrb_open();
>      struct RClass* potato_class = mrb_define_class(mrb, "Potato", mrb->object_class);
> +    MRB_SET_INSTANCE_TT(potato_class, MRB_TT_CDATA);
> 
>      mrb_define_method(mrb, potato_class, "initialize", create_potato, MRB_ARGS_NONE());
>      mrb_value potato_obj = mrb_obj_new(mrb, potato_class, 0, nullptr);
> ```
> 
> 🐈‍⬛ Perhaps we need further documentation.......

Ah yes it finally works! Thank you very much for your help.
