### ISSUE TITLE
The number of operands when outputting ARRAY code does not appear to be correct.

### ISSUE THREAD

**Issue by alpha-netzilla** [mruby/mruby#5990]
The operands of ARRY is BB.  Output in verbose mode appears to use three operands.
Is the output code in the `src/codedump.c` file correct? Sorry if there are any intentions to do this.

`
  CASE(OP_ARRAY, BB):
      fprintf(out, "ARRAY\t\tR%d\tR%d\t%d", a, a, b);
`

**Comment by matz** [comment]
It's redundant display to clarify the destination register. You should read "create array of `b` elements starting from the register `a` and assign the array to the register `a`".
