### ISSUE TITLE
One seemingly unnecessary parameter is passed in the block parameters.

### ISSUE THREAD

**Issue by alpha-netzilla** [mruby/mruby#5995]
In the file `lib/mruby/build/command.rb`, two parameters, `ext` and `compile`, are passed in the parameter of the "each" method,  but the latter appears to be unnecessary. 

```
      source_exts.each do |ext, compile|
```
It seems that the `compile` is not actually used, only `ext`.

I wonder if this is correct.

**Comment by matz** [comment]
You found a bug existed since 2013-01-20. Thank you.
