### ISSUE TITLE
Proper way to use static module variables

### ISSUE THREAD

**Issue by D3nX** [mruby/mruby#6027]
Hi!
I'm currently making a game using MRuby. However I'm facing some issues with static module variables.
My code kinda looks like this for now : 
```ruby
module Game
    @@env = {
        "_CURRENT_PLACE" => "",
        "_DRAW_MOVE_RECTS" => false,
        "_DRAW_COMMAND_RECTS" => false,
        "_MUTE" => false,
        "_HERO_NAME" => "",
    }

    def Game.get(str)
        return @@env[str]
    end

    def Game.set(key, val)
        @@env[key] = val
    end
end
```
The C++ code will call the set or get functions from time to time, the objective was to make a simple interface for generic / global informations between Ruby scripts and the C++ code.

Although it's probably not a very good practice, I would like to understand some things :
- If I don't call mrb_gc_full for each frames (btw, should I call constantly the gc when my game is running?), it will works for a few seconds then the data within @@env will be fully corrupted
- If I call mrb_gc_full, well it seems to be working without crashes, but it makes no sense to me, at least I don't get it why. And it feels like a cheap fix (although it perhaps completely makes sense and it's the way to go?)

I tried to ask GPT about my issue and it told me that "static module variable in mruby are meant to be constant" but I'm not sure how reliable that answer is.

So my question : why does it behave like that ? and how should I do it properly so it won't crash and be safe in the memory ?

Thank you for your answers.

**Comment by Chadowo** [comment]
Hi there, from the looks of it I can't tell that much about the problem, the ruby bit seems fine, so the problem may lie in the way you access the variables from your c/c++ code. If you can show it may be highly appreciated.

On another note, from the way you described your projects it seems you're using `mrb_funcall` or `mrb_funcall_argv` to call your ruby defined methods? do note that there are functions to access the module variables directly, namely `mrb_cv_get` `mrb_cv_set` (module variables are just class variables underneath), here's the [docs link](https://mruby.org/docs/api/headers/mruby_2Fvariable.h.html#mrb_cv_get-function).

---

> If I don't call mrb_gc_full for each frames (btw, should I call constantly the gc when my game is running?), it will works for a few  seconds then the data within @@env will be fully corrupted

From experience it should work just fine without having to call the GC constantly.

> If I call mrb_gc_full, well it seems to be working without crashes, but it makes no sense to me, at least I don't get it why. And it feels like a cheap fix (although it perhaps completely makes sense and it's the way to go?)

I doubt's that the way to go, the point about the GC is for it to do its job without user input, calling it every second or so would be highly inefficient.

**Comment by matz** [comment]
I see no problem in your code example. It may be in a bug in mruby, or maybe a bug in your (C++) code.
I need an issue reproducing code to address.

**Comment by D3nX** [comment]
> Hi there, from the looks of it I can't tell that much about the problem, the ruby bit seems fine, so the problem may lie in the way you access the variables from your c/c++ code. If you can show the code it'll be highly appreciated.
> 
> On another note, from the way you described your projects it seems you're using `mrb_funcall` or `mrb_funcall_argv` to call your ruby defined methods? do note that there are functions to access the module variables directly, namely `mrb_cv_get` `mrb_cv_set` (module variables are just class variables underneath), here's the [docs link](https://mruby.org/docs/api/headers/mruby_2Fvariable.h.html#mrb_cv_get-function).
> 
> > If I don't call mrb_gc_full for each frames (btw, should I call constantly the gc when my game is running?), it will works for a few  seconds then the data within @@env will be fully corrupted
> 
> From experience it should work just fine without having to call the GC constantly.
> 
> > If I call mrb_gc_full, well it seems to be working without crashes, but it makes no sense to me, at least I don't get it why. And it feels like a cheap fix (although it perhaps completely makes sense and it's the way to go?)
> 
> I doubt's that the way to go, the point about the GC is for it to do its job without user input, calling it every second or so would be highly inefficient.

Hi, sorry for the late.

First of all thank you for your insights, it's very much appreciated. And I didn't knew mrb_cv_get and mrb_cv_set, thanks for pointing that out!
For the C++ code, I'm afraid the code of my project as of now is quite big and a (joyful mess...) of C++ templated code. However, here is probably the most important function, calling the Ruby functions from C++ :

```c++
template<typename T = MRBInstancePtr, typename ...Args>
T _call(mrb_state* mrbs, mrb_value value, const std::string& funcName, Args ...args)
{
	std::vector<mrb::_Any> argsTab = { args... };
	int argc = sizeof...(args);
	mrb_value* argv = new mrb_value[argc];

	for (int i = 0; i < argc; i++)
	{
		if (argsTab[i].getType() == mrb::_Any::Type::BOOL)
			argv[i] = mrb_bool_value((argsTab[i].get<bool>() ? TRUE : FALSE));
		else if (argsTab[i].getType() == mrb::_Any::Type::INT)
			argv[i] = mrb_fixnum_value(argsTab[i].get<int64_t>());
		else if (argsTab[i].getType() == mrb::_Any::Type::DOUBLE)
			argv[i] = mrb_float_value(mrbs, argsTab[i].get<double>());
		else if (argsTab[i].getType() == mrb::_Any::Type::STRING)
			argv[i] = mrb_str_new_cstr(mrbs, argsTab[i].get<std::string>().c_str());
	}
	mrb_value rv = mrb_funcall_argv(mrbs, value, mrb_intern_cstr(mrbs, funcName.c_str()), argc, argv);

	if (mrbs->exc)
	{
		mrb_value error = mrb_funcall(mrbs, mrb_obj_value(mrbs->exc), "inspect", 0);
		me::meLogError<MRBHandler>("[Ruby Runtime]: " + std::string(RSTRING_PTR(error)));
		mrb_print_error(mrbs);
	}

	delete[] argv;

	MRBInstancePtr ptr = std::make_shared<MRBInstance>(mrbs, rv);

	if constexpr (std::is_same<T, MRBInstancePtr>::value)
		return ptr;
	return ptr->get<T>();
}
```

NOTES:
- "me::meLog" is just a logging function, a simple std::cout so do not worry about that
- "mrb::_Any" is basically a type holder for many simple values. It's used for templating purposes.

I hope the problem within this code might be clear? I thought maybe I shouldn't delete the "argv" but it changes nothing, so I kept it.

Thanks

**Comment by D3nX** [comment]
> I see no problem in your code example. It may be in a bug in mruby, or maybe a bug in your (C++) code. I need an issue reproducing code to address.

Hi, sorry for the late.

I was able to reproduce the error outside of my project with the following code :
``main.cpp``
```c++
#include <mruby.h>
#include <mruby/irep.h>
#include <mruby/string.h>
#include <mruby/compile.h>
#include <mruby/array.h>
#include <iostream>

std::string readFile(const std::string& path) {
    std::string output;
#if defined(WIN32) || defined(_WIN32) || defined(__WIN32__) || defined(__NT__)
    FILE* stream = NULL;
    fopen_s(&stream, path.c_str(), "rb");
#else
    FILE* stream = fopen(path.c_str(), "rb");
#endif
    if (stream) {
        fseek(stream, 0L, SEEK_END);
        int size = ftell(stream);
        fseek(stream, 0L, SEEK_SET);

        char* buffer = new char[size];
        fread(buffer, sizeof(char), size * sizeof(char), stream);
        output.assign(buffer, size);
        delete[] buffer;
        fclose(stream);
    }
    return output;
}


uint8_t* load_from_file(const std::string& path) {
    std::string data = readFile(path);

    if (data.size() == 0) {
        std::cerr << "Could not load any data!" << std::endl;
        return nullptr;
    }
    uint8_t* tab = new uint8_t[data.size()];
    for (std::size_t i = 0; i < data.size(); i++)
        tab[i] = static_cast<uint8_t>(data[i]);
    return tab;
}

mrb_value load_lib(mrb_state* mrb) {
    uint8_t* data = load_from_file("res/test_static_var.mrb");

    int ai = mrb_gc_arena_save(mrb);
    mrb_value irep_obj = mrb_load_irep(mrb, data);
    mrb_gc_arena_restore(mrb, ai);

    delete[] data;

    return irep_obj;
}

void check_errors(mrb_state* mrb) {
    if (mrb->exc) {
        mrb_value error = mrb_funcall(mrb, mrb_obj_value(mrb->exc), "inspect", 0);
        std::cout << "MRuby error: " << RSTRING_PTR(error) << std::endl;
        mrb_print_error(mrb);
    }
}

int main() {
    // Just builds the Ruby file into MRuby files, just for testing purposes
    system("call \"res/build.bat\"");

    // Add a random seed
    srand(time(nullptr));

    // Open the handler
    mrb_state* mrb = mrb_open();

    // Loads the library into memory
    load_lib(mrb);

    // Fetch the module
    RClass* gameModule = mrb_define_module(mrb, "Game");
    mrb_value gameModuleObj = mrb_obj_value(static_cast<void*>(gameModule));
    
    // Loop calling the "problematic" code
    while (1) {
        // Calling the "set" function
        mrb_int argc = 2;
        mrb_value* argv = new mrb_value[argc];

        // Define a given value
        mrb_int givenValue = rand() % 800;
        std::cout << "The given value: " << givenValue << std::endl;

        // Converting C/C++ types to MRuby types
        argv[0] = mrb_str_new_cstr(mrb, "PLAYER_X");
        argv[1] = mrb_fixnum_value(givenValue);
        
        // Call the "set" function from the Ruby code
        mrb_funcall_argv(mrb, gameModuleObj, mrb_intern_cstr(mrb, "set"), argc, argv);

        // Check if any error happened
        check_errors(mrb);

        delete[] argv;

        // Calling the "get" function
        argc = 1;
        argv = new mrb_value[argc];

        argv[0] = mrb_str_new_cstr(mrb, "PLAYER_X");

        // Call the "get" function
        mrb_value rv = mrb_funcall_argv(mrb, gameModuleObj, mrb_intern_cstr(mrb, "get"), argc, argv);

        check_errors(mrb);

        std::cout << "The value fetched back in the C++ code: " << mrb_as_int(mrb, rv) << std::endl;

        delete[] argv;
    }

    // Closes mruby
    mrb_close(mrb);

    return 0;
}
```
The Ruby code "test_static_var.mrb" is exactly the code example I sent already, compiled using mrbc.
The behavior looks to be the same with my project: it will run for a few seconds nicely, then crash "(unknown):0: nil cannot be converted to Integer (TypeError)".

For reference, I'm trying this on Windows 10/11, Visual Studio 2019 (MSVC C++).

NOTE: As a temporary fix I put the variable in global instead of static which seems to be working, but not a very great fix.

Hope this helps find out where I did an error.
Thank you.

**Comment by Chadowo** [comment]
> Hi, sorry for the late.

No problem at all!

> First of all thank you for your insights, it's very much appreciated. And I didn't knew mrb_cv_get and mrb_cv_set, thanks for pointing that out!
For the C++ code, I'm afraid the code of my project as of now is quite big and a (joyful mess...) of C++ templated code. However, here is probably the most important function, calling the Ruby functions from C++ :
> [...]

Taking a glance at it, it looks fine and solid, so I'd rule out the problem being here.

> I was able to reproduce the error outside of my project with the following code :
> [...]

This looks pretty interesting, I gave it a stab on my system and it worked flawlessly (Linux Mint 21.1 XFCE).
From the looks of it, the problem is specific to your environment, I don't have a windows machine to test it sadly.

For testing purposes you could use `mrb_cv_get`/`mrb_cv_get` instead to see if the issue persists.  
   
  
thanks for your time (and sorry for not being too useful of an answer)

**Comment by D3nX** [comment]
> > Hi, sorry for the late.
> 
> No problem at all!
> 
> > First of all thank you for your insights, it's very much appreciated. And I didn't knew mrb_cv_get and mrb_cv_set, thanks for pointing that out!
> > For the C++ code, I'm afraid the code of my project as of now is quite big and a (joyful mess...) of C++ templated code. However, here is probably the most important function, calling the Ruby functions from C++ :
> > [...]
> 
> Taking a glance at it, it looks fine and solid, so I'd rule out the problem being here.
> 
> > I was able to reproduce the error outside of my project with the following code :
> > [...]
> 
> This looks pretty interesting, I gave it a stab on my system and it worked flawlessly (Linux Mint 21.1 XFCE). From the looks of it, the problem is specific to your environment, I don't have a windows machine to test it sadly.
> 
> For testing purposes you could use `mrb_cv_get`/`mrb_cv_get` instead to see if the issue persists.
> 
> thanks for your time (and sorry for not being too useful of an answer)

Hi,

So I tried your suggestion on the sample C++ code I sent earlier : 
```cpp

int main() {
    // Just builds the Ruby file into MRuby files, just for testing purposes
    system("call \"res/build.bat\"");

    // Add a random seed
    srand(time(nullptr));

    // Open the handler
    mrb_state* mrb = mrb_open();

    // Loads the library into memory
    load_lib(mrb);

    // Fetch the module
    RClass* gameModule = mrb_define_module(mrb, "Game");
    mrb_value gameModuleObj = mrb_obj_value(static_cast<void*>(gameModule));
    
    // Loop calling the "problematic" code
    while (1) {
        // Define a given value
        mrb_int givenValue = rand() % 800;
        std::cout << "The given value: " << givenValue << std::endl;

        mrb_mod_cv_set(mrb, gameModule, mrb_intern_cstr(mrb, "@@env[\"PLAYER_X\"]"), mrb_fixnum_value(givenValue));

        // Check if any error happened
        check_errors(mrb);

        // Get the value
        mrb_value fetchedValue = mrb_cv_get(mrb, gameModuleObj, mrb_intern_cstr(mrb, "@@env[\"PLAYER_X\"]"));

        check_errors(mrb);

        std::cout << "The value fetched back in the C++ code: " << mrb_as_int(mrb, fetchedValue) << std::endl;
    }

    // Closes mruby
    mrb_close(mrb);

    return 0;
}
```

I'm not sure if I did it right, but it looks to be working flawlessly on my Windows machine!
It still makes no sense to me that calling a function for doing that don't work, but at least I have an alternative (and the right way to do it).

> thanks for your time (and sorry for not being too useful of an answer)

Thank you for taking your time to help me out! It's really appreciated 👍

**Comment by Chadowo** [comment]
Hi there.

>So I tried your suggestion on the sample C++ code I sent earlier :
> [...]
>I'm not sure if I did it right, but it looks to be working flawlessly on my Windows machine!
>It still makes no sense to me that calling a function for doing that don't work, but at least I have an alternative (and the right way to do it).

Yep, that's the way to do it, nice to hear it works! I agree that it's puzzling why your earlier approach didn't work, moreover why does it works normally on Linux, so the issue still persists.  

I lack knowledge about the internals of MRuby, so I can't presume that much about the issue. However I'll try to see if I can debug any nifty info about the problem.

Thanks.

**Comment by D3nX** [comment]
> Hi there.
> 
> > So I tried your suggestion on the sample C++ code I sent earlier :
> > [...]
> > I'm not sure if I did it right, but it looks to be working flawlessly on my Windows machine!
> > It still makes no sense to me that calling a function for doing that don't work, but at least I have an alternative (and the right way to do it).
> 
> Yep, that's the way to do it, nice to hear it works! I agree that it's puzzling why your earlier approach didn't work, moreover why does it works normally on Linux, so the issue still persists.
> 
> I lack knowledge about the internals of MRuby, so I can't presume that much about the issue. However I'll try to see if I can debug any nifty info about the problem.
> 
> Thanks.

After further investigation, recompiling my whole project under linux and trying different thing... I realised that I did something very dumb.

On my Windows machine, I realised that I pulled MRuby from the repo rather than taking a stable release. So I did recompile the stable one, and tried again, and guess what no more issues... At least, it looks very stable for now.

For reference, this was the commit I downloaded by error instead of the stable version :
```
commit 1c765dc37a80bf681bbab271b0ba90711d935be9 (HEAD -> master, origin/master, origin/HEAD)
Merge: db11e0749 f6c9191cd
Author: Yukihiro "Matz" Matsumoto <matz@ruby.or.jp>
Date:   Sat Mar 18 23:56:04 2023 +0900

    Merge pull request #5902 from dearblue/threadedcode

    Replace `MRB_NO_DIRECT_THREADING` with `MRB_USE_VM_SWITCH_DISPATCH`
```

So I suppose the feature was broken in this specific commit... If someone could confirm my doubts it would be highly appreciated.

I will still keep the issue open for a bit, as I'm working intensively with mruby at the moment for my project, so if the issue pops back again I can share with y'all, but I'm pretty sure it's just because I can't read and download the right version.

My apologies for probably having wasted your time and @matz time, I only figured out today that stupid error of mine that was making crash the whole project.

**Comment by Chadowo** [comment]
Hi there, sorry for being late!

> After further investigation, recompiling my whole project under linux and trying different thing... I realised that I did something very dumb.
>
> On my Windows machine, I realised that I pulled MRuby from the repo rather than taking a stable release. So I did recompile the stable one, and tried again, and guess what no more issues... At least, it looks very stable for now.

Oh I see, so that was the issue, makes a lotta sense now.

> For reference, this was the commit I downloaded by error instead of the stable version :
> [...]

Thanks for the info, when I have time I will pull mruby directly from master to see if your specific issue is still present

> My apologies for probably having wasted your time and \@matz time, I only figured out today that stupid error of mine that was
> making crash the whole project.

No worries at all, glad to see you'll could get the solution to your problem :)
