### ISSUE TITLE
Generated presym/table.h contains invalid characters 

### ISSUE THREAD

**Issue by jabamaus** [mruby/mruby#6044]
Building latest mruby head on windows with VS2022 causes bad characters in table.h. It does not handle backslashes correctly and produces lines like:

`"C:\x5cjames_projects\x5cGitHub\x5cmruby\x5cmrblib\x5cenum.rb"`

Which of course fails to build.

This appeared in [this commit ](https://github.com/mruby/mruby/commit/03a42b52eea4b15d98715c33da65556c03799476) by dearblue. I don't know if the decoding part of the code change also contains an error or not....

This is the second time I've come across a windows backslash bug and I'm surprised that this is passing the CI as I believe you do build under windows... I'd fix it myself but I don't have the expertise!

**Comment by Reckordp** [comment]
What about double backslash `\\`?

**Comment by jabamaus** [comment]
Thanks dearblue! :)

**Comment by dearblue** [comment]
@jabamaus,
I sent my solution as #6045.
If possible, it would be very helpful if you could confirm it.

**Comment by jabamaus** [comment]
Thanks so much dearblue. Unfortunately I won't be able to try it until Monday now. I'll let you know as soon as I've verified it.

**Comment by jabamaus** [comment]
I've tested this and it works perfectly :)
