### ISSUE TITLE
MRUBY_PACKAGE_DIR does not always have a value.

### ISSUE THREAD

**Issue by pyama86** [mruby/mruby#6064]
Hello,

I have a concern regarding the changes below. It seems that some of the builds may not work with the following modification:

[Link to the changes](https://github.com/mruby/mruby/pull/5928/files#diff-73bd5dcafbd1a1b6c497c5354f20745d061f8a5de196ed47e4235bf5da06c4f3R83)

Since MRUBY_PACKAGE_DIR does not always have a value, it appears that builds used by projects relying on libmruby.a might be affected. If possible, I would appreciate it if we could revert to using `libmruby_static` as it was done in versions prior to 3.2, instead of utilizing `libmruby_static.replace_prefix_by(build_dir => "$(MRUBY_PACKAGE_DIR)").`

**Comment by dearblue** [comment]
Sorry. It seems I made an incorrect confirmation the last time I did this.
I think I was able to fix it in #6069, but it would be helpful if you could check.

**Comment by pyama86** [comment]
Thank you for promptly creating the patch. I confirmed that it worked without any issues with the provided content. I appreciate your swift response.

**Comment by dearblue** [comment]
Thank you for confirming!
