### ISSUE TITLE
Will YARP(prism) be used as a built-in parser for mruby in the future?

### ISSUE THREAD

**Issue by LanzaSchneider** [mruby/mruby#6074]
@matz 
[Ruby Prism](https://github.com/ruby/prism)

According to the README.md of prism:
> This is a parser for the Ruby programming language. It is designed to be portable, error tolerant, and maintainable. It is written in C99 and has no dependencies. It is currently being integrated into [CRuby](https://github.com/ruby/ruby), [JRuby](https://github.com/jruby/jruby), [TruffleRuby](https://github.com/oracle/truffleruby), [Sorbet](https://github.com/sorbet/sorbet), and [Syntax Tree](https://github.com/ruby-syntax-tree/syntax_tree).

Can we expect mruby to come into prism's sphere of influence as well?

**Comment by matz** [comment]
Yes, in the future. But the priority is low, since we already have a working parser.

**Comment by LanzaSchneider** [comment]
Cool!
