### ISSUE TITLE
Why not stop updating the Copyright years? (著作年の更新をやめませんか？)

### ISSUE THREAD

**Issue by dearblue** [mruby/mruby#6080]
We can do this via GitHub Actions to automatically update the copyright years.
However, there is a clear pioneer who did not update the copyright years or removed the copyright year notation, so I propose this.

<https://github.com/marketplace/actions/update-license-copyright-year-s>

If removing it completely is a concern, how about leaving only the very first copyright year notation?

For example: `Copyright (c) 2010- mruby developers`.

### Legal Background

Japanese from here.

僕は法に詳しいわけではないのでご注意ください。
また、情報源が日本語版 Wikipedia のみであることもご注意ください。

  - (ja) ベルヌ条約: <https://ja.wikipedia.org/wiki/文学的及び美術的著作物の保護に関するベルヌ条約>
  - (en) Berne Convention: <https://en.wikipedia.org/wiki/Berne_Convention>

これによると、現在のベルヌ条約に批准する殆どの国家は、著作物を創作した時点で有効となる「無方式主義」を採用しているようです。
また、[ベルヌ条約に未加盟でも WTO に加盟しているとベルヌ条約に拘束される](https://www.wto.org/english/tratop_e/trips_e/intel2_e.htm) とあります (僕は英語がわかりません)。
<https://ja.wikipedia.org/w/index.php?title=文学的及び美術的著作物の保護に関するベルヌ条約&oldid=94385409#cite_ref-WTO-TRIPS_89-0>

私見ですが、著作年の表記が残っている背景を考察すると、

  - (冗長な) 利便性のために (要出典)。
  - これまでの慣習。特に米国の影響が強く (要出典)、米国が無方式主義を施行したのは 1989 年のようです。

**Comment by matz** [comment]
As you mentioned, it's for the pre 1989 USA convention. We have no legal obligation any longer.
I vote for changing to `Copyright (c) 2010- mruby developers`.

**Comment by matz** [comment]
OK, I will.
