### ISSUE TITLE
Incorrect symbolic sinks in binary built on Linux

### ISSUE THREAD

**Issue by buty4649** [mruby/mruby#6084]
Symbolic links of the binary files generated under `build/bin` are being created. However, these symbolic links are created with absolute paths, which can sometimes result in incorrect links. For instance, in my project, I am using Docker for the builds. When building on a Docker image, the binary is created at `/src/build/host/mruby`, but it appears at a different path when viewed from the host.

```
$ rake build
-- snip --
$ pwd
/home/buty4649/src/github.com/buty4649/rf

# The actual mruby binary is located under build/host/bin
$ ls -lah ./build/host/bin/mruby
-rwxr-xr-x 1 buty4649 buty4649 12M Oct 21 12:22 ./build/host/bin/mruby

# The path of mruby under build/bin is incorrect
$ ls -lah ./build/bin/mruby
lrwxrwxrwx 1 buty4649 buty4649 25 Oct 21 12:22 ./build/bin/mruby -> /src/build/host/bin/mruby
$ ls -lah /src/build/host/bin/mruby
/bin/ls: cannot access '/src/build/host/bin/mruby': No such file or directory
```

I suspect that the issue is caused by calling `File.expand_path` when creating the symbolic links, as seen here: https://github.com/mruby/mruby/blob/master/lib/mruby/build.rb#L400

**Comment by dearblue** [comment]
I think #6085 could have taken care of this.

In my opinion, I have the impression that `#{MRUBY_ROOT}/bin/` is a temporary working directory.
I think it is better to refer to `#{MRuby::Build#build_dir}/bin/` if possible when referring to it externally.

**Comment by matz** [comment]
#6085 merged. @buty4649 Does this solve the problem? If so, please close this issue.

**Comment by buty4649** [comment]
Issue #6085 has been perfectly resolved. It's excellent! Thank you so much!

```sh
$ ls -lah ./build/bin/rf
lrwxrwxrwx 1 buty4649 buty4649 14 Oct 23 20:42 ./build/bin/rf -> ../host/bin/rf
```
