### ISSUE TITLE
'Remote branch HEAD not found in upstream origin' error on build

### ISSUE THREAD

**Issue by buty4649** [mruby/mruby#6087]
I am building mruby with specified mgems. After performing `rake deep_clean` and trying to build it again, I encounter a 'Remote branch HEAD not found in upstream origin' error, and the build fails.

From what I've investigated, it seems that the issue is caused by the branch name written in build_config.rb.lock changing from master to HEAD.

## Reproduction Steps

I have placed the code to reproduce the issue on https://github.com/buty4649/mruby-remote-branch-bug. Please use this for reference.

1. Clone the repository from https://github.com/buty4649/mruby-remote-branch-bug and move to that directory.
    ```sh
    $ git clone https://github.com/buty4649/mruby-remote-branch-bug
    $ cd mruby-remote-branch-bug
    ```
2. At this point, it is set to `branch: master`.
    ```sh
    $ grep branch build_config.rb.lock
      branch: HEAD
    ```
3. Proceed with the build.
    ```sh
    $ MRUBY_CONFIG=$(pwd)/build_config.rb MRUBY_BUILD_DIR=$(pwd)/build rake -f /path/to/mruby/Rakefile
    ```
4. After the build completes, it changes to `branch: HEAD`.
    ```diff
    $ git diff | cat
    diff --git a/build_config.rb.lock b/build_config.rb.lock
    index db02184..642f97b 100644
    --- a/build_config.rb.lock
    +++ b/build_config.rb.lock
    @@ -7,6 +7,6 @@ builds:
       host:
         https://github.com/mattn/mruby-json.git:
           url: https://github.com/mattn/mruby-json.git
    -      branch: master
    +      branch: HEAD
           commit: f99d9428025469f2400f93c53b185f65f963e507
       version: 0.0.0
    ```
5. Cleanup build directory.
    ```sh
    $ MRUBY_CONFIG=$(pwd)/build_config.rb MRUBY_BUILD_DIR=$(pwd)/build rake -f /path/to/mruby/Rakefile deep_clean
    ```
6. Try building again, and the issue should reproduce.
    ```sh
    $ MRUBY_CONFIG=$(pwd)/build_config.rb MRUBY_BUILD_DIR=$(pwd)/build rake -f /path/to/mruby/Rakefile
    -- snip --
    fatal: Remote branch HEAD not found in upstream origin
    rake aborted!
    Command failed with status (128): [git clone --recursive --branch "HEAD" "htt...]
    -- snip ---
    ```

**Comment by dearblue** [comment]
This problem should have been solved by me in #4899, but I overlooked it.
:thinking: I will try to come up with a solution.

**Comment by dearblue** [comment]
I have sent #6092 as a proposed fix to this issue.
Thank you for the report.

**Comment by buty4649** [comment]
I also tested #6092 in my local environment. The bug I reported was fixed.
Thank you for the correction! 😄
