### ISSUE TITLE
mrb_fixnum resulting in different values depending on the boxing setting

### ISSUE THREAD

**Issue by yujiyokoo** [mruby/mruby#6093]
`mrb_fixnum` seems to result in different values depending on the boxing setting in `mrbconf.h`.

I have written a demo program here: https://gist.github.com/yujiyokoo/f578d1bee8dafe2357f65fd57a137a18
This has been tested on arm64 Mac and amd64 Linux.

If I edit `include/mrbconf.h` to use `MRB_NAN_BOXING` or `MRB_NO_BOXING`, I get the output "128" (expected). If I configure it to use `MRB_WORD_BOXING`, rebuild mruby and the demo program, it outputs "64" (unexpected).

From what I can figure out, it seems like this shifting by 1 bit might be happening when it's not needed but I am not clear on how it all works: https://github.com/mruby/mruby/blob/552944b34e730c77b20d306ada77387f6f5c7732/include/mruby/boxing_word.h#L160

Is this an issue with the current mruby code, or am I doing something wrong?

**Comment by dearblue** [comment]
The type corresponding to the `i` specifier of `mrb_get_args()` is `mrb_int`.

```patch


 static mrb_value print_num(mrb_state *mrb, mrb_value self) {
-  struct mrb_value score;
+  mrb_int score;
   mrb_get_args(mrb, "i", &score);
-  printf("%lld\n", (long long)mrb_fixnum(score));
+  printf("%lld\n", (long long)score);

   return mrb_nil_value();
 }
```

`mrb_get_args()` is the spicy part, since it is a variable length argument and the compiler doesn't do type checking for it.
\# I have been fantasizing about using libclang to do type checking for `mrb_get_args()`, but I haven't come up with a plan yet.

**Comment by yujiyokoo** [comment]
Oh I see. That resolved my issue! Thank you very much for your help @dearblue
