### ISSUE TITLE
fails to call superclass of wrapped method

### ISSUE THREAD

**Issue by jabamaus** [mruby/mruby#6098]
```
module Wrapper
  def wrap(meth)
    define_method(meth) do |*args, **kwargs, &block|
      super(*args, **kwargs, &block)
      puts "side effect"
      self
    end
  end
end

class MyString < String
  extend Wrapper
  wrap :<<
end


MyString.new << "a"
```

This code prints 'side effect' in cruby but with mruby I get

`test.rb:4:in <<: no superclass method 'wrap' (NoMethodError)`

What's going on here? This is with latest mruby head.

Thanks :)

**Comment by matz** [comment]
It is a bug. But it may take time to fix the issue. Stay tuned, please.

**Comment by jabamaus** [comment]
No problem. I think the problem got introduced in the past few months as I'm sure I've seen this working.
