### ISSUE TITLE
VM crashes with bread after #6101

### ISSUE THREAD

**Issue by matz** [mruby/mruby#6108]
After #6101, VM crashes with a simple script like `Class.new{break}`. Usually, I solve this kind of problem by myself, but honestly speaking, I don't understand this reorganization well enough to address the issue. @dearblue Could you check this problem, please?

It seems that VM calls `MRB_THROW` multiple times in the same `MRB_TRY` block to traverse the implicit `mrb->jmp` link (via `prev_jmp`) when unnecessary.

**Comment by dearblue** [comment]
Thanks for the report.
:scream_cat: I have confirmed the issue. Sorry about that.
I will look for the cause and fix it.
