### ISSUE TITLE
ARM-based macOS: Unable to build `mruby-compiler`: `syntax error, unexpected identifier, expecting string`

### ISSUE THREAD

**Issue by sizious** [mruby/mruby#6135]
I got some feedback on the Sega Dreamcast build configuration that I just pushed (https://github.com/mruby/mruby/pull/6130).

Everything works fine on Windows (using [DreamSDK](https://www.dreamsdk.org/)) and on GNU/Linux (tested on Debian/Ubuntu). But unfortunately, this configuration doesn't work on macOS. I'm not sure if this is really related to the configuration itself, as the error returned is: `/opt/toolchains/dc/kos-ports/mruby/build/mruby-3.2.0/mrbgems/mruby-compiler/core/parse.y:1449.9-19: syntax error, unexpected identifier, expecting string`.

Full log is:

```
CPP   src/gc.c -> build/dreamcast/src/gc.pi
CPP   mrbgems/mruby-bigint/core/bigint.c -> build/dreamcast/mrbgems/mruby-bigint/core/bigint.pi
CPP   mrbgems/mruby-compiler/core/codegen.c -> build/dreamcast/mrbgems/mruby-compiler/core/codegen.pi
GPERF mrbgems/mruby-compiler/core/keywords -> mrbgems/mruby-compiler/core/lex.def
YACC  mrbgems/mruby-compiler/core/parse.y -> mrbgems/mruby-compiler/core/y.tab.c
/opt/toolchains/dc/kos-ports/mruby/build/mruby-3.2.0/mrbgems/mruby-compiler/core/parse.y:1449.9-19: syntax error, unexpected identifier, expecting string
rake aborted!
Command failed with status (1): [bison -o "/opt/toolchains/dc/kos-ports/mru...]
/opt/toolchains/dc/kos-ports/mruby/build/mruby-3.2.0/lib/mruby/build/command.rb:33:in `_run'
/opt/toolchains/dc/kos-ports/mruby/build/mruby-3.2.0/lib/mruby/build/command.rb:259:in `run'
/opt/toolchains/dc/kos-ports/mruby/build/mruby-3.2.0/mrbgems/mruby-compiler/mrbgem.rake:23:in `block in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => default => all => gensym => /opt/toolchains/dc/kos-ports/mruby/build/mruby-3.2.0/build/dreamcast/presym => /opt/toolchains/dc/kos-ports/mruby/build/mruby-3.2.0/build/dreamcast/mrbgems/mruby-compiler/core/y.tab.pi => /opt/toolchains/dc/kos-ports/mruby/build/mruby-3.2.0/mrbgems/mruby-compiler/core/y.tab.c
(See full trace by running task with --trace)
make[2]: *** [all] Error 1
make[1]: *** [generatemruby] Error 2
make: *** [build-stamp] Error 2
2
Error building /opt/toolchains/dc/kos/../kos-ports/mruby. Bailing out.
```

Looks like the issue is from `YACC`, probably mruby needs GNU flex/bison installed. Unfortunately, I don't have a macOS to test that.

Do you know if other configurations are working properly on macOS?

Thanks!

**Comment by matz** [comment]
`bison` generated `y.tab.c` is included in the repository. Unless you have modified `parse.y` you don't have to re-generate `y.tab.c`. If the file timestamp causes an issue, use `touch` to update the timestamp. The other option is to install the newer `bison` (e.g. using `brew install bison`).

**Comment by sizious** [comment]
Thank you for your answer! 👍🏻
