### ISSUE TITLE
Infinite loop in String#index with binary data when MRB_UTF8_STRING is enabled

### ISSUE THREAD

**Issue by buty4649** [mruby/mruby#6143]
I've encountered an issue where enabling the MRB_UTF8_STRING flag leads to an infinite loop when using the String#index method on a string containing binary data.

### Steps to Reproduce
The issue can be reproduced with the following steps:

1. Enable the MRB_UTF8_STRING flag and build.
    ```ruby
    # build_config.rb
    MRuby::Build.new do |conf|
      toolchain :gcc
      conf.gembox 'default'
      conf.cc.defines << 'MRB_UTF8_STRING'
    end
    ```
2. Execute the following script:
    ```sh
    $ cat test.rb
    p "\x80k\xb8".index("\n")
    $ ./build/bin/mruby test.rb
    ```
3. The issue can be observed.

### Expected Behavior
The expected behavior is that in CRuby, it would return `nil`.

### Actual Behavior
The String#index method enters an infinite loop, and the process does not terminate.

### Additional Information
During debugging with gdb, it appears that the issue occurs in the `str_index_str_by_char_search` function in `src/string.c`. Specifically, an infinite loop seems to occur in the following part of the code:
https://github.com/mruby/mruby/blob/master/src/string.c#L412-L415

I am not very familiar with the Quick Search algorithm (Boyer-Moore-Horspool algorithm), so I'm not sure how to resolve this issue 😭.

I would appreciate it if you could look into this issue. If any more information is needed, please let me know.

**Comment by buty4649** [comment]
As a workaround, although it sacrifices speed, you can avoid this issue by using String#chars to convert the string to an array and then calling the index method:

```ruby
p "\x80k\xb8".chars.index("\n")
#=> nil

p "\x80k\n\xb8".chars.index("\n")
#=> 2

**Comment by dearblue** [comment]
I was able to reproduce the problem.

After a little research, I suspect that the problem is not in `str_index_str_by_char_search()`, but in `mrb_utf8len()`.
I also get an infinite loop in other places that call `mrb_utf8len()`.
e.g. `bin/mruby -e 'p "\x81xyz".chop!'`

Since `mrb_utf8len()` is also used to check if a character is illegal as UTF-8 (`String#valid_encoding?`), it may be desirable to separate the feature.

@matz, is there another preferred method of correction?

**Comment by buty4649** [comment]
I've just pulled the latest commit and rebuilt the system, and I'm happy to confirm that the issue has been resolved. Thank you for the fix!

**Comment by matz** [comment]
We are still working on refactoring `index` and `chars2bytes`. Notice us when you see any bugs.
