### ISSUE TITLE
Unexpected hash behavior on user-defined keys

### ISSUE THREAD

**Issue by catsidhe** [mruby/mruby#6168]
Consider this example:

```ruby
class A
  def ==(other)
    p "== #{self}"
    true
  end
  alias eql? ==
  def hash
    p "hash #{self}"
    1
  end
end

class B
  def ==(other)
    p "== #{self}"
    true
  end
  alias eql? ==
  def hash
    p "hash #{self}"
    1
  end
end

h = {}
h[A.new] = 1
p h.has_key?(B.new)
p h[B.new]
```
Ruby prints:
```
"hash #<A:0x000057dc6e12a5f0>"
"hash #<B:0x000057dc6e12a190>"
"== #<B:0x000057dc6e12a190>"
true
"hash #<B:0x000057dc6e129880>"
"== #<B:0x000057dc6e129880>"
1
```
mruby 3.2 prints:
```
"== #<B:0x59a7330ff860>"
true
"== #<B:0x59a7330ff5f0>"
1
```
mruby master prints:
```
false
nil
```
Bisecting pointed to https://github.com/mruby/mruby/commit/bc012deef95d514d4b2cbe1ec06b04059234e853
```
bc012deef95d514d4b2cbe1ec06b04059234e853 is the first bad commit
```
Which sure enough expects the classes to match. Would it be possible to revert to the original behavior (which I happen to rely on)? If not, how is the discrepancy with Ruby justified for this case?

**Comment by matz** [comment]
The Hash class is designed to use `#hash` and `#eql?` but when and how much to use them is implementation-dependent. mruby is slow (especially when calling the VM recursively), so it is implemented to avoid calling these methods whenever possible. This is not planned to be changed. Sorry.

**Comment by catsidhe** [comment]
Understandable. However this seems to change the semantics of `eql?` (as described on ruby-doc.org) - so perhaps it's worth mentioning in `limitations.md` to avoid surprises.

Per any chance, would you consider allowing `eql?` to be called if one of the classes is a subclass of another? I.e. something like:
```diff
-  if (mrb_class(mrb, obj1) != mrb_class(mrb, obj2)) return FALSE;
+  if (!mrb_obj_is_kind_of(mrb, obj1, mrb_class(mrb, obj2))
+      && !mrb_obj_is_kind_of(mrb, obj2, mrb_class(mrb, obj1))) return FALSE;
```
My use case is wrapping a native C++ class and then extending it in Ruby to add fluff, and I wanted to treat all Ruby instances wrapping the same native instance as equal. So my `hash` value was basically a native pointer.
