### ISSUE TITLE
Fails to build with tcc(Tiny C Compiler)

### ISSUE THREAD

**Issue by stalbordboat** [mruby/mruby#6173]
I wrote this build task for the `tcc` toolchain. It's just a modified gcc toolchain:
```ruby
MRuby::Toolchain.new(:tcc) do |conf, params|
  default_command = 'tcc'
  compiler_flags = %w(-g -O3 -Wall -Wundef)
  c_mandatory_flags = %w(-std=gnu99)
  compile_opt = '%{flags} -o "%{outfile}" "%{infile}"'

  conf.linker do |linker|
    linker.command = default_command
    linker.flags = [ENV['LDFLAGS'] || %w()]
    linker.libraries = %w(m)
    linker.library_paths = []
    linker.option_library = '-l%s'
    linker.option_library_path = '-L%s'
    linker.link_options = '%{flags} -o "%{outfile}" %{objs} %{flags_before_libraries} %{libs} %{flags_after_libraries}'
  end
end
```

When it reaches the point of building `mrbc`(linking it with `libmruby_core.a`) it fails and give me this error:
```shell
LD    build/host/mrbc/bin/mrbc 
tcc: error: undefined symbol 'etext'
tcc: error: undefined symbol 'edata'

```
any idea what's going on here? Thank you in advance for any help!

**Comment by dearblue** [comment]
Try adding `conf.defines << "MRB_NO_DEFAULT_RO_DATA_P"` in your build configuration file.

For other related settings, please check <https://github.com/mruby/mruby/blob/3.3.0/doc/guides/mrbconf.md#reduce-heap-memory-configuration>.

If you would like to know more about the implementation details (source code), please check <https://github.com/mruby/mruby/blob/3.3.0/include/mruby/value.h#L423-L457>.

**Comment by stalbordboat** [comment]
Thank you so much for your help!
