### ISSUE TITLE
Verson 3.3.0: time.h declares mrb_time_at. Function changed to time_at (no mrb_)

### ISSUE THREAD

**Issue by wsobel** [mruby/mruby#6195]
The API function `mrb_time_at` was changed in time.c to `time_at`. The time.h file still has `mrb_time_at`.

Added 

```c++
extern "C" {
  MRB_API mrb_value time_at(mrb_state *mrb, time_t sec, time_t usec, enum mrb_timezone zone);
}
```

as a temporary hack.

**Comment by matz** [comment]
Ah, `time_at` is not a static function. 5265e35 was wrong.
