### ISSUE TITLE
Wrong number of characters in broken UTF-8 string

### ISSUE THREAD

**Issue by dearblue** [mruby/mruby#6255]
mruby built with `MRB_UTF8_STRING` enabled does not count characters in the `0x80...0xc0` in broken strings.

Here is the result when built with `build_config/host-debug.rb`:

```ruby
p "\x80\x81\x82\x83".size
# => 0 (acctual; currently master 7edbff8c83cd19749da576aca945fcbf64602bd5, mruby-3.3.0, mruby-3.2.0)
# => 4 (expected; mruby-3.1.0, CRuby)
```

I checked with `git bisect` and it reported commit 916fd642fabf1edbcf9a6e2c476663c17198fffd.
But now it has been replaced by the SWAR technique, so a simple revert is not possible.

I don't know how to fix it, so I'll just report it.

**Comment by matz** [comment]
Ah, the new SWAR code assumes the string UTF-8 encoding is valid. Let me think for a while.
Thank you for the report.
