### ISSUE TITLE
Unable to define `==` for objects when using `Array#delete`

### ISSUE THREAD

**Issue by pusewicz** [mruby/mruby#6262]
Defining `==` method on an object so that it's used for comparison when using `Array#delete` causes an exception. For some reason, the `other` becomes an `Object`, rather than `Cell`.

#### Sample code

```ruby
class Cell
  attr_accessor :id

  def initialize
    @id = rand(1_000_000)
  end

  def ==(other)
    @id == other.id
  end

  def id
    @id
  end
end

cells = Array.new(1_000) { Cell.new }
1_000.times do |i|
  cells.delete(cells.sample)
end

puts "There are #{cells.size} cells left."
```

#### Expected

```
$ mruby test.rb
There are 0 cells left.
```

#### Actual

```
$ mruby test.rb
trace (most recent call last):
        [2] mruby.rb:18
        [1] mruby.rb:19
test.rb:9:in ==: undefined method 'id' (NoMethodError)
```

**Comment by leviongit** [comment]
this error does not occur at the current master commit (4a27a1880)

**Comment by leviongit** [comment]
this error does not occur at current master (19d9f48f7)

**Comment by pusewicz** [comment]
@leviongit I played around, and in fact it's an issue with the `Array#index`:

```ruby
class Cell
  attr_accessor :id

  def initialize
    @id = rand(1_000_000)
  end

  def ==(other)
    puts "Comparing #{other.class}"
    @id == other.id
  end

  def id
    @id
  end
end

cells = Array.new(1_000) { Cell.new }
puts cells.index(cells[100])
```

#### Expected

```
$ mruby test.rb
100
```

#### Actual

```
$ mruby test.rb
trace (most recent call last):
        [1] mruby.rb:19
mruby.rb:10:in ==: undefined method 'id' (NoMethodError)
```

**Comment by matz** [comment]
As general advice, the `==` method should accept any object as an argument. But we fixed the issue anyway.

**Comment by pusewicz** [comment]
@matz That's correct, but in my case I knew exactly that there would be only one type of object in the array.

**Comment by matz** [comment]
Despite of your expectation `==` method may be called from the library. In fact, the bug was in the find method calling `==`.
