### ISSUE TITLE
build with build_config.rb w/mruby extensions succeeds but doesn't create SciTE binary

### ISSUE THREAD

**Issue by dwilde1** [mruby/mruby#6284]
When I modify build_config.rb (as below) rake succeeds but SciTE is not created.
(source is latest 3.3 from Master)

MRuby::Build.new do |conf|
  conf.gem :core => 'mruby-eval'
  conf.gem :git => 'https://github.com/iij/mruby-io.git'
  conf.gem :git => 'https://github.com/iij/mruby-dir.git'
  conf.gem :git => 'https://github.com/iij/mruby-regexp-pcre.git' # or conf.gem :git => 'https://github.com/mattn/mruby-onig-regexp.git'
  conf.gem :git => 'https://github.com/sdottaka/mruby-bin-scite-mruby.git'
  conf.gem :git => 'https://github.com/mattn/mruby-require.git' # or conf.gem :git => 'https://github.com/iij/mruby-require.git'
end

When I perform the same additions to build_config/default.rb (see attached text file), I get the following errors in the build (after replacing mrb_exc_backtrace with mrb_print_backtrace)

" ... "
CXX   build/repos/host/mruby-bin-scite-mruby/tools/scite/src/mrubyExtension.cxx -> build/host/mrbgems/mruby-bin-scite-mruby/tools/scite/src/mrubyExtension.o
/opt/mruby/build/repos/host/mruby-bin-scite-mruby/tools/scite/src/mrubyExtension.cxx: In function ‘void backtrace(mrb_state*, const char*)’:
/opt/mruby/build/repos/host/mruby-bin-scite-mruby/tools/scite/src/mrubyExtension.cxx:1599:44: error: too many arguments to function ‘void mrb_print_backtrace(mrb_state*)’
 1599 |         mrb_value ary = mrb_print_backtrace(mrb, mrb_obj_value(mrb->exc));
      |                         ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /opt/mruby/build/repos/host/mruby-bin-scite-mruby/tools/scite/src/mrubyExtension.cxx:28:
/opt/mruby/include/mruby.h:1383:14: note: declared here
 1383 | MRB_API void mrb_print_backtrace(mrb_state *mrb);
      |              ^~~~~~~~~~~~~~~~~~~
/opt/mruby/build/repos/host/mruby-bin-scite-mruby/tools/scite/src/mrubyExtension.cxx:1599:44: error: conversion from ‘void’ to non-scalar type ‘mrb_value’ requested
 1599 |         mrb_value ary = mrb_print_backtrace(mrb, mrb_obj_value(mrb->exc));
      |                         ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/mruby/build/repos/host/mruby-bin-scite-mruby/tools/scite/src/mrubyExtension.cxx: In function ‘mrb_value mrb_subprocess_send(mrb_state*, mrb_value)’:
/opt/mruby/build/repos/host/mruby-bin-scite-mruby/tools/scite/src/mrubyExtension.cxx:1460:20: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
 1460 |         (void)write(psp->fd_pty_master, str, len);
      |               ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rake aborted!
Command failed with status (1): [g++ -MMD -c -g -O3 -Wall -Wundef -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/x86_64-linux-gnu -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -DSCI_LEXER -DGTK -DPIXMAP_PATH=\"/opt/mruby/share/pixmaps\" -DSYSCONF_PATH=\"/opt/mruby/share/scite\" -DMRBGEM_MRUBY_BIN_SCITE_MRUBY_VERSION=0.0.0 -DMRB_USE_RATIONAL -DMRB_USE_COMPLEX -DMRB_USE_BIGINT -DMRB_USE_DEBUG_HOOK -I"/opt/mruby/include" -I"/opt/mruby/build/repos/host/mruby-bin-scite-mruby/tools/scintilla/include" -I"/opt/mruby/build/repos/host/mruby-bin-scite-mruby/tools/scintilla/lexlib" -I"/opt/mruby/build/repos/host/mruby-bin-scite-mruby/tools/scintilla/src" -I"/opt/mruby/build/repos/host/mruby-bin-scite-mruby/tools/scite/lua/include" -I"/opt/mruby/build/repos/host/mruby-bin-scite-mruby/tools/scite/src" -I"/opt/mruby/build/host/include" -o "/opt/mruby/build/host/mrbgems/mruby-bin-scite-mruby/tools/scite/src/mrubyExtension.o" "/opt/mruby/build/repos/host/mruby-bin-scite-mruby/tools/scite/src/mrubyExtension.cxx"]
/opt/mruby/lib/mruby/build/command.rb:33:in `_run'
/opt/mruby/lib/mruby/build/command.rb:95:in `run'
/opt/mruby/lib/mruby/build/command.rb:120:in `block (2 levels) in define_rules'
Tasks: TOP => default => all => /opt/mruby/build/host/bin/scite => /opt/mruby/build/host/mrbgems/mruby-bin-scite-mruby/tools/scite/src/mrubyExtension.o
(See full trace by running task with --trace)
[scite_mruby.rb.txt](https://github.com/user-attachments/files/15525676/scite_mruby.rb.txt)
[scite_mruby.rb.txt](https://github.com/user-attachments/files/15525684/scite_mruby.rb.txt)

**Comment by matz** [comment]
`mruby-bin-scite-mruby` uses old API `mrb_print_backtrace(mrb, exc)`. You can fix it by removing the second argument.
But `mruby-bin-scite-mruby` has not been maintained for 10 years. I am not sure if you see any other compatibility problems.
