### ISSUE TITLE
mrb_fixnum returns wrong value if integer is large

### ISSUE THREAD

**Issue by rcheung2015** [mruby/mruby#6285]
## Steps to reproduce issue
1. Build mRuby under 32-bit x86 system (I used [Ubuntu 32-bit x86 image](https://hub.docker.com/r/i386/ubuntu))
2. Build mRuby with attached gem: [example.zip](https://github.com/user-attachments/files/15531035/example.zip). This is an executable reproduce the issue.
3. Run the test executable as follow:
~~~~
$ bin/mruby-bin-example 1716952164
mrb_fixnum: 728885884
mrb_integer: 1716952164
~~~~

## Analysis
Test code is as follow:
~~~~
mrb_value value = mrb_int_value(state, strtol(argv[i], NULL, 0));
printf("mrb_fixnum: %lld\n", (long long) mrb_fixnum(value));
printf("mrb_integer: %lld\n", (long long) mrb_integer(value));
~~~~
The test code creates an integer and retrieves its value using ``mrb_fixnum`` and ``mrb_integer``. Return value from ``mrb_integer`` is expected. Under 32-bit environment, value of ``mrb_fixnum`` is correct until input is larger than 1073741823 (hexadecimal 0x3fffffff).
The issue happens since version 3.0.0.

## Suggestion
As ``mrb_integer`` is current API since mRuby 3.0.0, my plan is changing my own application to use the new API. However, some old application running on 32-bit system may need ``mrb_fixnum`` function working with larger range of integers. So I hope the wrong (overflow?) return of ``mrb_fixnum`` can be fixed. At least make it work in the whole range of 32-bit integer.
If the issue cannot be fixed, I would suggest gives warning to developer or removes this old function (and friends) for good.

**Comment by matz** [comment]
It highly depends on the boxing configuration. We have three options:

* MRB_NAN_BOXING
* MRB_WORD_BOXING (default)
* MRB_NO_BOXING

If you want to map the full range of 32-bit integers, choose either MRB_NAN_BOXING or MRB_NO_BOXING. They are slightly less efficient, but they should work OK.

To use MRB_NO_BOXING for example, add the following line to your build_config script.

```ruby
conf.cc.defines = %w(MRB_NO_BOXING)
```

If this doesn't solve your issue, please reopen.
