### ISSUE TITLE
Mirror of prettier package for pre-commit is now archived

### ISSUE THREAD

**Issue by jbampton** [mruby/mruby#6291]
https://github.com/mruby/mruby/blob/73c3970ea13f4ed43127c005e54bd6ce51594b5b/.pre-commit-config.yaml#L57

This repository has been archived by the owner on Apr 12, 2024. It is now read-only. 

https://github.com/pre-commit/mirrors-prettier

Some more information:

https://prettier.io/

https://prettier.io/docs/en/precommit

**Comment by matz** [comment]
The mirror page says: prettier made some changes that breaks plugins entirely. So our options are:

* keep prettier from pre-commit as it is, and use archived old version forever
* drop prettier from pre-commit configuration

I'd vote for the latter since we don't use JavaScript/CSS.
