### ISSUE TITLE
`foo :bar {}` is legal in mruby?

### ISSUE THREAD

**Issue by catsidhe** [mruby/mruby#6298]
```ruby
def foo(*)
end
foo :bar {}
foo 'bar' {}
foo 1 {}
```

The syntax above works in mruby but not in CRuby. However `foo nil {}` doesn't work in mruby either.

The commit that made it possible is https://github.com/mruby/mruby/commit/e98823f1896d875b11d0e165d0e8cf9e478a8709
Intentional?

**Comment by matz** [comment]
I don't remember why I made this change, and as you pointed out, it's different from CRuby behavior.
I reverted the change.
