### ISSUE TITLE
method call faile on arm v5

### ISSUE THREAD

**Issue by yamori813** [mruby/mruby#6301]
Sorry use Japanese.

arm v5のベアメタルにポートしたのですが、mruby-yabm(mrbgem)のメソッドの呼び出しに失敗します。すべてのメソッドが失敗するわけではなく、一部のメソッドが失敗するようです。

https://github.com/yamori813/armbm-mruby
https://github.com/yamori813/mruby-yabm

たとえばhttpsをよぶと以下のエクセプションが発生します。

wrong number of arguments (given 4, expected 7)

httpsメソッドはmruby-yabmのソースで以下のように定義しています。

  mrb_define_method(mrb, yabm, "https", mrb_yabm_https, MRB_ARGS_REQ(4));

httpメソッドでは以下のエクセプションでした。

invalid argument specifier

gccは4.9.4を使っています。オブジェクトはarm v4で作っています。

mruby 3.2相当にソースを戻してみたのですが、同じでした。

MIPS SOCのベアメタルでは問題ありません。

デバッグ方法など教えていただけると助かります。

**Comment by dearblue** [comment]
ベアメタル環境でのデバッグについて僕はよくわからないので、とりあえず思いついたことを述べることにします。
以下のようにするとどうなるのでしょうか？

```diff
 static mrb_value mrb_yabm_https(mrb_state *mrb, mrb_value self)
 {
 mrb_value str;
 mrb_value host, addr, header;
 mrb_int port;
-char tmp[512];
+char tmp[512] = "SSiS";
 int len;
 int ip[8];
 int type;

-  mrb_get_args(mrb, "SSiS", &host, &addr, &port, &header);
+  mrb_get_args(mrb, tmp, &host, &addr, &port, &header);
   type = mrb_yabm_cpaddr(mrb, ip, addr);
   str = mrb_str_new_cstr(mrb, "");
   if (https_connect(RSTRING_PTR(host), ip, port, RSTRING_PTR(header), type)) {
```

**Comment by yamori813** [comment]
コメントありがとうございます。

上記の修正で問題は起きなくなりました。

今回新規アーキテクチャサポートのため、スタックの設定をメモリサイズに合わせて変更するようにしたのですが、それがまずかったようです。

お騒がせしてすみませんでした。
