### ISSUE TITLE
Calling method_missing with only Kwargs passes arguments incorrectly

### ISSUE THREAD

**Issue by petekinnecom** [mruby/mruby#6304]
Example:

```ruby
class Thing
  def method_missing(*a, **b)
    [a, b]
  end
end

Thing.new.undefined_method(a: 1, b: 2)
# => [[:undefined_method], [:undefined_method]]
```
It seems the args are not correctly passed to method missing, however, if there are any positional args, it works fine.  I've added on to make a failing test case you can see here: 

https://github.com/petekinnecom/mruby/commit/509590c18df04900490e73a0d2cf25035c978f6c

Thanks!

**Comment by dearblue** [comment]
Nice catch!

I'm going to create a pull request to fix it, can I include your test commit?
Your test commit will be followed by my fix commit.

My patch to fix it is as follows.

```patch
diff --git a/src/vm.c b/src/vm.c
index d9416d41b..8561868e3 100644
--- a/src/vm.c
+++ b/src/vm.c
@@ -629,7 +629,6 @@ prepare_missing(mrb_state *mrb, mrb_callinfo *ci, mrb_value recv, mrb_sym mid, m
   stack_extend(mrb, 4);

   argv = &ci->stack[1];         /* maybe reallocated */
-  argv[0] = args;
   if (ci->nk == 0) {
     argv[1] = blk;
   }
@@ -638,6 +637,7 @@ prepare_missing(mrb_state *mrb, mrb_callinfo *ci, mrb_value recv, mrb_sym mid, m
     argv[1] = argv[ci->n];
     argv[2] = blk;
   }
+  argv[0] = args;
   ci->n = CALL_MAXARGS;
   /* ci->nk is already set to zero or CALL_MAXARGS */
   mrb_ary_unshift(mrb, args, mrb_symbol_value(mid));
```

**Comment by petekinnecom** [comment]
Nice, sounds great, thank you. I stared at that function a bit, and tried some trial-and-error changes, but I kept getting errors about missing parenthesis, missing semi-colons, or not declaring variables, and my usual debugging technique of `binding.irb` didn't seem to work... 😂

**Comment by dearblue** [comment]
@petekinnecom,
I have created a pull request as #6305 that includes your test commit.
