### ISSUE TITLE
Error while trying to link mruby_core

### ISSUE THREAD

**Issue by hoshiumiarata** [mruby/mruby#6352]
When I try to link mruby_core to my project, I get the following error:

```
Undefined symbols for architecture x86_64:
  "_mrb_as_rational", referenced from:
      _int_div in libmruby_core.a[19](numeric.o)
  "_mrb_complex_add", referenced from:
      _mrb_int_add in libmruby_core.a[19](numeric.o)
      _flo_add in libmruby_core.a[19](numeric.o)
  "_mrb_complex_copy", referenced from:
      _init_copy in libmruby_core.a[6](class.o)
  "_mrb_complex_div", referenced from:
      _int_div in libmruby_core.a[19](numeric.o)
      _flo_div in libmruby_core.a[19](numeric.o)
  "_mrb_complex_mul", referenced from:
      _mrb_int_mul in libmruby_core.a[19](numeric.o)
      _flo_mul in libmruby_core.a[19](numeric.o)
  "_mrb_complex_new", referenced from:
      _mrb_int_sub in libmruby_core.a[19](numeric.o)
      _int_div in libmruby_core.a[19](numeric.o)
      _flo_div in libmruby_core.a[19](numeric.o)
      _flo_sub in libmruby_core.a[19](numeric.o)
  "_mrb_complex_sub", referenced from:
      _mrb_int_sub in libmruby_core.a[19](numeric.o)
      _flo_sub in libmruby_core.a[19](numeric.o)
  "_mrb_complex_to_f", referenced from:
      _mrb_ensure_float_type in libmruby_core.a[21](object.o)
  "_mrb_complex_to_i", referenced from:
      _mrb_ensure_integer_type in libmruby_core.a[21](object.o)
  "_mrb_init_mrbgems", referenced from:
      _init_mrbgems in libmruby_core.a[29](state.o)
  "_mrb_init_mrblib", referenced from:
      _mrb_init_core in libmruby_core.a[16](init.o)
  "_mrb_rational_add", referenced from:
      _mrb_int_add in libmruby_core.a[19](numeric.o)
  "_mrb_rational_copy", referenced from:
      _init_copy in libmruby_core.a[6](class.o)
  "_mrb_rational_div", referenced from:
      _int_div in libmruby_core.a[19](numeric.o)
      _int_quo in libmruby_core.a[19](numeric.o)
  "_mrb_rational_mark", referenced from:
      _gc_mark_children in libmruby_core.a[14](gc.o)
  "_mrb_rational_mul", referenced from:
      _mrb_int_mul in libmruby_core.a[19](numeric.o)
  "_mrb_rational_new", referenced from:
      _mrb_int_sub in libmruby_core.a[19](numeric.o)
      _int_quo in libmruby_core.a[19](numeric.o)
      _int_quo in libmruby_core.a[19](numeric.o)
  "_mrb_rational_sub", referenced from:
      _mrb_int_sub in libmruby_core.a[19](numeric.o)
  "_mrb_rational_to_f", referenced from:
      _mrb_ensure_float_type in libmruby_core.a[21](object.o)
  "_mrb_rational_to_i", referenced from:
      _mrb_ensure_integer_type in libmruby_core.a[21](object.o)
ld: symbol(s) not found for architecture x86_64
```

Is it not supposed to be used as a library?

**Comment by dearblue** [comment]
`bin/mrbc` is linked with `libmruby_core`.
The reason why the link succeeds is that mrbc itself complements the missing dummy functions.
The dummy functions are aggregated in [mrbgems/mruby-bin-mrbc/tools/mrbc/stub.c](https://github.com/mruby/mruby/blob/3.3.0/mrbgems/mruby-bin-mrbc/tools/mrbc/stub.c).

The first dummy function was added in commit ac22a63ae3c29ac3921f53ac63ae981ab0def744 for security reasons.
Several dummy functions were then added and created as separate files in commit e45081d310852d5f184337c007c824839ef8cd74.

A patch to allow users to use `libmruby_core` without having to define a dummy function is in #6024.
I will try to update it for now.

**Comment by matz** [comment]
@hoshiumiarata A direct answer to the original question is that you have to link `libmruby.a` instead of `libmruby_core.a`. The latter lacks functions that are introduced by mrbgems.

**Comment by hoshiumiarata** [comment]
@matz, @dearblue 
Thank you.
I wanted to use only the compiler part of mruby (I don't need the VM), but if mruby_core is not for public use, then I will give up.
(Maybe it would be better to remove mruby_core from the distribution (installation), because it's a bit misleading)

**Comment by dearblue** [comment]
@hoshiumiarata,
> (Maybe it would be better to remove mruby_core from the distribution (installation), because it's a bit misleading)

Am I correct in understanding that this means that `rake install` should not install `libmruby_core`?
If so, I think it's a good idea.
I'll see if I can figure out how to realize this.
