### ISSUE TITLE
mruby: powl() not available when compiling for Dreamcast

### ISSUE THREAD

**Issue by Tchan0** [mruby/mruby#6365]
Hello,

Tried to compile the latest mruby for Dreamcast, but it failed with this message:

/opt/toolchains/dc/kos-ports/mruby/build/mruby-3.2.0/src/readfloat.c: In function ‘mrb_read_float’:
/opt/toolchains/dc/kos-ports/mruby/build/mruby-3.2.0/src/readfloat.c:69:12: error: implicit declaration of function ‘powl’; did you mean ‘powf’? [-Werror=implicit-function-declaration]
   69 |     res *= powl(10.0, sign * e);
      |            ^~~~
      |            powf

Cause:  https://github.com/mruby/mruby/commit/bd668e4c9dc2244aa201addf95acbb8663596423
that went from pow() to powl()
This commit warned about architectures not supporting long doubles... and the Dreamcast seems to be one of those.

Dreamcast mruby compiled via:
- latest https://github.com/KallistiOS/KallistiOS
- latest https://github.com/KallistiOS/kos-ports
- using sh-elf-gcc 13.2.0

**Comment by gyrovorbis** [comment]
Confirmed also to be an issue with the latest `sh-elf-gcc 14.2.0`. I just don't believe Newlib-based platforms are going to have that function for most of its targets... If needed, I think we could add it to KallistiOS, but I'm pretty sure we don't *actually* have `long double`, and that it would just be a `#define` back to regular `pow()`...

**Comment by matz** [comment]
I see. I was concerned about that, but it has become a reality. We will take care of it as soon as possible. Thanks for the report.

**Comment by matz** [comment]
I found out we don't need `long double` for our purpose. I fill fix it soon.
