### ISSUE TITLE
instance_exec named block args don't work properly

### ISSUE THREAD

**Issue by jabamaus** [mruby/mruby#6389]
Using mruby head the following code correctly prints 1 in cruby but it prints 2 in mruby.

```
instance_exec(a: 1) do |a: 2|
  puts a
end
```

And without the default value it fails altogether

```
instance_exec(a: 1) do |a:|
  puts a
end
```

`instance_exec: missing keyword: a (ArgumentError)`

**Comment by jabamaus** [comment]
Is this possible to fix?

**Comment by matz** [comment]
It is. But I need some time.

**Comment by jabamaus** [comment]
Take it 😃

**Comment by dearblue** [comment]
@matz, If you are busy, I can send a PR. What do you think?
Unconfirmed, but I think the fix is just to replace `mrb_exec_irep()` with `mrb_exec_irep()` in the `obj_instance_exec()` function.

**Comment by matz** [comment]
@dearblue I still don't know how to fix it and would appreciate it if you could do it!

**Comment by dearblue** [comment]
I created it as #6391.
