### ISSUE TITLE
conf.enable_sanitizer "address,undefined,leak" stopped working

### ISSUE THREAD

**Issue by Asmod4n** [mruby/mruby#6433]
MRBC mrblib/00class.rb 
           mrblib/00kernel.rb 
           mrblib/10error.rb 
           mrblib/array.rb 
           mrblib/compar.rb 
           mrblib/enum.rb 
           mrblib/hash.rb 
           mrblib/kernel.rb 
           mrblib/numeric.rb 
           mrblib/range.rb 
           mrblib/string.rb 
           mrblib/symbol.rb 
==1287487==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
rake aborted!

i have to add conf.linker.flags_before_libraries << '-static-libasan' in my build_config.rb to keep on using asan, though, thats gcc specific and doesn't seem to work with clang.

i just ran git pull before compiling it again so i am on the latest commit 781359a1d as of now.

**Comment by matz** [comment]
Tell me a little more about your configuration. What compiler do you use? On which platform?
The current build works at least for me with clang 14.0.

**Comment by Asmod4n** [comment]
I am running this currently.

```bash
➜  uname -a         
Linux a0d7b954-vscode 6.11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.11-1~exp1 (2024-09-19) x86_64 GNU/Linux
➜  gcc --version                                            
gcc (Debian 12.2.0-14) 12.2.0
```

its happening while running a build_config.rb like this: https://github.com/Asmod4n/mruby-io_uring/blob/978d053f471fbc7e31b8bfa32c70bdced2cb3f54/build_config.rb

without -static-libasan it doesn't compile.


its practically a docker container which runs vscode-server so i can code inside a browser Independent of the computer i am currently using.

**Comment by Asmod4n** [comment]
guess i found the issue, when you still have the static compiled liburing.a around which uses asan and you try to link it then this issue occurs, a simple cleaning will do.

So.. this aint a mruby issue, right?

**Comment by Asmod4n** [comment]
But it would be cool when you are inside a mrbgem.rake to see if some enable sanitizers in a build_conf.rb, does that exist?
There are projects out there where you have to enable sanitizers for them using configure flags because the Makefile doesn't include CFLAGS and such.

**Comment by matz** [comment]
It's an issue from the combination of gcc and ASAN, probably. I use clang to use ASAN.
In that case, use clang for the time being, and we will try to fix the issue (by probably adding `-static-libasan` for gcc ASAN).

**Comment by Asmod4n** [comment]
It’s an issue with the bear app, not mruby.

closing this.
