### ISSUE TITLE
`OP_JMPUW` does not call the ensure block when it jumps to the beginning of the `begin` block

### ISSUE THREAD

**Issue by hoshiumiarata** [mruby/mruby#6439]
It seems that `OP_JMPUW` does not call the ensure block when `a` is pointing to the beginning of the `begin` block.

For example:

```ruby
for _ in [1]
  begin
    puts 1
    redo
  ensure
    puts 2
    break
  end
end
```

Ruby 3.3 will print:

```
1
2
=> nil
```

mruby (master) is indefinitly printing `1`.

This probably happens because `OP_JMPUW` is pointing to `puts 1`, so it interprets it as jumping before `puts 1` and after the `begin` keyword. However, it should jump before `puts 1` to outside of the `begin` block and call the ensure block.

https://github.com/mruby/mruby/blob/3505874f72fb6e7f78cba6f3d7cf9d587349667c/src/vm.c#L1724C11-L1724C109

If I understand correctly, the condition should be changed from:

```c
a < mrb_irep_catch_handler_unpack(ch->begin)
```

to:

```c
a <= mrb_irep_catch_handler_unpack(ch->begin)
```

**Comment by matz** [comment]
@dearblue What do  you think?
