### ISSUE TITLE
`break` inside `while` loop will execute the `ensure` block outside of the `while` loop

### ISSUE THREAD

**Issue by hoshiumiarata** [mruby/mruby#6441]
It seems that `break` inside a `while` loop will execute the `ensure` block outside of the `while` loop.
For example:

```ruby
begin
  while true
    puts 1
    break
  end
ensure
  puts 2
end
```

mruby (master) will output:

```
1
2
2
```

While Ruby 3.3 will output:

```
1
2
```

**Comment by dearblue** [comment]
Thank you for the report.
:scream_cat: I don't recall checking on this matter, so I probably didn't.
