### ISSUE TITLE
bigint: bug with division of a small number by a bigint

### ISSUE THREAD

**Issue by hoshiumiarata** [mruby/mruby#6456]
It seems that the division of a small number by a bigint, where one of the operands is a negative number, is not working correctly.

For example, the following code:

```ruby
-1 / (10**20)
```

mruby returns `1`, while ruby 3.3 returns `-1`.

The same issue occurs with the `divmod` method:

```ruby
-1.divmod(10**20)
```

mruby returns `[1, 99999999999999999999]`, while ruby 3.3 returns `[-1, 99999999999999999999]`.

Probably, there is a problem with the calculation of the sign of the result after rounding.

**Comment by matz** [comment]
Now we can merge #6444
