### ISSUE TITLE
Feedback on ruby 3.4.1, showing errors in colours (at the least one colour, that is red)

### ISSUE THREAD

**Issue by rubyFeedback** [mruby/mruby#6460]
This is just meant as quick feedback for matz, as I can not use the ruby bug tracker anymore. I'll close
the issue here after writing it, to keep the issue tracker here clean.

Recently ruby 3.4.1 was released. The to me most important change is the part where colours
are shown in error.

An example for this is the following image via KDE konsole terminal, hosted on imgur.com:

https://imgur.com/a/W8Vf3OW

This may not seem huge for others, but to me I can now instantly spot the error, as the
arrows are clearly indicating that, and also in colours (red), which is useful. I would not
even mind more colours, but I understand that this is mostly kept at a minimum, as
others may be confused by too many colours. But either way having the error indicated
clearly like that, is a huge visual help. So I think this was a very good change. That's it
for the feedback here. \o/

(So while this has nothing to do with mruby as such, I think it would also be super helpful
for mruby to have that - of course I don't know whether mruby has it or not. I use MRI most
of the time; mruby I want to use as a "rescue-shell" e. g. rather than busybox or any such 
tool, to have a minimal ruby that I can use to "bootstrap" things on Linux in general. I use
ruby to compile everything from source, for instance, which works very well; but admittedly
I use MRI like 99% of the time. I do also test alternatives such as natalie, or jruby, every now
and then.)

**Comment by matz** [comment]
For mruby, it is more difficult than for CRuby to expect color output support for error output destinations, but I would like to implement it if I can find the right way to determine it.
