### ISSUE TITLE
Collision string.h with the string.h of core foundation in OS X

### ISSUE THREAD

**Issue by nexon** [mruby/mruby#656]
Hi there!, i'm trying to run mruby (embedded) but when i try to compile i get this message...

/Users/user/mruby-headers/mruby/string.h:35:3: error: type name requires a specifier or qualifier
  MRB_OBJECT_HEADER;
  ^
/Users/user/mruby-headers/mruby/string.h:52:21: error: unknown type name 'mrb_state'
void mrb_str_decref(mrb_state_, struct mrb_shared_string_);
                    ^
/Users/user/mruby-headers/mruby/string.h:53:1: error: unknown type name 'mrb_value'
mrb_value mrb_str_literal(mrb_state_, mrb_value);
^
/Users/user/mruby-headers/mruby/string.h:53:27: error: unknown type name 'mrb_state'
mrb_value mrb_str_literal(mrb_state_, mrb_value);
                          ^
/Users/user/mruby-headers/mruby/string.h:54:21: error: unknown type name 'mrb_state'
void mrb_str_concat(mrb_state_, mrb_value, mrb_value);
                    ^
/Users/user/mruby-headers/mruby/string.h:54:44: error: redefinition of parameter 'mrb_value'
void mrb_str_concat(mrb_state_, mrb_value, mrb_value);
                                           ^
/Users/user/mruby-headers/mruby/string.h:54:33: note: previous declaration is here
void mrb_str_concat(mrb_state_, mrb_value, mrb_value);
                                ^
/Users/user/mruby-headers/mruby/string.h:55:1: error: unknown type name 'mrb_value'
mrb_value mrb_str_plus(mrb_state_, mrb_value, mrb_value);
^
/Users/user/mruby-headers/mruby/string.h:55:24: error: unknown type name 'mrb_state'
mrb_value mrb_str_plus(mrb_state_, mrb_value, mrb_value);
                       ^
/Users/user/mruby-headers/mruby/string.h:55:47: error: redefinition of parameter 'mrb_value'
mrb_value mrb_str_plus(mrb_state_, mrb_value, mrb_value);
                                              ^
/Users/user/mruby-headers/mruby/string.h:55:36: note: previous declaration is here
mrb_value mrb_str_plus(mrb_state_, mrb_value, mrb_value);
                                   ^
/Users/user/mruby-headers/mruby/string.h:56:1: error: unknown type name 'mrb_value'
mrb_value mrb_obj_as_string(mrb_state *mrb, mrb_value obj);
^
/Users/user/mruby-headers/mruby/string.h:56:29: error: unknown type name 'mrb_state'
mrb_value mrb_obj_as_string(mrb_state *mrb, mrb_value obj);
                            ^
/Users/user/mruby-headers/mruby/string.h:56:45: error: unknown type name 'mrb_value'
mrb_value mrb_obj_as_string(mrb_state *mrb, mrb_value obj);
                                            ^
/Users/user/mruby-headers/mruby/string.h:57:1: error: unknown type name 'mrb_value'
mrb_value mrb_str_resize(mrb_state *mrb, mrb_value str, int len); /_ mrb_str_resize _/
^
/Users/user/mruby-headers/mruby/string.h:57:26: error: unknown type name 'mrb_state'
mrb_value mrb_str_resize(mrb_state *mrb, mrb_value str, int len); /_ mrb_str_resize _/
                         ^
/Users/user/mruby-headers/mruby/string.h:57:42: error: unknown type name 'mrb_value'
mrb_value mrb_str_resize(mrb_state *mrb, mrb_value str, int len); /_ mrb_str_resize _/
                                         ^
/Users/user/mruby-headers/mruby/string.h:58:1: error: unknown type name 'mrb_value'
mrb_value mrb_string_value(mrb_state *mrb, mrb_value *ptr); /_ StringValue _/
^
/Users/user/mruby-headers/mruby/string.h:58:28: error: unknown type name 'mrb_state'
mrb_value mrb_string_value(mrb_state *mrb, mrb_value *ptr); /_ StringValue _/
                           ^
/Users/user/mruby-headers/mruby/string.h:58:44: error: unknown type name 'mrb_value'
mrb_value mrb_string_value(mrb_state *mrb, mrb_value *ptr); /_ StringValue */
                                           ^
/Users/user/mruby-headers/mruby/string.h:59:1: error: unknown type name 'mrb_value'
mrb_value mrb_str_substr(mrb_state *mrb, mrb_value str, mrb_int beg, int len);

Search more i find out that string.h of cocoa is "overriding" the actual string.h of mruby.

what can i do?, thanks!

**Comment by matz** [comment]
I think this resolved by 5c405de (#3032).
