### ISSUE TITLE
Examples do not show object lifecycle callbacks

### ISSUE THREAD

**Issue by gaffo** [mruby/mruby#904]
The c examples are pretty trivial. I would really like to see examples of hooking into the GC life-cycles for creating an instance of a ruby object implemented c, and for object deletion. Also there is no example of how to manage a c context (eg some memory pointer) in a ruby object implemented in c.

**Comment by jfcalvo** [comment]
A detailed example about this would be welcome. I'm a little bit lost about the same.

**Comment by cremno** [comment]
@jfcalvo: What exactly made you feel lost? Have you looked at `mruby-time`? There's some stuff you can ignore (fallback definitions for platforms without functions like `timegm()` or `gmtime_r()`) but otherwise it can be seen as an example.
